### ISSUE TITLE
mouse and keyboard was not an MTP device

### ISSUE THREAD

**Issue by loreberti89** [raspberrypi/firmware#1003]
Hello I have a problem with keyboard and mouse with my raspberrypi3.

kernel version: **Kernel 4.14.44-v7+**

When I put the usb In **/var/log/syslog** I receive this error:

> mtp-probe: bus: 1, device: 6 was not an MTP device

In **lsusb** I see correctly the device usb.

The problem is after boot because before the see the desktop I can press shift for enter in recovery mode and here mouse and keyboard work perfectly.

**Comment by popcornmix** [comment]
This repo is for GPU firmware issues.

Yours sounds like a a kernel (or possibly distro) issue.
https://github.com/raspberrypi/linux/issues would be a better place to report.
