### ISSUE TITLE
OSError: libbcm_host: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yujmo** [raspberrypi/firmware#1034]
When I try to use **image[ubuntu:armhf]** to control sensors in **rancheros**, I can use GPIO to control the sensor.

However, when I use the python module: picamera to control the Human body induction sensor sensor, it is wrong.The wrong message is: OSError: libbcm_host: cannot open shared object file: No such file or directory.
       
I have downloaded libbcm_host.so from GitHub and copied it to /usr/local/lib and /usr/lib, but still report the same error. I  need help. Thanks.🙂🙂🙂

**Comment by JamesH65** [comment]
This is not a bug in the firmware, but a user error. Please use the forum for questions like this. You are also using a non-officially supported OS.
