### ISSUE TITLE
Old u-boot and kernel with new firmware

### ISSUE THREAD

**Issue by svolpe** [raspberrypi/firmware#1044]
I'm using the raspberry-pi-cm module and have a design that uses a version of u-boot from 2013 and Linux version 3.18.16.
The raspberry-pi-cm had a change in the emmc that now requires the latest firmware for it to work.  I've been trying to get the older version of u-boot and Linux kernel to work with the latest firmware.  My question is do I stand a change of being able to get them working or has too much changed in the firmware since 2013 and I just need to start over with a new version of u-boot and Linux and do a complete re-port of my current design?

**Comment by ghollingworth** [comment]
Have you tried just copying over the bootcode.bin file?  I would guess that the change causing the problem is a new SDRAM device which needed to be supported at boot time.  I think the old start.elf should still work though...  Worth a try, otherwise there's no other recourse than to start again
