### ISSUE TITLE
I can't disable fuzzy format match

### ISSUE THREAD

**Issue by zervankoru** [raspberrypi/firmware#1047]
I've edited /boot/config.txt and added this line:
avoid_edid_fuzzy_match=1
But edidparser still promts: Enabling fuzzy format match...
Raspberry selects lower resolution, because it has higher mhz

**Comment by popcornmix** [comment]
``avoid_edid_fuzzy_match`` was removed from firmware in August 2012 so it will have no effect.

You'll need to post your edid and explain what hdmi mode you are getting and what mode you think you should get.

**Comment by zervankoru** [comment]
@popcornmix here it is
![photo_2018-09-30_18-15-16](https://user-images.githubusercontent.com/39313092/46259082-f362fc80-c4dc-11e8-803b-af6b2d7cf148.jpg)
I am getting mode DMT 51, and I want mode DMT 82 (I am using monitor HDMI-DVI).
Of cource, I can use manual mode setting in config.txt. I tried to do it and it works, but I want to Raspberry Pi select highest resolution by default (I dont care about blankink)

**Comment by zervankoru** [comment]
@popcornmix any ideas?

**Comment by popcornmix** [comment]
The actual edid.dat file would be more useful. Can you upload to a hosting site (e.g. dropbox/google drive) and provide a link.

**Comment by zervankoru** [comment]
@popcornmix https://drive.google.com/file/d/1uOqMulmqXOxtB5jygvyidwwEzrjZew-M/view?usp=sharing - edid.dat
Actually, I don't want to fix problem in my current case. I want to do something like avoid_edid_fuzzy_match=1, Raspberry Pi select the best resolution and fps, no matter what is the pixel clock

**Comment by popcornmix** [comment]
I posted in https://github.com/raspberrypi/firmware/issues/1046 the basic rules used for choosing the default resolution. I think the reason DMT51 is chosen over DMT82 is 51 is listed in the standard timings and 82 is not.
That is considered a preference by the monitor for those listed resolutions.

**Comment by zervankoru** [comment]
@popcornmix so can I do something to prevent this behavior?
I prefer this algorithm:
1) Get all available modes from edid
2) Select the ones with the biggest resolution
3) Select the one with the best framerate (fps)

**Comment by popcornmix** [comment]
That's not generally desired. Highest resolution is not necessarily best.
A monitor that is natively (i.e. has this many physical pixels) 1360x768 may support 1920x1080 but will provide a sharper image at its native resolution.

**Comment by zervankoru** [comment]
@popcornmix  if I connect my Pi to the same monitor but HDMI-HDMI, Pi selects 1920x1080. But there are black borders, that can be disabled by disable_overscan=1.

**Comment by popcornmix** [comment]
Yes - DVI connection prefers DMT modes.
HDMI connection prefers CEA modes. 1600x1200 isn't a standard CEA mode.

**Comment by JamesH65** [comment]
@zervankoru I believe that your questions have been answered, can this issue be closed?

**Comment by zervankoru** [comment]
Yea
