### ISSUE TITLE
Windows 10 IoT on Raspberry PI 3 reboot issue

### ISSUE THREAD

**Issue by alexiordan** [raspberrypi/firmware#1049]
Referenced from here in seek for help: https://github.com/ms-iot/bsp/issues/43

Tested with a Raspberry PI 3 Model B
OS: 17134

- I plug the Raspberry PI in
- I unplug the RaspberryPI while Windows is still loading (After 10 seconds from the Windows logo first splash screen). 
_Sometimes it also happens when unplugging while in home screen, after Windows is loaded, but I don't have a scenario for that yet._

- I plug it back in, Windows does not start. Only Power RED LED is on for about 60 seconds After those 60 seconds Act GREEN LED starts a cycle of 7 times blink forever,
- I unplug it
- I plug it back in and Windows starts.
_It also happened to try several restarts until it started OK, but then again, I don't have a scenario._

Raspbian, under the same conditions starts everytime.

**Comment by JamesH65** [comment]
We do not support WinIoT here I am afraid. it's a wholly Microsoft product which we don't actually work on at all. Looking at the link above, it appears that it is being handled there anyway, so closing.
