### ISSUE TITLE
RPI 3B+ with official 7" screen : white flash at startup

### ISSUE THREAD

**Issue by stephanedamo** [raspberrypi/firmware#1052]
Hello,

The Raspberry 3B+ connected to the official 7 inch screen creates a fast white flash at startup before the rainbow screen. Like someone suggested in the topic linked below, it *may* be due to the Backlight Enable signal which is set too early by the boot code, allowing the backlight to light up before any pixel data is sent, thus showing a blank screen.

Latest firmware code + empty config.txt and no kernel.img still produces this behavior.

Original topic : https://www.raspberrypi.org/forums/viewtopic.php?f=108&t=223825
Video showing the problem : https://www.youtube.com/watch?v=xQJWC97g7jU (interpolation disabled in this video -- but behavior is the same with default settings)

Preventing this white flash would be cleaner for the user experience, especially if the RPI is integrated into products.
Could you investigate this issue ?

**Comment by JamesH65** [comment]
As I stated on that forum thread, I doubt I'll have much time to look at this. The white flash appears to be between device startup and the GPU drawing the splash screen.

**Comment by JamesH65** [comment]
Although, a quick change might be to only enable the backlight (its actually a PWM system rather than on/off) when the driver start fn is called, rather than on open. If I have time I'll give that a try.

**Comment by JamesH65** [comment]
No, that didn't help.  Still a brief white flash before the rainbox screen turns up.  I suspect this would take too much investigation time to figure out where the flash is coming from, it could even be, as i am beginning to suspect,  in the (tiny) firmware on the display itself.  So as soon as it powers on, the display backlight is defaulted to on. By the time the GPU has opened up the driver, found the display and told it to turn the backlight off, its too late - the flash has appeared. I'll take another quick look, but no promises.

**Comment by stephanedamo** [comment]
Ok thanks for your help. I'll look if there is a hardware way of controlling it (like with a transistor connected to a GPIO), but it would be much easier if it could be done purely in software.

**Comment by JamesH65** [comment]
Think I have figured out what this is. A little more complicated that initially suspected, I think it's the timing between the rainbow screen and vsync.  The flash is the previous frame displayed by the HVS before the next vsync updates it to the rainbow. It's a bit more obvious if you reboot, where the flash isn't white but the last known display contents. I've got a fix where I delay the backlight coming on to later in the boot cycle, will pass it to code review to see what the other guys here think.

**Comment by JamesH65** [comment]
OK, we've merged the fix to our tree, and it will be available in rpi-update within a week I would think. Once it has had some testing by you lot I'll close this issue.

**Comment by stephanedamo** [comment]
Wow, such a nice reactivity ! Thanks a lot, i'll try your fix and tell you soon.

**Comment by popcornmix** [comment]
Fix should be in latest rpi-update firmware.

**Comment by stephanedamo** [comment]
Works perfectly ! Kudos.

**Comment by JamesH65** [comment]
Cheers.

**Comment by mangelozzi** [comment]
> What graphics driver are you using? This fix was on the legacy stack IIRC, it may be that FKMS and KMS need a similar fix? @6by9
I did have this:
```
 Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
max_framebuffers=2
```
But now that I comment out `dtoverlay=vc4-kms-v3d` I dont see the flash. Using `2021-10-30-raspios-bullseye-armhf-lite.img`
