### ISSUE TITLE
USBIP_VUDC module

### ISSUE THREAD

**Issue by grantbow** [raspberrypi/firmware#1064]
Please enabled USBIP_VUDC module as well. I need the "gadgets" USBIP module for a project.

Thank you for adding USBIP. VUDC was not in that list previously.

> Yes, USBIP_CORE, USBIP_HOST and USBIP_VHCI_HCD.

> Thanks!

_Originally posted by @Am1GO in https://github.com/raspberrypi/firmware/issues/353#issuecomment-72849996_

**Comment by popcornmix** [comment]
Added to kernel tree. Will appear in next rpi-update kernel.

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
