### ISSUE TITLE
PI Accepts Any DHCP Offer

### ISSUE THREAD

**Issue by kpelzel0522** [raspberrypi/firmware#1067]
I'm having an issue with network booting a cluster of Raspberry PIs (3B). It appears that booting a single PI works just fine, but the moment a second (or more) is introduced, they no longer boot. After sniffing the packets, the issue seems to be an ip address conflict between the multiple PIs. After some investigation, here's what we've found:

1. The PI seems to accept any DHCP offer that it sees regardless of the mac address that is specified in the offer.
2. The transaction ID of the DHCP discover packet sent from the PI is the same for every PI. (Transaction ID: 0x26f30339). This means that if the PI is verifying a matching transaction ID instead of the mac address in the returning DHCP offer, it will still cause a conflict due to every pi sending the same transaction id. 
3. The PI never sends a ACK packet to finish the DHCP handshake.

These issues (especially 1 & 2) make it impossible to boot two or more PIs simultaneously on the same network. I've attached a wireshark .pcapng file of the traffic for two PIs booting. Also the model of these PIs are 3B.
[rpi_boot.pcapng.zip](https://github.com/raspberrypi/firmware/files/2559904/rpi_boot.pcapng.zip)

**Comment by JamesH65** [comment]
Think this is one for you @ghollingworth but will flag up @pelwell  as well!

**Comment by ghollingworth** [comment]
Looking at the dump it looks like the reason why your system doesn't work is because your DHCP server broadcasts it's replies (all the other DHCP servers don't do this they reply to the macaddress that sent the DHCP request)

If you use ISC dhcp or dnsmasq to server DHCP addresses it'll work fine

Gordon
