### ISSUE TITLE
hello_pi missing library reference

### ISSUE THREAD

**Issue by TomMettam** [raspberrypi/firmware#1073]
It seems that hello_pi is missing a reference to -lvchostif, which is needed by hello_videocube, hello_triangle, etc (vc_dispmanx_update_start undefined reference)

Perhaps this is a change for the Pi 3?

**Comment by JamesH65** [comment]
This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.
