### ISSUE TITLE
hello_triangle2, "vertex" attribute of mandelbrot program is not setup

### ISSUE THREAD

**Issue by kaomoneus** [raspberrypi/firmware#1077]
Namely state->attr_vertex2 is always unitialized.
And it perhaps works due to bug in gles2 implementation, somehow it get linkage for the same-name attribute from another (julia) shader.

**Comment by kaomoneus** [comment]
Please find a patch in attachment.
--Cheers!

[attr_vertex2-issue-1077.patch.txt](https://github.com/raspberrypi/firmware/files/2630417/attr_vertex2-issue-1077.patch.txt)

**Comment by 6by9** [comment]
Please create a Pull Request against https://github.com/raspberrypi/userland/tree/master/host_applications/linux/apps/hello_pi. Userland is the source of these files.

**Comment by JamesH65** [comment]
I beleive this has been done so closing.

https://github.com/raspberrypi/userland/pull/508
