### ISSUE TITLE
rpi3b core timer in aarch64 mode

### ISSUE THREAD

**Issue by mlelstv** [raspberrypi/firmware#1083]
I am running a NetBSD kernel for aarch64 on a RPI3b. When busy, after some time, the timer interrupt stops. The timer interrupt is driven by the virtual ARMv8 generic timer. I have tracked this to the
core timer that apparently is reset to a low value, possibly zero. It then takes a long time to reach
the comparison value and trigger the next timer interrupt. Writing a reasonable value to the core
timer registers makes the interrupt trigger again and the clock continues.

Since nothing in the kernel would regularly write to the core timer and cause such a reset I was
wondering if the firmware can do this under some condition?

**Comment by pelwell** [comment]
The firmware/VPU does not have access to the per-core timers, so it can't be responsible for the resets.

**Comment by mlelstv** [comment]
The per-core timers are driven by the 'core timer', a local peripheral at 0x400001c/020. Is that also unreachable by the VPU ?

**Comment by popcornmix** [comment]
GPU cannot access peripherals at 0x4xxxxxxx addresses (it see's it's own L2 cache at that address).

**Comment by mlelstv** [comment]
Understood. Thanks for the answer.
