### ISSUE TITLE
Location of pre-compiled headers?

### ISSUE THREAD

**Issue by graysky2** [raspberrypi/firmware#1086]
I understand that https://github.com/raspberrypi/firmware provides the precompiled kernel and modules.  Shouldn't it also provide the corresponding precompiled headers?

**Comment by popcornmix** [comment]
You may have to explain what you mean by precompiled headers.

**Comment by graysky2** [comment]
Yes... in other words, if I copy the `modules/* to `/lib/modules/xxx/` and if I copy `kernel7.img` to `/boot` I am able to boot this kernel.  I am unable to build an out-of-tree modules though... I need the corresponding headers to do that.  I hope that makes sense.  Thanks!

**Comment by popcornmix** [comment]
If you are using kernel from apt (recommended) you can install kernel headers in the usual debian way:
sudo apt-get install raspberrypi-kernel-headers

If you are using rpi-update the you can use this:
https://github.com/notro/rpi-source/wiki

The kernel headers are a huge number of files, so won't be shipped as part of the firmware repo.

**Comment by graysky2** [comment]
OK, thanks.
