### ISSUE TITLE
Red led no green led

### ISSUE THREAD

**Issue by LewaIngame** [raspberrypi/firmware#1109]
Hello i have bought my raspberry pi 3b+ and the problem is no boot with my linux rasbian lite
plz help

**Comment by LewaIngame** [comment]
help plz

**Comment by pelwell** [comment]
If the green LED never comes on then unfortunately the Pi is faulty and should be returned to your supplier.

**Comment by LewaIngame** [comment]
my pi was work 4h and crashed and no response

**Comment by LewaIngame** [comment]
usb not word and hdmi too

**Comment by LewaIngame** [comment]
up

**Comment by pelwell** [comment]
> If the green LED never comes on then unfortunately the Pi is faulty and should be returned to your supplier.

**Comment by JamesH65** [comment]
This is the sort of issue that should be dealt with on the forums, not in the firmware repo issues list. Please start a thread there if you want more information.
