### ISSUE TITLE
hdmi_enable_4k is ignored

### ISSUE THREAD

**Issue by kapetanos** [raspberrypi/firmware#1156]
It seems that hdmi_enable_4k=1 in config.txt is ignored. With or without the option, my TV still gets a 4K resolution.

pi@raspberrypi:~ $ tvservice -s
state 0xa [HDMI CUSTOM RGB lim 16:9], 3840x2160 @ 30.00Hz, progressive

pi@raspberrypi:~ $ vcgencmd get_config hdmi_enable_4k
hdmi_enable_4k=0

Firmware version:
Jun 20 2019 16:04:31 
Copyright (c) 2012 Broadcom
version 407b1da8fa3d1a7108cb1d250f5064a3420d2b7d (clean) (release) (start)

**Comment by popcornmix** [comment]
hdmi_enable_4k=1 enables 4kp60 (which requires higher clocks and scrambling).
4kp30 is available without this setting if display's edid reports support..

**Comment by kapetanos** [comment]
Thanks. It seems that the documentation at https://github.com/raspberrypi/documentation/blob/master/configuration/hdmi-config.md is not clear about this.

**Comment by popcornmix** [comment]
@JamesH65 I agree - documentation isn't clear on this option.

**Comment by JamesH65** [comment]
Indeed, the docs were written before the change to the functionality - originally that option enabled all variants of 4k. It should really have changed name to hdmi_enable_4kp60 but the change was too close to release. I'll do the docs tomorrow.

**Comment by JamesH65** [comment]
Docs have been updated.
