### ISSUE TITLE
Pi4: has no entry in dt-blob.dts 

### ISSUE THREAD

**Issue by D-Alex** [raspberrypi/firmware#1176]
It seems dt-blob.dts is outdated as there are no changes for the last 7months. Everything else was updated 2 days ago. 

Is it possible to also release the new dt-blob.dts file?

**Comment by Picardu57** [comment]
Hello,
I need the revision of dt-blob.dts too to sync the camera flash on a pi4.

**Comment by pelwell** [comment]
Fixed by https://github.com/raspberrypi/firmware/commit/f6d9f139037bf421d5d25b1cebe1a67394542b4b.

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
