### ISSUE TITLE
[Question] Clock ID (mailbox property interface) of EMMC2

### ISSUE THREAD

**Issue by lategoodbye** [raspberrypi/firmware#1179]
Is the the clock of the EMMC2 interface on the Pi 4 accessible via mailbox property interface (at least "Get clock rate" 0x00030002)?
Which ID does the clock have?

**Comment by popcornmix** [comment]
Looks like it doesn't currently. Let me see if it can be added.

**Comment by popcornmix** [comment]
Latest rpi-update firmware has support for this. Use clock id=12 for emmc2.

**Comment by lategoodbye** [comment]
@vianpl @agherzan I think this is a necessary puzzle piece for the u-boot sdhci-bcm2835 driver, which get the current clock rate via mailbox interface.

**Comment by agherzan** [comment]
That is definitely a good point @lategoodbye . Also in my case the dts was incorrectly using the old address for the SD card interface.

**Comment by agherzan** [comment]
@lategoodbye there is also another bit that might be missing. The kernel uses a 1.8 regulator for the emmc2 interface.

**Comment by lategoodbye** [comment]
I'm not sure what you meant with old address of the SD card interface. The emmc2 is an additional interface (3rd), so we need to extend the driver with an additional compatible for the emmc2 interface. Yes, the 1.8 regulator new but not essential for booting.

**Comment by vianpl** [comment]
@mbgg might be interested

**Comment by agherzan** [comment]
@lategoodbye that's basically what I meant. I'll make the changes, test and push to the same branch.

**Comment by agherzan** [comment]
@popcornmix , can you also confirm the power device id?

**Comment by popcornmix** [comment]
There is no separate power domain for emmc2. It will be powered as long as arm is running.

**Comment by agherzan** [comment]
Thanks @popcornmix . I asked because I thought my current issue is somehow related to that. What happens is that the arm hangs as soon as I reset sdhci (0x2F). I've checked the ioaddr and it is `fe340000` and also the clock if used as being 12. Any brilliant ideas?

**Comment by lurch** [comment]
I've just added EMMC2 to https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface#clocks

P.S. Hello @agherzan :wave:

**Comment by agherzan** [comment]
@lurch Nice. Thanks.

**Comment by agherzan** [comment]
With some help from @mbgg https://github.com/agherzan/u-boot/tree/ag/rpi4 now contains support for both 32 and 64bit Raspberry Pi 4.

**Comment by pelwell** [comment]
Nice work - congratulations!

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
