### ISSUE TITLE
Raspberry Pi Keyboard Issue

### ISSUE THREAD

**Issue by TobyM10** [raspberrypi/firmware#119]
After having the device descriptor error with my keyboard. I decided to take the advice of another user  GriffenJBS on a different thread and purchase a powered usb hub. But I still receive the same error. 
My keyboard is a Microsoft Keyboard 600 listed as compatible with the pi on the Wikipedia site
I know The powered usb hub and keyboard are both working as I've tested them with 2 different laptops. Has anybody got any suggestions or experiencing similar problems?

**Comment by Ruffio** [comment]
@TobyM10 is this still an issue?

**Comment by Ruffio** [comment]
It looks like this issue is stalled as there have been no response for almost half a year now...
