### ISSUE TITLE
hello_fft exists with "Unable to enable V3D" on a Raspberry Pi 4

### ISSUE THREAD

**Issue by rreckel** [raspberrypi/firmware#1205]
As the title says, hello_fft.bin exists with the following message:
```
Unable to enable V3D. Please check your firmware is up to date.
```
even after using rpi-update

**Comment by popcornmix** [comment]
That is not supported on a Pi4. The 3d shader hardware which helllo_fft uses is quite different.

**Comment by popcornmix** [comment]
It is very likely that the arm cores are faster at doing ffts than the shaders on a Pi4 now.

**Comment by rreckel** [comment]
Ok. You can close the issue then.
I will only reference this issue on another project, so that everybody using a RPI4 uses the non GPU accelerated version.

Thanks
