### ISSUE TITLE
Tvservice does not detect modes via VGA666 on RPi4

### ISSUE THREAD

**Issue by alphanu1** [raspberrypi/firmware#1206]
Tvservice shows 0 modes for DMT and CEA on RPi4. This also means it no longer has the ability to change to these modes.

**Comment by JamesH65** [comment]
Please do not raise the same issue on two repos. The same people keep an eye on both, so it won't be missed, but duplicates make it VERY difficult to maintain a coherent dialog.

**Comment by JamesH65** [comment]
Please continue here https://github.com/raspberrypi/firmware/issues/1206

**Comment by pelwell** [comment]
I think you mean here: https://github.com/raspberrypi/userland/issues/566

**Comment by alphanu1** [comment]
Sorry, I realised this was not the right place for this issue. I forgot to close it after opening it in the right place.
