### ISSUE TITLE
Query: vcdbg version shows "(tainted)"

### ISSUE THREAD

**Issue by shib** [raspberrypi/firmware#1212]
What does "tainted" mean? 

The bootloader and other raspberrypi libs are stock version (The kernel is custom though). But it's tainted?

`pi@localhost:~ $ cat /etc/debian_version'
8.0

`pi@localhost:~ $ sudo vcdbg version`
vcos_build_version     = 4139c62f14cafdb7d918a3eaa0dbd68cf434e0d8 (tainted)
vcos_build_branch      = master
debug_sym: ReadVideoCoreMemoryBySymbol: Symbol not found: 'vcos_build_application'
vcos_build_application = ?
vcos_build_date        = Jul  3 2017
vcos_build_time        = 14:16:43
vcos_build_user        = dc4
vcos_build_hostname    = dc4-XPS13-9333
vcos_build_platform    = raspberrypi_linux
debug_sym: ReadVideoCoreMemoryBySymbol: Symbol not found: 'vcos_build_type
vcos_build_type        = ?`

`pi@localhost:~ $ dpkg -l | grep raspb`
ii  libraspberrypi-bin              1.20170703-1                     armhf        Miscellaneous Raspberry Pi utilities
ii  libraspberrypi-dev              1.20170703-1                     armhf        EGL/GLES/OpenVG/etc. libraries for the Raspberry Pi's VideoCore IV (headers)
ii  libraspberrypi-doc              1.20170703-1                     armhf        EGL/GLES/OpenVG/etc. libraries for the Raspberry Pi's VideoCore IV (headers)
ii  libraspberrypi0                 1.20170703-1                     armhf        EGL/GLES/OpenVG/etc. libraries for the Raspberry Pi's VideoCore IV
ii  raspberrypi-bootloader          1.20170703-1                     armhf        Raspberry Pi bootloader

`pi@localhost:~ $ uname -a`
Linux localhost 4.4.50-v7+ #1 SMP Mon Feb 5 02:51:30 UTC 2018 armv7l GNU/Linux

**Comment by pelwell** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=62006

It's just a glitch in the firmware build process - ignore it.
