### ISSUE TITLE
When i play a wav file with omxplayer in raspberry pi 3b+, i got a error code 0x80001005, can anyone tell me what's the meaning of that.

### ISSUE THREAD

**Issue by yxdming** [raspberrypi/firmware#1220]
when i play a wav file in raspberry 3b+ with omxplayer, it output nothing. And i found there are error messages in the omxplayer log file like that.

Does anyone tell me what's the meaning of error code 0x80001005, is it the limitation of hwrdware.

Because the samplerate of my wav file is 250000, so i change the parameter from 192000 to 250000 in ```OMXCore.cpp``` and recompile omxplayer again.

```
m_pcm_output.nSamplingRate = std::min(std::max((int)m_pcm_output.nSamplingRate, 8000), 250000);

m_pcm_output.nPortIndex = m_omx_mixer.GetOutputPort();
omx_err = m_omx_mixer.SetParameter(OMX_IndexParamAudioPcm, &m_pcm_output);
if(omx_err != OMX_ErrorNone)
{
  Logme(LOGERROR, "%s::%s - error m_omx_mixer SetParameter omx_err(0x%08x)", CLASSNAME, __func__, omx_err);
  return false;
}
```

when i play the wav file, i got the error message from the omxplayer.log as below:

```
15:31:54 T:2041236533 [OMXCore.cpp][SetParameter][1153] ERROR: COMXCoreComponent::SetParameter - OMX.broadcom.audio_mixer failed with omx_err(0x80001005)
15:31:54 T:2041236566 [OMXAudio.cpp][PortSettingsChanged][149] ERROR: COMXAudio::PortSettingsChanged - error m_omx_mixer SetParameter omx_err(0x80001005)
15:31:54 T:2041236591 [OMXAudio.cpp][AddPackets][982] ERROR: COMXAudio::AddPackets - error PortSettingsChanged omx_err(0x00000000)
```

and i found the definition of  error code ```0x80001005``` from the firmware code:

```
hardfp/opt/vc/include/IL/OMX_Core.h: OMX_ErrorBadParameter = (OMX_S32) 0x80001005,
/** One or more parameters were not valid */
OMX_ErrorBadParameter = (OMX_S32) 0x80001005,
```

So, what's the meaning of ```0x80001005``` and which parameter is valid?

Thanks.

**Comment by popcornmix** [comment]
Your question has been answered here: https://github.com/popcornmix/omxplayer/issues/735
