### ISSUE TITLE
xen boot on raspberry pi3 using efi-grub framework

### ISSUE THREAD

**Issue by dhananjayj29** [raspberrypi/firmware#1245]
I have tried booting xen on rpi3 using ubuntu 18.04 as dom0 , I have successfully installed xen hypervisor packages as well as tools using apt-get . 
finally grub setting is done to add xen option in one of the grub menu , When I try to boot rpi3 with xen enabled ubuntu I get the following error:
"synchronous abort" handler .......... 
prints some addresses and registers 
and finally
Reseting the CPU......

Does anyone has tried xen on rpi3 ..pl let me know

**Comment by JamesH65** [comment]
This is a question for the forum, not the firmware repo.
