### ISSUE TITLE
rpi 2 - ethernet led issue

### ISSUE THREAD

**Issue by Schlunze** [raspberrypi/firmware#1252]
**Hello,**

after set the following options in config.txt (rpi 2)
> dtparam=eth_led0=14
dtparam=eth_led1=14

ethernet leds still on after reboot. 
I expected them to be off on pi2 according to your [readme](https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README).
OS is libreelec (9.1.501) if this matters.

tx in advance for your reply

**Comment by trejan** [comment]
The documentation needs to be updated. eth_led0 and eth_led1 are only for the LAN7515 USB Ethernet chip used in the 3B+. The 3B and earlier boards have a completely different USB Ethernet chip which doesn't use those two options. You need to download and run the lan951x-led-ctl utility at each boot to turn off the LEDs.

**Comment by Schlunze** [comment]
Thank you for the useful information trejan.

Greetings
