### ISSUE TITLE
mmc0: error -84 whilst initialising SD card

### ISSUE THREAD

**Issue by rebroad** [raspberrypi/firmware#127]
This is on a new raspberry pi from element14 (SD card also from element14). Only changes have been a dist-upgrade. Extract fro dmesg:-

[    1.261911] Waiting for root device /dev/mmcblk0p2...
[    1.335949] mmc0: problem reading SD Status register.
[    1.338761] mmc0: error -84 whilst initialising SD card
[    1.437154] mmc0: problem reading SD Status register.
[    1.440229] Indeed it is in host mode hprt0 = 00021501
[    1.449582] mmc0: error -84 whilst initialising SD card
[    1.559803] mmc0: problem reading SD Status register.
[    1.563112] mmc0: error -84 whilst initialising SD card
[    1.639595] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.639767] Indeed it is in host mode hprt0 = 00001101
[    1.716980] mmc0: new high speed SDHC card at address 59b4
[    1.717629] mmcblk0: mmc0:59b4 00000 3.67 GiB
[    1.719247]  mmcblk0: p1 p2

The raspberry then continues to boot up with no problems.

**Comment by Ruffio** [comment]
@rebroad is this still an issue?

**Comment by Ruffio** [comment]
This issue should be closed due to inactivity

**Comment by pelwell** [comment]
We have a brand new driver using a different hardware interface. This issue is obsolete

**Comment by jeremysalwen** [comment]
I am getting exactly the same errors (`mmc3:  problem reading SD Status register` once, and repeatedly `mmc3: error -84 whilst initialising SD card`) on my Raspberry Pi 4B, when I connect the SDHCI controller to the SD Card slot, as described here: https://github.com/raspberrypi/documentation/issues/1209#issuecomment-513797407 .

This reproduces with multiple SD cards, and the sdhci controller is not connected to any other GPIOs when this is occurring.

Should I reopen this issue or create a new one?

**Comment by pelwell** [comment]
New issue, please - and state exactly what you have done and why (it often helps).
