### ISSUE TITLE
Documentation update Special bootcode.bin-only boot mode

### ISSUE THREAD

**Issue by treble2019** [raspberrypi/firmware#1305]
**Describe the bug**
Please add the 
https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/bootmodes/README.md#special-bootcodebin-only-boot-mode

to 
https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md

**Comment by pelwell** [comment]
I think you would agree this is a documentation issue, and should be opened in the [documentation repo](https://github.com/raspberrypi/documentation/issues).
