### ISSUE TITLE
Am I blocked or something?

### ISSUE THREAD

**Issue by persianpros** [raspberrypi/firmware#1330]
Hello,

Would you please check your blocklist for my account? We at Open Vision are working on enigma2 for RPi and I can't see any of your repos which I don't know why.

https://github.com/OpenVisionE2/meta-raspberrypi

**Comment by pelwell** [comment]
You can see this repo. What happens when you visit https://github.com/raspberrypi/linux/ ?

**Comment by persianpros** [comment]
I can see it but when I browse https://github.com/raspberrypi I see only 6 pinned repos and below is empty, is it ok?

**Comment by pelwell** [comment]
It's sounds like you are on the mobile site. Click the Repositories tab at the top of the page, or switch to the desktop version.

I'm pretty sure you aren't blocked, but reopen this issue if you find something specific that you can't do

**Comment by persianpros** [comment]
I'm using Firefox on Ubuntu 18.04 and I'm on the repositories tab but still I can see only pinned repos that's all!

**Comment by pelwell** [comment]
Try with the Firefox version of Incognito mode.

**Comment by persianpros** [comment]
It works but the moment I login everything will be gone. That's I'm trying to tell.

**Comment by pelwell** [comment]
If you can create an issue then you're not blocked by our organisation.

https://github.com/raspberrypi/usbboot is not one of the 6 pinned repos - can you view it?

**Comment by pelwell** [comment]
I've asked an admin and I can confirm that you aren't blocked - there must be something wrong with the settings on your browser or GitHub account.
