### ISSUE TITLE
/memreserve/ doesn't account for PSCI

### ISSUE THREAD

**Issue by kevans91** [raspberrypi/firmware#1340]
Hi,

The /memreserve/ regions in the RPi3/4 DTB currently include only the first page of memory. For spin-table, the default, this is fine, but the PSCI stubs (used by FreeBSD) available over in raspberrypi/tools surpass this by one more page, so early bootloaders or OS boot are free to clobber the latter part of the PSCI stubs and hilarity ensures.

Any chance of increasing these to cover the first two pages instead?

**Comment by pelwell** [comment]
I'm happy to take a Pull Request against our Linux repo.

**Comment by kevans91** [comment]
> I'm happy to take a Pull Request against our Linux repo.

Ah, it wasn't clear to me that the .dts for the .dtb's committed in this repo were available over there -- will do, thanks.

**Comment by pelwell** [comment]
By the way, where are the PSCI stubs in raspberrypi/tools?

**Comment by kevans91** [comment]
Whoops, sorry, I was referring to these guys: https://github.com/raspberrypi/tools/tree/master/armstubs

**Comment by pelwell** [comment]
Those stubs aren't PSCI stubs, and they're small, hence my confusion.

**Comment by kevans91** [comment]
Ah, shoot- I managed to confuse myself, since we derived parts of what we use from there. Local problem; sorry...
