### ISSUE TITLE
More information on SPI and NAND boot modes

### ISSUE THREAD

**Issue by LonerDan** [raspberrypi/firmware#1355]
Hello,
in the documentation of the GPIO boot mode, there is a mention of SPI and NAND boot modes with a note that there is no Linux support for them at the time. 
![image](https://user-images.githubusercontent.com/11718484/77224399-92facb80-6b65-11ea-990a-677acfe35506.png)
Since those boot modes especially intrigue me for my use case, I wanted to ask for more information. Is the Linux support being worked on? Alternatively, could this boot mode be used to load next stage bootloader (e.g. u-boot) that would then boot the full system (either from the same source or from sd card)?

**Comment by MDr164** [comment]
I think it has somewhat been discussed here https://github.com/raspberrypi/firmware/issues/874 as well but there is no further clarification to be found somewhere. The documentation still says those two modes are somewhat supported but not how to actually make use of them. The documentation also says those are being cycled through by the first stage bootloader but that's about it. The linked issue says those modes don't work while docs says otherwise but not how. Still kind of confusing.

**Comment by pelwell** [comment]
Documenting a feature that we have no plan to use (and haven't spent time finding the pitfalls of) isn't a good use of resources. Users would be forgiven for thinking that the feature was both tested and supported, when the opposite is true.

**Comment by MDr164** [comment]
Yes that makes total sense, but please then remove the lines in the documentation on raspberrypi.com, stating it works then OR add a disclaimer that it technically works when looking at the SoC side of things but that it's not implemented (and probably won't be). As of now it just unnecessarily confuses users reading that.

**Comment by JamesH65** [comment]
Can you link to the page in question?

**Comment by pelwell** [comment]
Confuses? Not the most obvious word for that sentence. Teases, perhaps, although that's not the intention. By documenting what the bit does (if not how to use it) the hope is that it saves curiosity from killing the Pi.

Won't fix.

**Comment by MDr164** [comment]
https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#boot-sequence is the page in question and the line that "confused" me in this case would be "NAND boot and SPI boot modes do work, although they do not yet have full GPU support." which was also mentioned in the linked issue. I think the fact that it explicitly says NAND boot and SPI boot modes do work should also mention what works in that context means, like the SoC support is there but the firmware has no support for that.
