### ISSUE TITLE
rpi4 buster bluetooth and wlan conflict

### ISSUE THREAD

**Issue by akicker** [raspberrypi/firmware#1360]
With the update from 27.3. (updating bluetooth, ... to bluetooth (5.50-1.2\~deb10u1)) raspbian buster on rpi4 bluetooth and wlan did work well (the first time on my rpi4) !!! :+1: 
Unfortunately updates from 30.3. to bluetooth (5.50-1.2\~deb10u1+rpt1 and 11 other updates) bluetooth and wlan conflicts again (BT off --> wlan ok, BT on --> very low wlan rx-rate). :-1: 
current using buster kernel 4.19.97

**Comment by pelwell** [comment]
I think this is the cause of a number of recent Bluetooth problem reports, but this isn't the right repo (it's firmware, but not VPU firmware) and it's been reported already (just not so concisely).

If you report it at the correct firmware repo - https://github.com/RPi-Distro/firmware-nonfree/issues - I'll redirect the other issues there.
