### ISSUE TITLE
Incorrect "linux,initrd-end" address (with extra DWORD padding)

### ISSUE THREAD

**Issue by kirgene** [raspberrypi/firmware#1395]
initramfs image is loaded into ram with additional (DWORD) padding

**To reproduce**
create initramfs image (`initrd.gz`) which size is not multiple of 4

**OR**

create a file which will be used as an initramfs image:
```
dd if=/dev/urandom of=initrd.gz bs=9957521 count=1
```

Add the following line to [initramfs.c:660](https://github.com/raspberrypi/linux/blob/79495a5ecdfba69de51e88701a69c42d09806d84/init/initramfs.c#L660) to debug this error:

```
printk(KERN_INFO "start = %x %x, end = %x %x %x %x\n", ((unsigned char *)initrd_start)[0], ((unsigned char *)initrd_start)[1], ((unsigned char *)(initrd_end - 4))[0], ((unsigned char *)(initrd_end - 3))[0], ((unsigned char *)(initrd_end - 2))[0], ((unsigned char *)(initrd_end - 1))[0]);
```

Boot system with the following line in config:
```
initramfs initrd.gz
```

**Expected behaviour**
system boots with initramfs image

**Actual behaviour**
kernel panic with the following messages:
```
Trying to unpack rootfs image as initramfs...
rootfs image is not initramfs (Decoding failed); looks like an initrd
```

**System**
Raspberry Pi 1 Model B Rev. 2
Firmware rev: a6c9b6b48ce86ef2527586a50760d52f1b33f642
Kernel: 5.4.42

**Comment by pelwell** [comment]
Alignment can't be the issue here, but it's possible the decompression code is checking the length. This is the first report of a problem with the file length padding so your choice of compression might be unusual, but it is clearly safer to preserve the lengths.

Are you using the default loader (start.elf) or one of the other variants? I can get you a test build of a patched version to confirm it works.

**Comment by pelwell** [comment]
You can download a complete firmware build here: https://drive.google.com/file/d/1GQFhQPt0uNGi2iYvnc20VpjjtG9Ugo65/view?usp=sharing
Feel free to only install the relevant version.

**Comment by pelwell** [comment]
The current rpi-update firmware release includes this fix.

**Comment by kirgene** [comment]
It works, thanks @pelwell
