### ISSUE TITLE
Add udlfb for displaylink screens

### ISSUE THREAD

**Issue by pssc** [raspberrypi/firmware#141]
A number of people seem to have had luck with display-link touch screens the currently involves replacing the whole kernel.

--- -   2013-01-29 10:30:20.596892704 +0000
+++ .config     2013-01-28 12:44:18.088627426 +0000
@@ -2227,16 +2227,17 @@
 CONFIG_FB_CFB_COPYAREA=y
 CONFIG_FB_CFB_IMAGEBLIT=y
 # CONFIG_FB_CFB_REV_PIXELS_IN_BYTE is not set
-# CONFIG_FB_SYS_FILLRECT is not set
-# CONFIG_FB_SYS_COPYAREA is not set
-# CONFIG_FB_SYS_IMAGEBLIT is not set
+CONFIG_FB_SYS_FILLRECT=m
+CONFIG_FB_SYS_COPYAREA=m
+CONFIG_FB_SYS_IMAGEBLIT=m
 # CONFIG_FB_FOREIGN_ENDIAN is not set
-# CONFIG_FB_SYS_FOPS is not set
+CONFIG_FB_SYS_FOPS=m
 # CONFIG_FB_WMT_GE_ROPS is not set
+CONFIG_FB_DEFERRED_IO=y
 # CONFIG_FB_SVGALIB is not set
 # CONFIG_FB_MACMODES is not set
 # CONFIG_FB_BACKLIGHT is not set
-# CONFIG_FB_MODE_HELPERS is not set
+CONFIG_FB_MODE_HELPERS=y
 # CONFIG_FB_TILEBLITTING is not set
 
 #
@@ -2247,7 +2248,7 @@
 # CONFIG_FB_UVESA is not set
 # CONFIG_FB_S1D13XXX is not set
 # CONFIG_FB_SMSCUFX is not set
-# CONFIG_FB_UDL is not set
+CONFIG_FB_UDL=m
 # CONFIG_FB_VIRTUAL is not set
 # CONFIG_FB_METRONOME is not set
 # CONFIG_FB_BROADSHEET is not set

**Comment by pssc** [comment]
Ok I am know longer sure what’s stopping this being enabled given deferred io has been enabled for the pitft drivers.

**Comment by popcornmix** [comment]
Okay, will enable and keep an eye out for any reports.

**Comment by pssc** [comment]
@popcornmix ok thanks will test with a MIMo720S and Pluggable USB2.0 adaptor.

**Comment by popcornmix** [comment]
Should be enabled now. Can you rpi-update and test?

**Comment by pssc** [comment]
[14937.223886] usb 1-1.3.3: new high-speed USB device number 10 using dwc_otg
[14937.323980] usb 1-1.3.3: New USB device found, idVendor=058f, idProduct=6254
[14937.324022] usb 1-1.3.3: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[14937.328983] hub 1-1.3.3:1.0: USB hub found
[14937.329325] hub 1-1.3.3:1.0: 4 ports detected
[14937.604041] usb 1-1.3.3.2: new high-speed USB device number 11 using dwc_otg
[14937.727582] usb 1-1.3.3.2: New USB device found, idVendor=17e9, idProduct=0335
[14937.727670] usb 1-1.3.3.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[14937.727692] usb 1-1.3.3.2: Product: MIMO
[14937.727709] usb 1-1.3.3.2: Manufacturer: DisplayLink
[14937.727778] usb 1-1.3.3.2: SerialNumber: 1071101867
[14937.833905] usb 1-1.3.3.3: new full-speed USB device number 12 using dwc_otg
[14937.947628] udlfb: DisplayLink MIMO - serial #1071101867
[14937.950357] udlfb: vid_17e9&pid_0335&rev_0120 driver's dlfb_data struct at cb48f800
[14937.950462] udlfb: console enable=1
[14937.950586] udlfb: fb_defio enable=1
[14937.964512] udlfb: shadow enable=1
[14937.965130] udlfb: vendor descriptor length:23 data:23 5f 01 00 21 00 04 04 07 00 01
[14937.965220] udlfb: DL chip limited to 1500000 pixel modes
[14937.972029] usb 1-1.3.3.3: New USB device found, idVendor=1ac7, idProduct=0001
[14937.972168] usb 1-1.3.3.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[14937.972728] usb 1-1.3.3.3: Product: USB Touchpanel
[14937.972913] usb 1-1.3.3.3: Manufacturer: e2i Technology, Inc.
[14937.973001] usb 1-1.3.3.3: SerialNumber: L000000000
[14938.011480] udlfb: allocated 4 65024 byte urbs
[14938.040129] usbcore: registered new interface driver udlfb
[14938.190155] udlfb: 800x480 @ 59 Hz valid mode
[14938.190347] udlfb: Reallocating framebuffer. Addresses will change!
[14938.234769] udlfb: 800x480 @ 59 Hz valid mode
[14938.236208] udlfb: set_par mode 800x480
[14938.286006] udlfb: DisplayLink USB device /dev/fb2 attached. 800x480 resolution. Using 1504K framebuffer memory
[14938.439105] input: e2i Technology, Inc. USB Touchpanel as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3.3/1-1.3.3.3/1-1.3.3.3:1.0/input/input9
[14938.449138] usbcore: registered new interface driver usbtouchscreen
root@raspberrypi:/home/pi# FBDEV=/dev/fb2 FPS=12 /opt/squeezeplay/bin/fbcp

Screen replicated onto MIMO 720S device nicely

**Comment by popcornmix** [comment]
Okay to close?

**Comment by pssc** [comment]
@popcornmix yup slay the 2 year old issue!

**Comment by jwilker2** [comment]
Hooray!

On Tue, Mar 24, 2015 at 10:45 AM, popcornmix <notifications@github.com>
wrote:

> Closed #141 <https://github.com/raspberrypi/firmware/issues/141>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raspberrypi/firmware/issues/141#event-263674686>.
>



-- 
*"The most exciting phrase to hear in science, the one that heralds new
discoveries, is not 'Eureka!' but 'That's funny...'" - Isaac Asimov*

**Comment by philharlow** [comment]
@pssc did you do anything extra to get the touchscreen to register? If I take a fresh copy of rasbian (2/16), run sudo rpi-update, sudo reboot and then connect my 720S via hub, the screen now turns green, so the udlfb part is working, but I am still get the 'device descriptor read/64, error -71' errors and the touchscreen doesn't register. Are you using the dwc_otg.speed=1 modification to use USB1.1 speeds? Also, sorry if this is the wrong place for this!

**Comment by pssc** [comment]
@philharlow is the usb t/s module loaded "insmod usbtouchscreen", mine's at home so I can have a poke tomorrow if needed (mine is also connected through a hub), evtest can be useful for debugging once you have an input device. Also  lsusb -tv see if you can see a hub with the screen and a hid/ts device.

**Comment by pssc** [comment]
@philharlow not a via chipset usb3 hub it is it?

**Comment by philharlow** [comment]
@pssc Thanks for the response! I apologize, I'm very green when discussing linux modules, kernels and usb protocol. I'm taking a fresh image of raspbian, setting it up to boot to x11, running sudo rpi-update, rebooting, then connecting the screen. I have my wireless mouse/kb adapter and the pi iteself (for power) plugged into the hub as well as the screen. I see this same result with two different usb 2.0 hubs I have.
When I run 'insmod usbtouchscreen' I get 'Error: could not load module usbtouchscreen: No such file or directory'.
When I run 'lsusb -tv' I get http://pastie.org/10081708. 
This is the tail of my dmesg: http://pastie.org/10081710
In the dmesg you can see the -71 errors I get where yours is happy. @jwilker2 found a workaround via dropping usb speeds by adding 'dwc_otg.speed=1' to the /boot/cmdline.txt file, and this does work for me and the screen registers without errors, but it nukes some other usb devices I was hoping to use as well. I also tried adding your 'dwc_otg.fiq_fsm_mask=0xf' to my /boot/cmdline.txt just in case that inadvertently did it, but still an error. I don't know what next steps I could try to debug this so if you had any ideas or could point me in the right direction it'd be greatly appreciated! Thanks!

**Comment by pssc** [comment]
@philharlow ok You shouldnt need dwc_otg.speed=1 all devices in the screen are 2.0 ,
type modprobe usbtouchscreen , if you get the green screen the framebuffer is working, can you give full dmesg ouput without  dwc_otg.speed=1

**Comment by philharlow** [comment]
@pssc Ok thanks. I ran sudo modprobe usbtouchscreen but didn't get any output, then connected screen and then here's the full dmesg: http://pastie.org/10082148 Thanks again!

**Comment by pssc** [comment]
@philharlow that's normal will go home tonight and compare output from my
working setup.

On 9 April 2015 at 11:24, philharlow <notifications@github.com> wrote:

> @pssc <https://github.com/pssc> Ok thanks. I ran sudo modprobe
> usbtouchscreen but didn't get any output, then connected screen and then
> here's the full dmesg: http://pastie.org/10082148 Thanks again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raspberrypi/firmware/issues/141#issuecomment-91185877>
> .
>



-- 
I Can Resist Everything Except Temptation -- Oscar Wilde

**Comment by philharlow** [comment]
Ok thank you!

**Comment by pssc** [comment]
@philharlow ```
root@raspberrypi:/home/pi# lsusb -tv
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=hub, Driver=hub/3p, 480M
        |__ Port 1: Dev 3, If 0, Class=vend., Driver=smsc95xx, 480M
        |__ Port 3: Dev 4, If 0, Class=hub, Driver=hub/7p, 480M
            |__ Port 1: Dev 5, If 0, Class=audio, Driver=snd-usb-audio, 12M
            |__ Port 1: Dev 5, If 1, Class=audio, Driver=snd-usb-audio, 12M
            |__ Port 1: Dev 5, If 2, Class=audio, Driver=snd-usb-audio, 12M
            |__ Port 1: Dev 5, If 3, Class=HID, Driver=usbhid, 12M
            |__ Port 4: Dev 8, If 0, Class=hub, Driver=hub/4p, 480M
                |__ Port 2: Dev 9, If 0, Class=vend., Driver=udlfb, 480M
                |__ Port 3: Dev 10, If 0, Class=vend., Driver=usbtouchscreen, 12M
            |__ Port 6: Dev 6, If 0, Class=HID, Driver=usbhid, 1.5M
            |__ Port 6: Dev 6, If 1, Class=HID, Driver=usbhid, 1.5M

[ 1495.181234] usb 1-1.3.4: new high-speed USB device number 8 using dwc_otg
[ 1495.281240] usb 1-1.3.4: New USB device found, idVendor=058f, idProduct=6254
[ 1495.281282] usb 1-1.3.4: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[ 1495.287657] hub 1-1.3.4:1.0: USB hub found
[ 1495.288058] hub 1-1.3.4:1.0: 4 ports detected
[ 1495.561279] usb 1-1.3.4.2: new high-speed USB device number 9 using dwc_otg
[ 1495.685047] usb 1-1.3.4.2: New USB device found, idVendor=17e9, idProduct=0335
[ 1495.685090] usb 1-1.3.4.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1495.685114] usb 1-1.3.4.2: Product: MIMO
[ 1495.685132] usb 1-1.3.4.2: Manufacturer: DisplayLink
[ 1495.685150] usb 1-1.3.4.2: SerialNumber: 1071101867
[ 1495.791169] usb 1-1.3.4.3: new full-speed USB device number 10 using dwc_otg
[ 1495.928727] usb 1-1.3.4.3: New USB device found, idVendor=1ac7, idProduct=0001
[ 1495.928966] usb 1-1.3.4.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1495.929180] usb 1-1.3.4.3: Product: USB Touchpanel
[ 1495.929305] usb 1-1.3.4.3: Manufacturer: e2i Technology, Inc.
[ 1495.929409] usb 1-1.3.4.3: SerialNumber: L000000000
[ 1496.019035] udlfb: DisplayLink MIMO - serial #1071101867
[ 1496.019118] udlfb: vid_17e9&pid_0335&rev_0120 driver's dlfb_data struct at d1225800
[ 1496.019135] udlfb: console enable=1
[ 1496.019146] udlfb: fb_defio enable=1
[ 1496.019160] udlfb: shadow enable=1
[ 1496.023385] udlfb: vendor descriptor length:23 data:23 5f 01 00 21 00 04 04 07 00 01
[ 1496.023425] udlfb: DL chip limited to 1500000 pixel modes
[ 1496.024549] udlfb: allocated 4 65024 byte urbs
[ 1496.029915] usbcore: registered new interface driver udlfb
[ 1496.208281] udlfb: 800x480 @ 59 Hz valid mode
[ 1496.208325] udlfb: Reallocating framebuffer. Addresses will change!
[ 1496.212309] udlfb: 800x480 @ 59 Hz valid mode
[ 1496.212346] udlfb: set_par mode 800x480
[ 1496.256812] udlfb: DisplayLink USB device /dev/fb2 attached. 800x480 resolution. Using 1504K framebuffer memory
[ 1496.435436] input: e2i Technology, Inc. USB Touchpanel as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3.4/1-1.3.4.3/1-1.3.4.3:1.0/input/input7
[ 1496.443769] usbcore: registered new interface driver usbtouchscreen

```

**Comment by pssc** [comment]
@philharlow are your hubs usb3 capable?

**Comment by philharlow** [comment]
@pssc They should only USB2.0. One of them was purchased before USB3.0 was even spec'd. I'll go home tonight and enable the dwc_otg.speed=1 to get the touchscreen to register and then Ill post the dmesg and lsusb output in case there's a hint in there? Thanks for the help!

**Comment by philharlow** [comment]
@pssc ok I added the dwc_otg.speed=1 mod and rebooted, then connected the display. Here's my lsusb -tv and dmesg: http://pastie.org/10091179

**Comment by pssc** [comment]
@philharlow what happens if you don't go through the hub? this is looking more like a doggy USB 1.1 pass through issue with the hub.

**Comment by philharlow** [comment]
@pssc Sorry for taking so long to respond! I use a powered hub to power the screen, but I finally was able to test powering it directly with a cable like this http://www.videk.co.uk/section.php/898/1/usb-y-power-cable, with the power side being plugged into an iphone charger, this is my lsusb and dmesg: http://pastie.org/10108598
I then tried this hub as well: http://www.tigerdirect.com/applications/SearchTools/item-details.asp?EdpNo=1155678 and got the same result: http://pastie.org/10108612
Are you able to connect the screen on a fresh image of raspbian?

**Comment by philharlow** [comment]
@pssc As I feel you can never have too many USB hubs, if you link the amazon page for the exact hub you're using, I'm willing to buy it just to eliminate any more variables between our setups. Thanks so much for your continued help with this!

**Comment by philharlow** [comment]
@pssc Could you tell me what hub you're using? I want to order one just to try.

**Comment by pssc** [comment]
@philharlow  http://www.amazon.co.uk/dp/B009R921SE but before you do that you varied the screen works on another box say a x86 linux/windows box?

**Comment by philharlow** [comment]
I just confirmed the touchscreen works on Ubuntu with and without the usb hub, and Windows shows the display, but I cannot get the touchscreen drivers to work, with or without the hub. I'll spend some time trying to get the drivers to work.
Thanks for the link. Haha, I had one of those exact hubs, but can't find it for the life of me, so I've just ordered another. I will report if the hub changes anything. Thanks!

**Comment by philharlow** [comment]
@pssc thanks again for all the help with this. Unfortunately I get the exact same behavior with the pluggable hub. Have you tried your screen working on a fresh copy of raspbian? I wonder if you've installed or configured something that lets the touchscreen work for you?

Thanks again for the help!
