### ISSUE TITLE
Question about GLESv2 and EGL vendor blobs

### ISSUE THREAD

**Issue by wormyrocks** [raspberrypi/firmware#1427]
Hi everyone,

I have a quick question about the Broadcom OpenGL vendor blobs in this repository.
I'm trying to get fully accelerated OpenGL video playback running on a wide range of devices (I'm not touching the Pi 4 for now). Some of the literature around getting OpenGL working on the Pi discusses using rpi-update, or manually grabbing, libGLESv2.so and libEGL.so from this repository.
However, it seems like that's no longer necessary, as libbrcmGLESv2.so and libbrcmEGL.so come packaged with a fresh install of Raspbian. (Buster, 5-24-2020 image). And I've done experiments where I change the linkage from hardware-accelerated video players between these two blobs, and can't detect a difference in output or performance.
So am I correct in assuming that libbrcmGLESv2.so is the same as libGLESv2.so, and libEGL.so is the same as libbrcmEGL.so? They don't pass a straight diff, but it seems like the binaries are exactly the same size, the symbol tables are the same length, and programs can link to either without an issue.
Last question, if there is some reason why I should still be interested in the libGLESv2.so and libEGL.so files, which Pi models should use the ones from the `hardfp` directory?

Thanks in advance!

**Comment by popcornmix** [comment]
libbrcmEGL.so is the preferred name to link against as it avoids conflicts with the mesa libEGL.so library.
libEGL.so in /opt/vc/lib is purely here for backwards compatibility and should probably be removed.

All pi models use the hardfp versions under raspbian. The non-hardfp are only useful for use in a distribution that doesn't use hardfp (e.g. debian armel - but I'm really not sure if anyone is using that on a Pi these days).
