### ISSUE TITLE
Latest stable kernel update broke LCD Driver

### ISSUE THREAD

**Issue by pheiduck** [raspberrypi/firmware#1429]
After the latest Kernel update this https://github.com/goodtft/LCD-show gets broken, the driver doesn’t work, the display stay with after reboot

**Comment by JamesH65** [comment]
You will need to post your issue here https://github.com/goodtft/LCD-show/issues for them to update their code for the latest kernel. Unfortunately, on a big kernel bump (4.19 to 5.4) a lot of things may have changed.

**Comment by pheiduck** [comment]
I downgraded to 4.19 works (temporarily) until the maintainer of LCD-show update their code for 5.4
