### ISSUE TITLE
Why when i boot Raspberry Pi, it will display declare x DBUS SESSION BUS ADDRESS= "unix : path=/ run/user/ 1000/bus"  declare DISPL AY="Localhost:ll. 0"

### ISSUE THREAD

**Issue by Dolphinzzx** [raspberrypi/firmware#1441]
![image](https://user-images.githubusercontent.com/31792429/88887545-2a3c0200-d26f-11ea-9c0d-ca37ef9a499c.png)

**Comment by pelwell** [comment]
This is not the right place to ask this question - it isn't a firmware issue, and it isn't even a Linux kernel issue; our [Forums](https://www.raspberrypi.org/forums/) would be better.

However, I think you must have a stray, lone `export` (with no parameters, or parameters that evaluate to whitespace) in one of your shell initialisation files, e.g.:
```
export
```
or
```
FOO=
export $FOO
```
The last line should say `export FOO`.
