### ISSUE TITLE
Tunneling

### ISSUE THREAD

**Issue by devalexqt** [raspberrypi/firmware#145]
Its possible to use tunnel  with passed data from video_decoder to video_encoder ?
I always get error:

-5: the data format was not acceptable to the sink
Need special configuration?

This my port setup configuration:

OMX_ERRORTYPE r;
   OMX_VIDEO_PARAM_PORTFORMATTYPE in_dec_format,out_enc_format,out_dec_Format;
   OMX_PARAM_PORTDEFINITIONTYPE in_enc_format;
   COMPONENT_T *video_decode = NULL,*video_encode=NULL,*video_resize=NULL, *video_render = NULL;
   COMPONENT_T *list[5];
   TUNNEL_T tunnel[4];
   ILCLIENT_T *client;
   int status = 0;

   memset(list, 0, sizeof(list));
   memset(tunnel, 0, sizeof(tunnel));

   if((client = ilclient_init()) == NULL){printf("=>Can't init ilclient_init()!\n");exit(-1);}
   if(OMX_Init() != OMX_ErrorNone){ilclient_destroy(client);printf("=>Can't init omx!\n");exit(-1);}

   // create video_decode
   if(ilclient_create_component(client, &video_decode, "video_decode", ILCLIENT_DISABLE_ALL_PORTS | ILCLIENT_ENABLE_INPUT_BUFFERS) != 0)
      status = -14;
   list[0] = video_decode;

   // create resize
   if(ilclient_create_component(client, &video_resize, "resize",ILCLIENT_DISABLE_ALL_PORTS) != 0){status = -14; printf("=> ilclient_create_component() for video_resize failed!!\n");exit(1);}
   list[1] = video_resize;

   // create video_encode
   if(ilclient_create_component(client, &video_encode, "video_encode",ILCLIENT_DISABLE_ALL_PORTS | ILCLIENT_ENABLE_OUTPUT_BUFFERS) != 0){status = -14; printf("=> ilclient_create_component() for video_encode failed!!\n");exit(1);}
   list[2] = video_encode;

   // create video_render
   if(status == 0 && ilclient_create_component(client, &video_render, "video_render", ILCLIENT_DISABLE_ALL_PORTS) != 0)
      status = -14;
   list[3] = video_render;

//   set_tunnel(tunnel, video_decode, 131, video_render, 90);
   set_tunnel(tunnel, video_decode, 131, video_encode, 200);

   if(status == 0){
      ilclient_change_component_state(video_decode, OMX_StateIdle);
     ilclient_change_component_state(video_encode, OMX_StateIdle);
                   }//if status

   //input dec format
   memset(&in_dec_format, 0, sizeof(OMX_VIDEO_PARAM_PORTFORMATTYPE));
   in_dec_format.nSize = sizeof(OMX_VIDEO_PARAM_PORTFORMATTYPE);
   in_dec_format.nVersion.nVersion = OMX_VERSION;
   in_dec_format.nPortIndex = 130;
   in_dec_format.eCompressionFormat = OMX_VIDEO_CodingAVC;
   r = OMX_SetParameter(ILC_GET_HANDLE(video_decode), OMX_IndexParamVideoPortFormat, &in_dec_format);
   if ( r!= OMX_ErrorNone){printf("%s:%d: OMX_SetParameter() for video_decode port 130 failed with 0x%08x!\n",__FUNCTION__, __LINE__, r);exit(-1);}

   //output dec format
   memset(&out_dec_Format, 0, sizeof(OMX_VIDEO_PARAM_PORTFORMATTYPE));
   out_dec_Format.nSize = sizeof(OMX_VIDEO_PARAM_PORTFORMATTYPE);
   out_dec_Format.nVersion.nVersion = OMX_VERSION;
   out_dec_Format.nPortIndex = 131;
  // out_dec_Format.eColorFormat = OMX_COLOR_FormatYUV420PackedPlanar;
  //if (OMX_GetParameter(ILC_GET_HANDLE(video_decode), OMX_IndexParamPortDefinition, &out_dec_Format) != OMX_ErrorNone) {printf("%s:%d: OMX_GetParameter() for video_encode port 131 failed!\n", __FUNCTION__, __LINE__);status=-1;exit(-1);}

   if(OMX_SetParameter(ILC_GET_HANDLE(video_decode), OMX_IndexParamVideoPortFormat, &out_dec_Format)!=OMX_ErrorNone){printf("=> Failed set  output port formats of buffers for port (video_decode) : 131 \n");status=-1;exit(-1);}

//   //input video_encode
   memset(&in_enc_format, 0, sizeof(OMX_PARAM_PORTDEFINITIONTYPE));
   in_enc_format.nSize = sizeof(OMX_PARAM_PORTDEFINITIONTYPE);
   in_enc_format.nVersion.nVersion = OMX_VERSION;
   in_enc_format.nPortIndex = 200;
   if (OMX_GetParameter(ILC_GET_HANDLE(video_encode), OMX_IndexParamPortDefinition,&in_enc_format) != OMX_ErrorNone) {printf("%s:%d: OMX_GetParameter() for video_encode port 200 failed!\n", __FUNCTION__, __LINE__);exit(1);}
   // Port 200: in 1/1 115200 16 enabled,not pop.,not cont. 320x240 320x240 @1966080 20
   in_enc_format.format.video.nFrameWidth = WIDTH;
   in_enc_format.format.video.nFrameHeight = HEIGHT;
   in_enc_format.format.video.xFramerate = 30 << 16;
   in_enc_format.format.video.nSliceHeight = in_enc_format.format.video.nFrameHeight;
   in_enc_format.format.video.nStride = in_enc_format.format.video.nFrameWidth;
   in_enc_format.format.video.eColorFormat = OMX_COLOR_FormatYUV420PackedPlanar;
   if (( r = OMX_SetParameter(ILC_GET_HANDLE(video_encode),OMX_IndexParamPortDefinition, &in_enc_format)) != OMX_ErrorNone){printf("%s:%d: OMX_SetParameter() for video_encode port 200 failed with %x!\n", __FUNCTION__, __LINE__, r);exit(1);}

   //output video_encode
   memset(&out_enc_format, 0, sizeof(OMX_VIDEO_PARAM_PORTFORMATTYPE));
   out_enc_format.nSize = sizeof(OMX_VIDEO_PARAM_PORTFORMATTYPE);
   out_enc_format.nVersion.nVersion = OMX_VERSION;
   out_enc_format.nPortIndex = 201;
   out_enc_format.eCompressionFormat = OMX_VIDEO_CodingAVC;
   if ((r = OMX_SetParameter(ILC_GET_HANDLE(video_encode),OMX_IndexParamVideoPortFormat, &out_enc_format)) != OMX_ErrorNone){printf("%s:%d: OMX_SetParameter() for video_encode port 201 failed with %x!\n",__FUNCTION__, __LINE__, r);exit(1);}

   if(status != 0 &&
      ilclient_enable_port_buffers(video_decode, 130, NULL, NULL, NULL) != 0 &&
      ilclient_enable_port_buffers(video_encode, 201, NULL, NULL, NULL) != 0){printf("Failed ilclient_enable_port_buffers\n");exit(-1);}
......
......

**Comment by Ruffio** [comment]
@devalexqt is this still an issue?

**Comment by popcornmix** [comment]
I see no evidence of a firmware bug. It sounds like a bug in the user code. Reopen if there is more information.
