### ISSUE TITLE
Add a PXE option

### ISSUE THREAD

**Issue by kieppie** [raspberrypi/firmware#147]
I've seen frequent requests in the forums for PXE support, so that PRi's can be booted off the local network.

The closest information I've come across is a post relating to U-Boot & GRUB PXE booting:
http://xinu.mscs.mu.edu/Raspberry_Pi#Booting

This is far from an elegant solution to a fairly common request.

Is there any chance such functionality could be baked into future releases or firmare upgrade/patches? 
Anything to just create a hook to bootstrap a PXE client process?

**Comment by badianeka** [comment]
What about iPXE which is open source and vastly superior to Intel's crap?  If that could be ported to these devices it would just be an amazing step.  Just plug them and boot and have FAI, ansible, Argonaut and FusionServer running.

**Comment by Ferroin** [comment]
@XECDesign You mean PXE is an x86 thing, which is itself still not correct (Itanium systems support it, as do some older MIPS systems).  The standard itself is actually now part of EFI too, so it is by no means architecture dependent, and on top of that, when someone says PXE these days, they usually just mean PXE style netboot (that is, using DHCP+TFTP).   As far as native firmware support, couldn't it be done in start.elf?  I was under the impression that that was the bootstrap-code for the ARM side of things, not the GPU, and the ARM core definitely has USB access.

@badianeka I don't know how well iPXE supports ARM processors or USB NIC's, but if it could be made to work, that would be absolutely amazing, and would provide much greater flexibility than U-Boot's network boot support (which while better than traditional PXE on most NIC's, still lacks support for many of the more interesting netboot methods (like direct NBD/iSCSI/ATAoE boot, HTTPS kernel downloads, and similar things)).

**Comment by badianeka** [comment]
I came across something while digging around.  It seems that Linaro might be doing some work:  and there is also cavium servers:

(http://lists.ipxe.org/pipermail/ipxe-devel/2015-December/004501.html), (http://lists.ipxe.org/pipermail/ipxe-devel/2015-November/004500.html), (https://releases.linaro.org/components/lava/16.2/), (https://firmwaresecurity.com/2015/10/07/ipxe-adds-uefi-http-boot-support/), (https://firmwaresecurity.com/tag/uefi-http-boot/), (https://lava.debian.net/static/docs/v2/ipmi-pxe-deploy.html), (http://dox.ipxe.org/files.html), (https://github.com/ipxe/ipxe/tree/master/src/arch/arm64/include/bits), (https://www.youtube.com/watch?v=W7fwu4t5Gtc), (https://github.com/chwilk/ipxe/commits/master). 

Cavium is just amazingly impressive: http://www.cavium.com/newsevents-GIGABYTE-announces-384-Core-2U-server-powered-by-Cavium-ThunderX-ARMv8-processors.html

By the way.

**Comment by badianeka** [comment]
I have managed to boot a machine using iPXE from a non DHCP network by being able to pass it the location of the tftp server and once it got the kernel with the location of the next-server it continued to build itself; as long as there is a route to the TFTP server it will be reached by a device whose MAC address is allowed by policy in order to secure such a network properly.

**Comment by badianeka** [comment]
Setting up Cobbler server and setting up a rack full or little arm machines would be a wonderful thing.  And as the last part of the process having them signal to an Ansible server that it's ready to be configured is beyond cool.  

But I guess users who are used to "images" and carrying CD/DVD/SD/USB media and devices are used to the waste of time and effort.
