### ISSUE TITLE
Pi 4: Netconsole set but no udp packet seen

### ISSUE THREAD

**Issue by RamaSpaceShip** [raspberrypi/firmware#1472]
**Describe the bug**
I have a P4 4GB with RaspiOS Desktop on it. USB storage is via a X835 board and a Sandisk SSD.
I can boot with /boot on the SD card and / on the SSD, but full USB boot doesn't work. :(

To investigate this issue, I tried to use netconsole, but I don't get any UDP message with Wireshark when booting without the SD card. :(

My bootloader settings are:
root@raspberrypi:~# vcgencmd bootloader_config
[all]
BOOT_UART=0
WAKE_ON_GPIO=1
POWER_OFF_ON_HALT=0
DHCP_TIMEOUT=45000
DHCP_REQ_TIMEOUT=4000
TFTP_FILE_TIMEOUT=30000
ENABLE_SELF_UPDATE=1
DISABLE_HDMI=0
BOOT_ORDER=0xf41

# Enable debug if GPIO 7 is pulled low
[gpio7=0]
NETCONSOLE=6666@192.168.1.14/,6666@192.168.1.2/

Before rebooting without the SD card, I verified the gpio 7:
root@raspberrypi:~# pigs r 7
0

But Wireshark on the machine at address 192.168.1.2 does not receive any UDP packet from 192.168.1.14.

The firmware is:
root@raspberrypi:~# rpi-eeprom-update 
BCM2711 detected
Dedicated VL805 EEPROM detected
BOOTLOADER: up-to-date
CURRENT: jeudi 3 septembre 2020, 12:11:43 (UTC+0000) (1599135103)
 LATEST: jeudi 3 septembre 2020, 12:11:43 (UTC+0000) (1599135103)
 FW DIR: /lib/firmware/raspberrypi/bootloader/stable
VL805: up-to-date
CURRENT: 000138a1
 LATEST: 000138a1

**To reproduce**
Set the netconsole as indicated above
check if messages are received on the target machine

**Expected behaviour**
I should see boot messages on UDP port 6666 using Wireshark on the target machine

**Actual behaviour**
No message is received

**System**
System Information
------------------

Raspberry Pi 4 Model B Rev 1.2
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

Raspberry Pi reference 2020-08-20
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 9a3a10bf1019ebb2d59053564dc6b90068bad27d, stage4

Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
Revision        : c03112
Serial          : 100000006baa8fa6
Model           : Raspberry Pi 4 Model B Rev 1.2
Throttled flag  : throttled=0x0
Camera          : supported=0 detected=0

Videocore information
---------------------

Sep  2 2020 21:13:13 
Copyright (c) 2012 Broadcom
version 4439d2aaa6c376a2d1ef4402f142e1cf4de37c43 (clean) (release) (start)

alloc failures:     0
compactions:        0
legacy block fails: 0

Filesystem information
----------------------
Sys. de fichiers blocs de 1K Utilisé Disponible Uti% Monté sur
/dev/root           30832068 6855768   22387076  24% /
devtmpfs             1827296       0    1827296   0% /dev
tmpfs                1959392    5120    1954272   1% /dev/shm
tmpfs                1959392     952    1958440   1% /run
tmpfs                   5120       4       5116   1% /run/lock
tmpfs                1959392       0    1959392   0% /sys/fs/cgroup
/dev/sda1             294736   56032     238704  20% /boot
/dev/sda4          924971004  145904  877769408   1% /home
tmpfs                 391876       8     391868   1% /run/user/1001
tmpfs                 391876       0     391876   0% /run/user/1000

Filename                                Type            Size    Used    Priority
/dev/sda3                               partition       4194236 0       -2
/var/swap                               file            102396  0       -3

Package version information
---------------------------
raspberrypi-ui-mods:
  Installé : 1.20200611
raspberrypi-sys-mods:
  Installé : 20200812
openbox:
  Installé : 3.6.1-8+rpt4
lxpanel:
  Installé : 0.10.0-2+rpt12
pcmanfm:
  Installé : 1.3.1-1+rpt23
rpd-plym-splash:
  Installé : 0.24

Networking Information
----------------------

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet x.x.x.x  netmask x.x.x.x  broadcast x.x.x.x
        inet6 y::y.y.y.y  prefixlen 64  scopeid 0x20<link>
        ether m.m.m.m  txqueuelen 1000  (Ethernet)
        RX packets 598  bytes 411997 (402.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 525  bytes 55351 (54.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet x.x.x.x  netmask x.x.x.x
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Boucle locale)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether m.m.m.m  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

USB Information
---------------

/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 3: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 12M
        |__ Port 3: Dev 3, If 1, Class=Human Interface Device, Driver=usbhid, 12M
        |__ Port 4: Dev 4, If 0, Class=Hub, Driver=hub/4p, 480M
            |__ Port 2: Dev 6, If 0, Class=Mass Storage, Driver=usb-storage, 480M
            |__ Port 1: Dev 5, If 0, Class=Mass Storage, Driver=uas, 480M

config.txt
----------

arm_freq=1500
audio_pwm_mode=514
config_hdmi_boost=5
core_freq=500
core_freq_min=200
disable_commandline_tags=2
disable_l2cache=1
display_hdmi_rotate=-1
display_lcd_rotate=-1
enable_gic=1
force_eeprom_read=1
force_pwm_open=1
framebuffer_ignore_alpha=1
framebuffer_swap=1
gpu_freq=500
gpu_freq_min=250
init_uart_clock=0x2dc6c00
lcd_framerate=60
mask_gpu_interrupt0=1024
mask_gpu_interrupt1=0x10000
max_framebuffers=2
over_voltage_avs=-42500
pause_burst_frames=1
program_serial_random=1
total_mem=4096
hdmi_force_cec_address:0=65535
hdmi_force_cec_address:1=65535
hdmi_pixel_freq_limit:0=0x11e1a300
hdmi_pixel_freq_limit:1=0x11e1a300
device_tree=-
overlay_prefix=overlays/
hdmi_cvt:0=
hdmi_cvt:1=
hdmi_edid_filename:0=
hdmi_edid_filename:1=
hdmi_timings:0=
hdmi_timings:1=

cmdline.txt
-----------
coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_headphones=1 video=HDMI-A-1:1280x1024M@60 smsc95xx.macaddr=DC:A6:32:80:30:7D vc_mem.mem_base=0x3eb00000 vc_mem.mem_size=0x3ff00000  console=ttyS0,115200 console=tty1 root=PARTUUID=03927c2a-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles

raspi-gpio settings
-------------------

BANK0 (GPIO 0 to 27):
GPIO 0: level=1 fsel=0 func=INPUT pull=UP
GPIO 1: level=1 fsel=0 func=INPUT pull=UP
GPIO 2: level=1 fsel=0 func=INPUT pull=UP
GPIO 3: level=1 fsel=0 func=INPUT pull=UP
GPIO 4: level=0 fsel=0 func=INPUT pull=UP
GPIO 5: level=1 fsel=0 func=INPUT pull=UP
GPIO 6: level=1 fsel=0 func=INPUT pull=UP
GPIO 7: level=0 fsel=0 func=INPUT pull=UP
GPIO 8: level=1 fsel=0 func=INPUT pull=UP
GPIO 9: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 10: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 11: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 12: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 13: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 14: level=1 fsel=0 func=INPUT pull=NONE
GPIO 15: level=1 fsel=0 func=INPUT pull=UP
GPIO 16: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 17: level=1 fsel=1 func=OUTPUT pull=DOWN
GPIO 18: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 19: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 20: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 21: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 22: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 23: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 24: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 25: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 26: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 27: level=0 fsel=0 func=INPUT pull=DOWN
BANK1 (GPIO 28 to 45):
GPIO 28: level=1 fsel=2 alt=5 func=RGMII_MDIO pull=UP
GPIO 29: level=0 fsel=2 alt=5 func=RGMII_MDC pull=DOWN
GPIO 30: level=0 fsel=7 alt=3 func=CTS0 pull=UP
GPIO 31: level=0 fsel=7 alt=3 func=RTS0 pull=NONE
GPIO 32: level=1 fsel=7 alt=3 func=TXD0 pull=NONE
GPIO 33: level=1 fsel=7 alt=3 func=RXD0 pull=UP
GPIO 34: level=0 fsel=7 alt=3 func=SD1_CLK pull=NONE
GPIO 35: level=1 fsel=7 alt=3 func=SD1_CMD pull=UP
GPIO 36: level=1 fsel=7 alt=3 func=SD1_DAT0 pull=UP
GPIO 37: level=1 fsel=7 alt=3 func=SD1_DAT1 pull=UP
GPIO 38: level=1 fsel=7 alt=3 func=SD1_DAT2 pull=UP
GPIO 39: level=1 fsel=7 alt=3 func=SD1_DAT3 pull=UP
GPIO 40: level=1 fsel=4 alt=0 func=PWM1_0 pull=NONE
GPIO 41: level=0 fsel=4 alt=0 func=PWM1_1 pull=NONE
GPIO 42: level=1 fsel=1 func=OUTPUT pull=UP
GPIO 43: level=1 fsel=0 func=INPUT pull=UP
GPIO 44: level=1 fsel=0 func=INPUT pull=UP
GPIO 45: level=1 fsel=0 func=INPUT pull=UP
BANK2 (GPIO 46 to 53):
GPIO 46: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 47: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 48: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 49: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 50: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 51: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 52: level=0 fsel=0 func=INPUT pull=DOWN
GPIO 53: level=0 fsel=0 func=INPUT pull=DOWN

vcdbg log messages
------------------

008017.376: bfs_xhci_retrieve 3ee76700
008017.388: bfs_xhci_retrieve VL805 flags 00000001
008036.253: brfs: File read: /mfs/sd/config.txt
008036.992: brfs: File read: 1784 bytes
008088.892: brfs: File read: /mfs/sd/config.txt
008095.693: brfs: File read: 1784 bytes
008542.600: gpioman: gpioman_get_pin_num: pin DISPLAY_DSI_PORT not defined
008545.056: *** Restart logging
008585.282: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
008585.298: HDMI0: hdmi_pixel_encoding: 300000000
008585.309: HDMI1: hdmi_pixel_encoding: 300000000
008590.263: dtb_file 'bcm2711-rpi-4-b.dtb'
008594.962: brfs: File read: /mfs/sd/bcm2711-rpi-4-b.dtb
008594.977: Loading 'bcm2711-rpi-4-b.dtb' to 0x100 size 0xb96f
008607.159: brfs: File read: 47471 bytes
008612.374: brfs: File read: /mfs/sd/overlays/overlay_map.dtb
008666.906: brfs: File read: 1423 bytes
008668.141: brfs: File read: /mfs/sd/config.txt
008668.618: dtparam: audio=on
008677.833: brfs: File read: 1784 bytes
008685.172: brfs: File read: /mfs/sd/overlays/vc4-fkms-v3d.dtbo
008701.737: Loaded overlay 'vc4-fkms-v3d'
008744.735: brfs: File read: 1238 bytes
008746.034: brfs: File read: /mfs/sd/cmdline.txt
008746.081: Read command line from file 'cmdline.txt':
008746.094: 'console=serial0,115200 console=tty1 root=PARTUUID=03927c2a-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles'
009916.628: brfs: File read: 166 bytes
010415.165: brfs: File read: /mfs/sd/kernel7l.img
010415.204: Loading 'kernel7l.img' to 0x8000 size 0x5b7fc0
010415.251: Device tree loaded to 0x2eff4100 (size 0xbedd)
010419.302: bfs_xhci_stop
010419.314: XHCI-STOP
010419.494: xHC ver: 256 HCS: 05000420 fc000031 00e70004 HCC: 002841eb
013465.474: vchiq_core: vchiq_init_state: slot_zero = 0xded80000, is_master = 1
013468.946: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
013476.239: TV service:host side not connected, dropping notification 0x00000002, 0x00000002, 0x00000023
019803.206: TV service:host side not connected, dropping notification 0x00000008, 0x00000004, 0x00000000

**Logs**
none as it is before the kernel is booted

**Additional context**
none

**Comment by pelwell** [comment]
NETCONSOLE is a configuration option for the BOOT EEPROM, not config.txt. See https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2711_bootloader_config.md and https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md.

**Comment by timg236** [comment]
Config keys values are limited to 32 characters,  surprisingly nobody has hit this before since it's been like that since day one!

The default source port is 6665 and default target port is 6666 so it's possible to get the same result with this slightly shorter string.

NETCONSOLE=6666@192.168.1.14/eth0,@192.168.1.2/

**Comment by RamaSpaceShip** [comment]
I changed the netconsole string in the bootloader config to the shortest I can:
NETCONSOLE=@192.168.1.8/,192.168.1.2/
But I still didn't get any UDP message.

Did you try the netconsole option, and thus do you have a bootloader config where the netconsole is working?
If so, I would like to know how different it is from mine.

**Comment by timg236** [comment]
I used the following config with the debug Pi connected directly to another Pi running WireShark,

NETCONSOLE=6666@192.168.1.14/,@192.168.1.2/

**Comment by RamaSpaceShip** [comment]
This is now solved

**Comment by timg236** [comment]
Great, thanks for confirming the workaround. The config parser is fixed and will appear in a future beta/stable release but I'll just document it as a limitation for now.
