### ISSUE TITLE
Ubuntu Raspberry Pi disabling Uboot fails boot process

### ISSUE THREAD

**Issue by gaynoraj19** [raspberrypi/firmware#1474]
**Describe the bug**
Booting linux kernel directly rather than through Uboot does not work on Ubuntu 18.04.5

**To reproduce**
Using a Raspberry Pi 4 4GB...
On a fresh SD card, install Ubuntu 18.04.5 (kernel version 5.4)
Add this to `config.txt` under `All` removing uboot sections
```
kernel=vmlinuz
initramfs initrd.img followkernel
```

**Expected behaviour**
The Pi should boot, bypassing uboot.

**Actual behaviour**
The Pi is stuck on the splash screen with no terminal output whatsoever.

**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:

* Which model of Raspberry Pi? 
Raspberry Pi 4 4 Gb

* Which kernel version (`uname -a`)?
Linux Ubuntu 5.4.0-1015-raspi

**Additional context**
Add any other relevant context for the problem.
This issue only exists on the newest kernel version which at this time is `Linux Ubuntu 5.4.0-1015-raspi`. This issue does not exist on Ubuntu 18.04.4 using kernel 5.3.0-1033-raspi2

**Comment by pelwell** [comment]
Why are you reporting this here? Wouldn't the Ubuntu forums be a better place?
