### ISSUE TITLE
"next" branch commit hash longevity

### ISSUE THREAD

**Issue by rsglobal** [raspberrypi/firmware#1484]
Hi,

Will SHA of commits in the next branch (v5.9) kept unchanged when merged into master or you plan to cherry-pick them?

**Comment by pelwell** [comment]
Upstream commits are always merged (unless they are downstream back-ports), but downstream commits are cherry-picked and rebased. At the point we make a branch our default branch we stop rebasing existing commits and the hashes become stable in that branch.

**Comment by rsglobal** [comment]
Thank you!
