### ISSUE TITLE
UART information needed.

### ISSUE THREAD

**Issue by kallisti5** [raspberrypi/firmware#15]
The BCM2835 manual notes a UART0 and a UART1.

From what I can gather, UART0 is the full PL011, and UART1 is the "miniUART" that is supposed to be simpler.

Questions:
* There is only one set of assigned tx and rx pins on the pi / bcm2835... how do you switch the pins between the two uarts?
* I see references to UART0 needs to have gpio 14 and gpio 15 in alt0 mode, is this the change needed to go from miniUART -> full PL011 mode?
* The BCM2835 pdf shows that the gpio 14 and 15 pins need to be "low", is this true?

What I really need is a high level overview of what steps are needed to get a uart to the state needed to output characters.

**Comment by Ruffio** [comment]
Is this issue still relevant or can it be closed?

**Comment by popcornmix** [comment]
See: https://github.com/raspberrypi/linux/pull/1008
