### ISSUE TITLE
wfcCreateDevice(WFC_DEFAULT_DEVICE_ID, NULL) fails

### ISSUE THREAD

**Issue by OtherCrashOverride** [raspberrypi/firmware#150]
See details here http://www.raspberrypi.org/phpBB3/viewtopic.php?f=67&t=32856

**Comment by Ruffio** [comment]
@OtherCrashOverride is this still an issue?

**Comment by Ruffio** [comment]
Please consider to close this issue due to lack of activity. It was created in 2013, I pinged @OtherCrashOverride in 2015 without any response.
