### ISSUE TITLE
How did you implement USB boot use-case?

### ISSUE THREAD

**Issue by ret394** [raspberrypi/firmware#1506]
I can see 2 ways -
1 Requires a SD card to be plugged in even after USB boot works.
2 Does not require an SD card to be plugged in.

To me option 2 makes more sense, if the SoC allows it.

you're welcome, as always. all the best. 👍
don't say nasty stuff or do rude stuff to folks on Github or other sites.

[ret394](https://github.com/ret394)

**Comment by ret394** [comment]
Question

**Comment by JamesH65** [comment]
Once USB boot is enabled you no longer need the SD card installed.
