### ISSUE TITLE
PI4: cannot run with DVI TV monitor

### ISSUE THREAD

**Issue by pmbert** [raspberrypi/firmware#1514]
I'm trying to run a new PI4 with a DVI TV monitor, which worked fine with a PI2. But I cannot manage it with PI4. Maybe someone can tell me, is it a bug or a defect or am I doing something wrong.

- tried to run the monitor with native resolution (1280x720, hmdi_group/mode not set)):
The graphical display (the GUI desktop) is covered with flickering horizontal stripes.

- tried to change the resolution with hdmi_group and hdmi_mode:
Change has no effect. Same display as above. None of the supported modes are
taken. Although the values were read from config.txt.
Example:
>> tvservice -s
state 0x6 [DVI CUSTOM RGB full 16:9], 1280x720 @ 60.00Hz, progressive
>> /opt/vc/bin/tvservice -m DMT
Group DMT has 5 modes:
  (prefer) mode 4: 640x480 @ 60Hz 4:3, clock:25MHz progressive 
           mode 9: 800x600 @ 60Hz 4:3, clock:40MHz progressive 
           mode 16: 1024x768 @ 60Hz 4:3, clock:65MHz progressive 
           mode 35: 1280x1024 @ 60Hz 5:4, clock:108MHz progressive 
           mode 85: 1280x720 @ 60Hz 16:9, clock:74MHz progressive 
>> cat /proc/cmdline
coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=HDMI-A-1:640x480M@60 smsc95xx.macaddr=DC:A6:32:D8:16:60 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=6b3fa55e-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles

- tried hdmi_safe=1:
The display is fine. But it's covering only the left side of the screen and moved a litte out of left border.
>> tvservice -s
state 0x6 [DVI CUSTOM RGB full 4:3], 1024x768 @ 60.00Hz, progressive
>> /opt/vc/bin/tvservice -m DMT
Group DMT has 5 modes:
  (prefer) mode 4: 640x480 @ 60Hz 4:3, clock:25MHz progressive 
           mode 9: 800x600 @ 60Hz 4:3, clock:40MHz progressive 
           mode 16: 1024x768 @ 60Hz 4:3, clock:65MHz progressive 
           mode 35: 1280x1024 @ 60Hz 5:4, clock:108MHz progressive 
           mode 85: 1280x720 @ 60Hz 16:9, clock:74MHz progressive 
>> cat /proc/cmdline
coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=HDMI-A-1:640x480M@60,margin_left=24,margin_right=24,margin_top=16,margin_bottom=16 video=HDMI-A-2:640x480M@60,margin_left=24,margin_right=24,margin_top=16,margin_bottom=16 smsc95xx.macaddr=DC:A6:32:D8:16:60 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=6b3fa55e-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles

- tried the parameters of hdmi_safe=1 as described in https://www.raspberrypi.org/documentation/configuration/config-txt/video.md:
Result is a blank screen with message 'Unsupported mode (H=65.64kHz V=56Hz)'
>> tvservice -s
state 0xa [HDMI CUSTOM RGB lim 16:9], 1920x1080 @ 60.00Hz, progressive
>> /opt/vc/bin/tvservice -m DMT
Group DMT has 19 modes:
  (prefer) mode 4: 640x480 @ 60Hz 4:3, clock:25MHz progressive 
           mode 5: 640x480 @ 72Hz 4:3, clock:31MHz progressive 
           mode 6: 640x480 @ 75Hz 4:3, clock:31MHz progressive 
           mode 8: 800x600 @ 56Hz 4:3, clock:36MHz progressive 
           mode 9: 800x600 @ 60Hz 4:3, clock:40MHz progressive 
           mode 10: 800x600 @ 72Hz 4:3, clock:50MHz progressive 
           mode 11: 800x600 @ 75Hz 4:3, clock:49MHz progressive 
           mode 16: 1024x768 @ 60Hz 4:3, clock:65MHz progressive 
           mode 17: 1024x768 @ 70Hz 4:3, clock:75MHz progressive 
           mode 18: 1024x768 @ 75Hz 4:3, clock:78MHz progressive 
           mode 21: 1152x864 @ 75Hz 4:3, clock:108MHz progressive 
           mode 28: 1280x800 @ 60Hz 16:10, clock:83MHz progressive 
           mode 32: 1280x960 @ 60Hz 4:3, clock:108MHz progressive 
           mode 35: 1280x1024 @ 60Hz 5:4, clock:108MHz progressive 
           mode 36: 1280x1024 @ 75Hz 5:4, clock:135MHz progressive 
           mode 47: 1440x900 @ 60Hz 16:10, clock:106MHz progressive 
           mode 48: 1440x900 @ 75Hz 16:10, clock:136MHz progressive 
           mode 51: 1600x1200 @ 60Hz 4:3, clock:162MHz progressive 
           mode 58: 1680x1050 @ 60Hz 16:10, clock:146MHz progressive
>> cat /proc/cmdline
coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=HDMI-A-1:640x480M@60,margin_left=24,margin_right=24,margin_top=24,margin_bottom=24 smsc95xx.macaddr=DC:A6:32:D8:16:60 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=6b3fa55e-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles

==========================================================================
my data:

Raspberry Pi 4 Model B Rev 1.4 Serial#: 10000000b0d4d88c
Memory:  1911988 kB

Firmware: 
Nov 30 2020 22:12:08 
Copyright (c) 2012 Broadcom
version ab1181cc0cb6df52bfae3b1d3fef0ce7c325166c (clean) (release) (start)

Raspbian GNU/Linux 10 (buster)
Linux raspberrypi4 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux

==========================================================================
following data are taken with hdmi_group/mode not set:

>> /opt/vc/bin/tvservice -s
state 0x6 [DVI CUSTOM RGB full 16:9], 1280x720 @ 60.00Hz, progressive

>> /opt/vc/bin/tvservice -m CEA
Group CEA has 0 modes:

>> /opt/vc/bin/tvservice -m DMT
Group DMT has 5 modes:
           mode 4: 640x480 @ 60Hz 4:3, clock:25MHz progressive
           mode 9: 800x600 @ 60Hz 4:3, clock:40MHz progressive
           mode 16: 1024x768 @ 60Hz 4:3, clock:65MHz progressive
  (prefer) mode 35: 1280x1024 @ 60Hz 5:4, clock:108MHz progressive
           mode 85: 1280x720 @ 60Hz 16:9, clock:74MHz progressive

>> /opt/vc/bin/tvservice -d edid.dat
Written 128 bytes to edid.dat

>> base64 edid.dat
AP///////wA0pEzGAAAAAB8OAQNqPCJ4Co5gpVVEmSQSSUshCACBgIHAAQEBAQEBAQEBAQEBAR0A
clHQHiAQkBMAVVAhAAAeAAAA/QA8PB5BCAAKICAgICAgAAAA/ABNZWRpb24gNDE0MjcKAAAA/wBT
YW1wbGUKCgoKCgoKAEQ=

>> /opt/vc/bin/edidparser edid.dat
Enabling fuzzy format match...
Parsing edid.dat...
HDMI:EDID version 1.3, 0 extensions, screen size 60x34 cm
HDMI:EDID features - videodef 0x6a !standby !suspend !active off; display type:non-rgb; sRGB is not default colourspace; preferred format is native; does not support GTF
HDMI:EDID found monitor range descriptor tag 0xfd
HDMI:EDID monitor range offsets: V min=0, V max=0, H min=0, H max=0
HDMI:EDID monitor range: vertical is 60-60 Hz, horizontal is 30-65 kHz, max pixel clock is 80 MHz
HDMI:EDID monitor range does not support GTF
HDMI:EDID found monitor name descriptor tag 0xfc
HDMI:EDID monitor name is Medion_41427
HDMI:EDID found monitor S/N descriptor tag 0xff
HDMI:EDID found preferred CEA detail timing format: 1280x720p @ 60 Hz (4)
HDMI:EDID established timing I/II bytes are 21 08 00
HDMI:EDID found DMT format: code 4, 640x480p @ 60 Hz in established timing I/II
HDMI:EDID found DMT format: code 9, 800x600p @ 60 Hz in established timing I/II
HDMI:EDID found DMT format: code 16, 1024x768p @ 60 Hz in established timing I/II
HDMI:EDID standard timings block x 8: 0x8180 81C0 0101 0101 0101 0101 0101 0101
HDMI:EDID found DMT format: code 35, 1280x1024p @ 60 Hz (5:4) in standard timing 0
HDMI:EDID found DMT format: code 85, 1280x720p @ 60 Hz (16:9) in standard timing 1
HDMI:EDID moving support for CEA mode 4 to DMT mode 85 because sink does not support HDMI
HDMI:EDID filtering formats with pixel clock unlimited MHz or h. blanking unlimited
HDMI:EDID best score mode initialised to CEA (1) 640x480p @ 60 Hz with pixel clock -1224935244 MHz (score 25)
HDMI:EDID best score mode is now DMT (4) 640x480p @ 60 Hz with pixel clock 25 MHz (score 18432)
HDMI:EDID best score mode is now DMT (9) 800x600p @ 60 Hz with pixel clock 40 MHz (score 28800)
HDMI:EDID best score mode is now DMT (16) 1024x768p @ 60 Hz with pixel clock 65 MHz (score 47185)
HDMI:EDID best score mode is now DMT (35) 1280x1024p @ 60 Hz with pixel clock 108 MHz (score 103643)
HDMI:EDID DMT mode (85) 1280x720p @ 60 Hz with pixel clock 74 MHz has a score of 80296
HDMI0:EDID preferred mode is updated to DMT (35) 1280x1024p @ 60 Hz with pixel clock 108000000 Hz
HDMI:EDID has only DVI support and no audio support
/opt/vc/bin/edidparser exited with code 0

>> sudo vcdbg log msg
004546.714: arasan: arasan_emmc_open
004989.656: brfs: File read: /mfs/sd/config.txt
004990.463: brfs: File read: 1919 bytes
005068.174: brfs: File read: /mfs/sd/config.txt
005084.698: brfs: File read: 1919 bytes
005545.211: gpioman: gpioman_get_pin_num: pin DISPLAY_DSI_PORT not defined
005547.670: *** Restart logging
005573.282: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
005573.298: HDMI0: hdmi_pixel_encoding: 300000000
005573.310: HDMI1: hdmi_pixel_encoding: 300000000
005588.622: dtb_file 'bcm2711-rpi-4-b.dtb'
005593.555: brfs: File read: /mfs/sd/bcm2711-rpi-4-b.dtb
005593.569: Loading 'bcm2711-rpi-4-b.dtb' to 0x100 size 0xb97c
005605.665: brfs: File read: 47484 bytes
005616.758: brfs: File read: /mfs/sd/overlays/overlay_map.dtb
005671.776: brfs: File read: 1523 bytes
005672.962: brfs: File read: /mfs/sd/config.txt
005673.451: dtparam: audio=on
005682.833: brfs: File read: 1919 bytes
005694.967: brfs: File read: /mfs/sd/overlays/vc4-fkms-v3d.dtbo
005711.908: Loaded overlay 'vc4-fkms-v3d'
005750.954: brfs: File read: 1446 bytes
005752.674: brfs: File read: /mfs/sd/cmdline.txt
005752.720: Read command line from file 'cmdline.txt':
005752.733: 'console=serial0,115200 console=tty1 root=PARTUUID=6b3fa55e-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles'
007070.583: brfs: File read: 166 bytes
008307.152: brfs: File read: /mfs/sd/kernel7l.img
008307.193: Loading 'kernel7l.img' to 0x8000 size 0x5dc538
008307.239: Device tree loaded to 0x2eff4100 (size 0xbeea)
008320.808: gpioman: gpioman_get_pin_num: pin SDCARD_CONTROL_POWER not defined
010606.966: vchiq_core: vchiq_init_state: slot_zero = 0xded80000, is_master = 1
010610.342: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
010617.586: TV service:host side not connected, dropping notification 0x00000002, 0x00000002, 0x00000023
015626.532: TV service:host side not connected, dropping notification 0x00000004, 0x00000004, 0x00000000
020384.246: TV service:host side not connected, dropping notification 0x00000004, 0x00000004, 0x00000000

>> cat /proc/cmdline
coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=HDMI-A-1:1280x1024M@60 smsc95xx.macaddr=DC:A6:32:D8:16:60 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=6b3fa55e-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles

**Comment by popcornmix** [comment]
Sorry, this report got missed over Christmas. Are you still having an issue?

You are using buster which is very old. It would be useful if you could retry with a new install of RPiOS bullseye, and then report if the issue is still present.
