### ISSUE TITLE
Can kernel/exfat add support for NFS?

### ISSUE THREAD

**Issue by shixudong2020** [raspberrypi/firmware#1538]
dorimanx /exfat-nofuse has added NFS support
https://github.com/dorimanx/exfat-nofuse/pull/101/commits/934ad9232f846a5ea580ea7221b4f8936c6cb691

**Comment by pelwell** [comment]
This issue/question (quissue?) concerns the Linux kernel, so it should have been reported/asked in the raspberrypi/linux repo. You would have been told there that once the support for NFS-sharing exfat volumes has been merged upstream (in the linux-next repo) we would probably be happy to back-port it into our current branches provided it wasn't too disruptive.

I've looked at linux-next and so far there is no sign of sharing support, so it will have to wait.
