### ISSUE TITLE
system fails to boot after renaming kernel

### ISSUE THREAD

**Issue by emanuel-bacigala** [raspberrypi/firmware#1567]
After renaming kernel7.img to kernel7-l318.img my CM3+ fails to boot.
Firmware hash is a48d332c35ee1c1c1ab433228e23317f62dcc5fb
Linux version 5.10.31-v7+

cmdline.txt:
dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline root=/dev/mmcblk0p2 rootfstype=ext4 fsck.repair=yes fsck.mode=force rootwait

config.txt:
kernel=kernel7-l318.img

framebuffer_depth=32
gpu_mem=256
avoid_warnings=1
disable_splash=1
ignore_lcd=1
hdmi_ignore_edid=0xa5000080
hdmi_drive=1

uart_2ndstage=1
uart0=on
gpio=32=a3,pn
gpio=33=a3,pu

dtparam=i2c2_iknowwhatimdoing=on

serial console output:
Raspberry Pi Bootcode
Read File: config.txt, 234
Read File: start.elf, 2955968 (bytes)
Read File: fixup.dat, 7311 (bytes)
MESS:00:00:01.908563:0: brfs: File read: /mfs/sd/config.txt
MESS:00:00:01.913030:0: brfs: File read: 234 bytes
MESS:00:00:01.972213:0: brfs: File read: /mfs/sd/config.txt
MESS:00:00:01.976626:0: gpioman: gpioman_get_pin_num: pin LEDS_PWR_OK not defined
MESS:00:00:02.008121:0: gpioman: gpioman_get_pin_num: pin FLASH_0_ENABLE not defined
MESS:00:00:02.014176:0: gpioman: gpioman_get_pin_num: pin FLASH_0_INDICATOR not defined
MESS:00:00:02.021923:0: gpioman: gpioman_get_pin_num: pin FLASH_0_ENABLE not defined
MESS:00:00:02.029367:0: gpioman: gpioman_get_pin_num: pin FLASH_0_INDICATOR not defined
MESS:00:00:02.037110:0: gpioman: gpioman_get_pin_num: pin BT_ON not defined
MESS:00:00:02.043770:0: gpioman: gpioman_get_pin_num: pin WL_ON not defined
MESS:00:00:02.077090:0: gpioman: gpioman_get_pin_num: pin LEDS_PWR_OK not defined
MESS:00:00:02.082918:0: *** Restart logging
MESS:00:00:02.086792:0: brfs: File read: 234 bytes
MESS:00:00:02.102188:0: HDMI0: hdmi_pixel_encoding: 162000000
MESS:00:00:02.107149:0: gpioman: gpioman_get_pin_num: pin CAMERA_0_I2C_PORT not defined
MESS:00:00:02.113971:0: dtb_file 'bcm2710-rpi-cm3.dtb'
MESS:00:00:02.123012:0: brfs: File read: /mfs/sd/bcm2710-rpi-cm3.dtb
MESS:00:00:02.127673:0: Loading 'bcm2710-rpi-cm3.dtb' to 0x100 size 0x690a
MESS:00:00:02.146868:0: brfs: File read: 26890 bytes
MESS:00:00:02.212805:0: brfs: File read: /mfs/sd/config.txt
MESS:00:00:02.216856:0: dtparam: i2c2_iknowwhatimdoing=on
MESS:00:00:02.235846:0: brfs: File read: 234 bytes
MESS:00:00:02.239349:0: brfs: File read: /mfs/sd/cmdline.txt
MESS:00:00:02.244361:0: Read command line from file 'cmdline.txt':
MESS:00:00:02.250227:0: 'dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline root=/dev/mmcblk0p2 rootfstype=ext4 fsck.repair=yes fsck.mode=force rootwait'
MESS:00:00:03.929490:0: gpioman: gpioman_get_pin_num: pin WL_ON not defined
MESS:00:00:03.938715:0: brfs: File read: 174 bytes
MESS:00:00:04.508699:0: brfs: File read: /mfs/sd/kernel7-l318.img
MESS:00:00:04.513097:0: Loading 'kernel7-l318.img' to 0x80000 size 0x60c690
MESS:00:00:04.519791:0: Device tree loaded to 0x2eff9200 (size 0x6d9c)
MESS:00:00:04.527513:0: uart: Set PL011 baud rate to 103448.300000 Hz
MESS:00:00:04.533803:0: uart: Baud rate change done...
MESS:00:00:04.537235:0: uart: Baud rate change done...
MESS:00:00:04.542985:0: gpioman: gpioman_get_pin_num: pin SDCARD_CONTROL_POWER not defined

...system hags here...

if I renamed kernel7-l318.img to kernel7.img and commented out kernel=... in config.txt system boots ok:
Raspberry Pi Bootcode
Read File: config.txt, 234
Read File: start.elf, 2955968 (bytes)
Read File: fixup.dat, 7311 (bytes)
MESS:00:00:01.908359:0: brfs: File read: /mfs/sd/config.txt
MESS:00:00:01.912825:0: brfs: File read: 234 bytes
MESS:00:00:01.971996:0: brfs: File read: /mfs/sd/config.txt
MESS:00:00:01.976410:0: gpioman: gpioman_get_pin_num: pin LEDS_PWR_OK not defined
MESS:00:00:02.007907:0: gpioman: gpioman_get_pin_num: pin FLASH_0_ENABLE not defined
MESS:00:00:02.013962:0: gpioman: gpioman_get_pin_num: pin FLASH_0_INDICATOR not defined
MESS:00:00:02.021710:0: gpioman: gpioman_get_pin_num: pin FLASH_0_ENABLE not defined
MESS:00:00:02.029153:0: gpioman: gpioman_get_pin_num: pin FLASH_0_INDICATOR not defined
MESS:00:00:02.036895:0: gpioman: gpioman_get_pin_num: pin BT_ON not defined
MESS:00:00:02.043557:0: gpioman: gpioman_get_pin_num: pin WL_ON not defined
MESS:00:00:02.077170:0: gpioman: gpioman_get_pin_num: pin LEDS_PWR_OK not defined
MESS:00:00:02.082998:0: *** Restart logging
MESS:00:00:02.086872:0: brfs: File read: 234 bytes
MESS:00:00:02.102261:0: HDMI0: hdmi_pixel_encoding: 162000000
MESS:00:00:02.107221:0: gpioman: gpioman_get_pin_num: pin CAMERA_0_I2C_PORT not defined
MESS:00:00:02.114044:0: dtb_file 'bcm2710-rpi-cm3.dtb'
MESS:00:00:02.123095:0: brfs: File read: /mfs/sd/bcm2710-rpi-cm3.dtb
MESS:00:00:02.127756:0: Loading 'bcm2710-rpi-cm3.dtb' to 0x100 size 0x690a
MESS:00:00:02.146950:0: brfs: File read: 26890 bytes
MESS:00:00:02.212888:0: brfs: File read: /mfs/sd/config.txt
MESS:00:00:02.216938:0: dtparam: i2c2_iknowwhatimdoing=on
MESS:00:00:02.235928:0: brfs: File read: 234 bytes
MESS:00:00:02.239444:0: brfs: File read: /mfs/sd/cmdline.txt
MESS:00:00:02.244443:0: Read command line from file 'cmdline.txt':
MESS:00:00:02.250309:0: 'wc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline root=/dev/mmcblk0p2 rootfstype=ext4 fsck.repair=yes fsck.mode=force rootwait'
MESS:00:00:03.925517:0: gpioman: gpioman_get_pin_num: pin WL_ON not defined
MESS:00:00:03.934685:0: brfs: File read: 173 bytes
MESS:00:00:04.508379:0: brfs: File read: /mfs/sd/kernel7.img
MESS:00:00:04.512342:0: Loading 'kernel7.img' to 0x8000 size 0x60c690
MESS:00:00:04.518515:0: Device tree loaded to 0x2eff9200 (size 0x6d9c)
MESS:00:00:04.526237:0: uart: Set PL011 baud rate to 103448.300000 Hz
MESS:00:00:04.532529:0: uart: Baud rate change done...
MESS:00:00:04.535962:0: uart: Baud rate change done...
MESS:00:00:04.541716:0: gpioman: gpioman_get_pin_num: pin SDCARD_CONTROL_POWER not defined
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.10.31-v7+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1412 SMP Wed Apr 21 15:44:09 BST 2021
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi Compute Module 3 Plus Rev 1.0
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] Reserved memory: created CMA memory pool at 0x2ac00000, size 64 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x000000002fffffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000002fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000002fffffff]
[    0.000000] percpu: Embedded 20 pages/cpu s50700 r8192 d23028 u81920
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 194880
[    0.000000] Kernel command line: coherent_pool=1M snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=1824 bcm2708_fb.fbheight=984 bcm2708_fb.fbdepth=32 bcm2708_fb.fbswap=1 smsc95xx.macaddr=B8:27:EB:BE:85:26 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  wc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline root=/dev/mmcblk0p2 rootfstype=ext4 fsck.repair=yes fsck.mode=force rootwait
[    0.000000] Kernel parameter elevator= does not have any effect anymore.
[    0.000000] Please use sysfs to set IO scheduler for individual devices.
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 697136K/786432K available (9216K kernel code, 1312K rwdata, 2948K rodata, 1024K init, 863K bss, 23760K reserved, 65536K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 32019 entries in 63 pages
[    0.000000] ftrace: allocated 63 pages with 6 groups
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] 	Rude variant of Tasks RCU enabled.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] random: get_random_bytes called from start_kernel+0x3ac/0x580 with crng_init=0
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000008] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000025] Switching to timer-based delay loop, resolution 52ns
[    0.000316] Console: colour dummy device 80x30
[    0.001197] printk: console [tty1] enabled
[    0.001265] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.001324] pid_max: default: 32768 minimum: 301
[    0.001542] LSM: Security Framework initializing
[    0.001800] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.001851] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.003463] Disabling memory control group subsystem
[    0.003600] CPU: Testing write buffer coherency: ok
[    0.004120] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.005373] Setting up static identity map for 0x100000 - 0x10003c
[    0.005582] rcu: Hierarchical SRCU implementation.
[    0.006523] smp: Bringing up secondary CPUs ...
[    0.007730] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.009026] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.010395] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.010556] smp: Brought up 1 node, 4 CPUs
[    0.010611] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.010643] CPU: All CPU(s) started in HYP mode.
[    0.010671] CPU: Virtualization extensions available.
[    0.011634] devtmpfs: initialized
[    0.029043] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.029320] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.029381] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.032642] pinctrl core: initialized pinctrl subsystem
[    0.033869] NET: Registered protocol family 16
[    0.038339] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.043996] audit: initializing netlink subsys (disabled)
[    0.044314] audit: type=2000 audit(0.040:1): state=initialized audit_enabled=0 res=1
[    0.044912] thermal_sys: Registered thermal governor 'step_wise'
[    0.046095] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.046159] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.046463] Serial: AMBA PL011 UART driver
[    0.063807] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.080162] raspberrypi-firmware soc:firmware: Attached to firmware from 2021-04-21T15:49:36, variant start
[    0.090172] raspberrypi-firmware soc:firmware: Firmware hash is a48d332c35ee1c1c1ab433228e23317f62dcc5fb
[    0.134082] Kprobes globally optimized
[    0.139079] bcm2835-dma 3f007000.dma: DMA legacy API manager, dmachans=0x1
...

This bug? might have been introduced with 5.10.y because when I tried 5.4.72 (7a06d62ff1c0c6bd72d4b9a91b6e38eaf68aeb70) there was no problem with different kernel name.

**Comment by pelwell** [comment]
And what happens if you use `kernel=kernel7.img`?

**Comment by pelwell** [comment]
I understand now - you are being bitten by a heuristic that says that, in the absence of other information, kernel names ending "8.img" should be run in 64-bit mode. Add `arm_64bit=0` to disable this feature.

**Comment by emanuel-bacigala** [comment]
After adding arm_64bit=0 system boots ok. Growing FW intelligence begins to cause problems. Thank you for helping me.

**Comment by pelwell** [comment]
I may reconsider that particular heuristic.

**Comment by emanuel-bacigala** [comment]
Adding some uart stage2 debugging msg like "CPU running in XXbit mode" can also help to identify similar problems.
