### ISSUE TITLE
Pi 400 - F10 power button does not work in suboptimal HDMI conditions

### ISSUE THREAD

**Issue by henk717** [raspberrypi/firmware#1576]
**Is this the right place for my bug report?**
The issue is regarding the bootup behavior of the Raspberry Pi 400, likely firmware related since it is also related to the shutdown. Could be kernel or eeprom related (Let me know if this is the case then ill open an issue there).

**Describe the bug**
In some of my configurations the F10 to power on button will not work on the Raspberry Pi 400's, in these configurations it is still possible to use FN + F10 to power down, including the hard power off when held long. Once off the device is unresponsive and will not turn on without first unplugging the power cord.

**To reproduce**
To reproduce the easiest method i found is to boot the device with an SDCard and the HDMI plugged in, if you do not have a HDMI device like a cheap capture card that triggers this bug it can be achieved by first unplugging the HDMI cord before powering down. So for example open up a terminal with the poweroff command, unplug the cable and hit enter. The device should now be unresponsive to F10 bootup.

**Expected behaviour**
F10 always boots up the device in a low powered state, unless specifically configured to go into a deeper sleep in the eeprom settings.

**Actual behaviour**
F10 bootup behavior depends on the HDMI state when the device was shut down, having no cable plugged in or an inferior display device such as a cheap capture card can trigger a state where the device powers off without the F10 button being able to turn it back on. This persists when you plug in a HDMI cable, the F10 button will still refuse to power it on indicating the fault might be in the power down behavior of the firmware. If you have a proper HDMI display connected and power the device down you are able to turn it on with F10 like normal. In the case of a HDMI capture card that triggers this behavior there is a chance you get it to behave like normal, but also a chance it refuses to work (In my case it mostly does not work with around 98% of the time resulting in a stuck device).

**System**
System Information
------------------

Raspberry Pi 400 Rev 1.0
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

Raspberry Pi reference 2020-05-27
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 825107f04027269db77426046f5085475b1ea22f, stage4

Linux retropie 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
Revision        : c03130
Serial          : 100000001328f87b
Model           : Raspberry Pi 400 Rev 1.0
Throttled flag  : throttled=0x0
Camera          : supported=0 detected=0
(Also happens on the latest raspberry pi os, eeprom is from april 29)

**Comment by timg236** [comment]
Closed due to inactivity
