### ISSUE TITLE
ERROR internal error: Unexpected enum value 0 for virDomainDeviceAddressType

### ISSUE THREAD

**Issue by Marietto2008** [raspberrypi/firmware#1586]
Hello.

it's more of a challenge,to be able to emulate the raspberry pi 3 on my Jetson nano (aarch64) using virt-install. I'm learning how to do that by reading heavily here :

https://github.com/dhruvvyas90/qemu-rpi-kernel

I tried to do something like this :

virt-install \
    --name pi \
    --machine raspi3 \
    --cpu arm1176 \
    --memory 1024 \
    --import \    --disk /root/Desktop/zi/Work/Android/Raspy/Debian/2019-09-26-raspbian-buster-lite.img,format=raw,bus=virtio \
    --network user,model=virtio \
    --video vga \
    --graphics spice \
    --rng device=/dev/urandom,model=virtio \
    --boot 'uefi=RPI_EFI.fd,dtb=bcm2710-rpi-3-b-plus.dtb,kernel=kernel8.img,kernel_args=root=/dev/vda2 rootwait panic=1 dwc_otg.fiq_fsm_enable=0' \
    --events on_reboot=destroy 

But I get this error :

ERROR internal error: Unexpected enum value 0 for virDomainDeviceAddressType

I've got the UEFI BIOS file from here :

https://github.com/andreiw/RaspberryPiPkg/blob/master/Binary/prebuilt/2019Jan16-GCC5/RELEASE/RPI_EFI.fd

I'm not sure if it isn't the right efi file to use in this specific configuration or if it is,but I'm passing the parameter badly. What do you suggest me to do ?

**Comment by pelwell** [comment]
Cleaner not a firmware problem because you aren't using the firmware.
