### ISSUE TITLE
Kernel header package is missing

### ISSUE THREAD

**Issue by eriktews** [raspberrypi/firmware#1616]
At least when using the 64 bit beta of Raspbian, there is currently no package that provides the kernel headers for the default kernel. Currently, the default kernel is 1:1.20210805-1 (5.10.17-v8+) but the only kernel header packages (linux-headers-....) are for 4.19.194-3. It would be great when the kernel headers would be provided here as well so that one can easily build additional modules for the kernel without having to install these headers manually or having to reinstall the entire kernel.

**Comment by popcornmix** [comment]
This is in't the right place for packaging issues.
Try here: https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/

**Comment by XECDesign** [comment]
To answer the question anyway, the headers package is `raspberrypi-kernel-headers`.
