### ISSUE TITLE
OMX_GetParameter  OMX_IndexParamVideoBitrate set zeros version, size, port

### ISSUE THREAD

**Issue by xlazom00** [raspberrypi/firmware#163]
OMX_VIDEO_PARAM_BITRATETYPE bitrate_param;

GST_OMX_INIT_STRUCT (&bitrate_param); // set up to init values
bitrate_param.nPortIndex = self->enc_out_port->index;

OMX_ERRORTYPE err;
err = OMX_GetParameter (self->enc->handle, OMX_IndexParamVideoBitrate, &bitrate_param);

OMX_GetParameter   return zero in version, size, port
It should return same port I setup up before OMX_GetParameter 
right version and size

some frameworks like gst-omx use get/set mechanism for initialization

**Comment by Ruffio** [comment]
@popcornmix has this been resolved in the jira bugtracker?

**Comment by popcornmix** [comment]
Pretty sure this has been fixed. @xlazom00 can you still reproduce this?

**Comment by 6by9** [comment]
Just looking at the source and I don't think this is fixed.
nSize an nVersion aren't set by default in the component, and getParameter copies port->video_bitrate in its entirety, so returns 0 for those fields. Two line patch required I think - @popcornmix I'll ping it through to you.

**Comment by popcornmix** [comment]
I've added @6by9's patch in latest rpi-update - does that help?

**Comment by JamesH65** [comment]
Can this be closed as fixed?

**Comment by JamesH65** [comment]
@6by9 This appears to be fixed?

**Comment by 6by9** [comment]
AFAIK It's fixed. Confirmation would have been nice from the OP, but may as well close after all this time.
