### ISSUE TITLE
Hibernation (suspension to disk), sleep (suspension to memory, low-power mode) remain unsupported.

### ISSUE THREAD

**Issue by NoSuck** [raspberrypi/firmware#1635]
@slaminger mentioned suspension in #1274, and I realized this should probably be opened as an issue.  The Pi is good hardware, but its lack of power management is baffling.  Suspend-to-disk (hibernation) would be especially useful, as the Pi is not like a desktop that stays plugged into the wall.  You should be able to unplug and go anywhere!

**Comment by NoSuck** [comment]
> It's the only device missing the fundamentals unfortunately.

Do you have any recommendations for desktop-replacement devices that do support hibernation, @slaminger?

**Comment by seamusdemora** [comment]
The exigencies of the startup period are easy enough to understand. But closing the door on the possibility of future innovation is a bit more difficult to fathom.

**Comment by JamesH65** [comment]
Which part of we don't have the manpower to do this is difficult to fathom? It also seems (to me at least) that the cost/benefit of doing this (some man years of work) lies firmly on the cost side. 

TBH, my brand new Dell laptop with windows11 fails more than it succeeds when it goes to sleep. Only this morning I woke to it on a blue recovery screen. If MS/Dell with all their manpower cannot get it to work properly, it doesn't bode well!

**Comment by seamusdemora** [comment]
@JamesH65 : Sorry you chose to take the comment negatively.
