### ISSUE TITLE
Kernel panic after bump to 5.10.73

### ISSUE THREAD

**Issue by mirak011** [raspberrypi/firmware#1636]
After upgrading to the latest firmware with kernel 5.10.73 Raspberry is not booting up and stops at kernel backtrace. It works without any issue with the previous commit with kernel 5.10.64, so far tested on Raspberry Pi 1B and 1A 

![rpi](https://user-images.githubusercontent.com/10831192/137476951-5cb44d6c-c066-4760-abb2-06d295b58736.jpg)

**Comment by popcornmix** [comment]
The fix should now be in rpi-update kernel.
