### ISSUE TITLE
Unable to send VLC video to display

### ISSUE THREAD

**Issue by JRDavisUF** [raspberrypi/firmware#1637]
Starting with commit 15471b6e99b6db2f3206f0aed67d0aebbfc9f9cf, I'm unable to use VLC to send a RTSP video stream to hdmi0/hdmi1.  Issue is described here:  https://forum.videolan.org/viewtopic.php?f=13&t=158305&p=521496#p521496

Using rpi-update to revert to a previous commit fixes the issue.

However, I cannot tell what the commit "firmware: video_decode: Ensure all buffers are flushed before port disable completes" actually changes to determine if this is a firmware issue or an issue with VLC (3.0.12-0+deb10u1+rpt2).

I'm using console login (ie no X11) and sending the video via:
  vlc rtsp://redacted -I dummy  --qt-fullscreen-screennumber=2
(The vlc binary has been tweaked so that it will run as root).   Although vlc runs nothing appears...Nothing related to it not working appears in the logs

I've got multiple PI 4 Modem B Rev 1.1 with this issue...although it does effect older PIs (Pi Model B Rev 2) as well.  The vc4-fkms-v3d overlay is loaded.  I tried a couple different combinations of the this overlay and gpu_mem in the config file to no avail.  I also tried bumping mmal logging up to 5 to see if I saw anything new ... to no avail as well.

Per the update to documentation/ilcomponents/video_decode.html
           <tr valign="top"><td><tt>OMX_IndexParamBrcmStopOnColourSpaceAndPARChange</tt>
          <td> Query /set whether the codec should stop and wait should either the colour space
            or pixel aspect ratio change.

"stop and wait" might be what it's doing....but that is as far as I got as I cannot really tell what this stuff is referring to...

**Comment by JRDavisUF** [comment]
Yup, thx.

**Comment by JRDavisUF** [comment]
All our feeds are internal, however, I can replicate the problem with:

vlc https://youtu.be/_7DpZSy_biY -I dummy --qt-fullscreen-screennumber=2

**Comment by yutayu** [comment]
@popcornmix 
:)
