### ISSUE TITLE
Framebuffer Entry in /chosen/framebuffer@xxx/format not correct

### ISSUE THREAD

**Issue by macromorgan** [raspberrypi/firmware#1643]
Problem:
For the /chosen entry describing the framebuffer, the format is not correct. I have set my dpi_output_format to 0x07f213 (DPI_OUTPUT_FORMAT_16BIT_565_CFG2) which I would expect would set the value of /chosen/framebuffer@3ea9b000/format to "r5g6b5", but instead it is showing as "a8r8g8b8".

To Reproduce:
Use a 16 Bit DPI screen. Set the following values in your config.txt:
framebuffer_width=640
framebuffer_height=480
enable_dpi_lcd=1
display_default_lcd=1
dpi_group=2
dpi_mode=87
dpi_output_format=0x07f213
dpi_timings=480 0 41 20 60 640 0 5 10 10 0 0 0 60 0 32000000 1
gpio=0-8=a2
gpio=12-17=a2
gpio=20-24=a2

Expected Behavior:
Since the dpi_output_format bits 0-3 equal one of 2, 3 or 4 I would assume the chosen node would show r5g6b5 as the format.

Actual Behavior:
chosen node shows the format as a8r8g8b8.

System: Raspberry Pi 4
Raspian OS Buster 5.10 kernel
DPI Screen: https://wiki.geekworm.com/2.8_inch_Touch_Screen_for_Pi_zero

**Comment by 6by9** [comment]
The display pipeline is not as simple as you make out.

Planes of any of a number of formats are composed by the Hardware Video Scaler (HVS), to timings programmed into the Pixel Valve (PV), and routed through an output block (DSI, HDMI, DPI, VEC, etc).

The bitdepth of the frame generated by the HVS is independent of the input planes (including your frame buffer), and indeed the conversion to RGB565 in your case happens in the DPI block, not the HVS.

**Comment by macromorgan** [comment]
Good to know. So... not an issue?
