### ISSUE TITLE
[Question] Firmware maintainer of BCM43430/1 in Raspberry Pi 3B?

### ISSUE THREAD

**Issue by Matheus-Garbelini** [raspberrypi/firmware#1676]
Hi, I'm trying to understand to what company to report a firmware vulnerability (DoS) for Raspberry Pi 3.
I understand that at some point the Cypress/Infineon acquired a part of broadcom so it may be responsible for further updates to BCM43430 chipset used in Raspberry Pi 3B. However, such chipset is quite old. Should I contact Infineon or Broadcom regarding firmware issues?
Specifically to brcm/brcmfmac43430-sdio firmware.

Regards.

**Comment by Matheus-Garbelini** [comment]
@pelwell thanks a lot for your fast reply. Will contact Infineon asap.

**Comment by Matheus-Garbelini** [comment]
Hi @pelwell, It seems Infineon is not replying for about a week.
Since you are an official raspberrypi maintainer, is it possible to sent the report directly to you via encrypted email?

Regards.

**Comment by pelwell** [comment]
I've asked our main Infineon contact how they want to handle this, and will get back to you with their answer.

**Comment by grsm17** [comment]
Hi Matheus - Could you confirm that you followed the process listed here for highlighting issues?
https://www.infineon.com/dgdl/Vulnerability_Notification_Process.pdf?fileId=8ac78c8b7ca35f7b017ca6d98b1c0000

If yes then i will chase our internal teams, if not then please do so and i will follow up once received by the team.

Thanks
Graham

**Comment by pelwell** [comment]
Thank you, Graham.

**Comment by Matheus-Garbelini** [comment]
Hi, @grsm17 and @pelwell , thanks a lot for the reply.

@grsm17 Yes, the report was sent to Infineon PSIRT (psirt@infineon.com) at January 12th, 10:15AM GMT, from my university email (matheus_garbelini@mymail.sutd.edu.sg). I've just sent a reply to the same email to help tracking it down by your team.

Regards and thanks for the attention.

**Comment by pelwell** [comment]
@Matheus-Garbelini I've heard that Infineon support are now looking into the report and will contact you directly as and when necessary 

Thanks for bringing this to our attention.

**Comment by Matheus-Garbelini** [comment]
@pelwell Indeed, everything is being handled now.
Thanks for your support and the work on Raspberry Pi platform.
