### ISSUE TITLE
Wiki Page - Mailbox Property Interface

### ISSUE THREAD

**Issue by michalsc** [raspberrypi/firmware#1690]
The Wiki page [Mailbox Property Interface](https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface) says that the Tag 0x00030003, Get Voltage, returns a value which is an offset from 1.2V described in 0.025V units. After looking what results I am getting from VPU, the Get Voltage tag returns an absolute value in microvolts.

Corrected Wiki would remove the disaccord and would save some time on debugging the apparently well working mailbox call.

**Comment by pelwell** [comment]
See https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface/61e6456dd263d75d5e4345c7290b6cac8089cc2b.

**Comment by michalsc** [comment]
Perfect! The new wiki explains it perfectly. I will close the issue now.

Thank You Phil for fixing it :)
