### ISSUE TITLE
libGLES missing symbol

### ISSUE THREAD

**Issue by MaitreDede** [raspberrypi/firmware#1693]
**Describe the bug**

I am trying to build a simple full screen web display, with 3D acceleation, based on alpine linux and midori.

With packaged libraries, I have the error `libEGL warning: DRI2: failed to authenticate`. Seams that this should be fixed by using libraries provided from firmware.

**To reproduce**
- Install a vanilla alpine armv7 on a raspberry pi 4
- enable opengl : https://wiki.alpinelinux.org/wiki/Raspberry_Pi#Enable_OpenGL_.28Raspberry_Pi_3.2F4.29
- install xorg, midori : `apk add --no-cache xorg-server xf86-input-libinput eudev eudev-openrc mesa xf86-video-fbdev xset bspwm gst-libav midori midori-lang`
- launch : `/usr/bin/xinit $(which midori) -e FullScreen -a https://www.raspberrypi.com/` : "failed to authenticate" and display is slow (looks like software rendering)
- replace native libs `libGLES` and `libEGL` with firmware
- launch (same command) : error is `glGetInternalformativ: symbol not found`

**Expected behaviour**
Expected is a fullscreen browser with 3D acceleation

**Actual behaviour**
Software rendering (if generic librairies) or does not start (with firmware libraries).

**System**

* Which model of Raspberry Pi? e.g. Pi4 4G
* Which OS and version (`cat /etc/rpi-issue`)? Alpine linux 3.15 armv7, built using https://gitlab.com/raspi-alpine/builder
* Which firmware version (`vcgencmd version`)? version bd88f66f8952d34e4e0613a85c7a6d3da49e13e2 (clean) (release) (start)
* Which kernel version (`uname -a`)? 5.15.22-0-rpi4 #1-Alpine SMP Wed Feb 9 15:42:14 UTC 2022 armv7l GNU/Linux

**Comment by popcornmix** [comment]
> replace native libs libGLES and libEGL with firmware

Not the right move. Firmware libraries are deprecated (and not supported at all on Pi4).
They need custom initialisation to attach to a dispmanx window context (also a deprecated interface).

If you want this to work, then using the kms driver (like RpiOS bullseye does) and mesa gl libraries is the correct direction to go in. But as @JamesH65 says, this isn't the place to ask. Possibly our forums or alpine linux forums.
