### ISSUE TITLE
Question: Does all CM4 and Rpi 400 have BCM2711 Stepping C0?

### ISSUE THREAD

**Issue by lategoodbye** [raspberrypi/firmware#1704]
The approach to patch the dma-range for emmc2 in the DT by the firmware doesn't work so well in complex boot chains like on Fedora.

So idea is to hardcode the proper dma-range on boards which should always have a BCM2711 Stepping C0. So the question is it save to assume CM4 and Rpi 400 always have at least C0 Stepping?

**Comment by timg236** [comment]
Yes

**Comment by lategoodbye** [comment]
Thanks a lot
