### ISSUE TITLE
Typo in mailbox Set voltage wiki

### ISSUE THREAD

**Issue by ProPuke** [raspberrypi/firmware#1708]
The wiki states the following [here](https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface#set-voltage) when talking about specified voltage values:

> * value <= 16: relative to platform-specific typical voltage, in 25mV steps
> * 16 < value < **50000**: relative to platform-specific typical voltage, in microvolts
> * value >= **500000**: absolute voltage in microvolts

(bold for emphasise)

Note the extra zero on one one of the 5x values. I assume they both should match and one is a typo.
I'm not sure which that would be, though.

**Comment by pelwell** [comment]
Now fixed. It's a Wiki though, meaning you could have just edited it yourself.
