### ISSUE TITLE
This demo application is not available on the Pi4

### ISSUE THREAD

**Issue by xingyun86** [raspberrypi/firmware#1715]
[pi4]
I want to use egl and dispmanx create window and set window's layer.But I found that it cannot be success. 
I use /opt/vc/.../hello_triangle2 to compile and run it. But response me "This demo application is not available on the Pi4" 。
How I can do? Please help me.
[version info]
```pi@raspberrypi: $ sudo rpi-eeprom-update
BOOTLOADER: up to date
   CURRENT: Thu 29 Apr 2021 04:11:25 PM UTC (1619712685)
    LATEST: Thu 29 Apr 2021 04:11:25 PM UTC (1619712685)
   RELEASE: default (/lib/firmware/raspberrypi/bootloader/default)
            Use raspi-config to change the release.

  VL805_FW: Using bootloader EEPROM
     VL805: up to date
   CURRENT: 000138a1
    LATEST: 000138a1
```
===============================================
pi@raspberrypi: $ uname -a
Linux raspberrypi 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux

**Comment by popcornmix** [comment]
dispmanx was a proprietary interface only used on raspberry pi.
That interface is deprecated (and was never supported for gl on pi4) in favour of standard linux APIs.
Some discussion of alternatives  [here](https://forums.raspberrypi.com/viewtopic.php?t=243707)

**Comment by xingyun86** [comment]
> 
But I cannot set my app ui‘s layer on monitor？Could you give me some supply？
I tried drm， but also give me show：
```
pi@raspberrypi: $ sudo ./drmtest 
resolution: 1280x1024
* failed to add service - already in use?
```

**Comment by popcornmix** [comment]
Are you launching from X? Try launching from console outisde of X (or change VT with ctrl-alt-F<n>)
