### ISSUE TITLE
Last Raspbian bookworm/sid initramfs-tools package (0.141) needs the kernel .config to recreate the initrd

### ISSUE THREAD

**Issue by arillle** [raspberrypi/firmware#1722]
Happened on raspberry pi3b running Raspbian bookworm/sid (kernel 5.15.32-v7l+)
Since the recent update of initramfs-tools package to 0.141, the creation of a new initrd will fail if the file /boot/config-5.15.32-v7l+ does not exist.
(as I'm booting on iSCSI, I'm recreating the initrd before booting on the kernel)
Would you please add the .config file to the repository please ?

**Comment by XECDesign** [comment]
We don't support testing and sid releases, or the initramfs-tools package. The existing package from Debian makes a lot of assumptions that don't work with our bootloader. The config file is the least of it. We do need to fix this, but I think that will be done by providing our own fork of the package. Unfortunately, that's currently not near the top of the todo list.

When bookworm is stable, we could take Debian's versions of the raspi-firmware and kernel packages, which have some hooks to set things up properly and auto-generate config.txt accordingly.
