### ISSUE TITLE
QT6 eglfs is not working on raspberry pi 4

### ISSUE THREAD

**Issue by PhysicsX** [raspberrypi/firmware#1724]
Hello

I cross compiled the qt6.3 for raspberry pi. But I can not run the eglfs platform.
It gives these erros:

![image](https://user-images.githubusercontent.com/7509762/166160299-377cca6b-8cfa-4da8-aed2-b28ff91da5d2.png)

Configuration output is like that 

```
QPA backends:
  DirectFB ............................... no
  EGLFS .................................. yes
  EGLFS details:
    EGLFS OpenWFD ........................ no
    EGLFS i.Mx6 .......................... no
    EGLFS i.Mx6 Wayland .................. no
    EGLFS RCAR ........................... no
    eglfs_egldevice ...................... yes
    eglfs_gbm ............................ yes
    EGLFS VSP2 ........................... no
    EGLFS Mali ........................... no
    EGLFS Raspberry Pi ................... no
    EGLFS X11 ............................ yes
```
EGLFS Raspberry Pi  is "no". It should be on also?
What should I do ? Is eglfs_egldevice not enough ?

**System**
Model           : Raspberry Pi 4 Model B Rev 1.1
Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux

Raspberry Pi reference 2022-04-04
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 226b479f8d32919c9fe36dd5b4c20c02682f8180, stage4

Thank you very much.

**Comment by carlonluca** [comment]
EGLFS Raspberry Pi is based on dispmanx, you need the old libbrcm libs for that. Also, I think I remember it is still not ported to cmake, I had to build it manually. KMS eglfs is probably what you want.

**Comment by PhysicsX** [comment]
Thanks for the answer.

KMS eglfs may be okay for me.

What should I do to enable kms eglfs ? Should I compile again the Qt?

Thank you.

**Comment by carlonluca** [comment]
You already did, eglfs GBM is enabled. For the rest not sure sorry, I saw those errors in quite a few cases.

**Comment by popcornmix** [comment]
This question would be better directed at eglfs/QT6 developers.

gbm generally means running fullscreen as the drm master.
This means it won't work from an X desktop session.
You can either boot to console and run it, or switch away from X VT (e.g. ctrl-alt-F2).

But I don't use eglfs (just using knowledge of gbm apps like kodi), hence the suggestion to ask eglfs/QT6 devs.
