### ISSUE TITLE
USB BOOT FOR Raspberry Pi 4B révision 1.5

### ISSUE THREAD

**Issue by fmoon4** [raspberrypi/firmware#1729]
**Is this the right place for my bug report?**
USB Booting, Yes

**Describe the bug**
I can't make Raspberry Pi 4B révision 1.5  boot from USB  SSD. 
I used the  the latest firmware April 2022. 
https://freeimage.host/i/jokLf2

**To reproduce**
List the steps required to reproduce the issue.
Make bootable USB SDD and 

**Expected behaviour**
Add a clear and concise description of what you expected to happen.

**Actual behaviour**
Add a clear and concise description of what actually happened.

**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:

* Which model of Raspberry Pi? Raspberry Pi 4B révision 1.5
* Which OS and version (`cat /etc/rpi-issue`)? recommande Raspbian 32b in the latest  Raspberry Pi Imager

**Logs**
see the screen here : https://freeimage.host/i/jokLf2

**Additional context**

**Comment by pelwell** [comment]
How did you configure your (not very) bootable SSD?

**Comment by timg236** [comment]
The screenshot indicates that there is no firmware (start4.elf, fixup4.dat, start.elf, fixup.dat) in the FAT boot partition. It would be verifying that the image was flashed correctly.
