### ISSUE TITLE
raspberry pi 4

### ISSUE THREAD

**Issue by khangTi** [raspberrypi/firmware#1730]
i am using 1 raspberry pi 4 model b, but when i install android 10 it gives me error attached,
Is there any way to fix this error? 
"start4x.elf: is not compatible
This board requires newer software
Get the latest software from https://www.raspberrypi.com/software/"
I'm using the setup file at this site: https://konstakang.com/devices/rpi4/LineageOS17.1/

**Comment by JamesH65** [comment]
We don't support Android here, try our forums, which have a third party Android section.

**Comment by timg236** [comment]
As James says Android isn’t supported but you can copy the *.elf and *dat files from this repo on to your Android repo. You might want to ping the Android maintainers and ask them to update the build.

**Comment by khangTi** [comment]
thanks so much, I will copy 2 files the *.elf and *dat to test run

**Comment by khangTi** [comment]
yeah I copied 4 files fixup4.dat, fixup4x.dat, start4x.elf, start4.self replaces the boot files and is already working, thank you very much
