### ISSUE TITLE
GPU memory leak with OMX_UseEGLImage and OMX_FreeBuffer

### ISSUE THREAD

**Issue by AD-N770** [raspberrypi/firmware#174]
I've been working last weeks[1] on supporting EGL rendering in gst-omx for GStreamer 0.10.

There's an example application[2] derived from hello_videocube that I'm using to test the code.

The schema implemented is the following:
1) the gst-omx decoder ask for application to provide a pool of 4 EGL images
2) when application provides a pool the decoder is tunneled to egl render component and the EGL images in the pool are populated to it's output pool using OMX_UseEGLImage.
3) if vide size change is detected the decoder+egl_render are flushed, moved to idle state, omx buffers freed with OMX_FreeBuffer and untunneled. And back to state 2 with the new size.

The issue I'm experiencing is that the GPU memory allocated in the first pool doesn't is not freed although the original GL Texture, the EGL image [3] and the omxbuffers are properly freed without errors.

I've tried to simulate the resource allocation schema with a modified hello_videocube dropping the omx part but replicating my approach of GLTexture+EGLImage creation/destruction and the leak is not reproducible.

My actual hypothesis is that OMX_UseEGLImage takes a reference to the EGLImage which is not released on OMX_FreeBuffer. Please could you explain which is the actual behaviour and confirm/refute my hypothesis ?

At [4] there's a log running the example application and invoking 'vcdbg reloc' at certain execution points that exhibit the leak in the 'Texture blob' objects.

[1] http://cgit.freedesktop.org/~adn770/gst-omx/log/?h=egl
[2] http://cgit.freedesktop.org/~adn770/gst-omx/tree/examples/egl/testegl.c?h=egl
[3] http://cgit.freedesktop.org/~adn770/gst-omx/tree/examples/egl/testegl.c?h=egl#n527
[4] https://dl.dropboxusercontent.com/u/4577541/testegl.log

**Comment by Ruffio** [comment]
@AD-N770 Is this still an issue?

**Comment by AD-N770** [comment]
I don't know. I haven't been working with the RPI in the last year.
