### ISSUE TITLE
5.15.68 missing modules

### ISSUE THREAD

**Issue by lee-yunseok** [raspberrypi/firmware#1747]
*** Updating firmware
 *** Updating kernel modules
find: ‘//root/.rpi-firmware/modules’: No such file or directory

 *** If no errors appeared, your firmware was successfully updated to 2563901a9922dd3fdca1b11b262eab46408e0849

https://github.com/raspberrypi/rpi-firmware/commit/2563901a9922dd3fdca1b11b262eab46408e0849

**Comment by popcornmix** [comment]
My mistake - I've pushed the fix.

**Comment by lee-yunseok** [comment]
Thank you for your work :)
