### ISSUE TITLE
Where to request new sensors support add?  Create dtoverlay support for AHTX family of sensors?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [raspberrypi/firmware#1757]
Where to request new sensors support add?  Create dtoverlay support for AHTX family of sensors?

**Comment by pelwell** [comment]
Open an issue in our Linux repo saying what you want and we'll consider it.

**Comment by pelwell** [comment]
When making your request, assume we know nothing about the sensors.

**Comment by Jibun-no-Kage** [comment]
Ah!  Thank you, I will do!
