### ISSUE TITLE
Video renders upside down and backwards when Broadcom proprietary tunnels are enabled

### ISSUE THREAD

**Issue by jldeon** [raspberrypi/firmware#176]
I first noted this issue on the RPi forums - http://www.raspberrypi.org/phpBB3/viewtopic.php?f=67&t=41007

Essentially, if the "Broadcom proprietary tunnels" are enabled, the video is rendered from an "egl_render" component onto the texture in an orientation that is flipped horizontally and vertically from the expected state.  

If you disable the proprietary tunnels, the video renders in the correct orientation, but there's a performance hit.  

An example of this which uses the hello_videocube demo as a starting point:

https://gist.github.com/jldeon/5505216#file-video-c-L147

I have modified triangle.c so that the cube doesn't move anymore (making the issue easier to see).  I have also modified video.c so that you can toggle the tunnel disable code off or on by commenting or uncommenting line 147.  

If you compile with this line commented out, you'll see that the bird's head points to the right.  If the line is not commented out, you'll see that the bird's head is pointing to the left.

It's a bit hard to see from this example code which way is the "correct" orientation.  I've been running some code which uses a similar pipeline to render to a Clutter/COGL texture.  This code displays the video properly if I use a software decoder, or on other Linux devices/PCs.  However, without disabling the tunnels, it renders upside down and backwards on the Pi.  

Thus, my current impression is that the Pi's firmware is misbehaving.  At the very least, it seems like regardless of the tunneling method between components, the video should render consistently.

**Comment by popcornmix** [comment]
Closing as there is no "correct" answer to how the texture should be oriented and changing it now would likely upset more users.
