### ISSUE TITLE
Raspberry Pi OS 5.15.84 seems to not forward IP packets at all independently of the net.ip4.ip_forward=1 sysctl variable setting

### ISSUE THREAD

**Issue by ThomasKorimort** [raspberrypi/firmware#1777]
I have produced some extensive documentation of my attempts of getting a Raspberry Pi 4 4GB and a WaveShare SIM8200EA M2 5G HAT modem working as a residential gateway combination. I got the modem working and able to connect to the internet on the Raspberry Pi 4 4 GB locally, but the packet forwarding seems to not work at all. When tracerouting the packets, there path always ends at my Raspberry Pi 4 4 GB supposed-to-be residential gateway without being frowarded to the ISP-provided dynamic IP address and tiny network. I have made a summary thread on the Raspberry Pi Forum containing firewall configuration, /etc/sysctl.conf settings, ISC DHCP server configuration and routing tables:

https://forums.raspberrypi.com/viewtopic.php?t=346017

**Comment by popcornmix** [comment]
As stated in linked thread, this isn't the right place for reporting a linux issue.
