### ISSUE TITLE
How to reduce fan speed of WaveShare SIM8200EA M2 5G HAT?

### ISSUE THREAD

**Issue by ThomasKorimort** [raspberrypi/firmware#1778]
https://www.waveshare.com/wiki/SIM8200EA-M2_5G_HAT

I am using the qmi_wwan driver for the Qualcomm Snapdragon X55 as well as dwc2 dtoverlay and g_ether kernel module. Like this i got the modem working as local internet connection. Now the fan is very loud and i don't know how to configure the speed of the fan.

**Comment by pelwell** [comment]
1. This is not the place to ask questions - try https://forums.raspberrypi.com/
2. This is not the place to ask questions about WaveShare products - try https://support.waveshare.com/hc/en-us/requests/new
