### ISSUE TITLE
Feature Request Possible?  PIR Motion Sensor Dtoverlay Possible?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [raspberrypi/firmware#1793]
Feature Request Possible?  PIR Motion Sensor Dtoverlay Possible?  Unlike many sensors I can't seem to find it the Linux kernel already supports a family of motion sensors, say the generic 'PIR' sensors?  If so, can we get an dtoverlay for such?  The PIR sensor specifically?

**Comment by Jibun-no-Kage** [comment]
A place to start, thanks.

**Comment by pelwell** [comment]
I've just given you a list.
