### ISSUE TITLE
 Drop data UART 3/5 if use UART with SPI in same time

### ISSUE THREAD

**Issue by tam1111574** [raspberrypi/firmware#1803]
Hi all,
I have a project which use the Raspberry CM4 connect with 2 STM32H7 via UART (UART3, UART5) and SPI (SPI0, SPI6)
The diagram of system in attached image
![Forum](https://user-images.githubusercontent.com/15842703/229343432-74979935-d8d5-49ec-8b34-44c21e44f0c4.png)

We have already tested follow the suggest in this post https://github.com/raspberrypi/firmware/issues/1017

We receive and transfer data via UART between Rasperry and 2 STM32H7 is ok, all data receive is correct. But when we begin transfer SPI, UART3 and UART5 will be lost data in raspberry side (The received data in STM32 MCU side is ok).
This is my configure in config.txt file
> over_voltage=6
> arm_freq=2000
> gpu_freq=700
> dtoverlay=vc4-fkms-v3d
> dtoverlay=dwc2,dr_mode=host
> disable_splash=1
> boot_delay=0
> force_turbo=1
> enable_uart=1
> dtoverlay=pi3-disable-bt
> dtoverlay=uart3
> dtoverlay=uart5
> dtoverlay=spi0-1cs
> dtoverlay=spi6-2cs
> avoid_warnings=2
> gpu_mem=8
> dtoverlay=disable-bt
> dtparam=i2c_arm=on
> dtparam=spi=on
> display_default_lcd=0
> dtoverlay=disable-wifi

For testing we make a small code in STM32 MCU transfer 5000 lines with same data via UART and check the received data in raspberry side. The data transfer via UART in STM32:
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
In the Raspberry side, we create two threads (Pthread in C program) to open SPI module and a while loop transfer the random data via SPI. (SPI package data 64 KB)
Parameter testing

- SPI speed 20MHz
- Uart baudrate 115200

This is some result:
- When disable SPI transfer, all data receive in both UART are correct in raspberry side. Data received via command
> cat /dev/ttyAMA1 or cat /dev/ttyAMA2

> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|
> |__--==AA==--__|__--==BB==--__|__--==CC==--__|__--==DD==--__|__--==EE==--__|__--==FF==--__|__--==GG==-__|

- When begin transfer SPI data (64KB), both UART is lost data. Data received via command
> cat /dev/ttyAMA1 or cat /dev/ttyAMA2

> |__--==AA==--__|__--==BB==--__|_- ==EE==--__|__--==FF==--__|__--==- -==DD==--__|__--==EE==--__|__--_ |__--==CC==--__|__--==DD==--__|- -__|__--==BB==--__|__--==CC==--= =-__|
> |__--==AA==--__|__--==BB== FF==--__|__--==GG==-__|
> |__--==- ==EE==--__|__--==FF==--__|__--=_ |__--==DD==--__|__--==EE==--__|- -__|__--==CC==--__|__--==DD==--A A==--__|__--==BB==--__|__--==CC- ==GG==-__|
> |__--==AA==--__|__--_ _--==FF==--__|__--==GG==-__|
> |_- __|__--==EE==--__|__--==FF==--_C ==--__|__--==DD==--__|__--==EE=- ==BB==--__|__--==CC==--__|__--=
>  |__--==AA==--__|__--==BB==--__|- -__|__--==GG==-__|
> |__--==AA==-E E==--__|__--==FF==--__|__--==GG- -==DD==--__|__--==EE==--__|__--=_ |__--==CC==--__|__--==DD==--__|= =--__|__--==BB==--__|__--==CC==G ==-__|
> |__--==AA==--__|__--==BB- ==FF==--__|__--==GG==-__|
> |__--_ _--==EE==--__|__--==FF==--__|__- __|__--==DD==--__|__--==EE==--_B ==--__|__--==CC==--__|__--==DD=_ --==AA==--__|__--==BB==--__|__--_ |__--==GG==-__|
> |__--==AA==--__= --__|__--==FF==--__|__--==GG==-= DD==--__|__--==EE==--__|__--==F_ _--==CC==--__|__--==DD==--__|__- __|__--==BB==--__|__--==CC==--_G ==-__|
> |__--==AA==--__|__--==BB- ==FF==--__|__--==GG==-__|
> |__--_ |__--==EE==--__|__--==FF==--__|= =--__|__--==DD==--__|__--==EE=== =BB==--__|__--==CC==--__|__--==_ _--==AA==--__|__--==BB==--__|__- __|__--==GG==-__|
> |__--==AA==--E ==--__|__--==FF==--__|__--==GG=- -==DD==--__|__--==EE==--__|__--_ _|__--==CC==--__|__--==DD==--__= --__|__--==BB==--__|__--==CC==-G G==-__|
> |__--==AA==--__|__--==B_ --==FF==--__|__--==GG==-__|
> |___ _|__--==EE==--__|__--==FF==--__C ==--__|__--==DD==--__|__--==EE=- -==BB==--__|__--==CC==--__|__--
>  |__--==AA==--__|__--==BB==--__|_- -__|__--==GG==-__|
> |__--==AA==--= EE==--__|__--==FF==--__|__--==G_ --==DD==--__|__--==EE==--__|__-_ _|__--==CC==--__|__--==DD==--__= --__|__--==BB==--__|__--==CC==-G G==-__|
> |__--==AA==--__|__--==B- -==FF==--__|__--==GG==-__|
> |__-_ _|__--==EE==--__|__--==FF==--__= =--__|__--==DD==--__|__--==EE==- ==BB==--__|__--==CC==--__|__--=
>  |__--==AA==--__|__--==BB==--__|- __|__--==GG==-__|
> |__--==AA==--E ==--__|__--==FF==--__|__--==GG=- -==DD==--__|__--==EE==--__|__--_ |__--==CC==--__|__--==DD==--__|A ==--__|__--==BB==--__|__--==CC=== =GG==-__|
> |__--==AA==--__|__--=_ _--==FF==--__|__--==GG==-__|
> |_- __|__--==EE==--__|__--==FF==--_C C==--__|__--==DD==--__|__--==EE- -==BB==--__|__--==CC==--__|__--| 
> |__--==AA==--__|__--==BB==--__= =--__|__--==GG==-__|
> |__--==AA== =EE==--__|__--==FF==--__|__--==_ --==DD==--__|__--==EE==--__|__-- -__|__--==CC==--__|__--==DD==--A A==--__|__--==BB==--__|__--==CC- -==GG==-__|
> |__--==AA==--__|__-_ _|__--==FF==--__|__--==GG==-__|= =--__|__--==EE==--__|__--==FF=== =CC==--__|__--==DD==--__|__--==| __--==BB==--__|__--==CC==--__|_| 
> |__--==AA==--__|__--==BB==--__- -__|__--==GG==-__|
> |__--==AA==-E E==--__|__--==FF==--__|__--==GG- -==DD==--__|__--==EE==--__|__--_ |__--==CC==--__|__--==DD==--__|= --__|__--==BB==--__|__--==CC==-= GG==-__|
> |__--==AA==--__|__--==_ _--==FF==--__|__--==GG==-__|
> |_- __|__--==EE==--__|__--==FF==--_C ==--__|__--==DD==--__|__--==EE=== =BB==--__|__--==CC==--__|__--==_ _--==AA==--__|__--==BB==--__|___ _|__--==GG==-__|
> |__--==AA==--_E ==--__|__--==FF==--__|__--==GG=- -==DD==--__|__--==EE==--__|__--_ |__--==CC==--__|__--==DD==--__|= --__|__--==BB==--__|__--==CC==-= GG==-__|
> |__--==AA==--__|__--==_ --==FF==--__|__--==GG==-__|
> |___ _|__--==EE==--__|__--==FF==--__C ==--__|__--==DD==--__|__--==EE=- ==BB==--__|__--==CC==--__|__--=
>  |__--==AA==--__|__--==BB==--__|_- -__|__--==GG==-__|
> |__--==AA==-= EE==--__|__--==FF==--__|__--==G_ _--==DD==--__|__--==EE==--__|__-- -__|__--==CC==--__|__--==DD==--A A==--__|__--==BB==--__|__--==CC- ==GG==-__|
> |__--==AA==--__|__--_ |__--==FF==--__|__--==GG==-__|
> = =--__|__--==EE==--__|__--==FF=== CC==--__|__--==DD==--__|__--==E_ _--==BB==--__|__--==CC==--__|___ |
> |__--==AA==--__|__--==BB==--_= =--__|__--==GG==-__|
> |__--==AA== =EE==--__|__--==FF==--__|__--==| __--==DD==--__|__--==EE==--__|_= --__|__--==CC==--__|__--==DD==-= =AA==--__|__--==BB==--__|__--==- ==GG==-__|
> |__--==AA==--__|__--_ _--==FF==--__|__--==GG==-__|
> |_- __|__--==EE==--__|__--==FF==--_C C==--__|__--==DD==--__|__--==EE_ --==BB==--__|__--==CC==--__|__--| 
> |__--==AA==--__|__--==BB==--__= =--__|__--==GG==-__|
> |__--==AA== =EE==--__|__--==FF==--__|__--==_ --==DD==--__|__--==EE==--__|__-- -__|__--==CC==--__|__--==DD==--A A==--__|__--==BB==--__|__--==CC- -==GG==-__|
> |__--==AA==--__|__-_ _|__--==FF==--__|__--==GG==-__|= =--__|__--==EE==--__|__--==FF=== =CC==--__|__--==DD==--__|__--==| __--==BB==--__|__--==CC==--__|_- __|
> |__--==AA==--__|__--==BB==--= FF==--__|__--==GG==-__|
> |__--==_ --==EE==--__|__--==FF==--__|__-_ _|__--==DD==--__|__--==EE==--__= =--__|__--==CC==--__|__--==DD=== AA==--__|__--==BB==--__|__--==C= =GG==-__|
> |__--==AA==--__|__--=| __--==FF==--__|__--==GG==-__|
> |- -__|__--==EE==--__|__--==FF==--C C==--__|__--==DD==--__|__--==EE- -==BB==--__|__--==CC==--__|__--| 
> |__--==AA==--__|__--==BB==--__= --__|__--==GG==-__|
> |__--==AA=== =EE==--__|__--==FF==--__|__--==| __--==DD==--__|__--==EE==--__|_- -__|__--==CC==--__|__--==DD==--A ==--__|__--==BB==--__|__--==CC=- ==GG==-__|
> |__--==AA==--__|__--| __--==FF==--__|__--==GG==-__|

We use kernel 5.10 and have already tested with kernel 6.1 but same result. Can give me a suggest for this problem ?.
Thank and best regard

**Comment by pelwell** [comment]
Duplicate of https://forums.raspberrypi.com/viewtopic.php?t=349756.
