### ISSUE TITLE
Firmware 1.20230405: CM4 with start4cd.elf/fixup4cd.dat fails to boot

### ISSUE THREAD

**Issue by srcshelton** [raspberrypi/firmware#1809]
**Describe the bug**

I have a headless CM4008032 module which I'm trying to optimally configure for server-type operation.

As part of this, I've tried to reducing the GPU memory to the minimum necessary by manually specifying:

```
start_file=start4cd.elf
fixup_file=fixup4cd.dat
```

But with this change alone, the CM4 fails to boot.  Commenting these two lines restores expected operation.

Full config.txt, split over 3 files `include`d by `config.txt`:

```
disable_overscan=1
[cm4]
camera_auto_detect=0
display_auto_detect=0
dtparam=noant=on,hdmi=off,sd_poll_once=on                                                         
dtoverlay=disable-bt                                                                              
dtoverlay=disable-wifi                                                                            
dtoverlay=ramoops-pi4,console-size=16384
max_framebuffers=0
arm_boost=1
[all]
start_file=start4cd.elf
fixup_file=fixup4cd.dat
arm_64bit=1
boot_delay=0
disable_poe_fan=1
disable_splash=1
enable_uart=1
force_eeprom_read=0
[cm4]
otg_mode=1
[all]
uart_2ndstage=1

include overclock.txt
initial_turbo=60
temp_limit=75

include legacy.txt
hdmi_ignore_edid_audio=1
enable_tvout=0
ignore_lcd=1
disable_touchscreen=1
hdmi_ignore_hotplug=1
disable_fw_kms_setup=1
avoid_warnings=1
```

Does the `cd` firmware variant lose any other functionality compared to the default one beyond a couple of VideoCore decoders, such as the ability to process complex `config.txt` files?

Is the `cd` firmware variant automatically chosen for reduced VideoCore memory allocations - and if so, what's the boundary to switch to this version?  Is the minimum VideoCore memory still 16MB as documented, even with the latest firmware and when running on the CM4?

*Update*: I can successfully boot with `gpu_mem=16` specified, but this doesn't appear to automatically select a different pair of start/fixup files.

**To reproduce**
With the cut-down VideoCore firmware loaded as above, the CM4 fails to boot.  Making no change other than commenting the two lines in `config.txt` restores expected boot behaviour.

**Expected behaviour**
Assuming that the two lines above are syntactically valid, I'd expect the system to boot with reduced VideoCore features available.

**Actual behaviour**

On reboot:

```
Initialising SDRAM 'Micron' 32Gb x2 total-size: 64 Gbit 3200
DDR 3200 1 0 64 152
Boot mode: SD (01) order f2564
SD HOST: 200000000 CTL0: 0x00800000 BUS: 400000 Hz actual: 390625 HZ div: 512 (256) status: 0x1fSD HOST: 200000000 CTL0: 0x00800000 BUS: 400000 Hz actual: 390625 HZ div: 512 (256) status: 0x1fff0000 delay: 276
OCR c0ff8080 [0]
CID: 00150100424a5444345203708e4e9788
 0xee
MBR: 0x00000800,    4096 type: 0x04
MBR: 0x00201800,  131072 type: 0x0b
MBR: 0x01f1f800,  131072 type: 0x0b
Trying partition: 0
GPT e60773e0a240de478c1d95d7d0aa35a3 000000001 003a3dfff num-partitions 128 entry-size 128
GPT partition: 0 b921b045-1df0-41c3-af44-4c6f280d3fae 000001800..0002017ff
GPT partition: 1 ebd0a0a2-b9e5-4433-87c0-68b6b72699c7 000201800..0002217ff
Matched GUID bootable-part-idx 0 want partition 0
type: 32 lba: 2103296 oem: 'BSD  4.4' volume: ' BOOT_0     '
rsc 32 fat-sectors 1008 c-count 129024 c-size 1
root dir cluster 2 sectors 0 entries 0
FAT32 clusters 129024
Trying partition: 0
GPT e60773e0a240de478c1d95d7d0aa35a3 000000001 003a3dfff num-partitions 128 entry-size 128
GPT partition: 0 b921b045-1df0-41c3-af44-4c6f280d3fae 000001800..0002017ff
GPT partition: 1 ebd0a0a2-b9e5-4433-87c0-68b6b72699c7 000201800..0002217ff
Matched GUID bootable-part-idx 0 want partition 0
type: 32 lba: 2103296 oem: 'BSD  4.4' volume: ' BOOT_0     '
rsc 32fat-sectors 1008 c-count 129024 c-size 1
root dir cluster 2 sectors 0 entries 0
FAT32 clusters 129024
Firmware: 82f3750a65fadae9a38077e3c2e217ad158c8d54 Mar 17 2023 10:50:56
Starting start4cd.elf @ 0xffa00200 partition 0
+

```

On cold boot:

```
RPi: BOOTLOADER release VERSION:8ba17717 DATE: 2023/01/11 TIME: 17:40:52
BOOTMODE: 0x06 partition 0 build-ts BUILD_TIMESTAMP=1673458852 serial f80ba322 boardrev d03140 stc 478836
PM_RSTS: 0x00001000
part 00000000 reset_info 00000000
Boot mode: SD (01) order f2564
SD HOST: 200000000 CTL0: 0x00800000 BUS: 400000 Hz actual: 390625 HZ div: 512 (256) status: 0x1fEMMC
SD retry 1 oc 0
tition: 0
GPT e60773e0a240de478c1d95d7d0aa35a3 000000001 003a3dfff num-partitions 128 entry-size 128
GPT partition: 0 b921b045-1df0-41c3-af44-4c6f280d3fae 000001800..0002017ff
GPT partition: 1 ebd0a0a2-b9e5-4433-87c0-68b6b72699c7 000201800..0002217ff
Matched GUID bootable-part-idx 0 want partition 0
type: 32 lba: 2103296 oem: 'BSD  4.4' volume: ' BOOT_0     '
rsc 32 fat-sectors 1008 c-count 129024 c-size 1
root dir cluster 2 sectors 0 entries 0
FAT32 clusters 129024
Trying partition: 0
GPT e60773e0a240de478c1d95d7d0aa35a3 000000001 003a3dfff num-partitions 128 entry-size 128
GPT partition: 0 b921b045-1df0-41c3-af44-4c6f280d3fae 000001800..0002017ff
GPT partition: 1 ebd0a0a2-b9e5-4433-87c0-68b6b72699c7 000201800..0002217ff
Matched GUID bootable-part-idx 0 want partition 0
type: 32 lba: 2103296 oem: 'BSD  4.4' volume: ' BOOT_0     '
rsc 32 Read start4cd.elf bytes   805756 hnd 0x6802
Read fixup4cd.dat bytes     3173 hnd 0xc4d8
0x00d03140 0x00000000 0x00001fff
MEM GPU: 76 ARM: 948 TOTAL: 1024
```

**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW
CM4008032

* Which OS and version (`cat /etc/rpi-issue`)?
n/a - system doesn't boot

* Which firmware version (`vcgencmd version`)?
Firmware files and kernel from tag 1.20230405

* Which kernel version (`uname -a`)?
6.1.21-v8+ (although this doesn't appear to be being reached)

N.B. Successful boot output:

```
RPi: BOOTLOADER release VERSION:8ba17717 DATE: 2023/01/11 TIME: 17:40:52
BOOTMODE: 0x06 partition 63 build-ts BUILD_TIMESTAMPInitialising SDRAM 'Micron' 32Gb x2 total-size: 64 Gbit 3200
DDR 3200 1 0 64 152
Initialising SDRAM 'Micron' 32Gb x2 total-size: 64 Gbit 3200
DDR 3200 1 0 64 152
EMMC
SD retry 1 oc 0
SD HOST: 200000000 CTL0: 0x00800f04 BUS: 25000000 Hz actual: 25000000 HZ div: 8 (4) status: 0x1fff0000 delay: 4
SD HOST: 200000000 CTL0: 0x00800f04 BUS: 50000000 Hz actual: 50000000 HZ div: 4 (2) status: 0x1fff0000 delay: 2
MBR: 0x00000001,    2047 type:-1df0-41c3-af44-4c6f280d3fae 000001800..0002017ff
GPT partition: 1 ebd0a0a2-b9e5-4433-87c0-68b6b72699c7 000201800..0002217ff
M0 b921b045-1df0-41c3-af44-4c6f280d3fae 000001800..0002017ff
GPT partition: 1 ebd0a0a2-b9e5-4433-87c0-68b6b72699c7 000201800..0002217ff
Matched GUID bootable-part-idx 0 want partition 0
type: 32 lba: 2103296 oem: 'BSD  4.4' volume: ' BOOT_0     '
rsc 32 fat-sectors 1008 c-count 129024 c-size 1
root dir cluster 2 sectors 0 entries 0
FAT32 clusters 129024
Read config.txt bytes     5149 hnd 0x23
Firmware: 82f3750a65fadae9a38077e3c2e217ad158c8d54 Mar 17 2023 10:50:39
Starting start4.elf @ 0xfec00200 partition 0
+

MESS:00:00:03.191148:0: arasan: arasan_emmc_open
MESS:00:00:03.192808:0: arasan: arasan_emmc_set_clock C0: 0x00800000 C1: 0x000e0047 emmc: 200000000 actual: 390625 div: 0x00000100 target: 400000 min: 400000 max: 400000 delay: 5
MESS:00:00:03.313035:0: arasan: arasan_emmc_set_clock C0: 0x00800000 C1: 0x000e0047 emmc: 200000000 actual: 390625 div: 0x00000100 target: 400000 min: 400000 max: 400000 delay: 5
MESS:00:00:03.325906:0: arasan: arasan_emmc_set_clock C0: 0x00800f00 C1: 0x000e0047 emmc: 200000000 actual: 390625 div: 0x00000100 target: 400000 min: 390000 max: 400000 delay: 5
MESS:00:00:03.497112:0: arasan: arasan_emmc_set_clock C0: 0x00800f02 C1: 0x000e0407 emmc: 200000000 actual: 25000000 div: 0x00000004 target: 25000000 min: 0 max: 25000000 delay: 1
MESS:00:00:03.513452:0: brfs: File read: /mfs/sd/config.txt
MESS:00:00:03.518271:0: brfs: File read: 5149 bytes
MESS:00:00:03.521428:0: brfs: File read: /mfs/sd/overclock.txt
MESS:00:00:03.526783:0: brfs: File read: 2208 bytes
MESS:00:00:03.531756:0: brfs: File read: /mfs/sd/legacy.txt
MESS:00:00:03.537468:0: brfs: File read: 3902 bytes
MESS:00:00:03.561538:0: HDMI1:EDID error reading EDID block 0 attempt 0
MESS:00:00:03.566042:0: HDMI1:EDID giving up on reading EDID block 0
MESS:00:00:03.572745:0: brfs: File read: /mfs/sd/config.txt
ined:00:00:03.578770:0: brfs: File read: 5149 bytes
MESS:00:00:04.106701:0: gpioman: gpioman_get_pin_num: pin LEDS_PWR_OK not defined
MESS:00:00:04.112343:0: *** Restart logging
MESS:00:00:04.114983:0: brfs: File read: 3902 bytes
MESS:00:00:04.119884:0: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_gp on reading EDID block 0
MESS:00:00:04.149040:0: hdmi: HDMI1:EDID error reading EDID block 0 attempt 0
MESS:00:00:04.154069:0: hdmi: HDMI1:EDID giving up on reading EDID block 0
MESS:00:00:04.159667:0: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
MESS:00:00:04.168431:0: HDMI0: hdmi_pixel_encoding: 300000000
MESS:00:00:04.173899:0: HDMI1: hdmi_pixel_encoding: 300000000
MEMESS:00:00:04.334779:0: brfs: File read: /mfs/sd/overlays/vc4-kms-v3d-pi4.dtbo
MESS:00:00:04.399992:0: Loaded overlay 'vc4-kms-v3d'
MESS:00:00:04.564841:0: brfs: File read: /mfs/sd/overlays/disable-bt.dtbo
MESS:00:00:04.583523:0: Loaded overlay 'disable-bt'
MESS:00:00:04.586925:0: brfs: File read: 2126 bytes
MESS:00:00:04.591669:0: brfs: File read: /mfs/sd/overclock.txt
MESS:00:00:04.596148:0: brfs: File read: 2208 bytes
MESS:00:00:04.601724:0: brfs: File read: /mfs/sd/legacy.txt
MESS:00:00:04.657251:0: brfs: File read: 3902 bytes
MESS:00:00:04.659535:0: brfs: File read: /mfs/sd/cmdline.txt
MESS:00:00:04.664452:0: Read command line from file 'cmdline.txt':
MESS:00:00:04.670302:0: 'console=serial0,115200 kgdboc=ttyAMA0,115200 root=PARTUUID=e9a81d93-fc67-4c5e-b555-d696357afa46 rootfstype=ext4 fsck.repair=yes rootwait cgroup_enable=memory cgroup_memory=1 zswap.enabled=1 zswap.compressor=lz4 zswap.max_pool_p
MESS:00:00:04.791745:0: brfs: File read: 256 bytes
MESS:00:00:07.393865:0: Kernel relocated to 0x200000
MESS:00:00:07.395721:0: Device tree loaded to 0x2eff2a00 (size 0xd5d3)
MEfffffff]
```

**Comment by pelwell** [comment]
No, I'm wrong. `start_x` and `start_debug` are things, `start_cd` isn't.

The differences in your bootloader log are strange - are both boots the same in all other respects?

**Comment by srcshelton** [comment]
> No, I'm wrong. `start_x` and `start_debug` are things, `start_cd` isn't.
> 
> The differences in your bootloader log are strange - are both boots the same in all other respects?

I've recently been through the documentation with a fine toothed comb - I did notice that this option seemed to be absent (which also made me wonder whether the cutdown firmware is legacy/unsupported at this point?)

In terms of the (slightly) different messages logged during boot - yes, the only difference is that one was captured after doing `shutdown -h now` from a previous session, whilst the other is following a cold boot.

**Comment by timg236** [comment]
gpu_mem=16 is the only way to boot start_cd.elf

**Comment by srcshelton** [comment]
Okay, can confirm that with `gpu_mem=16` I get:

```
Read config.txt bytes     5292 hnd 0x38
Read start4cd.elf bytes   805756 hnd 0x6802
Read fixup4cd.dat bytes     3173 hnd 0xc4d8
```

(… which was previously hidden by the TP2 serial issues and #1810)

I'll make a PR against the documentation to note that that start_file & fixup_file can't be used with the `cd` firmware.

Is it documented anywhere exactly _which_ features the `cd` firmware lacks?

**Comment by timg236** [comment]
Sorry, no idea.

**Comment by popcornmix** [comment]
> Is it documented anywhere exactly which features the cd firmware lacks?

It's not documented, but basically cameras, codecs and (firmware side/deprecated) 3d.

And the initial simple framebuffer used at the start of kernel boot is limited to 16bpp 1080p
(but kms/X can replace that with a 32bpp 4K framebuffer later in boot).

**Comment by srcshelton** [comment]
Closing as documentation updates are now raised as PRs.

**Comment by arretxe** [comment]
Just wanted to mention that in my CM4, even if I set gpu_mem=16 if fixup4.dat and start4.elf are not present it fails to boot (I thought it used the cd variants so it would not need the main ones).

I also tried plenty of combinations, like:

-  removing gpu_mem=16 but specifying start_file=start4cd.elf fixup_file=fixup4cd.dat FAIL
- keeping gpu_mem=16 but specifying start_file=start4cd.elf fixup_file=fixup4cd.dat FAIL
- keeping gpu_mem=16, removing start_file4cd.elf and fixup4cd.elf FAIL
- keeping gpu_mem=16, rename start4cd.elf and fixup4cd.dat to fixup4.dat and start4.elf FAIL
- keeping gpu_mem=16, rename start4cd.elf and fixup4cd.dat to fixup4.dat and start4.elf while keeping a copy of start4cd.elf and fixup4cd.dat SUCCESS

This took a while to discover, as I was compiling my buildroot with 
#BR2_PACKAGE_RPI_FIRMWARE_VARIANT_PI4 is not set
BR2_PACKAGE_RPI_FIRMWARE_VARIANT_PI4_CD=y
This generates only the cd variants, not the main ones, so I need to manuallly copy them.

Would appreciate if someone with deeper knowledge could confirm if this makes sense.
I thought maybe some earlier boot phase loooks for the non cd variants first, although apparently for that purpose the cd variants seem to work too if renamed.
