### ISSUE TITLE
RPi 4 firmware HDMI mode timings for groups 1 and 2

### ISSUE THREAD

**Issue by bit-bash** [raspberrypi/firmware#1814]
Just a quick question.

In config.txt for hdmi_group=1 and hdmi_group=2, I can set hdmi_mode=_nn_ to setup specific HDMI timings.

Is there some place I could find the specific hdmi_timings values for each mode in both groups?
Is this something that might be easy to extract from a firmware file myself?
I'm assuming there's some kind of lookup table in source code, but I guess the firmware source code is not open-source.

Thanks,
Doug.

**Comment by bit-bash** [comment]
Well I did a bit of digging and I found the CEA and DMT timings in start4.elf.
I wrote a tiny python script to decode the data into "hdmi_timings=" lines.
It mostly makes sense, but each timing entry in the structure has a leading 4-byte sequence, like 0x0FAB29CC. Just curious what this sequence is used for?

I've attached my results, if anyone else is interested.

[hdmitimings.txt](https://github.com/raspberrypi/firmware/files/11667771/hdmitimings.txt)

**Comment by bit-bash** [comment]
> This may be of use. https://www.raspberrypi.com/documentation/computers/config_txt.html#hdmi_mode

Thanks for the link, but I am quite familiar with that page - I use it as a baseline reference.
The CEA/DMT tables on that page don't show the specific timings for parameters such as H/V porches, sync widths and polarities, pixel clock, etc.

**Comment by 6by9** [comment]
CEA timings are all from CEA-861 - https://archive.org/details/CEA-861-D/page/n35/mode/2up
DMT timings are from VESA DMT - https://glenwing.github.io/docs/VESA-DMT-1.12.pdf

The same set of modes are defined in the kernel
CEA - https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/drm_edid.c#L733
DMT - https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/drm_edid.c#L239

As quoted in https://github.com/raspberrypi/linux/issues/4331#issuecomment-866750440, the table in the firmware is of the form
```
//   name         CEA code  Width  Hsync polarity     HFP  HSW  HBP  Height  Vsync polarity    VFP  VSW  VBP   Sync Offset  Pix rep Frame rate Interlaced?        Pixel clk freq (Hz) Aspect ratio
   { "1080i60",     {  5,  1920, HDMI_POSITIVE_SYNC,   88,  44, 148, 1080,  HDMI_POSITIVE_SYNC,  2,  5,  16,    0, 1100,       0,       60,    HDMI_INTERLACED   ,  74250000},        HDMI_ASPECT_16_9},
   { "1080p60",     { 16,  1920, HDMI_POSITIVE_SYNC,   88,  44, 148, 1080,  HDMI_POSITIVE_SYNC,  4,  5,  36,    0,    0,       0,       60,    HDMI_NONINTERLACED, 148500000},        HDMI_ASPECT_16_9},
```
The number you're seeing is most likely the pointer to the string const for the name.
I remember a copy of that full table being posted on gist.github.com or similar, but I can't find it at present.

**Comment by bit-bash** [comment]
Thanks - that's LOADS of good reference material!
