### ISSUE TITLE
Unstable bootcode/start.elf microSD access on Raspberry pi 3b+

### ISSUE THREAD

**Issue by pedro-javierf** [raspberrypi/firmware#1816]
**Describe the bug**
The latest bootloaders are having issues accessing the micro SD card consistently during boot time.

**To reproduce**
Raspberry Pi 3 b+ 
Tried two different microSD cards:
* Sandisk EDGE 16Gb (micro SDHC I1 A1 class 10) (official microSD bought w/ the raspberry)
* Generic 16Gb card (micro SDHC I1 class 10)
* Latest bootcode.bin from https://github.com/raspberrypi/firmware/raw/master/boot/bootcode.bin (modified with UART_BOOT=1 to see traces)
* Latest fixup.dat
* Latest start.elf
* config.txt with the following options:
  * enable_uart=1
  * core_freq=250
  * dtoverlay=pi3-disable-bt
  * uart_2ndstage=1
  * arm_64bit=1 

**Expected behaviour**
The device should consistently boot up to the point of starting the kernel8.img (Linux) on the microSD card.

**Actual behaviour**
A plethora of different traces are seen across boots. **UART is always available,** which must mean that the GPU first stage bootloader is able to access the microSD card and start the UART_BOOT=1 modified bootcode.bin.

Then, the following scenarios have been observed on UART:
* `No SD card detected, Try USB` (How's this possible?? clearly the microSD is accessible, since I'm seeing UART traces)
* `Found SD card, config.txt = 0, start.elf = 0, recovery.elf = 0, timeout = 0` (now it progresses further but still fails to access sd reliably, tries to do USB boot anyways)
* `Found SD card, config.txt = 1, start.elf = 1, recovery.elf = 0, timeout = 0` but then the device hangs on: `Read start.elf bytes 3746856'
Read fixup.dat bytes`
* `Found SD card, config.txt = 1, start.elf = 1, recovery.elf = 0, timeout = 0` but then it never manages to boot the kernel8 image, although it attempts to ("Loading kernel8.img at 0x80000) and so on.

I have tried formatting both microSDs in FAT32 repeatedly (with the SD foundation's official tool "SD card formatter", with Windows, and with MacOS). Formatting the card usually changes the odds of what of the scenarios is seen, but it appears to be very random.

Installing a mainstream OS (raspbian, etc) by flashing an .iso into the device (which installs all the needed partition) seems to work just fine and the OS always boots.

Scenario A:
<img width="868" alt="image" src="https://github.com/raspberrypi/firmware/assets/12979814/f46e0cf0-16a5-4766-be12-151298bf3f6b">

Scenario B:
<img width="1274" alt="image" src="https://github.com/raspberrypi/firmware/assets/12979814/1ae6b6c1-223f-4eeb-a74f-ff27b44a2d54">

Scenario C: (kernel8.img not a Linux kernel this time btw)
`Raspberry Pi Bootcode
Read File: config.txt, 211
Read File: start.elf, 2977280 (bytes)
Read File: fixup.dat, 7266 (bytes)
MESS:00:00:00.947622:0: brfs: File read: /mfs/sd/config.txt
MESS:00:00:00.951795:0: brfs: File read: 211 bytes
MESS:00:00:00.988122:0: HDMI0:EDID error reading EDID block 0 attempt 0
MESS:00:00:00.994289:0: HDMI0:EDID error reading EDID block 0 attempt 1
MESS:00:00:01.000626:0: HDMI0:EDID error reading EDID block 0 attempt 2
MESS:00:00:01.006962:0: HDMI0:EDID error reading EDID block 0 attempt 3
MESS:00:00:01.013299:0: HDMI0:EDID error reading EDID block 0 attempt 4
MESS:00:00:01.019636:0: HDMI0:EDID error reading EDID block 0 attempt 5
MESS:00:00:01.025973:0: HDMI0:EDID error reading EDID block 0 attempt 6
MESS:00:00:01.032310:0: HDMI0:EDID error reading EDID block 0 attempt 7
MESS:00:00:01.038646:0: HDMI0:EDID error reading EDID block 0 attempt 8
MESS:00:00:01.044983:0: HDMI0:EDID error reading EDID block 0 attempt 9
MESS:00:00:01.051078:0: HDMI0:EDID giving up on reading EDID block 0
MESS:00:00:01.057059:0: brfs: File read: /mfs/sd/config.txt
MESS:00:00:01.285320:0: gpioman: gpioman_get_pin_num: pin DISPLAY_DSI_PORT not defined
MESS:00:00:01.293697:0: *** Restart logging
MESS:00:00:01.296183:0: brfs: File read: 211 bytes
MESS:00:00:01.301093:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 0
MESS:00:00:01.308800:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 1
MESS:00:00:01.315658:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 2
MESS:00:00:01.322516:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 3
MESS:00:00:01.329373:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 4
MESS:00:00:01.336231:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 5
MESS:00:00:01.343089:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 6
MESS:00:00:01.349946:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 7
MESS:00:00:01.356804:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 8
MESS:00:00:01.363662:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 9
MESS:00:00:01.370276:0: hdmi: HDMI0:EDID giving up on reading EDID block 0
MESS:00:00:01.376180:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 0
MESS:00:00:01.383974:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 1
MESS:00:00:01.390831:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 2
MESS:00:00:01.397690:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 3
MESS:00:00:01.404547:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 4
MESS:00:00:01.411405:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 5
MESS:00:00:01.418261:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 6
MESS:00:00:01.425120:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 7
MESS:00:00:01.431978:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 8
MESS:00:00:01.438834:0: hdmi: HDMI0:EDID error reading EDID block 0 attempt 9
MESS:00:00:01.445450:0: hdmi: HDMI0:EDID giving up on reading EDID block 0
MESS:00:00:01.451065:0: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
MESS:00:00:01.459810:0: HDMI0: hdmi_pixel_encoding: 162000000
MESS:00:00:01.465534:0: vec: vec_middleware_power_on: vec_base: 0x7e806000 rev-id 0x00002708 @ vec: 0x7e806100 @ 0x00000420 enc: 0x7e806060 @ 0
MESS:00:00:01.482295:0: kernel=
MESS:00:00:01.488874:0: dtb_file 'bcm2710-rpi-3-b-plus.dtb'
MESS:00:00:01.492832:0: dtb_file 'bcm2710-rpi-3-b.dtb'
MESS:00:00:01.497689:0: dtb_file 'bcm2837-rpi-3-b-plus.dtb'
MESS:00:00:01.502981:0: Failed to load Device Tree file '?'
MESS:00:00:01.508278:0: Failed to open command line file 'cmdline.txt'
MESS:00:00:01.547578:0: brfs: File read: /mfs/sd/kernel8.img
MESS:00:00:01.551543:0: Loaded 'kernel8.img' to 0x80000 size 0x82024
MESS:00:00:01.557697:0: gpioman: gpioman_get_pin_num: pin EMMC_ENABLE not defined
MESS:00:00:01.567190:0: uart: Set PL011 baud rate to 103448.300000 Hz
MESS:00:00:01.573482:0: uart: Baud rate change done...
MESS:00:00:01.576912:0: uart: Baud rate`

**Additional context**
These microSD cards work perfectly with mainstream distributions. Could the power supply or the speed grade of the microSD cards have something to do? Am I using incorrect bootloaders? Thanks.

I can't find detailed information about the boot process **for each Raspberry Pi board revision**, so I don't know if I'm missing any piece to make the pi 3b+ boot appropriately.

**Comment by pelwell** [comment]
Have you considered using the `stable` firmware branch, which is used in the Debian package and image releases,  instead, i.e.: https://github.com/raspberrypi/firmware/raw/stable/boot/bootcode.bin ?

**Comment by pedro-javierf** [comment]
Hadn't even realised there was a stable branch since it's not mentioned anywhere. I'll give it a try

**Comment by pedro-javierf** [comment]
I have been able to reliably get to a `Loaded 'kernel8.img' to 0x80000 size 0x80064` with both the latest bootcode.bin (and also the stable bootcode.bin) by stripping the config.txt to just this:

```
enable_uart=1
#core_freq=250
#dtparam=audio=on_
#dtoverlay=pi3-disable-bt

# make start.elf print debug over the serial port
uart_2ndstage=1

# Let's boot the AArch64 kernel
arm_64bit=1
```

This got me thinking, could it be that the commented lines (e.g.: the dtoverlay) were making the bootcode.bin or the start.elf crash? **I don't have those overlays in the microSD**. Not sure if the `dtparam` and `core_freq` could have also had any effect. I wasn't expecting the different bootloaders to be so brittle to crash because of a missing file.

Now I'm just stuck at:

```
MESS:00:00:01.455269:0: HDMI0: hdmi_pixel_encoding: 162000000
MESS:00:00:01.460982:0: vec: vec_middleware_power_on: vec_base: 0x7e806000 rev-id 0x00002708 @ vec: 0x7e806100 @ 0x00000420 enc: 0x7e806060 @ 0x00000220 cgmsae: 0x7e806050
MESS:00:00:01.477756:0: kernel=
MESS:00:00:01.484401:0: dtb_file 'bcm2710-rpi-3-b-plus.dtb'
MESS:00:00:01.488429:0: dtb_file 'bcm2710-rpi-3-b.dtb'
MESS:00:00:01.493287:0: dtb_file 'bcm2837-rpi-3-b-plus.dtb'
MESS:00:00:01.498579:0: Failed to load Device Tree file '?'
MESS:00:00:01.503874:0: Failed to open command line file 'cmdline.txt'
MESS:00:00:01.543080:0: brfs: File read: /mfs/sd/kernel8.img
MESS:00:00:01.547046:0: Loaded 'kernel8.img' to 0x80000 size 0x80064
MESS:00:00:01.553199:0: gpioman: gpioman_get_pin_num: pin EMMC_ENABLE not defined
MESS:00:00:01.562684:0: uart: Set PL011 baud rate to 103448.300000 Hz
MESS:00:00:01.568976:0: uart: Baud rate change done...
MESS:00:00:01.572406:0: uart: Baud rate
```

So I probably have a broken baremetal Kernel, but I'll see what else I can find

**Comment by pedro-javierf** [comment]
I couldn't manage to make it fail again with just those options mentioned above, so it must have been all the comments that I stripped from the original config.txt that I got from the docs (which contains a lot of commented options) and maybe I changed something else in there. However, doing this I found why I might have been seeing those errors before when playing with the config.txt, and I've opened issue #1817
