### ISSUE TITLE
Deinterlacing MJPEG images just yields solid green picture

### ISSUE THREAD

**Issue by tp-m** [raspberrypi/firmware#182]
Easiest way to reproduce this is with omxplayer. I hope this is an acceptable test case:

<pre>
wget http://gh1.dark-stone.com/kholi/P1020080.MOV
omxplayer P1020080.MOV
omxplayer -d P1020080.MOV
</pre>

Video codec omx-mjpeg width 1280 height 720 profile -99 fps 30.000000

I realise these images here are not in fact interlaced, but surely it should work in any case?

**Comment by Ruffio** [comment]
@tp-m Is this still an issue?

**Comment by tp-m** [comment]
Sorry, missed the earlier comment. Will re-check.

**Comment by tp-m** [comment]
Seems to work fine now, at least an rpi2 (didn't test old rpi).
