### ISSUE TITLE
Modules missing from 6.1.52

### ISSUE THREAD

**Issue by whitslack** [raspberrypi/firmware#1824]
**Describe the bug**
The compiled kernel modules are missing from the 6.1.52 commit tree.

**To reproduce**
Clone this repo at 4cf57645af88e394e282d5cb95b4accecf653bc6.

**Expected behaviour**
There should be a `modules` directory like there was in the parent commit (80b2a85dee8f93cfa5ca4a9e3d9bcc8f3468ea18).

**Actual behaviour**
There is no `modules` directory.

**Comment by pelwell** [comment]
That is strange, because they are in the equivalent commit in the rpi-firmware repo: https://github.com/raspberrypi/rpi-firmware/commit/1714dfc184d0e4e87838a2141cf77cb7ef86d301.

**Comment by popcornmix** [comment]
My fault - I've just pushed a fix.
