### ISSUE TITLE
dpkg: unrecoverable fatal error

### ISSUE THREAD

**Issue by yi-yunseok** [raspberrypi/firmware#1832]
**Describe the bug**

When I use apt commands, terminal shows dkpg unrecoverable fatal error.

**To reproduce**

`sudo apt command (install, remove, purge, full-upgrade, others)`

**Expected behaviour**

APT commands should work properly.

**Actual behaviour**

`dpkg: unrecoverable fatal error, aborting:
 files list file for package 'liblinear4:arm64' is missing final newline
E: Sub-process /usr/bin/dpkg returned an error code (2)
`

**System**

* Raspberry Pi 4B
* 005a8c73b05a2cab394073150208bf4f069e861a
* 3094eda5aadf2c719edd2c68d1900884abc3dbca
* 6.1.57-v8+ #1688 SMP PREEMPT Thu Oct 12 15:14:26 BST 2023 aarch64 GNU/Linux

**Comment by popcornmix** [comment]
This isn't the right place for this (this is for reporting bugs in the start.elf firmware).

My first guess would be a corrupt sdcard.
I think asking this question in the [forum](https://forums.raspberrypi.com/) would be more appropriate.
