### ISSUE TITLE
Eclipse ThreadX is now open source - can GPU firmware source code be released as well?

### ISSUE THREAD

**Issue by xnox** [raspberrypi/firmware#1847]
Some sources online claim that GPU firmware is based on proprietary ThreadX which has now been opensourced. 

https://techcommunity.microsoft.com/t5/internet-of-things-blog/microsoft-contributes-azure-rtos-to-open-source/ba-p/3986318

Does that help with being able to release Raspberry Pi GPU firmware as open source as well?

**Comment by pelwell** [comment]
No.
