### ISSUE TITLE
Modules missing from 6.1.73

### ISSUE THREAD

**Issue by whitslack** [raspberrypi/firmware#1860]
It has happened again. ☹️

**Describe the bug**
The compiled kernel modules are missing from the 6.1.73 commit tree.

**To reproduce**
Clone this repo at 6e80cfaf803aa58efc9baf0031f4e64a69fe0ae8.

**Expected behaviour**
There should be a `modules` directory like there was in the parent commit (0968de28716a9b1f106b8492646d0ed0a2800152).

**Actual behaviour**
There is no `modules` directory.

**Comment by popcornmix** [comment]
My mistake. Can you try now?

**Comment by whitslack** [comment]
Looks good now. Thanks.
