### ISSUE TITLE
Fast boot RPI4

### ISSUE THREAD

**Issue by thefrankk** [raspberrypi/firmware#1866]
Is there any way to speed up the bootloader? I have 6s from power up to the rainbow screen and i need to speed up, I need to run a simple QT app and i need to fast boot as fast as possible.  I think is to much time having 6-7s from power up to the kernel initalization.

Thank you.

**Comment by pelwell** [comment]
You are far from the first person to ask that question. Unfortunately for you, initialising the DRAM controller accounts for most of this time, and that can't be skipped. FYI it has taken quite a bit of effort to get this delay as low as it is.

**Comment by thefrankk** [comment]
I know, I'm just want to make sure that I did all the research and there is no solution for this. 
It's kinda crazy that a rpi3 can boot on 2 sec but in rpi4 took a lot of time more.
Can you help me by recommend another board to get a 5-7s complete boot time? I'm watching the rockpro64 but I'm not sure.
Thank you.

**Comment by timg236** [comment]
Pi5 ?

**Comment by timg236** [comment]
Closing this because it’s not actually a bug report and the forums are the place for discussions
