### ISSUE TITLE
In reference to "Pi4 reboot not reliable, hangs forever while rebooting.",

### ISSUE THREAD

**Issue by epigramx** [raspberrypi/firmware#1867]
In reference to #1559, someone locked the issue and didn't tell us where the kernel bug reports exactly are linked and handled, so can someone inform us of that progress?

**Comment by pelwell** [comment]
The link is in #1559 - https://github.com/raspberrypi/linux/issues/5503.

**Comment by epigramx** [comment]
OK thanks, though it was unclear, because the only way it's grepped in there is an automatic reference and not a body of a comment towards the end.
