### ISSUE TITLE
bcm2712-rpi-5-b.dtb missing from firmware

### ISSUE THREAD

**Issue by nullr0ute** [raspberrypi/firmware#1870]
As of commit a43df3a002 the bcm2712-rpi-5-b.dtb disappeared from the firmware. The commit shows a number of details around kernel driver fixes but no mention of the removal of the RPi5 dtb so I'm unsure if it's intentional. The previous commit bumping to the 6.6 kernel contained it.

**Comment by popcornmix** [comment]
Ah my mistake. Added now.

**Comment by nullr0ute** [comment]
LGTM! Thanks

**Comment by Dent2024** [comment]
Hi, the bcm2712-rpi-5-b.dtb is still missing in the actual ZIP. Thanks a lot.
