### ISSUE TITLE
RPi3b+ GPU ROM issue, which makes ANY OS in Extended partition unbootable

### ISSUE THREAD

**Issue by mrdc** [raspberrypi/firmware#1887]
**Describe the bug**
Setting Extended partition type on microSD to `0xf` (W95 Extended) instead of `0x05` makes ANY OS in the Extended partition unbootable. RPi makes no output during this issue (screen, UART).

**To reproduce**
1. Make partition table according to this example:
```
Partition layout 
Device			Size	Id	Type:
/dev/mmcblk0p1          11.8G       b       W95 FAT32 (PINN/NOOBS RECOVERY partition)
/dev/mmcblk0p2          57.6.8G     f       W95 Ext'd
/dev/mmcblk0p5          32M         83      Linux (NOOBS SETTINGS partition)
/dev/mmcblk0p6          66M         b       W95 FAT32 (Raspbian Full boot partition)
/dev/mmcblk0p7          20.1G       83      Linux (Raspbian Full root partition)
/dev/mmcblk0p8          512M        6       W95 FAT16
/dev/mmcblk0p9          4.1G        83      Linux
/dev/mmcblk0p10         66M         b       W95 FAT32
/dev/mmcblk0p11         10.8G       83      Linux
```
2. Install NOOBS/PINN
3. Try to boot ANY OS: 
```
/dev/mmcblk0p7
/dev/mmcblk0p9
/dev/mmcblk0p11
```
Full research is here:
https://forums.raspberrypi.com/viewtopic.php?t=368723

**Expected behaviour**
OSes should boot.

**Actual behaviour**
OSes don't boot.

**System**
RPi3B+
* Which OS and version (`cat /etc/rpi-issue`)?*
```
 Raspberry Pi reference 2019-04-08
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, e910bf55ac92e27c6e                                                                                                          77043e8995bcb5e0a2d742, stage5
```
* Which firmware version (`vcgencmd version`)?
```
May  9 2023 12:17:54
Copyright (c) 2012 Broadcom
version 30aa0d70ab280427ba04ebc718c81d4350b9d394 (clean) (release) (start)
```
* Which kernel version (`uname -a`)?
`Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux`

**Comment by timg236** [comment]
That’s a known limitation. No plans to change this

**Comment by timg236** [comment]
I don’t think so but it could be. IIRC 0x0c is used in most of our image tools
