### ISSUE TITLE
Raspberry Pi 5 not booting at all

### ISSUE THREAD

**Issue by ilieciprian18** [raspberrypi/firmware#1891]
**Is this the right place for my bug report?**
This repository contains the GPU firmware used on the Raspberry Pi. This software is the closed source part of the Raspberry Pi system, it includes booting (including network booting and USB booting), low-level power and clock control, FKMS and legacy HDMI control (not full KMS that is in the linux kernel), hardware legacy codecs (MPEG2, H264 and VC1), encode hardware including the ISP (image sensor pipeline) and camera control, audio output (analogue and HDMI audio).

If you believe that the issue you are seeing is within this area, this is the right place. If not, we have other repositories for the linux kernel at [github.com/raspberrypi/linux](https://github.com/raspberrypi/linux) and Raspberry Pi userland applications at [github.com/raspberrypi/userland](https://github.com/raspberrypi/userland). If you have problems with the Raspbian distribution packages, report them in the [github.com/RPi-Distro/repo](https://github.com/RPi-Distro/repo). If you simply have a question, then [the Raspberry Pi forums](https://www.raspberrypi.org/forums) are the best place to ask it.

**Describe the bug**
Add a clear and concise description of what you think the bug is.
Raspberry Pi 5 refuses to boot with or without SD card, led light is constantly red, USB power is good with official adapter, 2 SD cards that are new were used both with latest version of Raspbian and factory settings Bootloader for RPi 5. Before the upgrade, the Pi was booting, but I had a preloaded version of Raspbian, and it would display only information, and the fact that the OS is not compatible with RPi 5. After loading the latest version of Raspbian, for RPi 5, it would not boot at all. The bootloader factory reset does not work either.

**To reproduce**
List the steps required to reproduce the issue.
Have a new RPi 5. It boots old Raspbian, made probably for RPi 4. After loading the latest version for RPi 5, it does not boot at all, with or without SD card.

**Expected behaviour**
Add a clear and concise description of what you expected to happen.
Raspberry Pi 5 should boot the latest version of Raspbian, or at least without SD card.

**Actual behaviour**
Add a clear and concise description of what actually happened.
RPi 5 does not boot at all. Red light is constantly on no matter how many presses or long presses of the PWR button.

**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:
could not run raspinfo as RPi does not boot.

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW -  Raspberry Pi 5 4GB RAM
* Which OS and version (`cat /etc/rpi-issue`)? - Raspberry Pi OS 64 bit, 15 March 2023 Release
* Which firmware version (`vcgencmd version`)?
* Which kernel version (`uname -a`)?

**Logs**
If applicable, add the relevant output from `dmesg` or similar.

**Additional context**
Add any other relevant context for the problem.

**Comment by timg236** [comment]
It sounds like an issue without your particular board. The best place to get help for this is the Troubleshooting forum unless you think it's a specific software issue in the firm and have logs

https://forums.raspberrypi.com/viewforum.php?f=28&sid=ed4b57a41fcf0916035e45cb0ea78516

Closing the issue but please comment if you have something to indicate that it's a software rather than a hardware issue
