### ISSUE TITLE
MAC_ADDRESS_OTP behavior

### ISSUE THREAD

**Issue by AKnepnep** [raspberrypi/firmware#1899]
I am using a CM4 with EMMC memory.

I am trying to override the MAC address of the ETH0 interface on my Raspberry Pi using MAC_ADDRESS_OTP.

I wrote my MAC address to OTP rows 40 and 41.

Using sudo vcgencmd otp_dump gives:

`40:010203dd
41:eeff0000
`

When using

`MAC_ADDRESS_OTP=4,5`

This works fine, and I get assigned the address:

`EE:FF:00:00:01:02`

But when using 

**`MAC_ADDRESS_OTP=5,4`

I get a random MAC address that changes on every reboot.

The documentation seems to indicate that I should be able to set the MAC address in the order that I want, and 01:02:03:DD:EE:FF should be a valid MAC address.

https://www.raspberrypi.com/documentation/computers/raspberry-pi.html

> Any two customer rows may be selected and combined in either order.

Thanks

**Comment by timg236** [comment]
01:02:03:DD:EE:FF  is multi-cast mac-address which would not be valid in this context so Linux is correctly giving you a random address instead.
