### ISSUE TITLE
No zram module in branch next?

### ISSUE THREAD

**Issue by dagger907** [raspberrypi/firmware#190]
Hi! Can't find the zram module(zram.ko) in the "next" branch. 

Can you please compile that module as well?

Best regards

**Comment by popcornmix** [comment]
ZRAM is in current kernel:
```
$ zcat /proc/config.gz |grep ZRAM
CONFIG_ZRAM=m
CONFIG_ZRAM_LZ4_COMPRESS=y
# CONFIG_ZRAM_DEBUG is not set
```
