### ISSUE TITLE
XiaoRGEEK raspberry pi radar car 

### ISSUE THREAD

**Issue by Joseph13289** [raspberrypi/firmware#1910]
Hi 
I got a XiaoRGEEK Raspberry PI radar car which after I assembled it was working properly, but on the second day when I turned it on the mouse on the touch screen was frozen, so I tried to fix it by installing a new Raspbian (Raspberry PI OS 64-BIT, Bookworm). But now when I turn the Radar car on, the touch screen on the radar car just shows a blank white screen. Do you know how to help fix my problem?

**Comment by pelwell** [comment]
Realistically, there's nothing we will be able to do to help you - it's not our product, and we know nothing about it.

I suggest you contact XiaoRGEEK directly: https://www.xiaorgeek.net/pages/contact-us
