### ISSUE TITLE
vc_dispmanx_snapshot() images sometimes distorted in the y-axis

### ISSUE THREAD

**Issue by AndrewFromMelbourne** [raspberrypi/firmware#196]
When vc_dispmanx_resource_create(), vc_dispmanx_snapshot() and vc_dispmanx_resource_read_data() are used to take snapshots the y-axis is distorted, if you use the dimensions returned by vc_dispmanx_display_get_info(). This has been seen to occur when using either a PAL or NTSC analog display.

PAL vc_dispmanx_display_get_info() returns 720x576, rectangle of 720x594 gives an undistorted snapshot
NTSC vc_dispmanx_display_get_info() returns 720x480, rectangle of 720x509 gives an undistorted snapshot

There is more information about this issue on the Raspberry Pi forum - http://www.raspberrypi.org/phpBB3/viewtopic.php?f=67&t=48369

**Comment by AndrewFromMelbourne** [comment]
Hi, as there is a flurry of activity on the firmware issues I thought I would retry this. To be honest I thought that it didn't really bother anyone else, given the number of units that have been sold.

Although, I in think [this recent thread on the Raspberry Pi forums](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=113419), Joe Schmoe was seeing the issue.

I cannot reproduce the problem using the firmware from Jun 19 2015 22:46:43 (Hexxeh commit d3e6f4a27d87c5229ad6c74fa9022a9451046add). I am wondering if a recent change has solved this issue.Perhaps related to the changes that caused [this issue](https://github.com/raspberrypi/firmware/issues/438).

The interesting thing is that requested overscan settings are no longer honored. For example on my display.

config.txt
```
disable_overscan=0
overscan_top=252
overscan_bottom=252
overscan_left=600
overscan_right=600
```

tvservice -s
```
state 0x12001a [HDMI CEA (16) RGB lim 16:9], 1920x1080 @ 60.00Hz, progressive
```

fbset
```
mode "624x480"
    geometry 624 480 624 480 16
    timings 0 0 0 0 0 0 0
    rgba 5/11,6/5,5/0,0/16
endmode
```
624 + 600 + 600 = 1824 != 1920
480 + 252 + 252 = 984 != 1080

@popcornmix what do you think? I am happy to close this issue as I can no longer reproduce the issue. Is the overscan behaviour expected?

**Comment by popcornmix** [comment]
There is a default overscan of 48 on each side. You should either use ``disable_overscan=1`` to remove the default and you'll get the setting you expect, or your maths should have:
624 + 600 + 600 + 48 + 48 = 1920
480 + 252 + 252 + 48 + 48 = 1080

**Comment by AndrewFromMelbourne** [comment]
Thanks @popcornmix. Closing as I can no longer reproduce.

**Comment by popcornmix** [comment]
There was a fix for scaling with overscan here: https://github.com/raspberrypi/firmware/commit/c7ec740caa359634d197249297ea597067e70180 which I suspect was when this got resolved.
