### ISSUE TITLE
I2C problem - Raspberry Pi freeze after using I2C sensor

### ISSUE THREAD

**Issue by iz8mbw** [raspberrypi/firmware#210]
Hi.
starting from one of the latest Raspberry Pi firmware (after the rpi-update command), about from the end of August 2013, the Raspberry Pi will freeze after this command to specify an I2C chip: echo tmp275 0x48 > /sys/class/i2c-adapter/i2c-1/new_device
The only way to start the Raspberry Pi again is to unplug and then plug the power.

This problem happens also in others situations:

Case 1:
This is the state of my modules:

root@raspberrypi:~# lsmod
Module                  Size  Used by
tun                    14995  2
i2c_dev                 5594  0
w1_therm                2995  0
w1_gpio                 1633  0
wire                   24973  2 w1_gpio,w1_therm
cn                      4834  1 wire
snd_bcm2835            16432  1
snd_pcm                77728  1 snd_bcm2835
snd_page_alloc          5169  1 snd_pcm
snd_seq                53482  0
snd_seq_device          6462  1 snd_seq
snd_timer              20110  2 snd_pcm,snd_seq
snd                    58744  7 snd_bcm2835,snd_timer,snd_pcm,snd_seq,snd_seq_device
leds_gpio               2243  0
led_class               3570  1 leds_gpio
i2c_bcm2708             3947  0

If I execute "echo tmp275 0x48 > /sys/class/i2c-adapter/i2c-1/new_device" the Raspberry Pi instantly freeze.

Case 2:
I load the new compiled module "hwmon" (modprobe hwmon), no error, but after loading the new compiled module "lm75" (modprobe lm75) the Raspberry Pi will freeze.

In all cases, nothing is written to log files because the Raspberry Pi will freeze instantly.

I will try to see if errors will appear to the HDMI out, because nothing is written to log files (messages, kernel.log, etc...), and if yes I will attach.
I hope that this problem will be solved, now I cannot use more the Raspberry Pi I2C bus.

**Comment by iz8mbw** [comment]
This issue is solved, it can be closed.

**Comment by pelwell** [comment]
Closing - thanks.
