### ISSUE TITLE
RasPi stopped working, booting only with HDMI connected

### ISSUE THREAD

**Issue by ghost** [raspberrypi/firmware#211]
Hi all together,

I have a problem with my RasPi, Model B, Rev. 2. After a few weeks of normal behaviour it suddenly stopped working properly.
I was using it in headless mode, only powersupply and ethernet were connected, I controlled it via SSH. My image is Raspbian wheezy 2013-07-26 on a SanDisk Ultra SDHC 8GB class 10, which is reported to work without problems and has been working for the last weeks.
Now, when I plug in power, only the red PWR led is on while the green ACT led glows fainty. The system will not boot up.
When I connect my RasPi and my TV via HDMI it boots up normal.
I already changed the sdcard and power supply. Voltages between TP1 and TP2 are ok (5.25V when halted, 5.00V when booted up), also the polyfuse F3 shows no resistance.
After searching the net for suggestions, I did an update of the whole system via rpi-update and apt-get update & apt-get upgrade but nothing changed. Also adding the lines boot_delay=1 and force_hdmi_hotplug=1 to /boot/config.txt had no effect. Sometimes it boots up without HDMI connected, but mostly it doesn't.

I've made a video of this behaviour, you can watch it here: http://youtu.be/DihjbOyrTj4

If you have another suggestion, please let me know.

Thanks, regards ChemDroid

**Comment by pierremoreau** [comment]
I just experienced the same issue today as I upgraded my Pi and modified the default `cmdline.txt`. Adding back `rootwait` solved it.
NB: I had the issue on two different Pis, one of them was quite unused.

**Comment by BlitzKraft** [comment]
I have the exact same issue. I tried it with different USB cords and powersupplies, but it only boots if and only if the HDMI is connected. 

I am using Raspi 3, with a Sandisk 8 GB card, 2016-03-18 Jessie.

However [this forum post](https://www.raspberrypi.org/forums/viewtopic.php?t=45189&p=358109) points out that this issue is caused by a bad grounding on the power supply. But that solution didn't work for me. 

I tried a different power supply, and powering it through the USB port on my computer. In each case it booted only if the HDMI is connected.

**Comment by jnoxon** [comment]
Thanks BlitzKraft, this solved the same issue I was having with my Pi 3 running Ubuntu.

**Comment by pboos** [comment]
I am experiencing the same problem. hdmi_force_hotplug seems not to work either for me :(. Neither setting it to 0 nor 1 works. As well it seems that the red led is lighting up when botting without hdmi connected.

**Comment by bitkill** [comment]
Same problem here. latest fw using rpi-update.
System only boots connected to hdmi monitor.

hdmi_force_hotplug=0 in /boot/config.txt does not work

**Comment by ColinK-at-github** [comment]
As with the people above I also experienced this problem.  I have had this Raspberry Pi for a couple of years now but just hadn't gotten around to it until now.  I believe my pi is a model 2 but don't know for sure.  I installed the latest version of raspian-jessie (2017-01-11).

Someone asked whether just touching the cable to the HDMI port helped.  In my case it did not.  The HDMI port actually had to be connected to the TV in order for the pi to boot.  Once booted the HDMI cable could then be removed and everything would continue to work fine.

1.  Ran rpi-update  (went from 4.4.34 to 4.9.y)
     Power recycle
     No Go

2. Tried adding hdmi_force_hotplug=0 in /boot/config.txt
    Power recycle
    No Go

3. Looked at adding rootwait to /boot/cmdline.txt but noticed that there is a typo in the original file.  rootwait was specified as roouwait.  I changed roouwait to rootwait.
     Power recycle
     SUCCESS!!!!
     I tried three or four times and everytime it worked!!

Don't know if this will work for everyone but in my case correcting the typo was the key (or perhaps a combination of the above I suppose).

Hope this helps someone else too.

Cheers,
./Colin

**Comment by nplanel** [comment]
adding hdmi_force_hotplug=1 in /boot/config.txt will fix this issue on RPI 3B+

**Comment by Geertiebear** [comment]
@nplanel that fixed it for me, thank you very much!

**Comment by hbarnard** [comment]
Thanks for all the comments. I've had this on one particular Pi Zero W. I've got `rootwait `and `hdmi_force_hotplug=0` on the system. But what seemed to work was changing the power supply to a new white 'official' and making sure that the micro-USB for the power was firmly in the socket.

**Comment by mmahut** [comment]
Having the same issue, both ```rootwait``` nor ```hdmi_force_hotplug=0``` are fixing the issue.

**Comment by JamesH65** [comment]
Try hdmi_force_hotplug=1 ??

What device are you using?

**Comment by mmahut** [comment]
> Try hdmi_force_hotplug=1 ??

Tried it, but I have the same problem.

> What device are you using?

Raspberry Pi 3 Model B+

**Comment by JamesH65** [comment]
And which OS? Anything else unusual about your setup?

**Comment by paulbastian** [comment]
I can confirm the last post. Installing ArchLinux ARM intially works headless, after the first pacman update, it only boots with HDMI cable connected. `hdmi_force_hotplug=1` then fixes the problem

**Comment by popcornmix** [comment]
@paulbastian this should have been fixed with https://github.com/raspberrypi/linux/pull/4547 and be present in latest RPiOS updates.
ArchLinux isn't something we directly support, so I'll Ieave it to someone who knows to say whether this commit is present.
