### ISSUE TITLE
core_freq seems to affect I2C operation

### ISSUE THREAD

**Issue by fangfufu** [raspberrypi/firmware#212]
Hello, 
My I2C device gives strange readings when the core_freq in /boot/config.txt is set to 450. 
When core_freq=450:
```
fangfufu@snowden:~/Pi-Weather$ ./Pi-Sensors
Board Version: 1
Board Temperature: 35 C
Humidity: 27 %
Room Temperature: -3244.8 C
Outdoor Temperature: 28.3 C
Board Pressure: 3364.5
```

When core_freq is not set:
```
fangfufu@snowden:~/Pi-Weather$ ./Pi-Sensors
Board Version: 1
Board Temperature: 35 C
Humidity: 26 %
Room Temperature: 29.1 C
Outdoor Temperature: 28.2 C
Board Pressure: 100.4
```

I wonder if this is related to the SD card corruption when core_freq is overclocked. Is there a fix for this problem other than not overclocking? 

In case you wonder, my I2C device is one of those Web4Robot Weather Station Board (http://www.web4robot.com/PiWeather.html).

**Comment by Ruffio** [comment]
@popcornmix is this still an issue?

**Comment by Ruffio** [comment]
@fangfufu can this issue be closed?

**Comment by fangfufu** [comment]
I sold my original Raspberry Pi.  I left my weather station board in China. 

I don't have the means to test this problem, please close the issue.

**Comment by Ruffio** [comment]
@fangfufu you just press the 'Close' button to close this issue... Thanks.

**Comment by fangfufu** [comment]
Thanks, issue closed.
