### ISSUE TITLE
Atheros device freeze the system

### ISSUE THREAD

**Issue by winstonma** [raspberrypi/firmware#215]
Here is my hardware setup:
  1. Raspberry Pi Model B (With Raspbian image)
  2. USB Hub (Tried one NEC and one generic brand)
  3. TP-Link TL-WN722N WiFi dongle (Atheros AR9271)

When I pull the Wifi dongle the system freeze - it can't take user input from keyboard, no SSH shell. I upgraded firmware-atheros from Jessie (version 0.40) and it didn't help.

I have no clue on the root cause but I suspect it is kernel-related issue (maybe USB driver related) since the atheros driver isn't platform specific.

Thanks for the time investigating the root cause and thanks for the help.

**Comment by Ruffio** [comment]
@winstonma is this still an issue?

**Comment by Ruffio** [comment]
@popcornmix as there have been no response from @winstonma from the question regarding if the issue still is presence from 17 Jun 2015, this issue should be closed

**Comment by winstonma** [comment]
Sorry I didn't use R-Pi since then
