### ISSUE TITLE
Raspberry PI not working properly on gigabit switch

### ISSUE THREAD

**Issue by alchemyx** [raspberrypi/firmware#217]
Hello,

With latest firmware I have a strange issues when RPI is connected to gigabit switch. It reports via mii-tool that it has 1000 half duplex link and gives some packet loss. On switch I see that it is 100 full duplex.:

```
root@sonda00:~# mii-tool
eth0: negotiated 1000baseT-HD flow-control, link ok
```

```
GigabitEthernet0/8 is up, line protocol is up (connected)
  Hardware is Gigabit Ethernet, address is 0015.63dc.4208 (bia
0015.63dc.4208)
  Description: IPTV Sonda00
  MTU 1500 bytes, BW 100000 Kbit, DLY 100 usec,
     reliability 255/255, txload 1/255, rxload 0/255
  Encapsulation ARPA, loopback not set
  Keepalive set (10 sec)
  Full-duplex, 100Mb/s, media type is 10/100/1000BaseTX
```
If I force 100 full duplex on switch side, RPI starts to report properly 100 full duplex:

```
root@sonda00:~# mii-tool 
eth0: negotiated 100baseTx-FD, link ok
```

So for me it is a definitely a bug, because ethernet on RPI is 100 Mbps.

**Comment by Ruffio** [comment]
@alchemyx is this still an issue?

**Comment by alchemyx** [comment]
Sorry I don't have access to spare RPI anymore to check it. 

-- 
Michał Margula, alchemyx@uznam.net.pl, http://alchemyx.uznam.net.pl/
"W życiu piękne są tylko chwile" [Ryszard Riedel]

Dnia 17 cze 2015 o godz. 19:56 Rasmus Christiansen <notifications@github.com> napisał(a):

**Comment by Ruffio** [comment]
@cleverca22 do you still have an issue?

**Comment by Ruffio** [comment]
@popcornmix this issue seems to be stalled

**Comment by TheEggAka** [comment]
Hi, i want only ask, if is this issue have some solution, becouse i have still this issue. When i plug in to 1000gb ether, havnt link, only when i change operation speed-duplex to 100Full than have link and working without packet lost.
