### ISSUE TITLE
SPDIF IEC61937 encapsulated AAC(adts stream) through  D2VOX device(hw:1,0) using ALSA outputs noise data.

### ISSUE THREAD

**Issue by shamyavani** [raspberrypi/firmware#222]
D2VOX device is USB based device used as second card to play the output.

I have played wav file using below command through D2VOX device , 
aplay -D plughw:1,0 filename1.wav

similar way, i tried to play IEC61937 encapsulated adts(aac) stream named as IEC61937_data.aac in which the contents are as [ 72 f8 1f 4e 07 00 68 00 ff f8 50 40 01 a2 44 d5 8b 00 c8 00 07....  ] 
here :
72 f8 1f 4e 07 00 68 00 : are spdif header.
 ff f8 50 40 01 a2 44 d5 8b 00 c8 00 07... : ADTS stream 

1. aplay -f S16_LE -Dplughw:1,0 IEC61937_data.aac 
Playing raw data 'IEC61937_data.bin' : Signed 16 bit Little Endian, Rate 8000 Hz, Mono

It outputs only noise ( kkrrr sound ) and not the audio data.

If i use mplayer as below :: 
2. mplayer -ao alsa:device=hw=1,0 IEC61937_data.bin 

through D2VOX device, audio output works fine. Audi o data can be listened.

I want to know the difference of above 2 commands( 1 and 2 ) .
does IEC61937 encapsulated AAC data cant pass through ALSA directly without using mplayer????
If can be played what are the steps... please reply......

**Comment by Ruffio** [comment]
@popcornmix there has been any response to your requestion for 2 years, I think the issue can be closed

**Comment by popcornmix** [comment]
Yes. I'm not convinced there exist any devices that support AAC passthrough.
xbmc used to have a gui option to enable AAC passthough support and never found any equipment that really supported it. It is now removed from the gui. See:
http://forum.kodi.tv/showthread.php?tid=152691&pid=1304248#pid1304248
