### ISSUE TITLE
1wire breaks camera module

### ISSUE THREAD

**Issue by deejot** [raspberrypi/firmware#228]
Hi there,

I recently did an update from

$ vcgencmd version
Oct  2 2013 19:02:03
Copyright (c) 2012 Broadcom
version 27c5a63b0c74c287a4cfa24ebdfd5aa5051a8d7d (clean) (release)
$ uname -a
Linux raspicam 3.6.11+ #557 PREEMPT Wed Oct 2 18:49:09 BST 2013 armv6l GNU/Linux

to

$ vcgencmd version
Nov  7 2013 16:45:47
Copyright (c) 2012 Broadcom
version 8573b0747a17baf22e97e08254737a13d80430dd (clean) (release)
$ uname -a
Linux campi 3.10.18+ #585 Thu Nov 7 15:16:15 GMT 2013 armv6l GNU/Linux

and after that camera didn't work anymore.

Error message:

pi@raspberrypi ~ $ raspistill -v -o test_w1_gpio.jpg

raspistill Camera App v1.3.5

Width 2592, Height 1944, quality 85, filename test_w1_gpio.jpg
[...lines omitted...]
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
mmal: camera component couldn't be enabled
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates

pi@raspberrypi ~ $

 Tracking down possible reasons (see http://www.raspberrypi.org/phpBB3/viewtopic.php?f=43&t=60518) showed that this seems to be an issue with 1wire. Camera works fine until the 1wire module w1-gpio is being loaded. Then by issuing the raspistill command, the cam starts up, takes its time (metering evaluation? I don't see if there is a preview while having the Rpi in a headless configuration ) and then the mentioned error message appears, cam LED stays on.

With the newest version now the error message appears instantly after a short flashing of the cam LED.

pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.10.18+ #594 PREEMPT Wed Nov 13 17:59:34 GMT 2013 armv6l GNU/Linux
pi@raspberrypi ~ $ vcgencmd version
Nov 12 2013 23:39:45
Copyright (c) 2012 Broadcom
version 4aee5454c7955e7bc0bbb152ca4c0e26e75376e1 (clean) (release)
pi@raspberrypi ~ $

**Comment by sibujacob** [comment]
Can you please elaborate [Elucidation)'s post

**Comment by pelwell** [comment]
This thread was last posted to 8 years ago - your chances of getting an answer _and_ the answer being relevant today is vanishingly small.

Locking.
