### ISSUE TITLE
omx video decode api

### ISSUE THREAD

**Issue by cleverca22** [raspberrypi/firmware#230]
I've been working on trying to get mplayer to run on the pi with full gpu decode, and I've hit a wall with the lack of documentation on the OMX interface

http://bpaste.net/show/151411/

I think I've properly adapted the hello_video.c code to remove the scheduler and accept data from player, but it just hangs at ilclient_get_input_buffer and never gets a buffer to put data into

is where any documentation on things like the ports in set_tunnel(&tunnel,video_decode,131,video_render,90); or how its supposed to be used, beyond hello_video?

**Comment by undali** [comment]
I'm facing same issue you described there. 

> the callback never gets ran, and after about 120 input buffers worth of data, the input buffers start blocking, and it just hangs

How did you fix that?

**Comment by cleverca22** [comment]
```
-rw-r--r-- 1 clever 1000 2.2K Sep  5  2013 vo_rpi.c
```
https://gist.github.com/20c6bba8cbf16237330df47225ef790b

cant remember how i fixed it, but thats the code i have left-over from when i was trying all of the above

i think it was something about having to start playback, and consume frames from the output as you feed it buffers on the input

**Comment by cleverca22** [comment]
@popcornmix at some point, i did figure out the b-frame issue
omx is undoing the b-frame reordering stuff, and then i feed the frames to ffmpeg
then ffmpeg undoes the reordering again, with an offset because ffmpeg expected a sync api, and omx was async, and i just gave it the frame from 20 frames ago
