### ISSUE TITLE
Include l2tp Kernel-Modules 

### ISSUE THREAD

**Issue by fmu83** [raspberrypi/firmware#236]
Can you include

l2tp_eth
l2tp_netlink

as compiled module?

I try to compile the modules multiple times seperatly but they did not fit to my my current installed kernel, so it would be nice to have them in the official kernel.

**Comment by Ruffio** [comment]
@fmu83 is this still an issue?

**Comment by popcornmix** [comment]
I believe this is in now:
```
$ zcat /proc/config.gz |grep L2TP
CONFIG_NETFILTER_XT_MATCH_L2TP=m
CONFIG_L2TP=m
# CONFIG_L2TP_DEBUGFS is not set
CONFIG_L2TP_V3=y
CONFIG_L2TP_IP=m
CONFIG_L2TP_ETH=m
CONFIG_PPPOL2TP=m
```

**Comment by Ruffio** [comment]
@fmu83 @popcornmix  please close this resolved issue
