### ISSUE TITLE
openmax h264 sps aspect ration don't support full range of aspect ratios

### ISSUE THREAD

**Issue by xlazom00** [raspberrypi/firmware#244]
openmax api has OMX_IndexParamBrcmPixelAspectRatio if we want to set aspect ratio in output h264 SPS 
but current api pass only some specific subset of aspect ratios (1:1, 10:11, 16:11, 40:33, 59:54, and 118:81)

plz add full sets with extended support
search VUI_aspect_ratio_idc in
http://iphome.hhi.de/suehring/tml/JM%20Reference%20Software%20Manual%20(JVT-AE010).pdf

or here
http://lists.freedesktop.org/archives/gstreamer-commits/2012-September/066175.html

**Comment by popcornmix** [comment]
I believe any aspect ratios can be specified now.
```
static OMX_BOOL valid_pixel_ratio(OMX_CONFIG_POINTTYPE *p)
{
   // h.264 codec can handle any 16-bit values
   return (p->nX | p->nY) & 0xffff0000 ? OMX_FALSE:OMX_TRUE;
}
```
