### ISSUE TITLE
changing h264 encoder level with openmax  hangup

### ISSUE THREAD

**Issue by xlazom00** [raspberrypi/firmware#250]
Add this to encoder example
and if change to unsupported h264 level openmax api hang up.
And sometimes I can't init openmax again.

  OMX_VIDEO_PARAM_PROFILELEVELTYPE profileLevelType;
   memset(&profileLevelType, 0, sizeof(OMX_VIDEO_PARAM_PROFILELEVELTYPE));
   profileLevelType.nSize = sizeof(OMX_VIDEO_PARAM_PROFILELEVELTYPE);
   profileLevelType.nVersion.nVersion = OMX_VERSION;
   profileLevelType.eProfile = OMX_VIDEO_AVCProfileMain;
   profileLevelType.eLevel = OMX_VIDEO_AVCLevel2;
   profileLevelType.nPortIndex = 201;
   r = OMX_SetParameter(ILC_GET_HANDLE(video_encode),
                       OMX_IndexParamVideoProfileLevelCurrent, &profileLevelType);
   if (r != OMX_ErrorNone) {
      printf
        ("%s:%d: OMX_SetParameter() for bitrate for video_encode port 201 failed with %x!\n",
         __FUNCTION__, __LINE__, r);
      exit(1);
   }

**Comment by Ruffio** [comment]
@xlazom00 is this still an issue?

**Comment by popcornmix** [comment]
Pretty sure this is fixed. @xlazom00 can you reproduce?

**Comment by xlazom00** [comment]
I just run both of my examples and no it isn't working

**Comment by 6by9** [comment]
CBR and CABAC together are not supported, so that is why CBR and high profile will fail.
The GPU lockup should have been fixed a while back - where exactly does your test fail?

**Comment by 6by9** [comment]
Ack that it shouldn't lock up (for some reason it is retrying over and over) - IL wasn't used for about the last 3 years on production devices in favour of MMAL.
The reason for the failure is that you've asked for Level 2 when you're encoding at 640x360@30. Level 2 maxes out at 352×288@30.0. Level 3 or above works fine.
As above, CBR and CABAC is not supported, and that will get stuck in the same loop.

I'm not going to investigate further for a fix, as it is only an issue if the client is being stupid. I believe all is good under MMAL and it will throw the correct error.

**Comment by Ruffio** [comment]
@6by9, @popcornmix shouldn't this issue be closed?
