### ISSUE TITLE
Kernel oops in vchiq when running OMXPlayer in tight loop

### ISSUE THREAD

**Issue by cjsoftuk** [raspberrypi/firmware#253]
One of my projects calls for OMXPlayer to be run in a very tight loop (i.e. video after video after video, ad infinitum for many hours).  When doing so, seemingly at random, the following will occur in dmesg

```
[ 2123.834308] ------------[ cut here ]------------
[ 2123.834377] WARNING: at drivers/misc/vc04_services/interface/vchiq_arm/vchiq_arm.c:2386 vchiq_release_internal+0xc4/0x284()
[ 2123.834391] Modules linked in: snd_bcm2835 snd_soc_bcm2708_i2s regmap_mmio snd_soc_core regmap_spi snd_pcm snd_page_alloc regmap_i2c snd_compress snd_seq snd_timer snd_seq_device evdev leds_gpio led_class snd
[ 2123.834472] CPU: 0 PID: 6789 Comm: HTV Notify Not tainted 3.10.25+ #622
[ 2123.834545] [<c0013a18>] (unwind_backtrace+0x0/0xf0) from [<c0010d7c>] (show_stack+0x10/0x14)
[ 2123.834590] [<c0010d7c>] (show_stack+0x10/0x14) from [<c001e5ac>] (warn_slowpath_common+0x4c/0x68)
[ 2123.834622] [<c001e5ac>] (warn_slowpath_common+0x4c/0x68) from [<c001e5e4>] (warn_slowpath_null+0x1c/0x24)
[ 2123.834658] [<c001e5e4>] (warn_slowpath_null+0x1c/0x24) from [<c0297a98>] (vchiq_release_internal+0xc4/0x284)
[ 2123.834693] [<c0297a98>] (vchiq_release_internal+0xc4/0x284) from [<c0298288>] (vchiq_ioctl+0x288/0x14ec)
[ 2123.834734] [<c0298288>] (vchiq_ioctl+0x288/0x14ec) from [<c00e6060>] (do_vfs_ioctl+0x7c/0x5cc)
[ 2123.834766] [<c00e6060>] (do_vfs_ioctl+0x7c/0x5cc) from [<c00e65e8>] (SyS_ioctl+0x38/0x60)
[ 2123.834843] [<c00e65e8>] (SyS_ioctl+0x38/0x60) from [<c000dac0>] (ret_fast_syscall+0x0/0x30)
[ 2123.834864] ---[ end trace 193ab30ddce1e3e2 ]---
[ 2123.834886] vchiq: vchiq_ioctl: cmd VCHIQ_IOC_RELEASE_SERVICE returned error -1 for service TVNT:6785
```

While in most cases, OMXPlayer continues faithfully without any apparent failure, sometimes it locks up (usually on one specific video, but that's not guaranteed).  Given that this appears to be a kernel/boot microcode issue rather than an OMXPlayer one, I'm reporting it over here.

**Comment by julianscheel** [comment]
@popcornmix Do you have any clue which changes migth have resolved this with omxplayer for @cjsoftuk ? I do see these oopses with VLC as well from time to time.

**Comment by Aiexis** [comment]
Hello
I have the same issue with a pi3 and omxplayer running H24 with 2 small videos
uname
4.9.28-v7+ #998 SMP Mon May 15 16:55:39 BST 2017 armv7l GNU/Linux
(minibian)
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Mon, 30 Jan 2017 01:52:37 +0000
        Version   : 62fb580 [master]

omxplayer still plays but I can see the same messages (WARNING: at drivers/misc/ etc...) between the 2 videos.
Thank you

**Comment by popcornmix** [comment]
@Aiexis You may get a better response with a new issue rather than posting on an old, closed issue.
Include your dmesg log. Include instructions for how to reproduce the issue. (e.g. provide sample files and a script that provokes the problem).

**Comment by Aiexis** [comment]
That's done, thank you @popcornmix
