### ISSUE TITLE
dispmanx resource physical address

### ISSUE THREAD

**Issue by cleverca22** [raspberrypi/firmware#257]
is it possible to get the physical address that a DISPMANX_RESOURCE_HANDLE_T stores the image data at?

i tried vc_dispmanx_resource_get_image_handle but that appears to point to an internal struct with unknown layout

it doesn't have to be visible to userspace, in-kernel will also work

**Comment by john-terraspace** [comment]
I've been trying to get this above process working, using the mailbox message: Tag: 0x00030014
But I seem to be going around in circles!

I used some example code from hello_fft to interface with the mailbox which seems to work fine, but I guess I've got the order of these operations are calls wrong. What is the correct sequence to get the raw image data ptr from the dispmanx resource?

int fd = mbox_open();
//uint32_t pImage = vc_dispmanx_resource_get_image_handle(this->front_resource);
//VC_IMAGE_T* pImage2 = (VC_IMAGE_T*)mapmem(BUS_TO_PHYS(pImage), sizeof(VC_IMAGE_T));
uint32_t memHandle = get_dispmanx_resource_mem(fd, this->front_resource);
uint32_t addr = mem_lock(fd, memHandle);
VC_IMAGE_T* pImage2 = (VC_IMAGE_T*)mapmem(addr, sizeof(VC_IMAGE_T));
memset32(pImage2, 0xff, 100);// this->size);
unmapmem(pImage2, sizeof(VC_IMAGE_T));
mem_unlock(fd, memHandle);
mbox_close(fd);

**Comment by 6by9** [comment]
Commenting on an issue that was closed 5 years ago isn't going to get much attention.
I'll respond on https://www.raspberrypi.org/forums/viewtopic.php?f=67&t=234404
