### ISSUE TITLE
pcm512x: probe of 1-004c failed with error -5

### ISSUE THREAD

**Issue by iz8mbw** [raspberrypi/firmware#273]
Hi.
I have this error in the messages:

May  4 10:40:29 raspberrypi kernel: [    7.641204] pcm512x: probe of 1-004c failed with error -5

I'm trying to find out info on Internet but no info...

**Comment by phlegx** [comment]
I have added ```blacklist snd_soc_pcm512x``` to a conf file and rebooted the system, but the problem persist.

**Comment by pelwell** [comment]
Have you disabled device tree ("device_tree=" in config.txt)?

What does "sudo vcdbg log msg" report?

**Comment by phlegx** [comment]
device_tree is disabled with "device_tree=" in config.txt

**Comment by pelwell** [comment]
Why? You wouldn't get this kind of problem if it was enabled.

**Comment by phlegx** [comment]
I use https://github.com/debian-pi/raspbian-ua-netinst and I dont have changed it.

**Comment by pelwell** [comment]
And the answer to my second question is...?

**Comment by pelwell** [comment]
Never mind. What does dmesg show after a boot?

**Comment by phlegx** [comment]
```
$ vcdbg log msg

Unable to determine the value of __LOG_START
Unable to read logging_header from 0x00000000
```

**Comment by iz8mbw** [comment]
Hi.
just for your info, on my Raspberry Pi 2 the device tree is not enabled (I don't have any line about device tree into file config.txt) and I did NOT added "blacklist snd_soc_pcm512x" into the file /etc/modprobe.d/raspi-blacklist.conf and I have NOT this error.

**Comment by pelwell** [comment]
Device Tree is enabled by default, so the fact that you don't have a device_tree= line means that you are using it.

**Comment by iz8mbw** [comment]
OK, but anyway I do not have the error :-)
