### ISSUE TITLE
CEC Fails randomly

### ISSUE THREAD

**Issue by scrag** [raspberrypi/firmware#274]
Hi,

I've posted over at Pulse-Eight/libCEC regarding random failure of CEC with my Panasonic Viera V10A, Panasonic SC-BT200 surround system and an audio extractor.

Lars @opdenkamp has looked at the issue and is adamant that it is a Pi firmware issue that needs to be addressed. My logs did not reveal anything.

Sam @samnazarko has also look been helpful with updating firmware to improve CEC with panasonic TVs.

Under Frodo I had to extract the TV's EDID data file and add it to /boot and add hdmi_edid_file=1 to config.txt This seems to have greatly improved the failure rate to, maybe, once a week.

I have also tried: Overriding the automatically detected physical address in XBMC, in system -> input devices -> peripherals -> CEC adapter. If your Pi is connected to HDMI 1 of the TV, use address "1000". If it's connected to HDMI 2, use "2000". 

The Pi is connected to HDMI 2 on the TV so I have also set 2000.

I am at a complete loss as to why it is happening. Once a week is bearable but still annoying when the kids want to watch something and it happens as they have no idea how to rectify it - nor does my wife.

http://forum.stmlabs.com/showthread.php?tid=10073&pid=101830

It is very hard to provide logs now as it only happens around once a week and that is random. Apparently the logs show nothing untoward or what is causing the issue.

Thanks in advance.

**Comment by Ruffio** [comment]
@scrag is this still an issue?

**Comment by scrag** [comment]
No. This is not an issue anymore. Has been fine for quite some time now.
