### ISSUE TITLE
720p stream is detected as interlaced by OMX video decoder

### ISSUE THREAD

**Issue by reufer** [raspberrypi/firmware#283]
While developing a native output plugin for the VDR (Video Disk Recorder, www.tvdr.de) I observed an issue with streams from ZDF HD (German FTA broadcast): The video is  always detected as 720i by the OMX decoder, instead of 720p as confirmed by ffprobe.

Today, I double checked with recent omxplayer and firmware, but the problem persists - so I guess, it's a firmware issue.

I have uploaded a snippet for testing: http://www.reufer.ch/temp/00001.ts

Regards,
Thomas

**Comment by deborah-c** [comment]
To add one further note: H.264 table D-1 notes a restriction that when pic_struct ==  0 (as here), "field_pic_flag shall be 0, TopFieldOrderCnt shall be equal to BottomFieldOrderCnt". In this stream, the latter condition isn't actually met, so the pic_struct value isn't technically legal...

**Comment by popcornmix** [comment]
Please try the latest firmware update.
This should report the test file as progressive.

**Comment by julianscheel** [comment]
I tested with quite a few german TV channels and all of them seem to be detected properly now. Thanks.

**Comment by reufer** [comment]
Works as expected now - thanks a lot!
