### ISSUE TITLE
Why is raspberrypi/firmware github web not being update

### ISSUE THREAD

**Issue by MrEngman** [raspberrypi/firmware#284]
Did a git pull of raspberrypi/firmware git repo about 00:06 pm Jun 1. It updated the firmware but the update is not showing on the web site? Why not?

The last commit showing is 02eed2f but shouldn't it now be f15c3b5?

    cd /home/pi/src/firmware
    git pull
    remote: Counting objects: 9, done.
    remote: Compressing objects: 100% (9/9), done.
    remote: Total 9 (delta 4), reused 0 (delta 0)
    Unpacking objects: 100% (9/9), done.
    From https://github.com/raspberrypi/firmware
       02eed2f..f15c3b5  master     -> origin/master
    Updating 02eed2f..f15c3b5
    Fast-forward
     boot/fixup.dat    |  Bin 5847 -> 5849 bytes
     boot/fixup_cd.dat |  Bin 2090 -> 2092 bytes
     boot/fixup_x.dat  |  Bin 8885 -> 8883 bytes
     boot/start.elf    |  Bin 2550840 -> 2552472 bytes
     boot/start_cd.elf |  Bin 509272 -> 511000 bytes
     boot/start_x.elf  |  Bin 3531752 -> 3533512 bytes
     6 files changed, 0 insertions(+), 0 deletions(-)

**Comment by Ruffio** [comment]
Was this just a glitch and can be closed?

**Comment by popcornmix** [comment]
I believe so. No other reports and it has since worked for me.
Reopen if this continues to be a problem.
