### ISSUE TITLE
HDMI blackout on 'video_render' creation

### ISSUE THREAD

**Issue by kirgene** [raspberrypi/firmware#286]
I'm trying to achieve seamless playback using OpenMAX.
I create and prepare 2 video pipelines: for current and next video that is going to be played. I destroy previous pipeline after few seconds of next video playback. So next video is played on foreground. It works fine but when I destroy previous pipeline or create next pipeline my monitor goes to sleep mode.
Running "tvservice -M" I see "HDMI in standby mode" during I create or remove "video_render" component.

I saw the same issue here:
http://www.raspberrypi.org/forums/viewtopic.php?f=67&t=50126.

Also running tvservice monitor and executing hello_video will output "HDMI in standby mode" message.

**Comment by Ruffio** [comment]
@kirgene is this still an issue?
