### ISSUE TITLE
OMX.broadcom.image_decode OMX_ErrorStreamCorrupt, Bitstream corrupt

### ISSUE THREAD

**Issue by biji** [raspberrypi/firmware#288]
From xbmc log:

ERROR: COMXCoreComponent::DecoderEventHandler OMX.broadcom.image_decode - OMX_ErrorStreamCorrupt, Bitstream corrupt

**Comment by mathieugouin** [comment]
I have a few jpeg photos that can reproduce this problem every time.  I'm on xbian with kodi 16.1.

The debug log shows the OMX bitstream corrupt error message.  This crash kodi.

However, according to http://techslides.com/demos/progressive-test.html my photo is not progressive...

Let me know if this is not the proper place to report this issue.  Thanks.
