### ISSUE TITLE
Flickering and no POST on older, low-res monitors

### ISSUE THREAD

**Issue by Markieta** [raspberrypi/firmware#289]
Using hdmi_drive=2 in the config.txt with low-res monitors causes flickering or no POST in the latest version of raspberrypi-vc.

These monitors use adapters to DVI, and work fine when hdmi_drive=1. However, this was not an issue before.

Last known working version was git316b922-14

**Comment by Ruffio** [comment]
@Markieta is this still an issue?

**Comment by Markieta** [comment]
@Ruffio I used to work on Pidora and I simply added an option to the installation menu indicating if the user is using a DVI adapter rather than HDMI directly.

hdmi_drive=1 should work for all monitors, but if you really are using HDMI, you will lose HDMI-audio. If the user does not select "Is using DVI adapter", then the installation would set it to hdmi_drive=2.

That beind said, is it really an issue? According to @popcornmix this behaviour is correct. I haven't worked on Pidora in a while. Hope I gave you some useful information, otherwise I'm just rambling. :)

**Comment by popcornmix** [comment]
The older firmware had the bug where hdmi_drive=2 was not applied in some circumstances. The bug fix seems to have exposed a limitation of the monitor not handling hdmi_driver=2 over DVI.
I don't see a bug here. If hdmi_drive=2 doesn't work with a monitor it shouldn't be specified.

Feel free to reopen if there is more evidence of a bug.
