### ISSUE TITLE
Network Problems when overclocking is enabled

### ISSUE THREAD

**Issue by ditschi** [raspberrypi/firmware#297]
Using XBian I have problems with network when enabling overclocking
  (see: http://forum.xbian.org/thread-2372-post-23453.html#pid23453)

Xbian won't boot up and stays at a "configure network" screen when overclocking is enabled. 

a possible solution by mk01:
are we speaking about impossible DHCP acquire ? we had just similar issue on cubox-i - u-boot/SPL code effectively messed up UDP on eth0 for maybe 30-40s after boot. so DHCP failed initially and system was done. static IP was ok. if DHCP was delayed with sleep 30 before ifup eth0, all was ok.

**Comment by Ruffio** [comment]
@ditschi is this still an issue?

**Comment by ditschi** [comment]
haven't had problems in the past time
