### ISSUE TITLE
usb wlan in bridge error

### ISSUE THREAD

**Issue by networkpadawan** [raspberrypi/firmware#301]
I have the following issue: 
- rpi with 1 ralink rt5370 connected, bridged with eth0, nothing else connected to usb or gpio.
- usb psu of 1 amp (http://pt.farnell.com/raspberry-pi-psu/rpi-psu-eu-mk1/power-supply-raspberry-5v-1a-euro/dp/2254794)
- hostapd is being used as Access Point.
- no overclock

as soon as i connect the wlan dongle, the rpi starts to crash.

on dmesg the only info that I can find is:

ERROR::dwc_otg_hcd_urb_enqueue:505: Not connected

I tried with 2 rpis (modelb/512) and 2 power supplies.

I don´t have hardware to measure, but i don´t think that 1 wlan dongle needs much power...

I think it should be some bug, but if anyone has any idea where to get more debug info i would apreciate it.

**Comment by Ruffio** [comment]
@networkpadawan is this still an issue?

**Comment by Ruffio** [comment]
@popcornmix this should be closed due to inactivity

**Comment by Ruffio** [comment]
@popcornmix, @networkpadawan this should be closed due to inactivity
