### ISSUE TITLE
USB and networking stop working on latest firmware.

### ISSUE THREAD

**Issue by simonhowes** [raspberrypi/firmware#313]
I have tried a clean install of Raspbian and Pidora. When running dist-update in Raspbian (jessie) or yum update in Pidora of the kernel only, reboot, USB and networking stop working. 

Running a model B 256MB.

**Comment by Ruffio** [comment]
@simonhowes is this still an issue?

**Comment by simonhowes** [comment]
@Ruffio No idea, my original model B was retired years ago.
