### ISSUE TITLE
usb no disk

### ISSUE THREAD

**Issue by dudducat** [raspberrypi/firmware#316]
with latest firmware ethernet stops working using an usb disk, and if ethernet works no disk is recognized (disk works properly attached to my debian notebook and worked well till last update/upgrade)

root@raspberrypi:~# uname -a
Linux raspberrypi 3.12.28+ #713 PREEMPT Fri Sep 19 16:43:32 BST 2014 armv6l GNU/Linux

....
[    2.167083] Key type dns_resolver registered
[    2.177361] registered taskstats version 1
[    2.183997] Waiting for root device /dev/mmcblk0p2...
[    2.207770] mmc0: host does not support reading read-only switch. assuming write-enable.
[    2.218648] Indeed it is in host mode hprt0 = 00021501
[    2.232784] mmc0: new high speed SDHC card at address e624
[    2.248914] mmcblk0: mmc0:e624 SU16G 14.8 GiB 
[    2.260231]  mmcblk0: p1 p2
[    2.320792] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    2.331913] VFS: Mounted root (ext4 filesystem) on device 179:2.
[    2.351161] devtmpfs: mounted
[    2.356170] Freeing unused kernel memory: 140K (c05bd000 - c05e0000)
[    2.418427] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    2.427421] Indeed it is in host mode hprt0 = 00001101
[    2.628921] usb 1-1: New USB device found, idVendor=0424, idProduct=9512
[    2.637241] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.647819] hub 1-1:1.0: USB hub found
[    2.657051] hub 1-1:1.0: 3 ports detected
[    2.938608] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    3.048939] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    3.057517] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.080998] smsc95xx v1.0.4
[    3.143838] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:91:1d:bf
[    4.026968] udevd[156]: starting version 175
[    6.239887] bcm2708-i2s bcm2708-i2s.0: Failed to create debugfs directory
[    9.955227] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   15.785616] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[   18.241325] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   19.402326] Installing knfsd (copyright (C) 1996 okir@monad.swb.de).
[   19.644904] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xDDE1
[   22.642297] bcm2835-cpufreq: switching to governor ondemand
[   22.642336] bcm2835-cpufreq: switching to governor ondemand
[   27.765990] Adding 102396k swap on /var/swap.  Priority:-1 extents:1 across:102396k SSFS
[   67.868959] usb 1-1.2: new high-speed USB device number 4 using dwc_otg
[   67.971164] usb 1-1.2: New USB device found, idVendor=067b, idProduct=2507
[   67.971198] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   67.971216] usb 1-1.2: Product: Mass Storage Device
[   67.971231] usb 1-1.2: Manufacturer: Prolific Technology Inc.
[   67.971245] usb 1-1.2: SerialNumber: 0
[   67.979118] usb-storage 1-1.2:1.0: USB Mass Storage device detected
[   67.989139] usb-storage 1-1.2:1.0: Quirks match for vid 067b pid 2507: 110
[   67.989385] scsi0 : usb-storage 1-1.2:1.0
[  100.309401] usb 1-1.2: reset high-speed USB device number 4 using dwc_otg
[  105.389463] usb 1-1.2: device descriptor read/64, error -71
[  105.579457] usb 1-1.2: device descriptor read/64, error -71
[  105.769493] usb 1-1.2: reset high-speed USB device number 4 using dwc_otg
[  105.849460] usb 1-1.2: device descriptor read/64, error -71
[  106.039575] usb 1-1.2: device descriptor read/64, error -71
[  106.229484] usb 1-1.2: reset high-speed USB device number 4 using dwc_otg
[  106.649332] usb 1-1.2: device not accepting address 4, error -71
[  106.729472] usb 1-1.2: reset high-speed USB device number 4 using dwc_otg
[  107.149330] usb 1-1.2: device not accepting address 4, error -71
[  107.149882] usb 1-1.2: USB disconnect, device number 4
[  107.150204] scsi 0:0:0:0: Device offlined - not ready after error recovery
[  107.229500] usb 1-1.2: new high-speed USB device number 5 using dwc_otg
[  107.309617] usb 1-1.2: device descriptor read/64, error -71
[  107.499469] usb 1-1.2: device descriptor read/64, error -71
[  107.689536] usb 1-1.2: new high-speed USB device number 6 using dwc_otg
[  107.769504] usb 1-1.2: device descriptor read/64, error -71
[  107.959481] usb 1-1.2: device descriptor read/64, error -71
[  108.149484] usb 1-1.2: new high-speed USB device number 7 using dwc_otg
[  108.569344] usb 1-1.2: device not accepting address 7, error -71
[  108.649493] usb 1-1.2: new high-speed USB device number 8 using dwc_otg
[  109.069357] usb 1-1.2: device not accepting address 8, error -71
[  109.069574] hub 1-1:1.0: unable to enumerate USB device on p

**Comment by Ruffio** [comment]
@dudducat is this still an issue?

**Comment by dudducat** [comment]
No It can be closed
Il 17/giu/2015 19:46, "Rasmus Christiansen" <notifications@github.com> ha
scritto:
