### ISSUE TITLE
No network after unloading snd_soc_tas5713

### ISSUE THREAD

**Issue by GrayShade** [raspberrypi/firmware#317]
After upgrading to 20a5bb644cf078f21cc056a58904e962fa545da2 ("kernel: Added driver for HiFiBerry Amp amplifier add-on board"), the snd_soc_tas5713 module gets loaded automatically even if no I2S sound card is present.

A few seconds after unloading that module, network stops working. There's nothing in dmesg before that and I don't have a serial cable to see the dump.

**Comment by Ruffio** [comment]
@GrayShade is this still an issue?

**Comment by GrayShade** [comment]
@Ruffio Sorry, I can't say right not, but it's probably fixed after all this time.

If you don't mind keeping the issue open, I can try to test it in a day or so.

**Comment by GrayShade** [comment]
It seems to work now. Closing.
