### ISSUE TITLE
Gpio-IR-Receiver doesn't work with latest start_x.elf 

### ISSUE THREAD

**Issue by mrniceplay** [raspberrypi/firmware#319]
Gpio-IR-Receiver doesn't work with latest start_x.elf.
The start.elf of Openelec 4.07 works without problems.
If i boot with the old start.elf and then boot with the new start.elf the gpio-ir-receiver works also. If i had disconnected power and hdmi the new start.elf doesn't work anymore.

**Comment by Ruffio** [comment]
@popcornmix this issue can be closed as it has been resolved
