### ISSUE TITLE
Req: separate monitor profiles

### ISSUE THREAD

**Issue by uecasm** [raspberrypi/firmware#320]
I would like to be able to use the same card (or card image) without changes to config.txt on many different monitors.  While most of the time an empty config.txt works fine for this, there are several cases where the Pi seems to pick the "wrong" display mode by default.  While config.txt allows a different mode to be selected manually, this then precludes using that card with another monitor without editing it again.

I suggest a very simple extension to the config.txt file format: monitor-specific sections.  The idea is that the file is broken into sections, like this:

    # any options up here always execute
    hdmi_force_hotplug=1

    [EDID=VSC-TD2220]
    # any options in here execute only if `tvservice -n` would be `device_name=VSC-TD2220`
    hdmi_group=2
    hdmi_mode=82

    [EDID=DWE-HDMI]
    # any options in here execute only if `device_name=DWE-HDMI`
    disable_overscan=1
    hdmi_group=2
    hdmi_mode=87
    hdmi_cvt 800 480 60 6 0 0 0

Any number of these sections could be added, and the options in a section with a non-matching EDID are simply skipped.

It's possible to do some of this later than in config.txt; I have a script that runs as early as I can manage that uses `tvservice -n` and `tvservice -e` along with `fbset` to "fix" the screen partway through boot, but this is still relatively late and it's not able to do `hdmi_cvt`, as that is missing (or at least not documented) in tvservice.  It would be cleaner if supported in config.txt though, and this doesn't seem all that hard to implement.

**Comment by popcornmix** [comment]
Please run rpi-update and test.

Sections like:
[EDID=DWE-HDMI]

should now be supported.

**Comment by uecasm** [comment]
Unfortunately this does not seem to be working as expected.  There's also an unfortunate (though not entirely unexpected) interaction with the new pi2 options.

I'm currently testing with a ViewSonic TD2200 monitor (which defaults to 1600x1200 instead of 1080p as desired), and this is my config:

    disable_splash=1
    [edid=VSC-TD2200]
    hdmi_group=2
    hdmi_mode=82
    [all]
    [pi1]
    initramfs initrd.img-3.18.7+ followkernel
    [pi2]
    initramfs initrd.img-3.18.7-v7+ followkernel

    # tvservice -n
    device_name=VSC-TD2220

If I comment out the edid heading then X boots up with 1920x1080 as expected.  As above, it boots to 1600x1200, which is the same as an empty config.txt.  If I omit the "[all]" tag then it also ignores the following initramfs lines.

(The need for "all" is the possibly unexpected interaction -- it's not necessarily bad, as it means that you can do "and" checks (eg. "if pi2 and using this monitor then")... but on the other hand I'm not sure why you'd want to do that.  Still, I suppose it could be useful if other such conditionals are added.)

**Comment by uecasm** [comment]
On a hunch, I just tried it again using "EDID=VSC-TD2220" instead of "edid=VSC-TD2220" and now it's working properly.  I wasn't expecting this to be case sensitive, or for it to require uppercase (since all the other config directives seem to be lowercase).

So with the "right" capitalisation this now seems to be working as expected after all, with the caveat about the "all" tag being needed as well.  Thanks very much for adding this (and the pi2 condition).

Are these things going to get documented on the elinux page?

**Comment by popcornmix** [comment]
The [all] behaviour is deliberate. Each section (serial number, pi1/pi2 or EDID) is a filter that persists until the end of the file (unless reset with [all]). You can combine multiple filters.

I can make the EDID= case insensitive.

elinux is unofficial / community edited, so feel free to update it.

**Comment by popcornmix** [comment]
Latest rpi-update is now case insensitve with EDID.
[garbage] will now be ignored rather than being treated as filtering only serial=0

**Comment by uecasm** [comment]
Regarding the wiki page, if there's a more authoritative place I'd like to know about it.  These new options aren't at http://www.raspberrypi.org/documentation/configuration/config-txt.md either and that page seems to say that it's either a copy of or at least partly based on the elinux page anyway.

I'm happy to try to edit the wiki page but there's apparently lots of things that I don't know about, such as the serial=0 thing you just mentioned.

**Comment by popcornmix** [comment]
http://www.raspberrypi.org/documentation/configuration/config-txt.md
is the official location, so would be the best place to add information. I expect I (or someone else will update it at some point). Pull requests are welcome though.

elinux is still referenced by some, so does no harm to update that too, but that's not the official source of information (even though there is some overlap in information with raspberry pi documentation, and some of the elinux info was written by me).

**Comment by lurch** [comment]
@uecasm The rapid pace of firmware development (which is good, as it means bugs quickly get fixed) unfortunately means there's several `config.txt` options which are undocumented in the official docs, and are only referenced in scattered [forum](http://www.raspberrypi.org/forums/) postings.
But hopefully most of the important ones are covered - feel free to open issues (or pull requests) in https://github.com/raspberrypi/documentation (which then gets automatically mirrored to http://www.raspberrypi.org/documentation/ ).

It was me that had the initial job of adapting / enhancing http://elinux.org/RPiconfig into http://www.raspberrypi.org/documentation/configuration/config-txt.md - the idea is that the official documentation should be more accurate (and up to date) than the community eLinux wiki documentation (which sometimes contains incorrect information).

**Comment by uecasm** [comment]
Added PR https://github.com/raspberrypi/documentation/pull/177.

**Comment by lurch** [comment]
Have you tested this all works, and can this issue be closed?

**Comment by uecasm** [comment]
I haven't tested the non-case-sensitivity yet, but I've tested everything else and it's working as expected.  Wasn't sure if this should be left open pending the doc update or not, but as far as I'm concerned this can probably be closed now.

**Comment by popcornmix** [comment]
Thanks for documentation PR.

**Comment by uecasm** [comment]
Not sure if I should open a separate issue for this or not, but while trying to use this with a new monitor I encountered a problem.  (I'm using firmware based on 46a04a4 from this repository at the moment.)

The boot-time config for the monitor is not being used.
`tvservice -n` reports `[E] No device present` (which is probably why it's not being used) but `tvservice -d` is still able to output an EDID file and `edidparser` is able to read that and to display a "monitor name descriptor tag 0xFC" with a reasonable monitor name.

I do have `hdmi_force_hotplug=1` in the config but I previously had the same value and things were working as expected.

`edidparser` is stating that the preferred mode is `CEA (4) 1280x720p @ 60` but the display is actually booting at DMT 640x480p.

I'm relatively certain that I had this monitor working previously with the same firmware (although it was a different Pi and a different HDMI cable), so I don't think that this is a firmware bug per se, but I'm puzzled with the different behaviour between -n and -d | edidparser.

**Comment by uecasm** [comment]
There does appear to be a small bug with this.

If I supply an `edid.dat` and `hdmi_edid_file=1` in the global section of the config file, then it does load the data from this file but then it uses the default settings instead of parsing the corresponding `[EDID=name]` section.

I suppose arguably having separate EDID filters is fairly useless when the EDID is being globally overridden like that, but it's not *completely* useless.  If it's an easy fix (clear config and reparse after loading an EDID file perhaps?) then that'd be nice but this is hardly essential.

**Comment by popcornmix** [comment]
This code has already become somewhat tortured with the read edid->read config->read edid path. I'm reluctant to add another read config iteration to that.

I believe if you are providing your own edid file, then you don't really need settings conditional on the contents of that edid file - you are in control of that.
