### ISSUE TITLE
Post Jul 5, 2014 gpioman firmware broke GPIO2 (pin3) behaviour, model B, rev.2

### ISSUE THREAD

**Issue by krattai** [raspberrypi/firmware#321]
I have an external hardware device connected to GPIO2/pin3 that drives the pin to low.  Was working with firmware from Jan. 6, 2014 until pre Oct. 1 update.

With upgrade to Oct. 1 firmware, external hardware continued to drive down pin3, even on sudo reboot, until the unit is powered down with disconnect of power supply and then power back up.  After this hard reboot, pin3 is not being driven down by external hardware.

Ideas?  Is there a way to roll back the firmware on these units or force specific firmware version?

**Comment by krattai** [comment]
For some reason, I can no longer revert to Jul 5, 2014 firmware.

pi@idetsys ~ $ sudo rpi-update d9eb023ba98317d81fc53a3f9d6752b127a8dbbf
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8107  100  8107    0     0   3187      0  0:00:02  0:00:02 --:--:--  3214
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Your firmware is already up to date

pi@idetsys ~ $ /opt/vc/bin/vcgencmd version
Jan 30 2015 18:28:08 
Copyright (c) 2012 Broadcom
version d6e004c61a7a749897c482c860d0b2c28196437e (clean) (release)

Did the updater change and so doesn't revert back that far?

**Comment by popcornmix** [comment]
It beleives you already have that version.
Run ```sudo rm /boot/.firmware_revision``` and then try to force it.

**Comment by krattai** [comment]
perfect.  thank you, that worked.

I'll have to add that to my patching system.  Not sure how many devices out there that are running the wrong version...  lol
