### ISSUE TITLE
OpenMAX h264 encoder discarding frames

### ISSUE THREAD

**Issue by xlazom00** [raspberrypi/firmware#329]
I am doing heavy encoding of multiple stream on rpi h264encoder
and sometimes I get zero data from encoder and
OMX_CONFIG_BRCMPORTSTATSTYPE / OMX_IndexConfigBrcmPortStats
get me Discards frames
Any idea why?
And how can I force encoder to don't discard any frames?

**Comment by popcornmix** [comment]
@xlazom00 okay to close?

**Comment by xlazom00** [comment]
you can close this issue
thx

**Comment by brunogm0** [comment]
6by9 any link for the ratecontrol code you described earlier? At least it appears different than JM, so i am curious.

**Comment by 6by9** [comment]
Sorry, it's in the closed source firmware, so I can't link to it.
