### ISSUE TITLE
hello_videocube doesn't work with other videos

### ISSUE THREAD

**Issue by etam89** [raspberrypi/firmware#332]
I converted some MP4 video to *.h264 format with ffmpeg or avconv.  hellow_videocube can't play the video - the cube is black.

**Comment by etam89** [comment]
Hi, Could you give me hint on what changes is needed to pause the video please?
ThanksEugene 

     On Friday, January 2, 2015 8:06 AM, popcornmix <notifications@github.com> wrote:
   

 Closed #332.—

**Comment by popcornmix** [comment]
Try changing the speed of the clock component. Set to 0 for pause. See:
https://github.com/popcornmix/omxplayer/blob/master/OMXClock.cpp#L499

**Comment by etam89** [comment]
Thank you very much.
I try to modify your hello_videocube/*.c to play h264 video at the same time by starting two threads of video_decode_test() each with its own video_decode,video_scheduler, video_cloc, egl_render, eglBuffer, eglImage and texture. I can see two video can play at the same time.  But after a while, one of the video is stuck at ilclient_get_input_buffer(player->video_decode, 130, 1) call.  The call never returns.  
What's interested is that, regardless video file, the stall always occurs on number 20 of such a call. Do I need to split other variable/object between the thread?  Do tunneling port number (like 130 for video_decode) matter?  I tinker with the port number of 130, and it doesn't seem solve the problem. 
Thanks.Eugene
 

     On Saturday, January 3, 2015 3:09 AM, popcornmix <notifications@github.com> wrote:
   

 Try changing the speed of the clock component. Set to 0 for pause. See:
https://github.com/popcornmix/omxplayer/blob/master/OMXClock.cpp#L499—

**Comment by popcornmix** [comment]
Are you saying you want two videos to be played concurrently, so you end up with two textures that are both used in the 3d rendering?
You'd certainly need the static objects in video.c to to be per thread.
You'll need significantly more gpu_mem allocated (try gpu_mem=256 for safety).

**Comment by etam89** [comment]
Thanks for you reply.
I started with the cube and later kept only one side if the cube. 
I used two separate textures one for each video.
I use struct to keep the data separate for each thread, similar to what you suggest.
I have ramp up gpu men to 256MB.

I can email u the source code if you like. 

Best regards
Eugene

**Comment by etam89** [comment]
d

On Friday, January 2, 2015 8:06 AM, popcornmix <notifications@github.com> wrote:
C

Closed #332.

**Comment by etam89** [comment]
Hi, I try to stop displaying the textures for the video when video is finished after modifying from the videocube.c example.  But I can't find ways to detect the completion of video play.  feof() comes much earlier than video completion.  how can I detect the video has completed? Thank you a bunch.Eugene 

     On Monday, February 2, 2015 6:23 PM, eugene tam <etam89@yahoo.com> wrote:
   

  d

     On Friday, January 2, 2015 8:06 AM, popcornmix <notifications@github.com> wrote:
   C

 Closed #332.—

**Comment by popcornmix** [comment]
You submit the last packet with EOS flag. e.g.
https://github.com/raspberrypi/firmware/blob/master/opt/vc/src/hello_pi/hello_video/video.c#L179
and then wait for the EOS event to be signalled from egl_render (i.e. when final frame has been rendered to texture)
https://github.com/raspberrypi/firmware/blob/master/opt/vc/src/hello_pi/hello_video/video.c#L185

**Comment by etam89** [comment]
Thank you very much. It works great.
But when I start feeding data a while after I stop feeding decoder buffer with data from video file, the video plays very fast and skip some frames. What should I do?

Best regards
Eugene

**Comment by popcornmix** [comment]
Probably an issue with timestamps. What are you setting timestamps and flags to?

**Comment by etam89** [comment]
I set buffer flag to OMX_BUFFERFLAG_STARTTIME. That's all I did. 
How can I set time stamp ?

Best regards
Eugene

**Comment by popcornmix** [comment]
I suspect you want the first packet to contain OMX_BUFFERFLAG_STARTTIME and any later packets to contain OMX_BUFFERFLAG_TIME_UNKNOWN.
I don't really know what you do after EOS.
If you close and reopen the openmax components, then you want to repeat the same process with the flags. If you don't close the openmax components, then I'd suggest just sending OMX_BUFFERFLAG_TIME_UNKNOWN.
