### ISSUE TITLE
MT7610U USB Dongle Kernel Module has to be recompiled every time there is a firmware update.

### ISSUE THREAD

**Issue by Boggartfly** [raspberrypi/firmware#333]
It's really difficult to get my system online after a system update because it **breaks** my wifi. To fix this I have to **recompile** the kernel module. The source is **GNU GPL V2 or later** compatible and is free to use and distribute. To fix this I would recommend
1. Add the source to the Raspberry Pi firmware repository.
2. Compile the kernel module every time there's a release. [the maintainers of course]
3. Ship it via the update.

You can find the source at http://www.mediatek.com/en/downloads/mt7610u-usb/

**Comment by popcornmix** [comment]
Closing. Please create a new issue (here: https://github.com/raspberrypi/linux/issues) when it's been accepted upstream.
