### ISSUE TITLE
Video_render set  DstRect Error

### ISSUE THREAD

**Issue by jfory** [raspberrypi/firmware#335]
I had changed pi's resolution to 3840*2160 and omxplayer is working. When enter the command, omxplayer do not show video.
"./omxplayer --win "2047 0 3840 1080" /home/pi/big.mov";
But, "./omxplayer --win "0 0 3840 1620" /home/pi/big.mov" is working.
the video file resolution equals 854*480.
I checked it and found when x1 larger than 2047, the window doesn’t show.
I think the oxmplayer has no problem.
Is there some issue in libs? 
It's the vital feature for my project,

**Comment by popcornmix** [comment]
Can you try with latest rpi-update firmware? I suspect this issue may have been solved.
