### ISSUE TITLE
wrong header location for pthreads-headers (while building quake3)

### ISSUE THREAD

**Issue by MarshallBanana0815** [raspberrypi/firmware#34]
while compiling quake3 on the raspbian distrib i encountered build errors due to a missing vcos_platform_types.h / vcos_platform.h

first fix was in opt/vc/include/interface/vcos/vcos_types.h:
- \- #include "vcos_platform_types.h"
- \+ #include "pthreads/vcos_platform_types.h"

second fix would be in all the opt/vc/include/interface/vcos/vcos*.h:
- \- #include "vcos_platform.h"
- \+ #include "pthreads/vcos_platform.h"

but being the lazy fool that i am i just copied the files from the pthreads subfolder there, after noticing that grep gave me to many files to fix that in :-P

i guess this would be just a very dirty fix because noone else reported it yet, and so might even be fixed by some makefile magic or the like in the quake3 repository? i can't imagine this problem to be a global one, probably also just tied to quake3+raspbian?
(i use the raspbian-r3.img from hexxeh)

anyways, with the above mentioned actions quake3 builds again...

**Comment by fscz** [comment]
why is this closed? it's still an issue

**Comment by juj** [comment]
Please reopen. This is still a bug, here are simple steps to reproduce e.g. for attaching to raspberry pi unit test suites:

1. Create a file a.c with the following one line of content:

    #include <EGL/egl.h>

2. Compile with `cc -I/opt/vc/include -c a.c`.

Observed: The compilation fails with the error message

    pi@raspberrypi ~/code/builds $ c++ -I/opt/vc/include a.c
    In file included from /opt/vc/include/interface/vcos/vcos_assert.h:149:0,
                     from /opt/vc/include/interface/vcos/vcos.h:114,
                     from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                     from /opt/vc/include/EGL/eglplatform.h:110,
                     from /opt/vc/include/EGL/egl.h:36,
                     from a.c:1:
    /opt/vc/include/interface/vcos/vcos_types.h:38:33: fatal error: vcos_platform_types.h: No such file or directory
    compilation terminated.
    pi@raspberrypi ~/code/builds $ 

Expected: As per the EGL spec, the above code should compile without an error.

**Comment by juj** [comment]
Running the following (blunt but functional) script on the command line fixes the headers for me:

    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos.h
    sudo sed -i 's/include "vcos_platform_types.h"/include "pthreads\/vcos_platform_types.h"/g' /opt/vc/include/interface/vcos/vcos_types.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_init.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_thread.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_mutex.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_mem.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_logging.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_string.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_event.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_tls.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_reentrant_mutex.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_named_semaphore.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_quickslow_mutex.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_event_flags.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_atomic_flags.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_once.h
    sudo sed -i 's/include "vcos_platform.h"/include "pthreads\/vcos_platform.h"/g' /opt/vc/include/interface/vcos/vcos_blockpool.h

There may be more, I just replaced the ones that the compiler complained about when including `EGL/egl.h`.

**Comment by fthiery** [comment]
I've been trying to compile gst-plugins-bad's OpenGL sink with EGL support as well, and had a really hard time making the ./configure checks pass.

So far i succeeded by linking to several folders manually (as below):
./configure CFLAGS=-I/opt/vc/include -I /opt/vc/include/interface/vcos/pthreads -I /opt/vc/include/interface/vmcs_host/linux/ LDFLAGS=-L/opt/vc/lib --disable-gtk-doc --disable-opengl --enable-gles2 --enable-egl --disable-glx --disable-x11 --disable-wayland --enable-dispmanx --no-create --no-recursion

The sed command above didn't do it.
