### ISSUE TITLE
huawei_cdc_ncm.ko driver is missing in kernel 3.18.1+

### ISSUE THREAD

**Issue by jomofer** [raspberrypi/firmware#342]
In kernel's above 3.12 cdc_ncm.ko driver has been splited for some huawei 4G dongles in 2 drivers: cdc_ncm.ko and huawei_cdc_ncm.ko. One example is E3276 dongle.
Without huawei_cdc_ncm, those modems dont work because wwan0 interface doesnt exist.

I have compiled the drivers (cdc_ncm.ko and huawei_cdc_ncm.ko) with the utility rpi-source and it worked.

I'm not used to work with kernel's, modules and those things, so I only wanted to know if they could be included to the repo in order to not needing recompiling from sources.

**Comment by popcornmix** [comment]
I assume you are asking for:
CONFIG_USB_NET_HUAWEI_CDC_NCM=m

If so, that has been added to 3.18 tree.

**Comment by jomofer** [comment]
Is new kernel 3.18.2+ compiled with that config now? So, I assume that the module huawei_cdc_ncm is not required anymore... I'll give it a try

**Comment by popcornmix** [comment]
You'll currently have to build the kernel to get this change.
I'll let you know when the next rebuilt kernel is pushed.

**Comment by jomofer** [comment]
Okay, thank you so much!

**Comment by popcornmix** [comment]
Run rpi-update. This modules should be present now.
(Note: the main rpi-update branch is now on 3.18 kernel, so BRANCH=next is not required)

**Comment by jomofer** [comment]
Hi

I have just tested with master branch and it works. Thank you so much!
