### ISSUE TITLE
USBIP support

### ISSUE THREAD

**Issue by Am1GO** [raspberrypi/firmware#353]
Please consider enabling USBIP for your kernel builds so anyone could use usbip after running rpi-update.

**Comment by popcornmix** [comment]
Do you also need?
      VHCI hcd (USBIP_VHCI_HCD)
      Host driver (USBIP_HOST)

**Comment by Am1GO** [comment]
Yes, USBIP_CORE, USBIP_HOST and USBIP_VHCI_HCD.

Thanks!

**Comment by popcornmix** [comment]
Should be added to linux tree and latest rpi-update firmware. Please test.

**Comment by Am1GO** [comment]
Works like a charm, thanks!
