### ISSUE TITLE
problem in cmdline.txt, it allowes setting bcm2708.serial=

### ISSUE THREAD

**Issue by ztutberidze** [raspberrypi/firmware#357]
If I set the bcm2708.serial with wrong serial number, than I can't get the right serial number. It is security issue, because I can't use the serial number for licensing. Someone can add this parameter in cmdline.txt and than there is noway how to identify is it correct or not. I think it will be good if start.elf will check if this parameter is in the cmdline.txt and than remove it from cmdline and pass other fields to kernel.

this is my /proc/cmdline and here is shown the right and wrang serial numbers:
dma.dmachans=0x7f35 bcm2708_fb.fbwidth=1920 bcm2708_fb.fbheight=1080 bcm2708.boardrev=0x10 bcm2708.serial=0xb08d6b65 smsc95xx.macaddr=B8:27:EB:8D:6B:65 bcm2708_fb.fbswap=1 bcm2708.disk_led_gpio=47 bcm2708.disk_led_active_low=0 sdhci-bcm2708.emmc_clock_freq=250000000 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 bcm2708.serial=0xb08d6b11 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait

but in /proc/cpuinfo I can see wrang one. If the assume that the first serial number in the /proc/cmdline is correctone that it's good. but i think it is easyer to drop this field in cmdline.txt while loading kernel.

**Comment by P33M** [comment]
Working as intended.

If you intend to tie a software licence to a board, then implement a mailbox interface query to directly request the serial number. This then allows encryption/etc of your proprietary code and will be a lot more robust than someone simply rooting the Pi and doing whatever they want.

https://github.com/raspberrypi/firmware/blob/master/opt/vc/include/interface/vmcs_host/vcgencmd.h

**Comment by ztutberidze** [comment]
Thanks for reply,
Can you tell me where to find the appropriate command which gets the serial number using gencmd?

**Comment by popcornmix** [comment]
Probably safest to use (equivalent of):
```
pi@raspberrypi:~ $ grep Serial /proc/cpuinfo 
Serial		: 00000000015c0525
```
Next firmware update I'll disallow setting bcm2708.serial / bcm2709.serial in cmdline.txt.

**Comment by lurch** [comment]
I guess another option is to manually parse the serial number out of the `vcgencmd otp_dump` output, in a similar style to https://github.com/raspberrypi/noobs/commit/fc5cf67ec6d8fff2b044765968aac7e635fab9ec

**Comment by popcornmix** [comment]
Yes, that would work (and can't be spoofed). 
```
vcgencmd otp_dump | grep ^28
28:960ef966
```
However current rpi-update firmware won't allow a bcm2708.serial= setting on command line.

**Comment by ztutberidze** [comment]
Thank you very mouch lurch and popcornmix. I will use this command in c interface.
Some how I couldn't find the documentation about gencmd available commands before.

**Comment by popcornmix** [comment]
```
$ vcgencmd commands
```
will list the supported commands. Most are documented here:
http://elinux.org/RPI_vcgencmd_usage

**Comment by ztutberidze** [comment]
Thank you again

**Comment by popcornmix** [comment]
Okay to close?

**Comment by ztutberidze** [comment]
OK
