### ISSUE TITLE
D-Link DWA-131 not working with latest kernel

### ISSUE THREAD

**Issue by jolny** [raspberrypi/firmware#359]
D-Link DWA-131 works fine before apt-get update/upgrade to the new kernel.
Afterwards, however, it stops working.
Tested with an old Model B with older software and worked fine.

**Comment by taher-mosbah** [comment]
see discussion 
https://github.com/raspberrypi/linux/issues/755

Apparently the problem is fixed but we have to wait for next release, or is there anyway to do it manually ?

**Comment by jolny** [comment]
Thanks for the info! There are descriptions on how to do it manually in that thread. Maybe update && upgrade would fix it already. Otherwise, wait for new image. Closing thread :)
