### ISSUE TITLE
problem powering on HDMI

### ISSUE THREAD

**Issue by ztutberidze** [raspberrypi/firmware#368]
When I power off HDMI with tvservice -o and then I power on with tvservice -p. My tv set "samsung smarttv ue46es7500s" automatically turns on 3D mode. Is this problem comming from firmware? or there is any option to disable 3D?

**Comment by popcornmix** [comment]
What does "tvservice -s" say when TV is showing 3d mode?

**Comment by ztutberidze** [comment]
state 0x12001a [HDMI CEA (16) RGB lim 16:9], 1920x1080 @ 60.00Hz, progressive

**Comment by popcornmix** [comment]
That suggests we are not outputting 3D signalling (it would show "3D SbS" if we were).
You could try adding "hdmi_ignore_edid_3d=1" to config.txt which will ignore any 3d capabilities of the TV, but I suspect that won't help.

**Comment by ztutberidze** [comment]
I think the problem is in tvservice -o, because when I ask raspberry to switch off the HDMI, the tv detects HDMI power off letter, but if I check tvservice -s the result is state 0x120002 [TV is off], but tv is showing that the device is connected. 

So... If I power on HDMI imediatelly before tvset detects HDMI off, then I am getting 3D mode enabled.

**Comment by ztutberidze** [comment]
hdmi_ignore_edid_3d=1 has no effect.

**Comment by popcornmix** [comment]
I don't believe this is due to any signalling we are doing.
I suspect the TV has an automatic 3D detection going on (e.g. comparing left and right sides of image) which is falsely triggering.

When you do:
```
fbset -depth 8 && fbset -depth 16
```
So the console reappears, what does the TV do?

**Comment by ztutberidze** [comment]
it does nothing.

**Comment by ztutberidze** [comment]
the delay between issuing tvservice -o and tvset detects there is no signal is about 10 sec. is it normal?

**Comment by popcornmix** [comment]
I'm sure we stop outputting immediately after "tvservice -o".
It's up to the display how long it takes to detect this.

I'm suspect the 3D detection is a TV issue rather than a Pi issue -
I'd need to see evidence that other makes of TV behave the same way to make me believe this is a Pi issue.

If any users have a 3D TV connected to their Pi, can they run:
```tvservice -o && tvservice -p```
and report if the TV switches to a 3D mode.

**Comment by ztutberidze** [comment]
I will check it on another 3D tvset at home.

**Comment by ztutberidze** [comment]
I have inserted this code
        property2.property = HDMI_PROPERTY_3D_STRUCTURE;
        property2.param1 = HDMI_3D_FORMAT_NONE;
        property2.param2 = 0;
everything is ok.

**Comment by popcornmix** [comment]
Where did you insert those lines?

**Comment by ztutberidze** [comment]
I made little program to switchon the HDMI and before call the function vc_tv_hdmi_power_on_explicit_new()  I inserted it.

**Comment by popcornmix** [comment]
Could you confirm if this version of tvservice works okay for you:
https://dl.dropboxusercontent.com/u/3669512/temp/tvservice

**Comment by ztutberidze** [comment]
I can't run program you provide, I get the signal
Illegal instruction

**Comment by popcornmix** [comment]
Ah - that was a Pi2 build. Can you try downloading again?

**Comment by ztutberidze** [comment]
it's working thanks

**Comment by popcornmix** [comment]
That version should be in latest rpi-update version.

**Comment by ztutberidze** [comment]
Thank you again.
