### ISSUE TITLE
IP address no more assigned after "service networking restart"

### ISSUE THREAD

**Issue by iz8mbw** [raspberrypi/firmware#370]
My Raspberry Pi has a static IP (on eth0) correctly assigned into /etc/network/interfaces file.
If I change the IP into /etc/network/interfaces (in my case with an IP part of the same subnet) and then I execute "service networking restart" the Raspberry Pi will be not more reachable because there is not more an IP assigned on eth0.
Before "lost" the IP, this msg appears "Running /etc/init.d/networking restart is deprecated because it may not re-enable some interfaces".
Why this issue?

**Comment by PureGrap** [comment]
put on top of the script : auto eth0
/etc/init.d/networking restart

This worked for me

**Comment by Ruffio** [comment]
Can this issue be closed?

**Comment by Ruffio** [comment]
@iz8mbw Can this issue be closed?

**Comment by iz8mbw** [comment]
Ok

Sent from Gmail on Android
Il 24/giu/2015 14:41, "Rasmus Christiansen" <notifications@github.com> ha
scritto:
