### ISSUE TITLE
RPI2 multiple openmax pipelines block temperature sensor and more

### ISSUE THREAD

**Issue by xlazom00** [raspberrypi/firmware#373]
When I start 4 instances of /opt/vc/src/hello_pi/hello_encode
with 
while true
do
    ./hello_encode.bin /dev/null 2>&1 > /dev/null
done

/opt/vc/bin/vcgencmd measure_temp
return:
vc_gencmd_send returned -1
vchi_msg_dequeue -> -1(22)

**Comment by popcornmix** [comment]
Yes, the gencmd service is limited to 4 concurrent clients, and hello_encode calls bcm_host_init() which does start the gencmd service.

**Comment by Ruffio** [comment]
@popcornmix it looks like it is working as designed and the issue can be closed.
