### ISSUE TITLE
Broken detection of HDMI modes

### ISSUE THREAD

**Issue by kirgene** [raspberrypi/firmware#376]
Seems that rev. https://github.com/raspberrypi/firmware/commit/f15c3b5e4018b974de30d95d3173b1e936f66bd7 broke detection of HDMI modes when I plug cable after boot.
Running `tvservice -m CEA` and `tvservice -m DMT` gives me correct modes on rev. https://github.com/raspberrypi/firmware/commit/02eed2f817b42590180270dd0059a9e97cf2ced3 but on https://github.com/raspberrypi/firmware/commit/f15c3b5e4018b974de30d95d3173b1e936f66bd7 (next rev.) I see very few and incorrect HDMI modes.

Here is output of `vcgencmd get_config int`
hdmi_force_hotplug=1
disable_overscan=1
ramfsaddr=0xd00000
program_serial_random=1
config_hdmi_boost=2
emmc_pll_core=1
hdmi_force_cec_address=65535
disable_splash=1
temp_limit=85
force_pwm_open=1
pause_burst_frames=1
avoid_fix_ts=1

**Comment by popcornmix** [comment]
I'm not sure which repo the ``f15c3b5`` and ``02eed2f`` refer to.
Can you use rpi-update hashes (From https://github.com/Hexxeh/rpi-firmware/commits/master)
or (complete) output of "vc_gencmd version"

**Comment by kirgene** [comment]
It's
https://github.com/raspberrypi/firmware/commit/f15c3b5e4018b974de30d95d3173b1e936f66bd7
and
https://github.com/raspberrypi/firmware/commit/02eed2f817b42590180270dd0059a9e97cf2ced3

**Comment by popcornmix** [comment]
hdmi cable should be plugged in before boot.
edid reading is only triggered by a hotplug change event, and yiour hdmi_force_hotplug=1 masks that.
Try this: http://kodi.wiki/view/Raspberry_Pi_FAQ#TV_is_not_detected_unless_powered_on_first
if you want a fixed edid without the display being available on boot.

**Comment by Ruffio** [comment]
@kirgene @popcornmix can this be closed?
