### ISSUE TITLE
No console output/bootup on Bitrig anymore

### ISSUE THREAD

**Issue by Bluerise** [raspberrypi/firmware#381]
Hi,

I'm porting the Bitrig operating system to the raspberry pi and have bootup issues since cc47954caf69dbf60bcd8d2580029469e70bc77b.

In the commit before, I get proper serial/console output. Since that commit, updated by copying start\*.elf and fixup\*.dat, I do not get any output anymore.

Did something special change about the console in that commit? What has changed in the firmware?

**Comment by popcornmix** [comment]
Are you using initramfs? If so try test firmware here:
https://github.com/raspberrypi/firmware/issues/374

**Comment by Bluerise** [comment]
Yes. Exactly! I had the issue that I can't load my fully blown kernel to kernel_address 0x00300000 directly. Apparently it's too big to be put there like that.

Instead I have a tiny program loaded as kernel to 0x8000 and the actual kernel loaded as initramfs. The tiny program just jumps to 0x00300000.

Your posted firmware makes it work again.

**Comment by popcornmix** [comment]
Can you confirm latest rpi-update firmware fixes the issue.

**Comment by Bluerise** [comment]
Works well for me, closing the issue, thanks!
