### ISSUE TITLE
Raspberry Pi 2 USB disconnect

### ISSUE THREAD

**Issue by Saudumm** [raspberrypi/firmware#395]
Every time I connect a USB soundcard to my Raspberry Pi 2 Model B, the USB controller disconnects after a random time, if sound is played via the USB soundcard. Also, you can hear a popping noise every now and then from the speakers when sound is played. Raspbian continues to run, except for every USB device or the Ethernet port.
I found dozens of threads for "Failed to read reg index 0x00000114" but they all are a year old and there the problem got fixed in April 2014 with a firmware update. Maybe this has something to do with the USB controller on the Raspberry Pi 2 specifically?

- The problem does not occur when I connect the speakers directly to the headphone jack and disconnect the sound card.
- The sound card is connected to a powered USB-Hub (but problem does also occur if i connect it directly to the Pi)
- Raspberry receives enough power (constantly 5V)
- Doesn't matter if a WiFi Stick or Ethernet cable is connected.
- Tested two different USB-soundcards that are confirmed working (one from adafruit and a Creative Play sound card)

I'm at a loss here. Headphone jack is working fine, but sound isn't that good.

I uploaded the interesting part of the syslog to pastebin: http://pastebin.com/yn4PUUwm

**Comment by popcornmix** [comment]
Can you create this here:
https://github.com/raspberrypi/linux/
as it is a linux kernel rather than gpu firmware issue.
