### ISSUE TITLE
UART ttyUSB0 not shown ArchLinux

### ISSUE THREAD

**Issue by roblad** [raspberrypi/firmware#399]
Hi,

After upgrade there is issue, FT232 not shown as /dev/ttyUSB0.
lsusb shows:

Bus 001 Device 004: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
there is some error in:

linux-raspberrypi
from 3.18.7-8
to 3.18.9-2
raspberrypi-firmware-bootloader
from 20150221-1
to 20150316-1
raspberrypi-firmware-bootloader-x
from 20150221-1
to 20150316-1
raspberrypi-firmware-tools
from 20150221-1
to 20150316-1

**Comment by popcornmix** [comment]
Arch uses its own kernel which we can't support.
Can you confirm if you see the same issue with raspbian?

**Comment by roblad** [comment]
No

on Raspbian there is no error

Regs,
Robert

2015-03-22 15:54 GMT+01:00 popcornmix <notifications@github.com>:

**Comment by popcornmix** [comment]
You'll need to report this to Arch.

**Comment by roblad** [comment]
Hi,

Have you got link to issue problem for them ?

Regs,


2015-03-22 16:51 GMT+01:00 popcornmix <notifications@github.com>:

**Comment by popcornmix** [comment]
Posting here: http://www.raspberrypi.org/forums/viewforum.php?f=53
would be a good place to start.

**Comment by roblad** [comment]
Hi,

I found workaround 

sudo /usr/sbin/rmmod ftdi_sio
sleep 2
sudo /usr/sbin/modprobe ftdi_sio vendor=0x0403 product=0x6001
