### ISSUE TITLE
RPi2, HAT with overlay in EEPROM

### ISSUE THREAD

**Issue by andrejst** [raspberrypi/firmware#410]
Is loading overlays from HAT's EEPROM supported on RPi2? I am experiencing problems with a HAT which works with RPi B+, but when connected to RPi2 the overlay is not loaded from EEPROM.

**Comment by pelwell** [comment]
The firmware in the current Raspbian image (due to be updated soon) doesn't support HAT's on Pi 2, but if you run `sudo rpi-update` you will get a new firmware that fixes that.

**Comment by andrejst** [comment]
Thanks, I can confirm that it works with my HAT too.
