### ISSUE TITLE
mistake in new firmware readme for lirc gpio module

### ISSUE THREAD

**Issue by crazy-george** [raspberrypi/firmware#412]
hi, in this write up to the firmware

https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README

for lirc it says 

    dtoverlay=lirc-rpi

This causes the file /boot/overlays/lirc-rpi-overlay.dtb to be loaded. By
default it will use pins 17 (out) and 18 (in), but this can be modified using
DT parameters:

    dtoverlay=lirc-rpi,gpio_out_pin=17,gpio_in_pin=13

whereas lirc defaults to GPIO 17 and 18 ( Pins 11 and 12 )  

So i think it should say pins 11 and 12  ( and maybe gpio 17 and 18 ) to be clear

Sorry if am wrong, am a newbie of sorts

**Comment by popcornmix** [comment]
I think we generally use the gpio numbers rather than pin numbers, so I'd think making it clear it is gpio 17 and gpio 18 would be useful.
@pelwell ?

**Comment by pelwell** [comment]
When creating overlays I have tried to replicate the existing module parameter names, to minimise the amount of new stuff people have to learn. We could change the README to say GPIOs rather than pins, but I'm reluctant to change the parameter names.

**Comment by popcornmix** [comment]
Yes, just changing the README to make it clear it is GPIO numbers not pin number would help.

**Comment by pelwell** [comment]
See https://github.com/raspberrypi/firmware/commit/25b436de03dd15d199efeaa2b303d728422b4748

**Comment by pelwell** [comment]
OK to close this?

**Comment by Ruffio** [comment]
@crazy-george is this still an issue? Please close it if it has been resolved. Thanks.
