### ISSUE TITLE
initramfs followkernel not working

### ISSUE THREAD

**Issue by fabled** [raspberrypi/firmware#413]
I built 3.18.11 kernel with Device Tree enabled. The kernel does not find initramfs when using followkernel option, but if specifying address manually everything works. Same happens with rpi1 and rpi2 kernels. Apparently the address calculated by followkernel is invalid in some cases.

**Comment by Ruffio** [comment]
@fabled Can this issue be closed? 3.18.11 is a long time ago. Do you still have this issue?

**Comment by fabled** [comment]
Seems to work with 4.4.y.
