### ISSUE TITLE
#780 stops a USB hard drive root filesystem from mounting.

### ISSUE THREAD

**Issue by DougieLawson** [raspberrypi/firmware#415]
This is a recurrence of closed issue https://github.com/raspberrypi/firmware/issues/374

I've had to revert my B+ with a USB HDD to 3.18.9 to get the USB HDD running again.

**Comment by popcornmix** [comment]
Latest firmware update won't have caused this (it was a very minor change to deinterlace). Can you confirm the exact firmware update that causes the problem?

i.e. ```sudo rpi-update <hash>``` and find the first hash that is broken from https://github.com/Hexxeh/rpi-firmware/commits/master

**Comment by DougieLawson** [comment]
I've rebuilt my SDCard (from a working backup), re-run rpi-update and I can't recreate the error.
