### ISSUE TITLE
trouble updating with rpi-update

### ISSUE THREAD

**Issue by mrpetrov** [raspberrypi/firmware#416]
~ $ date
Tue Apr 21 23:30:32 EEST 2015
 ~ $ sudo rpi-update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
curl: (7) Failed to connect to 199.27.75.133: Network is unreachable
 !!! Failed to download update for rpi-update!
 !!! Make sure you have ca-certificates installed and that the time is set correctly

Possible github issues?

**Comment by popcornmix** [comment]
If you run:
```curl  https://raw.githubusercontent.com/Hexxeh/rpi-update/master/rpi-update```
what does it do?

**Comment by mrpetrov** [comment]
I've had trouble on my end - rpi-update works fine after I lost some time searching for the problem, found it and fixed it.
Sorry for the noise...
