### ISSUE TITLE
HDMI mode switching breaks EGL

### ISSUE THREAD

**Issue by wm4** [raspberrypi/firmware#421]
Run any EGL application, use `tvservice` to change the video mode, the screen becomes black. EGL applications can't recover. It doesn't appear to raise an EGL_CONTEXT_LOST error either.

**Comment by popcornmix** [comment]
This is expected behaviour. Any dispmanx layers will be lost when changing HDMI mode. The host code needs to destroy and recreate dispmanx layers (which includes EGL) when changing HDMI mode.

**Comment by wm4** [comment]
Seriously? And you're supposed to register a tv service callback to detect this, or what?

Sometimes I wonder if this device was engineered to generate pain...

**Comment by popcornmix** [comment]
Who is calling tvservice to change hdmi mode?
What do you expect to happen with your 1920x1080 overlay when someone switches to VGA mode?

**Comment by wm4** [comment]
>Who is calling tvservice to change hdmi mode?

The user? Apparently it also happens when the HDMI cable is replugged, but I didn't retest it just now.

> What do you expect to happen with your 1920x1080 overlay when someone switches to VGA mode?

Something reasonable? Like clipping it, or at least doing something standard. And not do something completely unusual that breaks the architecture of everything.

**Comment by popcornmix** [comment]
No, unplugging hdmi doesn't cause this behaviour.
You would need to run tvservice to set the HDMI mode (or use the tvservice API explicitly).

**Comment by julianscheel** [comment]
@popcornmix Is it possible to rebind the eGL context to a new dispmanx layer without recreating the whole context? I think this would help to support dispman reconfiguration in stuff like Qt5, which currently requires applications to be restarted after mode changes.

**Comment by popcornmix** [comment]
The context contains a reference to display which presumably will have changed (potentially to something with a different resolution), so I imagine that is not going to work.
Anything that calls eglGetCurrentDisplay:
https://github.com/raspberrypi/userland/blob/master/interface/khronos/egl/egl_client.c#L2140 
is likely to get confused.

**Comment by Ruffio** [comment]
@wm4 can this issue be closed?

**Comment by wm4** [comment]
There is no indication that this has been fixed, if you mean that.

**Comment by JamesH65** [comment]
Closing as a wont fix. The amount of work to change the current behaviour is not cost effective, given this is something that is rarely done.

**Comment by popcornmix** [comment]
Also the arm side GL driver is where we are heading and that won't have this specific issue.
(I haven't checked its behaviour but it won't be using the same code as the firmware display/gl driver).

**Comment by sirus20x6** [comment]
what about using tv service to turn a monitor off and then back on again? I don't care if the context is unusable while the monitor is off, but when it comes back on hdmi should be in the same mode as before.

**Comment by popcornmix** [comment]
Use ``vcgencmd display_power 0`` to turn off display and ``vcgencmd display_power 1`` to turn it back on again. This doesn't tear down the list of displayed elements like using the tvservice so may behave as you desire.
