### ISSUE TITLE
Typo:  bmp085_i2s ->  bmp085_i2c

### ISSUE THREAD

**Issue by 0xFACE** [raspberrypi/firmware#431]
https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README#L158
-File:   bmp085_i2s-sensor-overlay.dtb
+File:   bmp085_i2c-sensor-overlay.dtb

https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README#L161
-Load:   dtoverlay=bmp085_i2s-sensor
+Load:   dtoverlay=bmp085_i2c-sensor

**Comment by popcornmix** [comment]
ping @pelwell

**Comment by pelwell** [comment]
Fixed.

Thanks.
