### ISSUE TITLE
Binaries in hardfp/opt/vc/lib do not have hard-float flag in elf header

### ISSUE THREAD

**Issue by rogerjames99** [raspberrypi/firmware#436]
The binaries in the hardfp/opt/vc/lib directory do not have the hard-float flag set in the ELF header. This means that later versions of the ld.so loader will not find them via the ldconfig cache even though they appear to be in there. This may also apply to other parts of the hardfp tree, but I have not checked. Can someone with access check in a rebuild with the correct flags set.

**Comment by popcornmix** [comment]
Can you explain exactly how you are detecting this and what you think should be done differently to fix this? The libraries are built with ``-mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard`` so you'll have to be more specific about what is being requested.

**Comment by rogerjames99** [comment]
On 09/06/15 12:52, popcornmix wrote:
>
> Can you explain exactly how you are detecting this and what you think 
> should be done differently to fix this? The libraries are built with 
> |-mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard| so you'll have to be 
> more specific about what is being requested.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/raspberrypi/firmware/issues/436#issuecomment-110330076>.
>
Mea culpa,

I just rechecked and realised I had used the files from the wrong part 
of the tree. Please kill this issue.

The adafruit pitft install kills the /opt/vc part of the tree and I had 
used the wrong files to replace it. Loads of strange missing so file 
errors! Took a while to twig as the ldconfig cache looked like the files 
where present. Maybe I should suggest to the loader guys that they put 
out a warning if a file is ignored due to wrong flags.

Sorry,

Roger
