### ISSUE TITLE
No more /proc/config.gz?

### ISSUE THREAD

**Issue by jorti** [raspberrypi/firmware#442]
I'm trying to find the config file of the 4.0.5 kernel, but it looks like it isn't available anymore in /proc/config.gz

Is it available somewhere?

**Comment by popcornmix** [comment]
It is now built as a module to save some RAM. Try this first:
``sudo modprobe configs``

**Comment by jorti** [comment]
Fantastic. Than you.

**Comment by krummrey** [comment]
modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.26-v7+/modules.dep.bin'

Any way to get around this?

**Comment by popcornmix** [comment]
@krummrey working here:
```
pi@domnfs:~ $ sudo modprobe configs
pi@domnfs:~ $ zcat /proc/config.gz |grep SND_BCM2835
CONFIG_SND_BCM2835=m
CONFIG_SND_BCM2835_SOC_I2S=m
```
I can only assume you have something corrupt in your install.
Are you running raspbian jessie? Are you up to date (``sudo apt-get update && sudo apt-get dist-upgrade``)? What does ``uname -a`` report?

**Comment by Marietto2008** [comment]
root@DESKTOP-N9UN2H3-WLS2:/usr/src/4.19.43-microsoft-standard# sudo cp /proc/config.gz config.gz
cp: cannot stat '/proc/config.gz': No such file or directory

**Comment by Marietto2008** [comment]
root@DESKTOP-N9UN2H3:/usr/src/4.19.43-microsoft-standard# sudo modprobe configs
modprobe: FATAL: Module configs not found in directory /lib/modules/4.4.0-19041-Microsoft

**Comment by pelwell** [comment]
It doesn't look like you are using a Raspberry Pi, so you shouldn't be posting here.

**Comment by Marietto2008** [comment]
linux works the same everywhere....

**Comment by JamesH65** [comment]
> the basic working of linux is the same everywhere....

True, but this isn't "the basic workings of linux" as its dependant on the configuration of the kernel build. Which is mostly defined by whatever distribution it is using. So, no, thing is not something we are going to answer, because we cannot answer it.

More to the point, why should we provide technical support to people who are not using our product?

**Comment by pelwell** [comment]
Just Google "Linux config.gz".

**Comment by deomaximo** [comment]
> It is now built as a module to save some RAM. Try this first:
> `sudo modprobe configs`
> 
> (or add `configs` to /etc/modules if you always want it available).

Thank you so much!!
