### ISSUE TITLE
missing /proc/config.gz (or D/L of config file used?)

### ISSUE THREAD

**Issue by steffenkremser** [raspberrypi/firmware#447]
i've been using rpi-update on gentoo with great success, but (absent kernel sources -  including a matching .config) many system packets rely on /proc/config.gz to detect avaiable kernel features. ditto for rebuilding the kernel from sources ...

Unfortunately, the latest build does not include /proc/config.gz anymore. 
(firmware_revision=19debdef5d132a12bf8df73d5e77e607066c8757) 

Could we get the proc entry back?

**Comment by XECDesign** [comment]
It's compiled as a module now.
```sudo modprobe configs```
