### ISSUE TITLE
Is .config available for 4.0.7 build?

### ISSUE THREAD

**Issue by ha5di** [raspberrypi/firmware#448]
Hi

is kernel config file .config available for current 4.0.7 build? There is no /proc/config.gz as it was in 3.x releases and do not find in GITHUB.

Thanks... Béla

**Comment by Terminus-IMRC** [comment]
See issue https://github.com/raspberrypi/firmware/issues/447.
/proc/config.gz is now compiled as a module and can be seen by doing ```sudo modprobe configs```.

**Comment by ha5di** [comment]
Thanks, it works.
