### ISSUE TITLE
Can the boot process be made more ARM-centric

### ISSUE THREAD

**Issue by swarren** [raspberrypi/firmware#45]
The BCM2835 boot process at present is very roughly:

* Boot ROM executes on the VC, loads various pieces of SW into RAM, and runs them on the VC.

* Code on the VC loads kernel/... from SD card into RAM, and starts the ARM processor, thus executing the kernel.

* The code on the VC continues to run, and the kernel communicates with it.

Is it possible to invert this process to something more ARM-centric and typical:

* Boot ROM executes on the VC, loads a blob into RAM that contains (a) absolutely minimal SW required to power on and boot the ARM, and (b) and ARM-based bootloader. Nothing else is set up on the VC. The VC goes completely idle once the ARM is started.

* The ARM-based bootloader (e.g. U-Boot) loads the kernel from SD card (or network or wherever), and jumps to it.

* The Linux kernel contains a driver which loads the VC firmware into RAM, and causes the VC to execute it.

This has the following advantages:

* The binary blob the boot ROM loads contains extremely minimal code just to boot the ARM with the concatenated ARM-based boot-loader. As such, all the device tree setup (or whatever else was needed) to boot the Linux kernel (or whatever other OS) would be in a standard ARM-based (and open-source) bootloader, rather than in something that the general community can't easily modify. Moving this code out of the binary bootloader would reduce duplication when people do unexpected things like using U-Boot instead of directly booting a kernel.

* Before the kernel loads any firmware and causes the VC to execute it, it is in complete control of the system (and in particular RAM), so issues such as reducing the memory size the kernel is aware of (or reserving regions of RAM) based on the particular VC firmware used to boot the system, are eliminated. Related to this, it'd be nice if the VC binary blob could be reworked so that Linux was the master and the VC the slave for memory partitioning; VC code determines this at runtime based on a message from ARM rather than at compile-time for example. Perhaps with Linux in charge, the VC wouldn't even need a single contiguous chunk of RAM, but could use arbitrary pages?

* It puts the kernel completely in charge, which is always a good thing. It's much more similar to how any other device that Linux interacts with and contains firmware works.

This would likely mean opening up a lot more documentation though, e.g. Linux (and/or a bootloader such as U-Boot) would have to gain code to directly control the power controller rather than sending messages to the VC to do so on its behalf, and some amount of information would be needed on how to get the VC to execute the downloaded firmware. Without knowledge of what the VC is doing today, it's hard to say what else might have to open up. Perhaps the VC MMU would need to be programmed by the ARM before sending the firmware for example?

**Comment by Ruffio** [comment]
@popcornmix this issue is rather old, so I guess that the progress has stopped? Should it be closed?

**Comment by swarren** [comment]
Closing this for now. I expect this won't happen at this late stage. I've also heard hints during the kernel upstreaming process that parts of the SoC register set simply can't be accessed from the ARM CPU so this request can't entirely be implemented anyway.
