### ISSUE TITLE
YUV firmware change. 

### ISSUE THREAD

**Issue by tvjon** [raspberrypi/firmware#451]
Since updating today, the "hello_video" & derivatives will no longer display any h264 files. The files still play fine in omxplayer

**Comment by popcornmix** [comment]
Yes, I have a fix for this - will push later today.

**Comment by popcornmix** [comment]
Pushed. Run rpi-update and test please.

**Comment by tvjon** [comment]
Well, I can now play *.h264 via, for example, "hello_video", thank you, BUT; your "hello_video_simple" application (no clock or scheduler components) will not play any h264's. BTW, although you posted back that the array subscript error was fixed, I've checked back a few times, & your files are still dated Dec 2014, so maybe your fix didn't make it to Github?

I've just booted from a month old backup, & hello_video_simple.c built plays fine in that "old" firmware.

**Comment by popcornmix** [comment]
Could you test this firmware:
https://dl.dropboxusercontent.com/u/3669512/temp/firmware_150724.zip

unzip into boot directory of sdcard

**Comment by tvjon** [comment]
Initial tests suggest those files have enabled decoding & playback again, thank you, & thank you for the hello_video_ simple file change.

**Comment by popcornmix** [comment]
This fix should be in latest rpi-update firmware

**Comment by popcornmix** [comment]
There was another update today that could affect this.
Please test and close if okay.

**Comment by tvjon** [comment]
Yes, seems fine, thank you.
