### ISSUE TITLE
Servoblaster on Kernel 4.1 does not work

### ISSUE THREAD

**Issue by AFUDIrk** [raspberrypi/firmware#467]
Have with my Raspberry Pi 2 B the new kernel, now the servos no longer work in conjunction with the servo Blaster.
In Kenel 4.0.8-v7 it still functioned.

**Comment by pelwell** [comment]
As joan has [already told you](https://www.raspberrypi.org/forums/viewtopic.php?p=807065#p807065), ServoBlaster will need to be updated to work with 4.1. I suggest you [contact the author](https://github.com/richardghirst/PiBits/issues).
