### ISSUE TITLE
AppArmor support

### ISSUE THREAD

**Issue by diekmann** [raspberrypi/firmware#468]
Does the pre-built kernel image support AppArmor? It seems that raspbian ships it per default but the kernel does not support it.

**Comment by popcornmix** [comment]
Raspbian includes the whole debian repo, which includes 43000 packages. Many of which don't make sense on all platforms.

A quick look shows these (and possibly other) kernel options are required:
```
CONFIG_SECURITY_APPARMOR
CONFIG_SECURITY
CONFIG_AUDIT
CONIG_SECURITY_PATH
CONFIG_SECURITYFS
SECURITY_NETWORK
```
Generally these options do add overhead to the kernel, and are wanted by a very small percentage of users. As such building a custom kernel may be the best option.

But this is the wrong place for this. The linux repo would be the correct place if you want to pursue this. However without evidence of a large number of user wanting this, and evidence that it doesn't have a performance impact on the existing kernel, it's unlikely these options will be added.
