### ISSUE TITLE
libkmod: ERROR. Pointing to previous kernel.

### ISSUE THREAD

**Issue by Fourdee** [raspberrypi/firmware#474]
Hi,

Ran rpi-update. It upgraded to 4.1.7.
Removed the previous kernels (4.1.6).

No sound, libkmod pointing to previous kernel.
> root@dietpi:/#  modprobe snd_bcm2835
libkmod: ERROR ../libkmod/libkmod.c:554 kmod_search_moddep: could not open moddep file '/lib/modules/4.1.6-v7+/modules.dep.bin'
root@dietpi:/# ls -lha /lib/modules/
total 16K
drwxr-xr-x  4 root root 4.0K Sep 18 12:34 .
drwxr-xr-x 13 root root 4.0K Sep 18 12:21 ..
drwxr-xr-x  3 root root 4.0K Sep 18 12:25 4.1.7+
drwxr-xr-x  3 root root 4.0K Sep 18 12:25 4.1.7-v7+

Clearly, running the following fixes the issue:
> cp -R /lib/modules/4.1.7+ /lib/modules/4.1.6+
cp -R /lib/modules/4.1.7-v7+ /lib/modules/4.1.6-v7+
modprobe snd_bcm2835

Also posted to rpi-update Git: https://github.com/Hexxeh/rpi-update/issues/192

**Comment by popcornmix** [comment]
I'll close this as it's definitely not a firmware issue (it could be a linux issue, but no evidence of that yet).
We'll carry on in the other report.
