### ISSUE TITLE
mmal: error_concealment after seek/discontinuity

### ISSUE THREAD

**Issue by julianscheel** [raspberrypi/firmware#485]
Is it somehow possibe to force the mmal decoder into waiting for the next valid frame as it is done on startup when error_concealment is enabled later on? Ie when a discontinuity appeared or a seek was done?

**Comment by popcornmix** [comment]
You should be flushing video_decode on a seek. That should put it into "waiting for IDR" mode, and concealing frames before there.

**Comment by julianscheel** [comment]
Ah, thanks, my bad. I did flush, but at that point error_concealment was actually disabled to workaround https://github.com/raspberrypi/firmware/issues/375
