### ISSUE TITLE
mmal: Safe to rely on MMAL_EVENT_FORMAT_CHANGED

### ISSUE THREAD

**Issue by julianscheel** [raspberrypi/firmware#489]
Can we be sure that at least one MMAL_EVENT_FORMAT_CHANGED will appear when starting to decode a frame? Or can it happen under some circumstances that the decoder starts to output data without having sent a format changed event?

**Comment by 6by9** [comment]
The code isn't the clearest, but appears that it should unconditionally send an MMAL_EVENT_FORMAT_CHANGED event having either decoded the header bytes, or got the first image out. It then also monitors the images produced and produces another event should the resolution ever vary.
There does appear to be slightly odd code that if you set format crop.width/height on the input port, those get reflected to the output port, but no event is generated, but I don't think that is a situation that is generally worried about.

**Comment by julianscheel** [comment]
@6by9 Thanks for clarification

**Comment by Ruffio** [comment]
@julianscheel can this issue be closed now?

**Comment by julianscheel** [comment]
Yes, thanks.
