### ISSUE TITLE
 cec device know longer detected with LCD screen 

### ISSUE THREAD

**Issue by pssc** [raspberrypi/firmware#495]
root@screenpi:/home/pi# /opt/squeezeplay/bin/libcec-daemon -l -v
INFO - Opened /dev/uinput
INFO - Created uinput device
ERROR - No adapters found
root@screenpi:/home/pi# uname -a
Linux screenpi 4.1.12-v7+ #824 SMP PREEMPT Wed Oct 28 16:46:35 GMT 2015 armv7l GNU/Linux
root@screenpi:/home/pi# 

This worked when I first got the screen going with simultaneous HDMI output (audio still working)

**Comment by popcornmix** [comment]
Do are you saying this worked with an earlier firmware version? If so can you identify the version that stopped it working?
(using rpi-update <hash> with the hash from https://github.com/Hexxeh/rpi-firmware/commits/master)

**Comment by pssc** [comment]
Couldn't  find one that worked chopped through to September, however I can not confirm that even with display_default_lcd=0, I cant get cec working, confirmed it still works with the B on my desk.

**Comment by popcornmix** [comment]
Does unplugging the LCD make CEC work?

**Comment by pssc** [comment]
No... which probably means libcec library issues...

**Comment by popcornmix** [comment]
You say the B works? I assume that's with a different TV? Does swapping the Pi's over change anything? Has the non-working TV ever worked? Might be worth a full power cycle of TV (unplug from mains for a while) - they often seem to retain stale information about a CEC client which stops it working.

**Comment by pssc** [comment]
no same TV swapped the HDMI cable to the B

**Comment by popcornmix** [comment]
Are you running raspbian? Same versions or is Pi2 newer?
Can you swap sdcards between the two Pi's?

**Comment by pssc** [comment]
@popcornmix confirmed as a libcec2 issue not all versions of libcec2 are the same libcec2 >= 2.2.0 was needed on jessie(2.1.4) to make the tool report the inbuilt adaptor static linking to libcec2 wasn’t enough either, sorry about the wild goose chase.

**Comment by popcornmix** [comment]
So is this sorted? Okay to close?
