### ISSUE TITLE
/proc/config.gz: No such file or directory

### ISSUE THREAD

**Issue by iz8mbw** [raspberrypi/firmware#509]
Hi.
The file /proc/config.gz is not there.
What I do:

cd /usr/src
wget https://github.com/raspberrypi/linux/archive/rpi-4.1.y.tar.gz
tar xvfz rpi-4.1.y.tar.gz
ln -s /usr/src/linux-rpi-4.1.y /lib/modules/4.1.13+/build
cd /lib/modules/4.1.13+/build
make mrproper
sudo gzip -dc /proc/config.gz > .config

root@raspberrypi:/lib/modules/4.1.13+/build# sudo gzip -dc /proc/config.gz > .config
gzip: /proc/config.gz: No such file or directory

**Comment by pelwell** [comment]
This is an FAQ: https://github.com/raspberrypi/firmware/issues/442

**Comment by iz8mbw** [comment]
Thanks!
