### ISSUE TITLE
Repeating problems with wireless connection

### ISSUE THREAD

**Issue by ThomasKorimort** [raspberrypi/firmware#511]
Hi! I use Edimax WLAN adapter for my RPi2B, wich was recommended by multiple magazines on RPi to be a nicely compatible WLAN stick for Rapsbian resp. Linux on RPI2. It uses RTL8188CUS driver which is included in Debian and seems to work together with wpa-supplicant to be used in WLAN network of 802.11 n type. However, connection speeds are far below what is posible. In the same WLAN network i have multiple Windows 8/10 and Android devices, which can use my ADSL 8 MBit line nicely and it is possible to watch 2-3 video streams at the same time without problem. However, connection seems to be very slow for my RPi2B with Edimax, for sure much slower than n standard although driver says it is using n standard. Another problem is, that my RPi2B disconnects from WLAN regularly and needs to be rebooted for being accessible again via SSH or any other way. Obviously wpa-supplicant does not do its job correctly or something is wrong with the WLAN driver. I have observed, that recently there was an update of wpa-supplicant package in the Debian Jessie distro in Raspbian. Even after updating the problem of disconnection and slow connection speeds remained, despite all other network devices running at acceptable speeds.

So, what could be the problem? I even bought one new router with multiple antenna and high connection speeds in order to solve slow internet connectivity with my ADSL router. Although now signal strength is much better, still my RPi2 is very slow with WLAN, although some improvement of connection and ssh access speed was notified by using a new WLAN router and a new ADSL router.

I suspect there is either a problem with the kernel drivers for WLAN in Debian for RPi platform (ARM HF) or with wpa-suplicant. Given the problems with connection speed i would suspect that it is the WLAN driver, which slows down internet/WLAN traffic speed. Who would be willing to investigate the problem?

Many greetings, Thomas Korimort.

**Comment by popcornmix** [comment]
The issue won't be firmware related so this isn't the right place to report.
I'd suggest posting in the [forum](https://www.raspberrypi.org/forums/index.php) to begin with.
If there is evidence of a kernel issue then [the linux repo](https://github.com/raspberrypi/linux/issues) would be the right place, but the forum is the right place to start.
