### ISSUE TITLE
Raspi Freeze on FW 4.1.15- v7+ #830

### ISSUE THREAD

**Issue by Phelonas** [raspberrypi/firmware#517]
I experienced a Raspi Freeze after a couple of hours. I had the command "top" running too see which process causes it, and it was RTW_CMD_THREAD with 100% CPU and a Time Value of 310. I suggest  the rtw command is connected to the wifi drivers. I'm using an Edimax EW-7811UN dongle. Messages shows this 

[messages.txt](https://github.com/raspberrypi/firmware/files/66339/messages.txt)

Error accured somewhere around Dec 17 19:17:10

**Comment by popcornmix** [comment]
More likely a kernel than a firmware issue so best to open here where the right people are more likely to see: https://github.com/raspberrypi/linux/issues

But without more information there's not much we can do (I don't see any errors in log).
If you can reproduce the problem on demand, and explain exactly what commands you run to provoke it then we might get somewhere.
