### ISSUE TITLE
Broken #include statements in /opt/vc/include

### ISSUE THREAD

**Issue by fordfrog** [raspberrypi/firmware#562]
while trying to compile kodi on rpi 2, i've encountered many errors related to #include files not being found. looking at the source it seems some include files were move around but the paths were not adjusted. these are the correct paths for current code:

#include "interface/vcos/pthreads/vcos_platform_types.h"
#include "interface/vcos/pthreads/vcos_platform.h"
#include "interface/vmcs_host/linux/vchost_config.h"

**Comment by Ruffio** [comment]
@fordfrog how about submitting a PR for this?

**Comment by popcornmix** [comment]
Not sure this is still an issue after https://github.com/raspberrypi/userland/pull/298

**Comment by Ruffio** [comment]
@fordfrog can you please upgrade and confirm if your issue has been resolved? Thanks.

**Comment by fordfrog** [comment]
@Ruffio i do not have rpi with gentoo anymore so unfortunately i cannot test it.

**Comment by Ruffio** [comment]
@fordfrog since you you are the only one with this issue for 6 months, I suggest that you close this issue. Thanks.
