### ISSUE TITLE
edidparser: Add more fields

### ISSUE THREAD

**Issue by Terminus-IMRC** [raspberrypi/firmware#566]
opt/vc/bin/edidparser doesn't print some EDID fields such as ID Manufacturer Name, Year of Manufacture and so on. Please add them.

In addition, I want to know why edidparser isn't open-sourced.

**Comment by JamesH65** [comment]
There is the edid-decode app in the repo which does what you require.

edidparser has some parts in it that we are unable to open source (not ours), hence the app itself is not open source.
