### ISSUE TITLE
ALSA Still Wonky After Update

### ISSUE THREAD

**Issue by ratherDashing** [raspberrypi/firmware#57]
ALSA works better now after the update but pianobar on raspbian still stutters even under no load (30%).

Using screen I got it to crash just by switching from bash:0 to bash:1 with this output to dmesg

[  675.740026] vcos: [3020]: bcm2835_audio_close:702 bcm2835_audio_close: failed on waiting for event (status=10)

**Comment by Ruffio** [comment]
Is this still an issue?

**Comment by popcornmix** [comment]
Closing as believed to be fixed. Reopen if still an issue.
