### ISSUE TITLE
MMAL renderer represents ARGB alpha black instead of transparent

### ISSUE THREAD

**Issue by zillevdr** [raspberrypi/firmware#581]
I will render a OSD as ARGB. The transparent part of the picture is black. The layer behind is'nt visible. 

format->encoding = MMAL_ENCODING_ARGB;

is set. What can I do to that the renderer use the alpha value from picture?

**Comment by 6by9** [comment]
Currently nothing. It really supports XRGB, but there isn't a format for that. It only supports a global alpha.
I did look briefly at supporting ARGB with per pixel alpha, but never completed it. I'll see if I can find time to resurrect it.

You can use the DispmanX API directly to support ARGB - that's all that MMAL video_render is wrapping with some buffer management.

**Comment by zillevdr** [comment]
OK, thank you!

**Comment by Ruffio** [comment]
@zillevdr can this be closed?

**Comment by zillevdr** [comment]
I think yes. Now I use DispmanX API.
