### ISSUE TITLE
README does not state where source code can be found

### ISSUE THREAD

**Issue by rebroad** [raspberrypi/firmware#583]
The current README file explains that this repository stores the pre compiled binaries. Could it be amended to include where to find the source code also?

**Comment by 6by9** [comment]
The firmware is closed source. You aren't going to find source code or the required tools to build custom versions.

**Comment by rebroad** [comment]
Ah, ok. Well, it could mention that then.

**Comment by cleverca22** [comment]
and name which parts are open-source and where (the kernel, modules, userland libs)

**Comment by lurch** [comment]
It was a long time ago, but I wrote some details in https://github.com/raspberrypi/documentation/pull/153#issuecomment-71926226

**Comment by Ruffio** [comment]
@rebroad can this issue be closed?

**Comment by Ruffio** [comment]
@popcornmix as firmware is close source, therefore the soruce code can't be found anywhere, so this 'issue' should be closed.
