### ISSUE TITLE
CONFIG_BTRFS=y instead of CONFIG_BTRFS=m

### ISSUE THREAD

**Issue by dsx724** [raspberrypi/firmware#596]
Enable built-in support for BTRFS roots please. Checksumming, compression, and copy-on-write can greatly reduce the problems users encounter with MicroSD cards.

**Comment by txt-file** [comment]
I would also love to use btrfs as root file system. Especially on small and/or slow SD cards the compression is very useful.

**Comment by grigorig** [comment]
BTRFS would massively bloat the kernel image and is still considered unstable. After my requests to include IPv6 in the kernel image were turned down, a feature that is roughly 30% of the size of BTRFS, I don't think this is going to happen and not particularly useful either.

**Comment by popcornmix** [comment]
Agreed.
