### ISSUE TITLE
raspberry pi 3 do not boot?

### ISSUE THREAD

**Issue by mllapps** [raspberrypi/firmware#598]
Hy, I am trying to boot raspberry pi 3 with the releases from 2016-03-15 but it doesn't work. Can someone help me? Whats the correct git version?

**Comment by mllapps** [comment]
I found a solution.

https://github.com/raspberrypi/firmware/commit/951799bbcd795ddf27769d14acf4813fdcbe53dc

**Comment by popcornmix** [comment]
By the way there is a newer raspbian release which hopefully works directly for you:
https://www.raspberrypi.org/blog/another-update-raspbian/

**Comment by mllapps** [comment]
Oh thanks. :-)
