### ISSUE TITLE
Add OES_depth_texture

### ISSUE THREAD

**Issue by loganmc10** [raspberrypi/firmware#610]
You can feel free to close this if it is impossible.

It would be so nice if the Raspberry Pi supported OES_depth_texture

https://www.khronos.org/registry/gles/extensions/OES/OES_depth_texture.txt

Most mobile phones (including the iPhone and any Android device I've heard of) supports this extension, and it is difficult to get some GLES applications to work because the Raspberry Pi doesn't support it

**Comment by popcornmix** [comment]
This won't happen with the closed source driver.
We no longer have access to the devs who wrote this driver, so nothing more than trivial fixes are really possible.
Work is active on the arm-side open source driver. See [here](https://www.raspberrypi.org/blog/another-new-raspbian-release). You should test if the extension is supported there. If not it could be requested here: https://github.com/anholt/linux/issues
