### ISSUE TITLE
hello-teapot drawing with no textures

### ISSUE THREAD

**Issue by atic-atac** [raspberrypi/firmware#612]
Running the latest firmware as of today, and trying the hello-teapot demo.

It seems on some occasions when trying to execute this demo, the textures fail to operate, but no errors are returned in the program.

Any clues ?

**Comment by popcornmix** [comment]
What do you have gpu_mem set to? Does it help to increase it (e.g. to 128M).

**Comment by atic-atac** [comment]
already set gpu_mem=512

**Comment by atic-atac** [comment]
it looks like port settings changed for port 221 (egl_render output) never gets triggered

**Comment by popcornmix** [comment]
So from boot, does it always work the first time?
If you keep running/stopping it how often does it fail?

**Comment by atic-atac** [comment]
It's pretty sporadic, but it looks like it does work first time.

**Comment by atic-atac** [comment]
second time usually fails

**Comment by atic-atac** [comment]
in fact, after the first time, you are pretty lucky for it to work again.

**Comment by popcornmix** [comment]
It's worked ten times in a row for me.

Did it work reliably with an older firmware?

What does:
```
vcgencmd version
vcgencmd get_config int
uname -a
```

**Comment by atic-atac** [comment]
# vcgencmd version
Jun  8 2016 16:08:27 
Copyright (c) 2012 Broadcom
version 1c8638223821fe0ed16e20bd8e948b6cc037fa4a (clean) (release)

**Comment by atic-atac** [comment]
# vcgencmd get_config int
arm_freq=900
audio_pwm_mode=1
config_hdmi_boost=5
disable_commandline_tags=2
disable_l2cache=1
disable_splash=1
enable_uart=1
force_eeprom_read=1
force_pwm_open=1
framebuffer_depth=32
framebuffer_ignore_alpha=1
framebuffer_swap=1
hdmi_force_cec_address=65535
hdmi_group=2
hdmi_mode=82
init_uart_clock=0x2dc6c0
lcd_framerate=60
over_voltage_avs=0x1b774
pause_burst_frames=1
program_serial_random=1
sdram_freq=450
second_boot=1
temp_limit=85

**Comment by atic-atac** [comment]
# uname -a
Linux raspberrypi 4.4.13-v7+ #893 SMP Wed Jun 8 14:39:18 BST 2016 armv7l GNU/Linux

**Comment by popcornmix** [comment]
It's working for me (with same kernel/firmware).
Has it worked for you reliably with a older firmware version?
Does it fail with a clean raspbian install?

**Comment by atic-atac** [comment]
I can't say I tried with earlier firmware.

I'd have to take some time to install a clean install though.

**Comment by popcornmix** [comment]
You can try:
```
vcgencmd set_logging level=0xc0
/opt/vc/src/hello_pi/hello_teapot/hello_teapot.bin
sudo vcdbg log msg
```
which gets some gpu side logging out. Any obvious difference in log between good and bad run?

**Comment by atic-atac** [comment]
there's a lot of stuff in there, not sure exactly what I'm looking for.

**Comment by popcornmix** [comment]
Run a diff would be my suggestion. Or use a paste site and post links to them.

**Comment by atic-atac** [comment]
yeah, but it seems as though the threading shows some different behaviour when fill/empty happens so there's some bits in the diff that would need skipping over.

**Comment by Ruffio** [comment]
@atic-atac has this been resolved or would you link to at paste site?

**Comment by atic-atac** [comment]
Not sure why it doesn't work with teapot, but my application works fine. So close it.
