### ISSUE TITLE
Request: API for checking whether power supply is sufficient or not

### ISSUE THREAD

**Issue by Terminus-IMRC** [raspberrypi/firmware#614]
I request for an API (vcgencmd, mailbox or whatever) which checks whether power supply is sufficient or not.

Currently, if power supply is not enough, a small rainbow indicator appears at the top-right of HDMI output. However, plugging HDMI may result in power insufficient (My HDMI-to-VGA converter consumes electricity a lot). So I want to check power supply sufficiency without a display.

Could you add such API?

**Comment by popcornmix** [comment]
Try ``vcgencmd get_throttled``
See [here](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=147781&start=50#p972790) for interpretation.

**Comment by Terminus-IMRC** [comment]
Very sorry for my lack of searching...
