### ISSUE TITLE
Wifi issue

### ISSUE THREAD

**Issue by YasinGS** [raspberrypi/firmware#618]
Hi everybody, 
I have issue with my Raspberry pi 3.. I have wifi but we can't manage monitor because it is internal card then i buy a wifi dongle but I don't know how to setup my raspberry pi 3. I look for in web but all tutorials is for raspberry pi 2 ou raspberry pi 
If you know how to setup the raspberry pi 3 for usb dongle for manage monitor 
Thanks

**Comment by Ruffio** [comment]
@YasinGS this is not a 'how to site', but only used for issues/bugs. Please use the Forum for 'how to': https://www.raspberrypi.org/forums/

**Comment by Ruffio** [comment]
@popcornmix please close this 'question'. Thanks
