### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by Thymo-** [raspberrypi/firmware#626]
"./boot: start*.elf, fixup*.dat, bootcode.bin are the GPU firmware and bootloaders.
  Their licence is described in 'LICENCE.broadcom'. The kernel*.img and *.dtb"

LICENSE is spelled as 'LICENCE'.

The file name in question has the same spelling error.

**Comment by pelwell** [comment]
http://www.oxforddictionaries.com/definition/english/licence

**Comment by Thymo-** [comment]
Didn't realize the British version was spelled that way.

My apologies.
