### ISSUE TITLE
Please provide Kernel headers required to build modules with the firmware

### ISSUE THREAD

**Issue by ssprabhu** [raspberrypi/firmware#63]
Please provide the kernel headers required to build modules along with the firmware files. 

I had to compile a module for the wifi usb dongle and ended up building the kernel so that I could use the resulting Module.symvers to build my module. I will need to do this everytime I use the latest firmware from the git repo. Having the kernel headers which includes Module.symvers will make this much easier for people like me who need to compile a separate module.

**Comment by nh2** [comment]
Is there any update on the? I can't build modules because

```
make[1]: *** /lib/modules/3.12.35+/build: No such file or directory.  Stop.
```

**Comment by layerzerolabs** [comment]
Yeah - I'm still struggling to compile kernel modules - and then when I do, I have remember to postpone updates that bring in a new kernel. Why can't the foundation re-jig of raspian include headers? 

Why is this issue still open after over two years!!!? I can't believe it's that difficult to fix, so there must be an explanation that isn't being made public - what can this be? It doesn't sit well with the open-source ethos, keeping the headers obscure, does it?

And yes, I'm sure if I spent a couple of days learning the deep intricacies of kernel trees and so on I could probably do it for myself. But that isn't what the Pi is all about, is it? What about people who just want to make something that involves non-standard hardware?

I've found that doing:
    sudo aptitude install -y linux-image-rpi2-rpfv linux-headers-rpi2-rpfv
    echo -e "kernel=vmlinuz-3.18.0-trunk-rpi2\ninitramfs initrd.img-3.18.0-trunk-rpi followkernel" | sudo tee -a /boot/config.txt
gets me an older kernel with headers - hope this helps others waiting for this issue to be fixed, or at least waiting for an answer as to why it can't be fixed.

**Comment by pelwell** [comment]
I'm new to this issue (and relatively new to RPi as well), but it strikes me that having the kernel headers in two places for the sake of convenience is a bad idea. How do you guarantee to request the correct .deb headers package for your kernel? How do we ensure that the packages are kept up-to-date? It also doesn't help people who rpi-update.

Isn't better to use the *completely public* github raspberrypi/linux repo, having first ascertained the relevant branch and commit for your kernel?

**Comment by Ferroin** [comment]
This issue is still open because people don't find the source tree to be an acceptable alternative to a headers package.

Also, the Pi isn't intended to just make everything easy for people, it is designed first and foremost as a tool for education, and if everything just gets handed to you, you will never learn anything.

It really is rather simple to get the headers out of the __public__ source tree for the kernel, though apparently some people can't figure it out, so here's the procedure:
1. On the Pi, use git to clone the source repository:
    ```git clone --depth=1 git://github.com/raspberrypi/linux.git rpi-linux```
2. Switch to whichever branch corresponds to your kernel version:
   ```git checkout rpi-3.18.y```
   ```git checkout rpi-3.12.y```
   etc.
3. From the kernel source tree, configure the kernel:
   ```make bcmrpi_defconfig```
4. Install the kernel headers:
   ```make prepare headers_install```
5. Build external modules, pointing them at the kernel source directory you cloned earlier.
6. To update:
   ```git pull && make clean bcmrpi_defconfig prepare headers_install```
   and then rebuild the external modules.

**Comment by Ruffio** [comment]
@ssprabhu can this be closed?

**Comment by ssprabhu** [comment]
Yes. It can be closed.

**Comment by Ruffio** [comment]
Can't you close it?

**Comment by Shulyaka** [comment]
Still having the same issue
```
root@speaker:~# ls /lib/modules/
5.4.51+  5.4.51-v7+  5.4.51-v7l+  5.4.51-v8+  5.4.58+  5.4.58-v7+  5.4.58-v7l+	5.4.58-v8+
root@speaker:~# find /lib/modules -name build
/lib/modules/5.4.51+/build
/lib/modules/5.4.51-v7l+/build
/lib/modules/5.4.51-v7+/build
root@speaker:~# uname -r
5.4.58-v7l+
root@speaker:~# apt-get update && apt-get install raspberrypi-kernel-headers
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]       
Hit:2 https://dl.yarnpkg.com/debian stable InRelease                                                                       
Hit:4 http://raspbian.raspberrypi.org/raspbian buster InRelease              
Hit:3 https://www.lesbonscomptes.com/upmpdcli/downloads/raspbian buster InRelease
Fetched 32.6 kB in 2s (16.4 kB/s)                      
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
raspberrypi-kernel-headers is already the newest version (1.20200811-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@speaker:~#
```

**Comment by popcornmix** [comment]
Are you running rpi-update kernel? 

apt kernel headers only match the latest apt kernel (which is 5.4.51 currently).

**Comment by Shulyaka** [comment]
Yes, I had issues with USB and hoped that rpi-update would help with that, but I thought 5.4.58 was the latest

**Comment by wandercn** [comment]
sudo apt install raspberrypi-kernel raspberrypi-kernel-headers raspberrypi-bootloader

**Comment by JamesH65** [comment]
That comment is 10 years old and not quite so relevant nowadays.
