### ISSUE TITLE
INFO: Where can I find the .config file?

### ISSUE THREAD

**Issue by renatoriolino** [raspberrypi/firmware#636]
Hi, 

I can't find anywhere the config file used to build kernel.

I'm using the kernel 4.1.19-v7+ (from 20160315) but I need to add aufs to it.  I have already downloaded the source but I'm still missing the .config file used to compile it.

Thanks

**Comment by popcornmix** [comment]
It's in arch/arm/configs/bcm2709_defconfig (for pi2/pi3) or arch/arm/configs/bcmrpi_defconfig (for pi1) 
See: https://www.raspberrypi.org/documentation/linux/kernel/building.md
