### ISSUE TITLE
`disable_pvt` unknown after boot, replacement?

### ISSUE THREAD

**Issue by natevw** [raspberrypi/firmware#640]
I am trying to figure out why rpitx, which does some serious GPIO "bitbanging"-type stuff, is glitching out on my Raspberry Pi 3: https://github.com/F5OEO/rpitx/issues/29

The recommendation for these sorts of things, e.g. see issue #497, is to set `disable_pvt=1` in config.txt. There was a bug with that setting that needed to be fixed, but I'm running the latest NOOBS Raspbian (2016-05-27) from half a year after that same issue was closed, so I'm assuming I have the fix.

What's curious, however, is that even with my text setting in place, `vcgencmd get_config disable_pvt` says the setting is "unknown"! When I tried to research this a bit more I came across https://github.com/raspberrypi/firmware/commit/ac0c0bff7951a39d371a46c4a80a9ec560e33c16 which includes a change "Remove disable_pvt option"!

Am I understanding that commit message correctly? I can't seem to find the actual source change there — perhaps this is still the infamous closed source part of the system? — but it would be great if there were a bit more info on this change.

Is it expected that `disable_pvt=1` will no longer work? Is there a replacement?

**Comment by popcornmix** [comment]
We no longer do the slow part of the PVT that required disabling sdram so the setting is no longer needed.
You shouldn't get periodic pauses caused by the sdram being disabled any more.
Just remove ``disable_pvt=1`` from config.txt (although leaving it there is harmless) and you will be fine.
