### ISSUE TITLE
OMX_EmptyThisBuffer hangs 

### ISSUE THREAD

**Issue by atic-atac** [raspberrypi/firmware#641]
Just opening a new case after looking at issue #449.

It seems I can get the above call to hang when using dispmanx submit() calls, but I can't get it to hang when using submit_sync() calls.

I can try and get to a test case, but maybe there's someone who knows why the above could hang ?

**Comment by atic-atac** [comment]
O.k. I have a theory that there is multiple submit() calls outstanding and some queue gets full.

I can workaround the issue. So closing.

**Comment by atic-atac** [comment]
I'm going to reopen as I suspect it's worth tracking this so I can understand things.

**Comment by popcornmix** [comment]
Well, you'll need to post some test code that shows the problem if you want any feedback.

Make sure you are not calling block GPU calls from GPU callbacks (e.g. dispmanx/openmax) which would be a recipe for deadlocks.

**Comment by atic-atac** [comment]
O.k. I'm not going to have time to follow this up at the moment. Maybe reopen later, but for now closing.
