### ISSUE TITLE
raspberrypi-bootloader should not depend on raspberrypi-kernel

### ISSUE THREAD

**Issue by ali1234** [raspberrypi/firmware#646]
It is perfectly reasonable to use a custom kernel without having raspberrypi-kernel installed. But the dependency does not allow this.

**Comment by popcornmix** [comment]
This is a packaging issue.
Can you report it here: https://github.com/RPi-Distro/repo/

**Comment by ali1234** [comment]
https://github.com/RPi-Distro/repo/issues/40
