### ISSUE TITLE
v.4.4.20 uninitialized urandom read (16 bytes read, 24 bits of entropy available)

### ISSUE THREAD

**Issue by Ruffio** [raspberrypi/firmware#658]
After upgrading to v.4.4.20 I get these messages in dmesg:

pi@raspberrypi:~ $ dmesg | grep random
[    2.040097] random: systemd: uninitialized urandom read (16 bytes read, 24 bits of entropy available)
[    2.302018] random: systemd-sysv-ge: uninitialized urandom read (16 bytes read, 57 bits of entropy available)
[    2.425209] random: systemd: uninitialized urandom read (16 bytes read, 71 bits of entropy available)
[    2.426475] random: systemd: uninitialized urandom read (16 bytes read, 71 bits of entropy available)
[    2.427852] random: systemd: uninitialized urandom read (16 bytes read, 71 bits of entropy available)
[    2.445699] random: systemd: uninitialized urandom read (16 bytes read, 71 bits of entropy available)
[    2.446509] random: systemd: uninitialized urandom read (16 bytes read, 71 bits of entropy available)
[    2.446676] random: systemd: uninitialized urandom read (16 bytes read, 71 bits of entropy available)
[    2.477281] random: systemd: uninitialized urandom read (16 bytes read, 71 bits of entropy available)
[    2.480513] random: systemd: uninitialized urandom read (16 bytes read, 71 bits of entropy available)
[    4.652536] random: nonblocking pool is initialized

I don't recall that I have seen this before. Is that expected?

**Comment by popcornmix** [comment]
I believe this is not new, just the way it is being logged is new. See:
https://patchwork.kernel.org/patch/9173499/

> Since systemd is consistently using /dev/urandom before it is
initialized, we can't see the other potentially dangerous users of
/dev/urandom immediately after boot.  So print the first ten such
complaints instead.

Doesn't seem to be a Pi specific issue. E.g. x86 log with similar messages:
https://repos.fedorapeople.org/repos/thl/kernel-vanilla-mainline/fedora-24/x86_64/dmesg-4.8.0-0.rc0.git6.1.vanilla.knurd.1.fc24.x86_64.log

I've not found if there is a way of avoiding these messages so far.
