### ISSUE TITLE
Where is /modules?

### ISSUE THREAD

**Issue by xJota** [raspberrypi/firmware#660]
Maybe I'm just stupid (highly possible) but after the last commit /modules is gone, or moved elsewhere.

Is this intentional?

**Comment by AndrewFromMelbourne** [comment]
The kernel modules have always been in /lib/modules/...

**Comment by xJota** [comment]
I don't mean that. I mean the pre-built modules that used to exist in this repository.

**Comment by popcornmix** [comment]
You are correct. They are present in rpi-firmware.
Not sure what typo caused them to be misplaced, but that should be restored now.

**Comment by Ruffio** [comment]
@xJota can this be closed now?

**Comment by xJota** [comment]
Yes, I'm so sorry, I completely forgot to reply to this. It's fixed :)

**Comment by Ruffio** [comment]
@xJota then close it ;-(
