### ISSUE TITLE
ARMv8 architected timer

### ISSUE THREAD

**Issue by Klamath233** [raspberrypi/firmware#662]
Hi folks,

It's my first time to post here. Hello to everyone.

I've read that ARMv8 requires architected timers accessible via CNT-prefixed instructions. I wonder if this is supported in the Pi 3 Model B? Is it a free-running timer or derived from GPU timers?

Thanks,
Xi

**Comment by pelwell** [comment]
Please don't cross-post - I see you have a Forum post [here](https://www.raspberrypi.org/forums/viewtopic.php?f=72&t=159858), and this isn't a suitable venue for questions.

**Comment by Klamath233** [comment]
@pelwell Sorry for the inconvenience. I didn't mean to break the rule.
