### ISSUE TITLE
Disable QPU mailbox commands when vc4 is loaded

### ISSUE THREAD

**Issue by anholt** [raspberrypi/firmware#669]
I'm starting work on making it so that you can run `hello_fft` under vc4.  My current thought is to intercept the mailbox commands in the firmware driver and hand them off to vc4 instead.

However, for safety, similarly to the disabling of tvservice's commands, it would be nice if the firmware could disable qpu_enable and qpu_execute mailbox commands when we've found the v3d (without `status="disabled"`) in the devicetree.  Right now if you run `hello_fft`, it locks up the GPU such a way that it never recovers.

**Comment by popcornmix** [comment]
Yes, that should be possible.

**Comment by popcornmix** [comment]
This is in latest rpi-update firmware.

**Comment by Ruffio** [comment]
@anholt have you tested with the 'lastest' firmware? Can this issue be closed?

**Comment by Ruffio** [comment]
@anholt any update on this? Have you tested with a firmware newer than 18 Pct 2016 where it was fixed?

**Comment by popcornmix** [comment]
I'll close as request has been implemented.
Can always be re-opened if there are still issues.
