### ISSUE TITLE
Version Information

### ISSUE THREAD

**Issue by bryankemp** [raspberrypi/firmware#68]
I posted this as an issue for the rpi-update tool, but I think it requires some co-ordination.

"""Would it be possible to show version information (maybe created by raspberry-pi firmware team) of existing a new versions before preceding? This would help to ensure that fixes from the other project are in a particular update."""

**Comment by Ruffio** [comment]
As this issue is closed at rpi-update (https://github.com/Hexxeh/rpi-update/issues/19) I think it should be closed here as well..
