### ISSUE TITLE
The fixup.dat or start.elf or u-boot.bin will cause the serial port output messy.

### ISSUE THREAD

**Issue by latiaoxia** [raspberrypi/firmware#687]
This is about the uart used by BT, on the raspi2 this problem is still there.

**Comment by latiaoxia** [comment]
If I use the old one, the output is right.

**Comment by JamesH65** [comment]
@latiaoxia Is this still an issue or can it be closed?

**Comment by latiaoxia** [comment]
Please close it, thank you.



在 2017年12月21日，23:48，James Hughes <notifications@github.com<mailto:notifications@github.com>> 写道：


@latiaoxia<https://github.com/latiaoxia> Is this still an issue or can it be closed?
