### ISSUE TITLE
not getting any data

### ISSUE THREAD

**Issue by milad6506** [raspberrypi/firmware#693]
dear all
i hope it is the right place to ask this question.
i have a NIREN product for connecting my RPI to the CANBUS network. i added the required items to config.xt but when i enter candump in terminal, i get nothing.
is there anything to add?
for example all the codes i found require libraries such as linux/spi.h or linux/can/platform/mcp2515.h and etc which are not present in my OS include folder.
what can i do about it.?
kernel version 4.4.3
i will be grateful if you can help me with this.

**Comment by pelwell** [comment]
This is not a firmware issue. There are plenty of people in the Raspberry Pi Forums using the MCP2515 - the Interfacing forum is a good place to start (https://www.raspberrypi.org/forums/viewforum.php?f=44).
