### ISSUE TITLE
no wan0 after upgade

### ISSUE THREAD

**Issue by tim3dman** [raspberrypi/firmware#706]
After updating my Raspberry Pi2 from 4.4.34 to 4.4.38 I lose wan0 and am unable to reconfigure?

**Comment by pelwell** [comment]
1. Which distribution are you running?
2. How did you upgrade?
3. What is the output of `dmesg` after booting?
4. Do you mean `wan0` , or is that a typo?

**Comment by tim3dman** [comment]
I'm using jessie lite, I used apt-get upgrade dist I think? not sure about dmesg as I've rolled back to a backed up 4.4.38. By wan0, when I ifconfig I only have lan and loopback but know wifi.

**Comment by popcornmix** [comment]
What is the wifi device?
Output of ``lsusb`` and ``lsmod`` on working and not working systems may be useful.

**Comment by Ruffio** [comment]
@tim3dman what do you day?

**Comment by Ruffio** [comment]
@tim3dman what do you say to @popcornmix commands? Has this issue been resolved?
