### ISSUE TITLE
config.txt: „total_mem“ with invalid value prevent the RPi1 from booting

### ISSUE THREAD

**Issue by herrmeier01** [raspberrypi/firmware#717]
bootloader configuration config.txt

Example 1: (A Pi1 with 512MB Ram will not boot)

[pi1]
total_mem=512

Example 2: (A Pi1 with 512MB Ram will not boot)

[pi1]
total_mem=513

This issues is not reproducible at Pi2 and Pi3!

**Comment by popcornmix** [comment]
We can clamp the total_mem size to the size of the physical sdram which should avoid the issue.

**Comment by herrmeier01** [comment]
Great job! Both issues #716 and #717 are fixed (Pi1 256M and Pi1 512M) and "total_mem" works fine now

Thanks a lot
