### ISSUE TITLE
Question: tagging/release policy for distributions

### ISSUE THREAD

**Issue by dezgeg** [raspberrypi/firmware#737]
Do you have any recommendations on what versions of the firmware & kernel (https://github.com/raspberrypi/linux) downstream distributions should package?
Should they be following latest tags (e.g `1.20161215` currently) or master? What is Raspbian's policy?

**Comment by popcornmix** [comment]
@XECDesign adds the tags when raspbian bumps the firmware/kernel version used in the bootloader packages.
So they should occur at points in time we believe are stable and would probably be a good choice for other distributions to pick from if they don't want the "bleeding edge" versions.

**Comment by dezgeg** [comment]
Okay, that sounds good. Thanks!
