### ISSUE TITLE
latest start_x.elf fixup_x.elf only support mem up to 256MB?

### ISSUE THREAD

**Issue by jeffersonchua** [raspberrypi/firmware#740]
Setting these two parameters in /boot/config.txt caused mem to become 256MB on pi3. It used be 1GB on 4.8.0 ... didn't realized till now ... somewhere after 4.8.0, it became 256MB.

start_file=start_x.elf
fixup_file=fixup_x.elf

Jeff.

**Comment by pelwell** [comment]
Try:
```
start_file=start_x.elf
fixup_file=fixup_x.dat
```
(Note the file extension on the second line)

Better still, delete both lines and replace them with:
```
start_x=1
```

**Comment by jeffersonchua** [comment]
Phil,

> fixup_file=fixup_x.dat

> (Note the file extension on the second line)

Silly me. Sorry, didn't see that!

> Better still, delete both lines and replace them with:

> start_x=1

That worked.

Thank you for spotting the mistake!

Jeff.
