### ISSUE TITLE
Out of the box question about the firmware...

### ISSUE THREAD

**Issue by Electron752** [raspberrypi/firmware#744]
I suspect this is completely out of left field, but I'll ask anyway.

I was wondering why an OPTION doesn't exist to have the firmware turn off after a certain stage in the boot sequence.  I'm thinking of say an application with the compute module that doesn't run Raspbian and doesn't have a video display attached.  In that case the only function of the firmware at that point is frequency scaling, power control, and thermal management.  These seem like functions that could quite easily be run on the arm without the gpu, or possibly even with the gpu turned off or disabled.

Again, I understand why the firmware is absolutely necessary in the case of Raspbian, but I'm talking about alternative distributions without an attached monitor.  And again, this is thinking way outside of the box.

**Comment by popcornmix** [comment]
We have always wanted to produce a minimal open source firmware release that can be built with the reverse engineered tools. This would have no firmware side support for display, video decoder, camera, audio, frequency scaling etc. As such it would be of interest to very few users and so is low priority. But it is something we'd like to do.

The current firmware does constantly do background work. The thermal management is probably most critical. Allow that to be disabled and have people overclocking and hitting temperatures of 150'C would be a concern. We only got agreement from the major distributors (who handle warranty returns) for allowing user overclock based on firmware side safeguards.

The firmware also manages sdram settings. The temperature is read and refresh settings are updated regularly. Under-voltage detection and lowering of clocks is handled on firmware side. Also HDMI hotplug detect and updating edid. The ACT LED is currently handled by the firmware on Pi3.
