### ISSUE TITLE
What is the "noflush" param of execute_qpu mailbox call?

### ISSUE THREAD

**Issue by Terminus-IMRC** [raspberrypi/firmware#747]
What is the "noflush" param of execute_qpu mailbox call? What does it mean?
On some situations with `noflush=1`, our QPU program doesn't sync DMA even if it reads vpm_ld/st_wait at the end of it. Is "noflush" related to DMA?

**Comment by Terminus-IMRC** [comment]
We checked that it is not related to L2 or other caches.

**Comment by popcornmix** [comment]
By default the qpu_execute call does a GPU side L1 and L2 data cache flush before executing the qpu code. If you are happy it is safe not to do this, setting ``noflush=1`` will be a little quicker.

**Comment by Terminus-IMRC** [comment]
Thanks. The cause of our bug may not be here...
