### ISSUE TITLE
RealVNC is broken - tells me it's un-licenced.

### ISSUE THREAD

**Issue by DougieLawson** [raspberrypi/firmware#757]
https://github.com/Hexxeh/rpi-firmware/commit/5eb58b416697071f9187aa85cea23004ca0270f4 breaks RealVNC.

If I revert to https://github.com/Hexxeh/rpi-firmware/commit/52241088c1da59a359110d39c1875cda56496764 it's back working.

I'll try https://github.com/Hexxeh/rpi-firmware/commit/3e1c3e9ba2b948e6023114b9633223363da78679 to see if it's the 4.9 kernel (don't think so) or the firmware (hence why I opened the issue here).

**Comment by DougieLawson** [comment]
It works OK if I revert to https://github.com/Hexxeh/rpi-firmware/commit/3e1c3e9ba2b948e6023114b9633223363da78679

**Comment by sconemad** [comment]
Thanks for reporting this @DougieLawson. I've investigated this and it would appear to be an issue in RealVNC Server. We'll do our best to have a fix for before the 4.9 kernel becomes the default.

**Comment by DougieLawson** [comment]
Thanks.

Give me an alpha or beta test version. I've got 12 out of 14 raspberries running 4.9 kernels that I can test on.

**Comment by dividuum** [comment]
Random throught since I also ran into "problems" with 4.9: Maybe RealVNC checks the Pi serial by reading  `/sys/module/[bcm2708|bcm2709]/parameters/serial`? Those seem to have disappeared with 4.9. So `/proc/cpuinfo` seems to be the best way to get the serial number?

**Comment by DougieLawson** [comment]
@dividuum I've got a 4.9.11-v7+ #971 system and ```sys/module/[bcm2708|bcm2709]/parameters/serial``` doesn't exist on there, but RealVNC is working.

**Comment by sconemad** [comment]
A new version of the realvnc-vnc-server package (version 6.0.2.26367) has just been made available in the repository, which should fix this problem.

**Comment by DougieLawson** [comment]
Thank you - it's working on 4.9.13+ #974 now.

**Comment by Ruffio** [comment]
@DougieLawson so this can be closed now?

**Comment by DougieLawson** [comment]
RealVNC fixed this with an update to their package.
