### ISSUE TITLE
Sync issue in files and folder after reboot

### ISSUE THREAD

**Issue by djrocktarun** [raspberrypi/firmware#774]
I am using RPi 2 and Linux raspberrypi 3.18.7-v7+ #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015 armv7l GNU/Linux.

Actually i am facing this issue since 1 month. Files and folder not able to sync after reboot.

Also sudo sync not helping in that case.

Here what i did

- Do changes in some file or create a new file or folder.

- Then run **sudo sync**

- Then run **sudo reboot**

After restart no changes retain in RPi.

Kindly help me if any one also facing this issue and find the solution.

**Comment by XECDesign** [comment]
If you do the same thing on another computer, do you see the same problem? I had a card which started ignoring writes suddenly. It appeared to work, since the data was cached by the OS, but a reboot or a remount would ensure all the 'written' data was discarded, no matter what computer or OS I used.

**Comment by djrocktarun** [comment]
Yes i tried using with different Raspberry pi 2 as well with the same SD card. Issue still present.

Yes i know the cached data will be discarded after reboot or a remount. But i am not able to understand

- Why any files changes still be in cache for so long period of time ?

- If file changes are in cache, How can i confirm that all data is permanently write to the memory before system restart. Because **sudo sync** is not working in my case

**Comment by XECDesign** [comment]
I would guess since sync only flushes the write buffers, it doesn't give the OS a reason to drop the read cache.

In any case, I think it's a dead card and you will see the same behaviour on a desktop PC or in a camera, It's very unlikely that this is a raspberry pi firmware issue.

**Comment by Ferroin** [comment]
>Why any files changes still be in cache for so long period of time ?

Because there is no reason for the OS to not keep them cached if it has enough room.  If it's active data, it's likely to get used again soon, so there's no point in purging it from the cache if there's room for it.

>If file changes are in cache, How can i confirm that all data is permanently write to the memory before system restart. Because sudo sync is not working in my case

If your hardware is lying about writes completing, then there's not really anything you can do except get better hardware.  You might try checking the card with [f3](https://github.com/AltraMayor/f3), that will tell you whether or not the card has just gone bad, or if it's actually a counterfeit (which can display the same kind of behavior as this after a while), but keep in mind that that need to wipe the card to test it properly with f3.

**Comment by Ferroin** [comment]
Oh, I forgot to mention, the quick way to see for certain if the data is being read from cache and the writes are just getting dropped by the card is to call sync then do:
`echo 2 > /proc/sys/vm/drop_caches`
as root and verify if any files you had changed got reverted as if you had rebooted.

Make sure if you do that that you have almost nothing running, if the SD card is dropping writes, then that will likely cause most things you have running to lose their mind.

**Comment by djrocktarun** [comment]
I tried the steps you suggest above @Ferroin

- Change a file using nano editor

- Then run **sudo sync**

- Then run as superuser  **echo 2 > /proc/sys/vm/drop_caches**

After that i open the file and found no data in file 

file content are look like **@@@@@@@@@@@@@@@@@**

After **sudo reboot** my SD card not able to boot.

When i tried to check the boot logs using FTDI 

the logs stops after this line

Uncompressing Linux... done, booting the kernel.


Any suggestion to avoid this sync issue ?

**Comment by Ferroin** [comment]
It's definitely a hardware issue given what you've said (although I have to admit I didn't expect that to nuke the SD card, that should have just dropped everything from the cache), so the only thing that's going to fix it is getting a new SD card.

**Comment by feherneoh** [comment]
I'm interested in the brand of your SD card. My Samsung Evo card bought with my first Pi does not write any data, and still reports write succes. Samsung eMMC chips in lots of phones I know do exactly the same too. Is it by any chance a Samsung card too?

**Comment by djrocktarun** [comment]
No its not Samsung Sd card. My Sd card is of Strontium class 6 oemid : 0X5446

**Comment by JamesH65** [comment]
@djrocktarun Did a new SD card fix the issue? Is so please close. If not please add any more information.

**Comment by djrocktarun** [comment]
Yes i changed my SD card manufacturer and new firmware version (4.4.5), 
new SD card not showing this issue. 

I am closing this issue, as its like to be an hardware issue not the firmware issue.
