### ISSUE TITLE
Fix for Raspberry Pi 3 [brcmfmac.ko] Error 2

### ISSUE THREAD

**Issue by DarthKeizer** [raspberrypi/firmware#779]
When installing I had the following error during the step:

Go to the patches folder for the bcm43438 chipset: cd patches/bcm43438/7_45_41_26/nexmon/
Compile a patched firmware: make

> BUILDING DRIVER  brcmfmac/brcmfmac.ko (details: log/driver.log)
> make[1]: *** /lib/modules/4.9.17-v7+/build: No such file or directory.  Stop.
> Makefile:41: recipe for target 'brcmfmac.ko' failed
> make: *** [brcmfmac.ko] Error 2

Fixed it by manually copying the content of /lib/modules/4.4.50-v7+/build to /lib/modules/4.9.17-v7+/build

Can anyone make a quick sudo code for me to do this :)?

**Comment by pelwell** [comment]
This repo is for the official Raspberry Pi firmware. Try reporting your issue here: https://github.com/seemoo-lab/nexmon/issues
