### ISSUE TITLE
BCM43438 Firmware location

### ISSUE THREAD

**Issue by YOUN3SS** [raspberrypi/firmware#784]
Hi,

Can someone tell me where is the firmware for 43438 Broadcom chip?
In /lib/firmware/brcm I found only for 43430 (.bin)

Can you also tell me if it uses other generic firmwares (since it is Wi-Fi and Bluetooth), like brcmfmac or brcm80211?

Thank you.

**Comment by pelwell** [comment]
Although the device is the 43438, it identifies itself as 43430 and the firmware is /lib/firmware/brcm/brcmfmac43430-sdio.{bin,txt} .

**Comment by YOUN3SS** [comment]
Thanks for the answer @pelwell.

When I remove these files,  I don't see the error saying that firmware is not loaded.
(dmesg | grep bluetooth)

That's my doubt that Raspbian uses other paths for this chip...
http://youness.net/raspberry-pi/bluetooth-headset-raspberry-pi-3-ad2p-hsp

**Comment by pelwell** [comment]
The Bluetooth firmware is completely separate - that is `/lib/firmware/BCM43430A1.hcd`.

**Comment by YOUN3SS** [comment]
I didn't see this file in Raspbian Jessie by default, is it installed separately also?
Thanks.

**Comment by pelwell** [comment]
What do you mean by "by default"? If you install Raspbian Jessie (even Jessie Lite), that file is there.

**Comment by YOUN3SS** [comment]
Ok I checked in wrong folder.
We can close the issue. Thank you again.
