### ISSUE TITLE
Raspberrypi zero W support

### ISSUE THREAD

**Issue by telphan** [raspberrypi/firmware#785]
The yocto BSP layer for raspberrypi pulls the firmware as a tar archive that gets generated from the tags in the firmware repo. 
Now we are trying to fully support the raspberrypi zero W and we mainly need this commit (https://github.com/raspberrypi/firmware/commit/f5446ba0b3bbd4241bf0ad35a2c9f299f5c447d5).
When are you guys planning on adding this commit to the stable branch and tagging?

**Comment by lurch** [comment]
Does https://github.com/raspberrypi/firmware/tree/1.20170303 not include the required changes? AIUI that's the firmware included in the latest Raspbian release, which AFAIK does fully support the Pi Zero W.
I suspect https://github.com/raspberrypi/firmware/commit/f092ca8e39b137277a63ce4dfb56514e51bdf404 might be the commit of interest?

**Comment by agherzan** [comment]
PIng @telphan

**Comment by Ruffio** [comment]
@telphan what do you say to @lurch question?

**Comment by telphan** [comment]
@lurch Sorry for the late response, I was on a small holiday. It seems like you are right, that is the commit I am looking for. Thank you very much for your help.

**Comment by telphan** [comment]
@lurch Sorry for the late response, I was on a small holiday. It seems like you are right, that is the commit I am looking for. Thank you very much for your help.

**Comment by telphan** [comment]
@lurch Sorry for the late response, I was on a small holiday. It seems like you are right, that is the commit I am looking for. Thank you very much for your help.

**Comment by telphan** [comment]
@lurch Sorry for the late response, I was on a small holiday. It seems like you are right, that is the commit I am looking for. Thank you very much for your help.

**Comment by telphan** [comment]
@lurch Sorry for the late response, I was on a small holiday. It seems like you are right, that is the commit I am looking for. Thank you very much for your help.

**Comment by telphan** [comment]
@lurch Sorry for the late response, I was on a small holiday. It seems like you are right, that is the commit I am looking for. Thank you very much for your help.

**Comment by telphan** [comment]
@lurch Sorry for the late response, I was on a small holiday. It seems like you are right, that is the commit I am looking for. Thank you very much for your help.
