### ISSUE TITLE
USB composite gadget, HID function not working on kernel 4.9

### ISSUE THREAD

**Issue by mame82** [raspberrypi/firmware#786]
Issue already opened for kernel, but I have seen that firmware master is on same kernel. Pending issue is here https://github.com/raspberrypi/linux/issues/1943

**Comment by popcornmix** [comment]
The linux tree is the correct place for this.

**Comment by mame82** [comment]
I see. It was irritated by the fact that current firmware master seems to be based on 4.9.19 because if this non working module will be shipped it will blow functionality of my current Pi [project](https://github.com/mame82/P4wnP1) which heavily relies on HID gadegt support.

Thx for your reply, regards
