### ISSUE TITLE
bootcode:serialnumber type booting Raspberry Pi 2 not exist

### ISSUE THREAD

**Issue by radicspeter** [raspberrypi/firmware#794]
According to https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net.md
i would like to use serial_number in the network booting on Raspberry Pi 2.

But if i make a serialnumber folder in the tftpboot root folder, my raspberry is not try to search its tftpboot\serialnumber\start.elf it's on searching on tftpboot\start.elf.

Following net_mod tutorial it is booting up succesfull but only if i put boot files to root of tftp folder...
Thanks, for any help

![2222](https://cloud.githubusercontent.com/assets/16365492/24801719/a7a8487c-1ba5-11e7-99c6-689fb38f0d7a.PNG)

**Comment by popcornmix** [comment]
Ping @ghollingworth

**Comment by pelwell** [comment]
Do you have any more history than that? I'd want to see from the first DHCP request onwards, and your trace starts much later than that.

**Comment by radicspeter** [comment]
![33333](https://cloud.githubusercontent.com/assets/16365492/24806516/6a5ea64a-1bb5-11e7-9e76-5a528adf1d92.PNG)

**Comment by ghollingworth** [comment]
It's on my list, might have to ask someone else to look at it though!

**Comment by pelwell** [comment]
From what I can see, bootcode.bin always tries to find "<serial>/start.elf" after DHCP and ARP. The only reason it would not is if your bootcode.bin predates that code, which was committed in July last year (I'd have to hunt around to find out which firmware release it first appeared in.

Which firmware are you running? Assuming you haven't tried to mix & match bootcode.bin and start.elf, `strings /boot/start.elf | grep VC_BUILD` should give a sensible answer.

**Comment by pelwell** [comment]
Update: So I hunted around, and the bootcode with network booting support hit the next branch Jul 26 2016, then was merged into master Jan 10 2017.

**Comment by amtssp** [comment]
Is it not the same issue as described here: https://github.com/raspberrypi/firmware/issues/754

**Comment by pelwell** [comment]
Thanks for trying. I'm going to be limited in what I can do until next week, but between us we'll make it work.

**Comment by radicspeter** [comment]
Thanks pelwell, i can't wait ;)

**Comment by pelwell** [comment]
Can you download and test [this bootcode.bin](https://drive.google.com/open?id=0B_P-i4u-SLBXcEpRbDhSaVNJQ3c)? It should only alter behaviour in the case where bootcode.bin is present on the SD card and the failover to net booting.

**Comment by radicspeter** [comment]
Thanks, i am going to test today, i have just seen in the #754 that it is working well now... But i will reply ;)

**Comment by popcornmix** [comment]
The fix should be in latest rpi-update firmware

**Comment by radicspeter** [comment]
Okay. now i tested and working good here! Thanks to solved the issue. Ticket closed...
![netboot](https://cloud.githubusercontent.com/assets/16365492/25198277/408ae2f2-2547-11e7-83c1-1782d18fc241.PNG)
