### ISSUE TITLE
PAL-B/G Colorcarrier (4.43 MHz) randomly lost since 4.9.14 

### ISSUE THREAD

**Issue by Quantomax** [raspberrypi/firmware#795]
Since commit b30461d2621e71eb9b8845b38738af177b9181ed (bump to Kernel 4.9.14) I mostly get b/w video on a PAL-B/G TV (Germany, 4.43 MHz) via Video-Out, interchanged with only some seconds "color" every now and than on a Pi2. Going back to d8803bc3b369b087450e636beb0cb30857e3215e resolves the issue. 

Boot is colored, until use of TVService in vdr start-script:
/usr/bin/tvservice -o
/usr/bin/tvservice -c "PAL 4:3"

Config.txt:
disable_overscan=0
overscan_scale=1
hdmi_drive=2
sdtv_mode=2
sdtv_aspect=1
sdtv_disable_colourburst=0
gpu_mem_1024=256

**Comment by popcornmix** [comment]
There were a couple of changes in that firmware. I'll try reverting one. Can you test:
https://drive.google.com/uc?id=0B-6zmEDJwxZEbnljcWdZUUpWZTA&export=download
and let me know if it is good/bad?

**Comment by Quantomax** [comment]
Updated Firmware, copied files above to /boot, rebooted and seems to work ... 
Thanks. ;-)

**Comment by popcornmix** [comment]
Thanks.

@ghollingworth This is due to "Set up HDMI VCO same for VEC as for HDMI".

**Comment by popcornmix** [comment]
Can you test again with latest rpi-update firmware?

**Comment by Quantomax** [comment]
Firmware / Kernel 4.9.23 works colourized as expected on PAL-B/G TV. Thanks for the fix.
