### ISSUE TITLE
#758 - How to confirm same issue?

### ISSUE THREAD

**Issue by nicksoph** [raspberrypi/firmware#797]
Hi, purchased a PiZero W a few weeks ago and only just started trying to use it. Using the latest full standard image, (full download twice onto 2 SD cards - same symptoms which are; The bluetooth Icon shows but there are only two grey bars with 2 red crosses where the wifi icon should be, clicking that produces an error message that 'No wireless interfaces found'. What do I need to do to test this is a fault with the board and not something that can be fixed by reprogramming at this end?

vcgencmd and cpuinfo details below -

sudo vcgencmd
08:00000000
09:00000000
10:00000000
11:00000000
12:00000000
13:00000000
14:00000000
15:00000000
16:24280000
17:1020000a
18:1020000a
19:ffffffff
20:ffffffff
21:ffffffff
22:ffffffff
23:ffffffff
24:ffffffff
25:ffffffff
26:ffffffff
27:00005050
28:6a3da2f0
29:95c25d0f
30:009000c1
31:00000000
32:00000000
33:00000000
34:00000000
35:00000000
36:00000000
37:00000000
38:00000000
39:00000000
40:00000000
41:00000000
42:00000000
43:00000000
44:00000000
45:00000000
46:00000000
47:00000000
48:00000000
49:00000000
50:00000000
51:00000000
52:00000000
53:00000000
54:00000000
55:00000000
56:00000000
57:00000000
58:00000000
59:00000000
60:00000000
61:00000000
62:00000000
63:00000000
64:00000000
65:00000000
66:00000000

 /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 997.08
Features	: half thumb fastmult vfp edsp java tls
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2708
Revision	: 90000c1
Serial	: 000000006a3da2f0

**Comment by pelwell** [comment]
Open a terminal window and type:
```
grep Revision /proc/cpuinfo
```
What does it say?

**Comment by nicksoph** [comment]
Hi - see edit

**Comment by nicksoph** [comment]
Copied from terminal window 
Might be harder to find as plain text but error msgs in red on screen  
re brcmfmac at 
8.59... 
8.9.... 
11.42 ...
11.642...
14.8...


.

[dmesg.txt](https://github.com/raspberrypi/firmware/files/919096/dmesg.txt)

**Comment by nicksoph** [comment]
Hi Phil, I think this is fixable from this end -  just managed to get the wifi adaptor to show.

**Comment by pelwell** [comment]
Cool - I was failing to see anything wrong. Can I ask what you've done?

**Comment by nicksoph** [comment]
Installed 10.4.17 Jessie full from rp org on sd card and noticed fault as described above. (rinsed and repeated) same issue. Reported fault here and posted info as shown. Followed advice on Rpi org forum suggesting the following - Removed SD card from Zero W and into RPi 3. Ran - sudo apt-get update & sudo apt-get upgrade. Didnt take a proper note of what was updated but 'update' seemed to install only some language files and 'upgrade' one small file (19kb?). Shutdown Rpi3 and rebooted the zero W with the updated sd card. Wireless network adaptor was now there and scanning. 

Went through the process again - freshly installed image onto card placed into zero W - network adaptor there! Nothing else physically changed - same kb/mouse/power supplies/cables.

Compared old and new vcgencmd & /proc/cpuinfo - exactly the same.
Attached new dmesg output- which to my untrained eye seems the same.
[dmesg2.txt](https://github.com/raspberrypi/firmware/files/919477/dmesg2.txt)

Thank you for your help.
