### ISSUE TITLE
Pi zero W appears in the wrong config.txt filter

### ISSUE THREAD

**Issue by dp111** [raspberrypi/firmware#799]
Still testing but it appears the Pizero W appears in the pi1 filter and not pi0. Suggested fix either add a pi0w filter or move it to the pi0 filter.

**Comment by pelwell** [comment]
Yes, you are correct. Can you rpi-update to the latest version, then copy [this firmware](https://drive.google.com/file/d/0B_P-i4u-SLBXUlhVWnlESC1ubFU/view?usp=sharing) (start*.elf, fixup*.dat and bootcode.bin) into /boot and try again? You should find that the "[pi0]" section as used on a Zero W.

**Comment by popcornmix** [comment]
Can you test latest rpi-udpate firmware?

**Comment by dp111** [comment]
I'm sorry, I don't have a Pi Zero W to test with.

**Comment by pelwell** [comment]
I'll close this issue then.
