### ISSUE TITLE
Official RPi2 Touchscreen does not shows when using "vc4-kms-v3d" but HDMI works.

### ISSUE THREAD

**Issue by TheAifam5** [raspberrypi/firmware#812]
Hey,
Yesterday and today i had a lot of problems with that dtoverlay. I have Raspbery Pi 2 and official RPi2 Touchscreen 7" on ArchLinux based OS - B.E.N.J.A.
When I use "vc4-kms-v3d", XOrg sees the display but does not rendering - its black but everything works when i connect display to the HDMI port and shows only on HDMI. I didnt tested other outputs. XOrg doesn't reporting any issues.
But when i use "vc4-**f**kms-v3d" everything works fine but i heard that is **experimental** actually.
Also i see that resolution is 2px smaller 799x479 (should be 800x480).

Want also inform that older version (4.7 or 4.9 of kernel and firmware from 2016 - contains iso from B.E.N.J.A project) works but after system update doesnt work anymore.

More info here: https://github.com/WebReflection/benja/issues/13

Regards,
Mateusz.

**Comment by popcornmix** [comment]
The vc4-kms-v3d doesn't use the firmware for display.
Issues with vc4-kms-v3d should be reported here: https://github.com/anholt/linux/issues/

**Comment by WebReflection** [comment]
I can confirm, using `vc4-fkms-v3d` fixed the issue out of the box.

This can be closed.

**Comment by xaviergmail** [comment]
I still suffer from this and unfortunately fake kms gives Kivy a really tough time, where as kms doesn't. Are there any known workarounds?
