### ISSUE TITLE
MMAL camera image overlay Example?

### ISSUE THREAD

**Issue by AlexanderShniperson** [raspberrypi/firmware#832]
Hi,
can some one make an example of creation overlay image over camera preview, like it does in [Python Picamera](https://github.com/waveform80/picamera)?
p.s. it is hard to understand Python source code

**Comment by 6by9** [comment]
userland issue, not firmware.

Overlay over preview (not recording it) is just creating a MMAL video_render component, setting the display rectangle and layer (```MMAL_PARAMETER_DISPLAYREGION```) appropriately, and sending it a buffer with your image in it.

**Comment by AlexanderShniperson** [comment]
thanks for reply, will open it at userland
the general problem is: i am from Java world, so i don't exactly understand what you mean, i need simple solution

**Comment by 6by9** [comment]
https://github.com/raspberrypi/userland/issues/405
Please close this issue.
