### ISSUE TITLE
dispmanx stability / apparent 64 element limit

### ISSUE THREAD

**Issue by hermanhermitage** [raspberrypi/firmware#84]
Observed:
- I call vc_dispmanx_element_add() to add layers. 
- I add 'n' (more than 64) layers and each call apparently succeeds. (Return value is ok, not sure how many elements appear on the screen).
- On removing the layers or quitting the process, it seems like 'n'-64 layers remain.
- Dispmanx becomes unstable and eventually the display shuts down.

Latest firmware and foundation raspbian image.

Expected:
- Return code of 0 if vc_dispmanx_element_add() has hit a limit and no more elements can be added; OR
- All elements are added and removed ok and dispmanx remains stable.

**Comment by Ruffio** [comment]
@hermanhermitage is this still an issue?

**Comment by hermanhermitage** [comment]
Good question.  I will have to dust off my test program and try it again and then close the issue!

**Comment by Ruffio** [comment]
@hermanhermitage have you had the time to test it?

**Comment by Ruffio** [comment]
@popcornmix this issue seems to be stalled...

**Comment by popcornmix** [comment]
Closing. Feel free to reopen if you have time for more testing.
