### ISSUE TITLE
Watchdog package has several flaws after updates

### ISSUE THREAD

**Issue by paulvee** [raspberrypi/firmware#847]
The watchdog package does not allow a persistent installation across a reboot using the systemV way of doing things in Jessie Lite (2016-03-18) anymore. The installation messages of the package shown on the console are confusing and do not point to solutions. The only way to get it working across a reboot now is to use rc.local or cron. That is a kludge at best, so what is the correct installation procedure now.

Trying to install watchdog the systemd way is also not working. Although the systemd service files for watchdog and wd_keepalive are installed, they do not work without changes and there are no pointers offered to lead to a proper installation.

I wrote a post on the Raspberri Pi forum that details the problems with the messages and the installation issues.

https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=147501&p=973710#

**Comment by XECDesign** [comment]
Doesn't looks like there is anything wrong on the firmware or kernel level, so this should probably be closed.
Addressed here: https://github.com/RPi-Distro/repo/issues/74
