### ISSUE TITLE
Bluetooth causes ticks noise on analog sound output(jack)

### ISSUE THREAD

**Issue by ShFil119** [raspberrypi/firmware#852]
It looks like old, but still alive bug.
https://www.raspberrypi.org/forums/viewtopic.php?f=38&t=30669

**Comment by P33M** [comment]
What model of Raspberry Pi are you using where this issue is exhibited?

**Comment by ShFil119** [comment]
It's Rpi 3 with Raspian lite. It's working as sound server in lan network. For this purpose I use pulseaudio pulseaudio-module-zeroconf and avahi-daemon.

**Comment by ShFil119** [comment]
It's Raspberry 3 with raspbian lite. It's working as sound server in lan network. For this purpose I use pulseaudio pulseaudio-module-zeroconf and avahi-daemon.

**Comment by P33M** [comment]
So the onboard Bluetooth, correct? What peripherals are paired via Bluetooth - if you unpair them, does the problem go away completely - i.e. with Bluetooth active but not used is the audio disruption not present?

**Comment by ShFil119** [comment]
I haven't been using rpi's bluetooth. 
Raspbian has default default enabled bluetooth service and after disabling it, problem gone.

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
