### ISSUE TITLE
16bpp issue?

### ISSUE THREAD

**Issue by rosery** [raspberrypi/firmware#86]
Hi. the 16bpp mode that pi does .. is it 555, or 565, and if 565, can we get it to 555? also does the R<->B swap work on it too?

(RISCOS 16 bit is:  top bit opaque, 5bits B, 5 bits G, least significant 5 bits R. it would be useful to be able to get that mode)

Thanks
John

**Comment by Ruffio** [comment]
@rosery is this still an issue or can it be closed?

**Comment by rosery** [comment]
thanks
