### ISSUE TITLE
raspberry pi 0 enc28j60 driver start but eth0 is not enable

### ISSUE THREAD

**Issue by mrclemds** [raspberrypi/firmware#872]
I followed many tutorial on how to add a ethernet port to the raspberry pi 0 with the enc28j60 module i've buy but when i plug a cable no led light up until i unplug/replug vvc or ground pin from the module and then it's detected by the other device but the raspberry pi itself does nothing.
Sorry for my english ...

ifconfig :
![image](https://user-images.githubusercontent.com/5255256/30294889-03f5dd14-973f-11e7-8716-2f65631148bd.png)

lsmod :
![image](https://user-images.githubusercontent.com/5255256/30294915-1a9c2d34-973f-11e7-8d99-6d82b601338f.png)

dmesg :
![image](https://user-images.githubusercontent.com/5255256/30295534-38c6f2ec-9741-11e7-956d-35d22418da20.png)

**Comment by fedorovvl** [comment]
you tried command "ifconfig eth0 up"?

**Comment by mrclemds** [comment]
Nop i was thinking "ifup eth0" is the same.
what's the difference with "ifup eth" ?
I find that's the /etc/network/interfaces file who cause this because it was empty.
Thank you for the help.
