### ISSUE TITLE
Export cached RSTS value via MBOX interface

### ISSUE THREAD

**Issue by steelman** [raspberrypi/firmware#877]
u-boot will greatly benefit from knowledge of RSTS value because it can take different route to boot a device depending on reboot reason and reboot partition (although that is already "consumed"). u-boot has implemented MBOX interface. Unfortunately RSTS isn't exported via this interface.

Please add a tag to read RSTS (the value available now via `vcgencmd get_rsts`) via MBOX interface.

**Comment by popcornmix** [comment]
Sounds reasonable. I'll add this when I get a chance.

**Comment by steelman** [comment]
Thank you in advance.

**Comment by popcornmix** [comment]
Added this. Will be in next rpi-update firmware
```
vcgencmd get_rsts
get_rsts=2
/opt/vc/bin/vcmailbox 0x00040011 8 8 0 0
0x00000020 0x80000000 0x00040011 0x00000008 0x80000004 0x00000002 0x00000000 0x00000000
```
The sixth word output should match the ``vcgencmd get_rsts`` value.

**Comment by popcornmix** [comment]
This is in latest rpi-update firmware

**Comment by steelman** [comment]
Thanks. I will check on Monday. BTW, what are the other arguments ("8 8 0 0") and results?

**Comment by popcornmix** [comment]
There is only one useful work of result. The rest is the protocol for the mailbox interface (e.g. lengths of messages/results). https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
