### ISSUE TITLE
program_gpio_bootmode broken on pi3b

### ISSUE THREAD

**Issue by peterhassing** [raspberrypi/firmware#888]
Hi,

After a considerable amount of testing I think program_gpio_bootmode is broken at least on pi3b.
[Here](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=195145) is my forum post about it.

Regards,
Peter.

**Comment by pelwell** [comment]
Answered in the forum post, but in summary: yes, it is broken.

A fix is in the pipeline.

**Comment by peterhassing** [comment]
This has been fixed in kernel 4.9.60
After setting program_gpio_bootmode=1 and setting program_usb_boot_mode=1 my otp bit reads:
17:3028000a

Thanx for the update guys !! You rock !
