### ISSUE TITLE
audio interrupted by occasional short silence

### ISSUE THREAD

**Issue by tvjon** [raspberrypi/firmware#905]
Playing mp3 files after this firmware update results in occasional small gaps, the longest so far just over a second, of silence, via the analogue port. The music does resume, but obviously can't be enjoyed like that.

$ vcgencmd version
Nov 21 2017 16:16:32 
Copyright (c) 2012 Broadcom
version 2c2faa4c5e38cc04d01245905b8338e8fc55ee0d (clean) (release)
$

**Comment by JamesH65** [comment]
Is this still present on the latest kernel, or can the issue be closed?

**Comment by tvjon** [comment]
I currently have to use:
Linux sa1 4.19.14-v7+ #1188 SMP Wed Jan 9 22:11:22 GMT 2019 armv7l GNU/Linux
as I'm testing some cameras, so no, I'll close it.
