### ISSUE TITLE
VideoCore PPU/Vector Rasterization API

### ISSUE THREAD

**Issue by hermanhermitage** [raspberrypi/firmware#91]
This issue is a placeholder for discussing possible accelerated 2d API.

(From https://github.com/raspberrypi/firmware/issues/84#issuecomment-8387931)
"GPU is quite capable of efficient sprite blits, including transparency/alpha and even arbitrary rotation/scaling. However we are missing a nice API"

Assuming you have the rasterizers already written (otherwise I'll look into it after writing up my documentation on writing raw VideoCore Vector kernels), it would be great to have the API exposed.

Justification:
  - Maximizing SoC utilization :)
  - Bare or Non linux OS which havent ported userland OpenVG/OpenGLES infrastructure.
  - Applications where latency of scene at a time approach is limiting.

**Comment by Ruffio** [comment]
@hermanhermitage I believe that this can be closed as there have been no updates in 2 years?

**Comment by hermanhermitage** [comment]
No updates.
