### ISSUE TITLE
Cannot Create Window Surface 

### ISSUE THREAD

**Issue by thedigitalempress** [raspberrypi/firmware#912]
I am trying to complete the 2nd program in Chapter 6 of "Learning Python with Raspberry Pi" and after running the code on the pi I get this error in the stack trace. 

![screen shot 2017-12-06 at 6 05 11 pm](https://user-images.githubusercontent.com/33044102/33690120-18a6febe-dab0-11e7-8c51-2701eb5d929d.png)

I've been researching for some time now on how to resolve the issue but haven't found much. I did analyze the rip_egl.py code and saw that I should come here if there are any issues. 

![screen shot 2017-12-06 at 6 05 32 pm](https://user-images.githubusercontent.com/33044102/33690153-4cb8474e-dab0-11e7-89e2-ea4c18cee046.png)

It will run the first half of the code and will not display the pygame window for the music player. This is my code. 

https://github.com/thedigitalempress/screenDance/blob/master/screenDance.py

Thanks for your help!

**Comment by JamesH65** [comment]
Closing as this issue is not kernel related. Please use the forums for this sort of question.

**Comment by ghollingworth** [comment]
Just checking with the author of the book as to where you should post this question.

Thanks

Gordon
