### ISSUE TITLE
Forcing USB device mode boot even when there is a full firmware on the SD card.

### ISSUE THREAD

**Issue by ali1234** [raspberrypi/firmware#914]
This is part question, part feature request.

Suppose I have a RPi Zero with a blank SD card, and I load the MSD firmware over USB with rpiboot or usbbootgui. Now I write my firmware on to the USB storage device and reboot. It should now boot my firmware from the SD card.

But supposing I write a bad firmware and the device goes in to a boot loop. Is it possible to force a boot from USB without removing the SD card? So that I can once again boot the MSD firmware from rpiboot and write a different firmware on to the SD card?

The N900 had a boot option called "boot_wait" for this purpose. It would specify number of seconds to wait for a USB connection before continuing normal boot. Would it be possible to have something like this in config.txt? (If it does not already exist.)

**Comment by ghollingworth** [comment]
Unfortunately not, once the bootrom finds a bootcode.bin on the SD card it will boot from it.  This is why we specifically have to interrupt the CMD line from the eMMC to the processor when you want to boot from USB on the compute module (otherwise it'd be impossible to get out of this situation)

**Comment by ali1234** [comment]
Wow. I'm glad I'm not trying to build a real product based on this.

**Comment by JamesH65** [comment]
Because sarcasm works so well when wanting help.

**Comment by ali1234** [comment]
Help has already been refused.

**Comment by pelwell** [comment]
First of all, this paragraph makes no sense:

> Suppose I have a RPi Zero with a blank SD card, and I load the MSD firmware over USB with rpiboot or usbbootgui. Now I write my firmware on to the USB storage device and reboot. It should now boot my firmware from the SD card.

Secondly, "refused" implies a lack of will, when in fact it is a lack of possibility - the bootrom is immutable, and it does what it does.

Thirdly, if you were serious about building a field-updateable product then you would partition the SD card (assuming you aren't using an EMMC which is more suited to the job - Pi Zero was never intended to form part of products, that's what CM is for) and create a nominally read-only partition containing U-boot or some other loader - NOOBS even -  and put the OS/application in a separate partition.
