### ISSUE TITLE
Debian sid problem with kernel 4.14

### ISSUE THREAD

**Issue by evasjo** [raspberrypi/firmware#915]
cmdline.txt:
dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p3 rootfstype=f2fs elevator=deadline rootwait

Firmware branch: master
config.txt:
device_tree=bcm2837-rpi-3-b.dtb     // From 4.13
kernel=vmlinuz-4.13.0-1-armmp-lpae
initramfs initrd.img-4.13.0-1-armmp-lpae followkernel
// Works very good!

Firmware branch: master
config.txt:
device_tree=bcm2837-rpi-3-b.dtb     // From 4.14
kernel=vmlinuz-4.14.0-1-armmp-lpae
initramfs initrd.img-4.14.0-1-armmp-lpae followkernel
// Black screen in the middle of the boot, never got kde login.

Firmware branch: next
config.txt:
device_tree=bcm2837-rpi-3-b.dtb     // From 4.13
kernel=vmlinuz-4.13.0-1-armmp-lpae
initramfs initrd.img-4.13.0-1-armmp-lpae followkernel
// Black screen

Firmware branch: next
config.txt:
device_tree=bcm2837-rpi-3-b.dtb     // From 4.14
kernel=vmlinuz-4.14.0-1-armmp-lpae
initramfs initrd.img-4.14.0-1-armmp-lpae followkernel
// Never found DVI signal (HDMI-DVI cable), black screen after that.

**Comment by pelwell** [comment]
We support the Raspbian distribution, the downstream kernel and the firmware. If you can identify something in any of those that cause problems for another kernel or distribution then we may be able to help, but we can't diagnose faults in non-standard configurations.
