### ISSUE TITLE
Camera metering mode not exposed in OMX IL

### ISSUE THREAD

**Issue by dridri** [raspberrypi/firmware#917]
Are there any reason why it is not possible to change metering mode of the camera board in IL ? Any workaround ?

**Comment by 6by9** [comment]
They're there.
https://github.com/raspberrypi/userland/blob/master/interface/vmcs_host/khronos/IL/OMX_IVCommon.h#L1001
```OMX_METERINGTYPE eMetering;```
used with index ```OMX_IndexConfigCommonExposureValue```

**Comment by dridri** [comment]
Okay looks like I was a bit late on headers version.. sorry for this dumb issue, closing it
