### ISSUE TITLE
Interprocessor (&Inter OS) Communication Latency

### ISSUE THREAD

**Issue by hermanhermitage** [raspberrypi/firmware#92]
This is a placeholder to discuss tackling the interprocessor comms latencies.
(From: https://github.com/raspberrypi/firmware/issues/84#issuecomment-8397220)
"The mailbox/property interface takes about 350us to send a set_clock_rate message and get a response back.
I believe the clock changing is a small fraction of that time. I believe the majority of the time is taken by ARM side context switches."

My thoughts are this is a major show stopper on fine grained dispatch and thus problematic for non batch (scene at a time) workloads.  Experience with other architectures you can get down to low microsecond uni-directional dispatch of jobs, and <50us when notification/sync is required.

I'm not across linux nor the impact of virtual indexing on context switching on the ARM, nor the VideoCore background workload, nor whether all work must be scheduled via tasks or whether interrupt worker functions can be pumped by interrupts (eg. making one VideoCore scalar processor dedicated to executing work tasks scheduled direct from interrupts or watching a ringbuffer - without the need for context switching).

It feels like software architecture is getting in the way of what the hardware can do.  The CPUs are 1 AXI clock away right?  There is custom mailbox (fifo) - to avoid paying SDRAM latencies on interprocessor comms?

As a starting point, is there some way I can break down and measure the elements of a typical message/response in terms of where the time is taken up?
(arm user -> context switch -> arm driver -> mailbox -> gpu interrupt -> gpu driver -> context switch -> gpu work -> ... return message...)

Whats the best userland component to look into for understanding the latency?

Thanks.

**Comment by brunogm0** [comment]
Anyone care to enable ARM TCM in RPi, some patchs use it on the arm1176 for U300 and s3c64xx ?
IIRC ITCM and DTCM are 16k total each divided in 4k zones?  Also anyone can confirm that two DMa channels exist to comunicate from/to TCMs?

**Comment by swarren** [comment]
I believe the TCM is optional, and does not exist in the RPi. At least, when someone asked me about it before, and I checked the ARM registers that represent the TCM presence/size, those registers said there wasn't one.

**Comment by popcornmix** [comment]
Yes, there is no TCM in RPi (nor any arm side DMA).

**Comment by brunogm0** [comment]
thanks, these cause confusion http://sandsoftwaresound.net/raspberry-pi/arm11-microarchitecture/

**Comment by Ruffio** [comment]
@hermanhermitage is this still an issue?
