### ISSUE TITLE
Modules.symvers for 4.1.20?

### ISSUE THREAD

**Issue by ce3a** [raspberrypi/firmware#920]
Where do I find the **Modules.symvers** files for kernel **4.1.20**?

Commit ["Bump to 4.1.20"](https://github.com/raspberrypi/firmware/tree/4bf906cdd221c4f6815d0da7dda0cd59d25d945b/extra) seems to contain the files from the previous kernel version (4.1.19). I have build a kernel module using this file, but it does not load:

 `insmod` fails with **"Invalid module format"**

I assume, it is because I was using the Modules.symvers from a different kernel.

Many thanks in advance.
Best regards.

**Comment by JamesH65** [comment]
That is a very old kernel.  Probably easier moving to a newer kernel version. Better performance and security as well.

**Comment by JamesH65** [comment]
This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.
