### ISSUE TITLE
Can't boot with Pi 2 Model and SD card with bootcode.bin on it.

### ISSUE THREAD

**Issue by wasi54** [raspberrypi/firmware#922]
Flash Drive OCZ Vertex 4 SATA III Solid State Drive 64GB.
It is connected by a dual USB connector adaptor (one for data and one for USB power supply).
If the Power for  the Flash raises about 50-100 ms before the Power of the Raspi, then booting is fine and everthing is working as expected.
If the the power raises at the same time, it won't boot and the gren LED lamp on the Pi starts blinking after some seconds.
Is there a way to increase the delay the Pi start?

Thanks in advance

**Comment by pelwell** [comment]
Create a file called `timeout` on the SD card and see if that helps. It may have to non-zero length.

**Comment by wasi54** [comment]
Great, thats the solution!
