### ISSUE TITLE
CONFIG_USB_TMC=m

### ISSUE THREAD

**Issue by jakemagee** [raspberrypi/firmware#929]
Would it be acceptable to add USBTMC (CONFIG_USB_TMC=m) to the list of pre-compiled modules?  I doubt it gets used much, but it would keep some of us from having to build and distribute it manually.

**Comment by pelwell** [comment]
What does it do? You aren't exactly selling it. ;-)

**Comment by Ferroin** [comment]
USB TMC is the USB Test and Measurement Class.  Example devices include USB oscilloscopes, USB logic analyzers, and USB connected multimeters.  Essentially, it's the USB equivalent of the old SCSI and RS232 interfaces a lot of test-bench equipment used to push data to a computer.

**Comment by pelwell** [comment]
It's a 25KB module - not the smallest but not exactly bloated. I'm OK with including it - @popcornmix ?

**Comment by popcornmix** [comment]
I'm okay with this being added if @jakemagee (or others) would still find it useful.

**Comment by dedekind** [comment]
+1
It is useful, please, enable it.

**Comment by dedekind** [comment]
I have users trying to control Yokogawa power meters from Raspberry Pi, and today 'yokotool' (https://github.com/intel/yoko-tool) requires the usbtmc kernel driver for that, so having the driver available as module would help the users.

**Comment by janzhen96** [comment]
+1 
Can you please enable the usbtmc kernel driver.

**Comment by pelwell** [comment]
Added - see https://github.com/raspberrypi/linux/commit/b3a4c69c56f4db99b091305a33aa7c9b090aaad1.

**Comment by popcornmix** [comment]
Available in latest rpi-update kernel.

**Comment by popcornmix** [comment]
@jakemagee please test and close if happy.

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
