### ISSUE TITLE
Official 7 " touch screen: Touch out of calibration after firmware update.

### ISSUE THREAD

**Issue by fosspill** [raspberrypi/firmware#945]
I believe this is a firmware issue since the only cause for this issue is updating the firmware.

The touch works perfectly at the top of the display, but the further down you touch you'll have more offset between your finger and the cursor.
All the way to the bottom of the screen the offset is about 1cm.

I've tried with and without overscan, no change. Only thing that helps is to go back to the old firmware.

I would appreciate any tips or help. Should I just go back to an older firmware version? Is there a specific one I should try?

**Comment by JamesH65** [comment]
I think I have found a problem with the device tree overlay - I accidentally set the vertical resolution to 600, not 480. Doh. Anyway, pushing a fix though to 4.9 and 4.14, in the mean time you can manually change the overlay, it's called rpi-ft5406-overlay.dts, edit it to replace the 600 with 480 and it should now scale correctly.

**Comment by pelwell** [comment]
Compile the modified overlay with:
```
$ dtc -@ -I dts -O dtb -o rpi-ft5406.dtbo rpi-ft5406-overlay.dts
```
Copy the resulting .dtbo to /boot/overlays.

**Comment by fosspill** [comment]
pi@raspberrypi:~ $ uname -r
4.14.18-v7+

**Comment by JamesH65** [comment]
That's great - thanks for reporting it.
