### ISSUE TITLE
Unable to boot rpi3 with firmware 1676ddb0792f1d1678efed0399c55128bc8203a6 or newer

### ISSUE THREAD

**Issue by leoguiders** [raspberrypi/firmware#946]
I am having the following issue with my Raspberry Pi 3 model B:

Bootup hangs with the ACT led flashing 8 times (4 long flashes, 4 short flashes) which according to https://elinux.org/R-Pi_Troubleshooting#Green_LED_blinks_in_a_specific_pattern indicates "SDRAM not recognised. You need newer bootcode.bin/start.elf firmware."

I had this issue with the latest lite image of raspbian stretch so i went back to the latest lite image of jessie that i was actually able to boot and updated/upgraded everything except the raspberrypi-bootloader package.

Then I updated the bootloader one changeset at a time to come to the conclusion that the commit 1676ddb0792f1d1678efed0399c55128bc8203a6 (or rpi-update 5ad8a401aef4973e19678c1510f52d34a558eea4) actually breaks my raspberry pi.

(I could narrow it down to start.elf because I can use any other bootloader file from that commit).

Is there any way to actually see what is happening in that early stage?

**Comment by pelwell** [comment]
We've looked into the code changes around that time and the current thinking is that your Pi must have a very subtle fault that causes the new firmwares to think it is unrecognised and therefore unlicensed.

Send your shipping address to phil@raspberrypi.org and we'll send you a new Pi 3 in exchange for you returning the (presumed) faulty one. We'll include a decent SD card to cover your costs.

**Comment by leoguiders** [comment]
Great, thanks for your help!

**Comment by pelwell** [comment]
RPi3 was found to be faulty, in a way which hadn't been a problem before a firmware change in July, and replaced.
