### ISSUE TITLE
v7: USB gadget function drivers are missing

### ISSUE THREAD

**Issue by t-8ch** [raspberrypi/firmware#947]
The v7+ module tree is missing the drivers for USB gadget functions in drivers/usb/gadget/function
They are present in the non-v7+ tree.
Observered on latest master (9ab68bf), 4.14.20 and 4.9.59.

I could not find any documentation if this intentional.

**Comment by t-8ch** [comment]
Ok, I found the defconfig in the linux repo. In which repo should I lobby to get this included?

**Comment by pelwell** [comment]
https://github.com/raspberrypi/linux/issues

**Comment by t-8ch** [comment]
Thanks, will do.
