### ISSUE TITLE
What happened to the modules directory?

### ISSUE THREAD

**Issue by TeaRex73** [raspberrypi/firmware#949]
The last commit (the one updating the kernel from 4.14.20 to 4.14.21) removed the modules directory completely. Was that on purpose? If so, is there any replacement? In my project, I use a build script for a slightly patched kernel that uses the configs.ko in the modules directory to clone the configuration of the official kernel (and then it makes two small changes to it). This fails now because it can't find the configs.ko module.

**Comment by popcornmix** [comment]
You are correct - that was unintended. The modules should be back in raspberrypi/firmware repo.

**Comment by TeaRex73** [comment]
Thanks a lot, fix is confirmed. Issue closed.
