### ISSUE TITLE
PXN-0082 USB Joystick not working with 4.14.30-v7+ on RPi3

### ISSUE THREAD

**Issue by tednilsen** [raspberrypi/firmware#964]
Dead, no lights after upgrading. The joystick itself is ok on previus firmware.

**Comment by popcornmix** [comment]
This won't be a firmware issue. Create an issue here:
https://github.com/raspberrypi/linux/issues
and include output of ``lsusb`` and ``lsmod`` on both the working (presumably 4.9.xx?) and the 4.14.30 kernels.
