### ISSUE TITLE
DS1621 sensor kernel driver module is missing

### ISSUE THREAD

**Issue by soosp** [raspberrypi/firmware#973]
I'm running Raspbian 9.4 on an Raspebrry Pi 3 with the latest kernel (Linux pi1 4.14.33-v7+ #1109 SMP Tue Apr 10 17:28:38 BST 2018 armv7l GNU/Linux) updated with rpi-update. I have to use a DS1621 I2C temperature sensor but the related kernel module is missing. Please include it into the next build.
It would be nice to add a proper overlay too.
Thanks in advance.

**Comment by pelwell** [comment]
This is a kernel issue, so https://github.com/raspberrypi/linux/issues/2509 has been reopened.
