### ISSUE TITLE
Raspberry Pi userspace tools and libraries for armv7

### ISSUE THREAD

**Issue by pipiche38** [raspberrypi/firmware#979]
All in the subject. How can we get the userspace tools and librairies for armv7 ?

I currently have a Rpi3B+ installed with Fedora kernel 4.16.3-300.fc28.armv7hl
and would like to get the userspace tools and libraries .

Is there a way to get source code of it

**Comment by pelwell** [comment]
"Raspberry Pi userspace tools and libraries" is a bit vague, but take a look at the [userland repo](https://github.com/raspberrypi/userland).

**Comment by pelwell** [comment]
Yes, that is one of the utilities built from the code in the userland repo - the source is [gencmd.c](https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/gencmd/gencmd.c). The buildme script in the root saves you having to understand CMake.

**Comment by pipiche38** [comment]
Got it ! Thanks
