### ISSUE TITLE
CM3 does not boot with gpu_mem_1024 below 32

### ISSUE THREAD

**Issue by bterrier** [raspberrypi/firmware#984]
When in `config.txt` `gpu_mem_1024` is set to any value below 32 the Raspberry Pi Compute Module 3 does not boot and the green LED blinks 4 times.

According to the [documentation](https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md) the minimum value should be 16 and not 32.

**Comment by pelwell** [comment]
How are you booting the CM3?

Setting gpu_mem below 32 forces the use of `start_cd.elf` (and `fixup_cd.dat`). Are those files present?

**Comment by bterrier** [comment]
@pelwell 
My bad, the `_cd` files are not present.

I am using buildroot, and it only puts the "start.elf` and `fixup.dat` files.
