### ISSUE TITLE
bootcode.bin does not support the Raspberry Pi 3 Plus model

### ISSUE THREAD

**Issue by tinue** [raspberrypi/firmware#988]
The `bootcode.bin` that is available on this repository does not support the Raspberry Pi 3 Plus model. This is the console output that I get:
```
Found SD card, config.txt = 0, start.elf = 0, recovery.elf = 0, timeout = 1
Trying USB
USB Host enumeration failed, no device detected at root
```

Compare this to the output from a Raspberry Pi 3 model:
```
Found SD card, config.txt = 0, start.elf = 0, recovery.elf = 0, timeout = 1
Trying USB
Hub device found at addr 4, enumerating HUB
Initialise hub
Found 5 ports, multi_tt = 1
Setting interface 0
Enabling PORT POWER on port 1
Enabling PORT POWER on port 2
Enabling PORT POWER on port 3
Enabling PORT POWER on port 4
Enabling PORT POWER on port 5
Waiting for devices to respond to reset
Found device on port 1
Found highspeed device
Device found: type = Ethernet adapter, addr = 5
Found device on port 5
Device failed to respond to reset
Trying booting from Ethernet device addr 5
Initialise ethernet with MAC b8:27:eb:6d:a4:07
Wait for Link up
```

Apparently the USB hub device or the host itself is not supported yet.

**Comment by popcornmix** [comment]
Ping @ghollingworth

**Comment by tinue** [comment]
Thanks for the quick support! I'll check back on Tuesday.

**Comment by tinue** [comment]
Just wondering: I checked all three official locations of bootcode.bin and don't seem to find an updated version. Do you know if it is coming?

Which one of these is the best location to check?
* https://github.com/raspberrypi/firmware/blob/master/boot/bootcode.bin
* https://github.com/RPi-Distro/firmware/blob/debian/boot/bootcode.bin
* https://github.com/raspberrypi/firmware/files/1466884/bootcode.bin.gz

**Comment by Dowster64** [comment]
Hi, I'm just wondering too.  I've got a piserver application for a number of machine monitors and I guess I'm counting on bootcode.bin working to boot and reboot the monitors,

Thanks in anticipation!

Steve

**Comment by popcornmix** [comment]
An update has been pushed.

**Comment by tinue** [comment]
Thank you, it works fine.

**Comment by lowlyocean** [comment]
@popcornmix @tinnue Please advise location of working bootcode.bin? I am trying from [next branch](https://github.com/raspberrypi/firmware/blob/next/boot/bootcode.bin) without sucess
