### ISSUE TITLE
dpkg unrecoverable error raspberrypi-kernel-headers contains empty filename

### ISSUE THREAD

**Issue by jimlynnjulian** [raspberrypi/firmware#989]
I get the mentioned error when I try to setup the RPi as a wifi access point and install hostapd and dnsmasq. That's the only time I've encountered the error. This is my first install of Stretch.

A temporary work around may be to uninstall and then install the files. Then reinstalling the kernel headers.
I'm using the headers to compile a driver. The idea is to have downloaded and installed the programs and made the wifi access point before compiling the driver. Can I uninstall the headers with no ill effects? 

This is the result of an attempt to uninstall the headers:
"sudo dpkg --remove raspberrypi-kernel-headers
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'raspberrypi-kernel-headers' contains empty filename"

UPDATE: I installed Stretch on a different SD card and installed everything except the new headers.
I copied the driver compiled on a different card and used that iinstead of compiling new headers. That works. During the course of making the RPi an access point, I was required to change the ownership of /var/www/html from 'pi' to 'www-data'. WhenI attempted to drag 'n drop files into the directory (Mobaxterm sftp browser) I fot permissipon error messages, but the first was the familiar 'raspberrypi-kernel-headers' 'empty filename' message. Note, I had never installed new headers on the new SD card.
Strange. The new card is working completely.

The only two anomolies are:
1.) I couldn't start and enable the driver service without getting failure notices, yet the driver service is running.
2.) While making the RPi an access point, a fixed IP number was assigned to the pi. I used the DHCP reservation number and assignment on my router.
A different number has been assigned and ignores both sources, the RPi and the router.

The error message must be derived from the driver itself since that is the only machine code copied to the new card. The other files are all text files, in the form of custom scripts, written by me. One remote possibility is the RPi keeps a history in onboard flash memory.

**Comment by XECDesign** [comment]
Sounds more like a corruption issue. Maybe `sudo apt clean && sudo apt install raspberrypi-kernel-headers --reinstall`

**Comment by jimlynnjulian** [comment]
Thank you XECDesign

I think this is more along the line of what I need:

dpkg -c full-path-to-debfile | awk '{if ($6 == "./"){ print "/."; } \
else if (substr($6, length($6), 1) == "/") \
{print substr($6, 2, length($6) - 2); } \
else { print substr($6, 2, length($6) - 1);}}' \
> /var/lib/dpkg/info/packagename.list
