### ISSUE TITLE
eglGetDisplay heap corruption

### ISSUE THREAD

**Issue by johang** [raspberrypi/firmware#99]
I have an issue where a call to eglGetDisplay somehow writes in Glib's thread-local storage, which corrupts Glib's slice allocator. The pointer magazine1 here (0x3000) is corrupted:

```
Program received signal SIGSEGV, Segmentation fault.
g_slice_alloc (mem_size=12)
    at /build/glib2.0-GEFbTq/glib2.0-2.32.3/./glib/gslice.c:988
988     /build/glib2.0-GEFbTq/glib2.0-2.32.3/./glib/gslice.c: No such file or directory.
(gdb) bt
#0  g_slice_alloc (mem_size=12)
    at /build/glib2.0-GEFbTq/glib2.0-2.32.3/./glib/gslice.c:988
[...]
(gdb) p tmem
$2 = (ThreadMemory *) 0x12698
(gdb) p *tmem
$3 = {magazine1 = 0x3000, magazine2 = 0x12a98}
```

It should contain approximately the same address as magazine2. I have tracked this down to two instructions in eglGetDisplay. See line +36 and +40:

```
(gdb) disassemble eglGetDisplay
Dump of assembler code for function eglGetDisplay:
=> 0x40148690 <+0>: push    {r4, lr}
   0x40148694 <+4>: ldr r3, [pc, #44]   ; 0x401486c8 <eglGetDisplay+56>
   0x40148698 <+8>: ldr r2, [pc, #44]   ; 0x401486cc <eglGetDisplay+60>
   0x4014869c <+12>:    add r3, pc, r3
   0x401486a0 <+16>:    ldr r2, [r3, r2]
   0x401486a4 <+20>:    mov r4, r0
   0x401486a8 <+24>:    ldr r0, [r2]
   0x401486ac <+28>:    bl  0x4014650c
   0x401486b0 <+32>:    cmp r0, #0
   0x401486b4 <+36>:    movne   r3, #12288  ; 0x3000
   0x401486b8 <+40>:    strne   r3, [r0]
   0x401486bc <+44>:    mov r0, r4
   0x401486c0 <+48>:    pop {r4, lr}
   0x401486c4 <+52>:    b   0x40146104
   0x401486c8 <+56>:    muleq   r2, r8, r10
   0x401486cc <+60>:            ; <UNDEFINED> instruction: 0x000004b0
End of assembler dump.
```

Sadly, the only way to reproduce the issue is by building Cogl[1] and running any of the example Cogl programs. I have not found a way to reproduce the crash without Cogl. My question is, why is eglGetDisplay writing there, and what is it writing?

It's easy to workaround this issue though. Thing is, eglGetDisplay doesn't seem to do anything important and always returns 1. I just replace the call with 1.

[1] http://git.gnome.org/browse/cogl

**Comment by STCDIY** [comment]
看不懂
