### ISSUE TITLE
Newer stretch reports incorrect screen height

### ISSUE THREAD

**Issue by mrmsbarnes** [raspberrypi/firmware#996]
My monitor is Asus VS24A (1920x1200)

cat /proc/sys/kernel/osrelease
4.14.34-v7+

ls -la /opt/vc/lib/libbcm_host.so
-rw-r--r-- 1 root root 99516 Mar 28 05:07 /opt/vc/lib/libbcm_host.so

from tkinter import *
root =Tk()
print (root.winfo_screenwidth())
1920
print (root.winfo_screenheight())
1080       <--- wrong

Problem [also] shows in bcm's graphics_get_display_size() from bcm_host.c

On earlier stretch release:

cat /proc/sys/kernel/osrelease
4.9.59-v7+

pi@raspberrypi:~ $ ls -la /opt/vc/lib/libbcm_host.so
-rw-r--r-- 1 root root 99516 Oct 30  2017 /opt/vc/lib/libbcm_host.so

from tkinter import *
root =Tk()
print (root.winfo_screenwidth())
1920
print (root.winfo_screenheight())
1200       <--- correct

**Comment by popcornmix** [comment]
Report output of ``tvservice -s`` and ``fbset`` on system with the problem.

**Comment by mrmsbarnes** [comment]
With release 2017-11-29 raspbian:

 

pi@raspberrypi:~ $ cat /proc/sys/kernel/osrelease

4.9.59-v7+

pi@raspberrypi:~ $ tvservice -s

state 0x12000a [HDMI DMT (68) RGB full 16:10], 1920x1200 @ 60.00Hz, progressive

pi@raspberrypi:~ $ fbset

 

mode "1920x1200"

    geometry 1920 1200 1920 1200 32

    timings 0 0 0 0 0 0 0

    rgba 8/16,8/8,8/0,8/24

endmode

 

 

With release 2018-04-18 raspbian:

 

pi@pissever:~ $ cat /proc/sys/kernel/osrelease

4.14.34-v7+

pi@pissever:~ $ tvservice -s

state 0x12000a [HDMI DMT (82) RGB full 16:9], 1920x1080 @ 60.00Hz, progressive

pi@pissever:~ $ fbset

 

mode "1920x1080"

    geometry 1920 1080 1920 1080 32

    timings 0 0 0 0 0 0 0

    rgba 8/16,8/8,8/0,8/24

endmode

 

Equipment is Raspberry Pi 3

**Comment by popcornmix** [comment]
Any custom config.txt settings?

Can you post output of ``sudo vcdbg log msg`` on working and not working system?

**Comment by mrmsbarnes** [comment]
The only config.txt change I caused was setting preferred gpu-mem to 128 (recommended by rpi3d).  Other noted differences were there in release.

 

2017-11-29 raspbian:

See attached oldgood.txt lines 6, 41, 50, 88 output of sudo vcdbg log msg

 

/boot/config.txt attached as oldconfig.txt.  Note lines 24-29:

# uncomment if hdmi display is not detected and composite is being output

#hdmi_force_hotplug=1

 

# uncomment to force a specific HDMI mode (this will force VGA)

#hdmi_group=1

#hdmi_mode=1

 

2018-04-18 raspbian:

See attached newbad.txt.  Note lines 47,48,49, and 114 are not present in old good output and lines 41/41 and 88/91 disagree.

 

/boot/config.txt attached as newconfig.txt.  Lines 24-49:

# uncomment if hdmi display is not detected and composite is being output

hdmi_force_hotplug=1

 

# uncomment to force a specific HDMI mode (this will force VGA)

hdmi_group=2

hdmi_mode=82

 

Run on same Pi hardware.

It may be irrelevant but I note many /boot files in the new release are dated March 28 and not April 18.  I will advise in a follow-up if reverting config.txt changes is effective.

**Comment by mrmsbarnes** [comment]
I am VERY sorry for your time and my time I wasted with this issue.  I cannot recreate pi3d installation steps that could have corrupted /boot/config.txt.

Next time I’ll verify a problem is repeatable before bothering raspberrypi/firmware.

My apologies.

 

From: Scott Barnes [mailto:sbarnes@dslextreme.com] 
Sent: Tuesday, May 22, 2018 12:50 AM
To: 'raspberrypi/firmware'
Subject: RE: [raspberrypi/firmware] Newer stretch reports incorrect screen height (#996)

 

The only config.txt change I caused was setting preferred gpu-mem to 128 (recommended by rpi3d).  Other noted differences were there in release.

 

2017-11-29 raspbian:

See attached oldgood.txt lines 6, 41, 50, 88 output of sudo vcdbg log msg

 

/boot/config.txt attached as oldconfig.txt.  Note lines 24-29:

# uncomment if hdmi display is not detected and composite is being output

#hdmi_force_hotplug=1

 

# uncomment to force a specific HDMI mode (this will force VGA)

#hdmi_group=1

#hdmi_mode=1

 

2018-04-18 raspbian:

See attached newbad.txt.  Note lines 47,48,49, and 114 are not present in old good output and lines 41/41 and 88/91 disagree.

 

/boot/config.txt attached as newconfig.txt.  Lines 24-49:

# uncomment if hdmi display is not detected and composite is being output

hdmi_force_hotplug=1

 

# uncomment to force a specific HDMI mode (this will force VGA)

hdmi_group=2

hdmi_mode=82

 

Run on same Pi hardware.

It may be irrelevant but I note many /boot files in the new release are dated March 28 and not April 18.  I will advise in a follow-up if reverting config.txt changes is effective.
