### ISSUE TITLE
Firmware doesn't reply via mailbox property

### ISSUE THREAD

**Issue by lategoodbye** [raspberrypi/firmware#999]
Hi,
during a test with the current linux-next-20180517 (bcm2835_defconfig, Raspberry Pi Zero W, Raspbian rootfs) i switched the firmware driver from builtin to kernel module. As a result the raspberrypi firmware driver hangs endlessly during driver probe.

After some investigations i was able to narrow down the hang to the [wait_for_completion](https://github.com/torvalds/linux/blob/master/drivers/firmware/raspberrypi.c#L55) within rpi_firmware_transaction during request of firmware revision.

I applied the following patch in order to avoid at least the hanging
```
diff --git a/drivers/firmware/raspberrypi.c b/drivers/firmware/raspberrypi.c
index 0602626..9b7d0b6 100644
--- a/drivers/firmware/raspberrypi.c
+++ b/drivers/firmware/raspberrypi.c
@@ -54,8 +54,12 @@ rpi_firmware_transaction(struct rpi_firmware *fw, u32 chan, u32 data)
        reinit_completion(&fw->c);
        ret = mbox_send_message(fw->chan, &message);
        if (ret >= 0) {
-               wait_for_completion(&fw->c);
-               ret = 0;
+               if (wait_for_completion_timeout(&fw->c, HZ * 2)) {
+                       ret = 0;
+               } else {
+                       dev_err(fw->cl.dev, "Transaction timeout\n");
+                       ret = ETIMEDOUT;
+               }
        } else {
                dev_err(fw->cl.dev, "mbox_send_message returned %d\n", ret);
        }
```

But i was always getting Transaction timeouts. The only difference which comes to my mind between a builtin driver and a kernel module is the timing. In case of builtin the firmware driver probes after 2s and as a kernel module after 28s.

Firmware version: 2018-04-16 18:16

Do you have an explanation for this behaviour?

Edit: I noticed a bug in my patch (ret = -ETIMEDOUT), but this is not relevant to the reported issue.

**Comment by pelwell** [comment]
I can't immediately see why delaying the start of the firmware (and hence mailbox) driver.

The mailbox task on the VPU is started almost immediately after the ARM is allowed out of reset. Until the ARM side is started no ARM<->VPU traffic (mailbox properties, VCHI[Q]) can occur.

Does adding `initcall_debug` to the command line shed any light?

**Comment by lategoodbye** [comment]
Regarding to my patch above, is there a sensible timeout for the completion?

**Comment by pelwell** [comment]
I'd rather understand the underlying problem, which I'm investigating now.

**Comment by pelwell** [comment]
Have you only tried with a Zero W?

In my testing with a 3B, it fails if I'm mounting the rootfs from NFS,  but mounting from SD card in the usual way works. 

In the failure cases I see the firmware driver is never started and the LAN chip doesn't appear. Nothing ever gets as far sending the VPU a mailbox command, so I think we can exonerate the firmware.

**Comment by lategoodbye** [comment]
I tried only Zero W. This means you cannot reproduce the issue with an RPI 3B and the same config (bcm2835_defconfig)?

**Comment by pelwell** [comment]
Is that a valid configuration? It kills the network and display for me.

I can try on a Zero W.

**Comment by lategoodbye** [comment]
Absolutely, kernelci tests this configuration everyday for the RPI 3B ([example](https://kernelci.org/boot/id/5b0e630a59b514628279a88a/)).

**Comment by lategoodbye** [comment]
@anholt
Maybe you also want to take a look on this.
It seems to me that in case the v3d power domain is disabled, we get the following error:
```
[    2.203714] vc4-drm soc:gpu: bound 20806000.vec (ops vc4_vec_ops)
[    2.220780] vc4-drm soc:gpu: bound 20400000.hvs (ops vc4_hvs_ops)
[    2.238357] vc4-drm soc:gpu: bound 20206000.pixelvalve (ops vc4_crtc_ops)
[    2.256474] vc4-drm soc:gpu: bound 20207000.pixelvalve (ops vc4_crtc_ops)
[    2.274518] vc4-drm soc:gpu: bound 20807000.pixelvalve (ops vc4_crtc_ops)
[    2.291902] [drm:vc4_v3d_bind] *ERROR* V3D_IDENT0 read 0xdeadbeef instead of 0x02443356
```
Is it possible to probe vc4-drm without v3d anyway?
What's your opinion about the firmware driver patch above?

**Comment by anholt** [comment]
If we can't get our power domains, DSI and HDMI won't work either.  We need them to actually work.  Timing out our firmware transactions just means everything will fall over, which doens't seem like much of a fix to me.

**Comment by pelwell** [comment]
Without some motivation for the change, this whole exercise is pointlessly time-consuming.

**Comment by lategoodbye** [comment]
The patch isn't intended to fix anything but waiting endlessly and notice the user something gone wrong. A driver function should never block forever.

The root cause of the missing reply is a different issue and should be fixed, too.

**Comment by pelwell** [comment]
The raspberrypi-power driver depends on RASPBERRYPI_FIRMWARE=y, but nothing depends on the power driver, so it's never going to end well. If you must have a timeout then a second should be more than adequate, but making RASPBERRYPI_FIRMWARE a bool and adding the extra dependencies seems like a better option all round.

It seems like a bug that the power_domains property is silently ignored in the absence of the driver, which happens because unless the driver is selected PM_GENERIC_DOMAINS is not defined. Perhaps all drivers that use PM should also select it, or just enable it for the platform.

**Comment by lategoodbye** [comment]
Okay, this makes perfectly seems regarding to the power domain issues. But i still don't understand why the firmware driver (only depends on mailbox) doesn't receive a reply. I noticed in the underlying mbox driver some debug, maybe this provides more information.

**Comment by lategoodbye** [comment]
I enabled the debug in the mbox driver and in bad case i see "Request" entries, but not the "Reply" entries in the interrupt handler.

After that i disabled the VC4 driver in kernel config in order to avoid possible consequences from probe fail. In this case we receive the replies from the firmware as expected. I assume the VC4 probe fail accidentally disables a requirement of the mailbox driver (clock?).

```
--- regdump_4.17_module_without_v4_good.log	2018-05-31 19:52:48.534970709 +0200
+++ regdump_4.17_module_with_v4_bad.log	2018-05-31 19:52:48.534970709 +0200
@@ -41,8 +41,8 @@
 ctl = 0x000002d4
 div = 0x00004000
 /sys/kernel/debug/clk/hsm
-ctl = 0x00000000
-div = 0x00000000
+ctl = 0x00000247
+div = 0x00001520
 /sys/kernel/debug/clk/isp
 ctl = 0x000002d4
 div = 0x00004000
@@ -124,21 +124,21 @@
 cm = 0x0000020a
 a2w = 0x00000004
 /sys/kernel/debug/clk/pllh
-cm_ctrl = 0x00000000
-a2w_ctrl = 0x0002102d
+cm_ctrl = 0x00000100
+a2w_ctrl = 0x0003102d
 frac = 0x00000000
 ana0 = 0x00900000
 ana1 = 0x0000000c
 ana2 = 0x00000000
 ana3 = 0x00000000
 /sys/kernel/debug/clk/pllh_aux
-cm = 0x00000000
-a2w = 0x00000004
+cm = 0x00000100
+a2w = 0x00000104
 /sys/kernel/debug/clk/pllh_pix_prediv
-cm = 0x00000000
+cm = 0x00000100
 a2w = 0x00000100
 /sys/kernel/debug/clk/pllh_rcal_prediv
-cm = 0x00000000
+cm = 0x00000100
 a2w = 0x00000100
 /sys/kernel/debug/clk/pwm
 ctl = 0x00000200
@@ -186,6 +186,7 @@
        pllh_pix_prediv                0        0        0     3375000          0 0  
           pllh_pix                    0        0        0      337500          0 0  
        pllh_aux                       0        0        0   216000000          0 0  
+          hsm                         0        0        0   163597633          0 0  
           vec                         0        0        0   108000000          0 0  
        pllh_rcal_prediv               0        0        0     3375000          0 0  
           pllh_rcal                   0        0        0      337500          0 0  
@@ -233,4 +234,3 @@
  aveo                                 0        0        0           0          0 0  
  pcm                                  0        0        0           0          0 0  
  pwm                                  0        0        0           0          0 0  
- hsm                                  0        0        0           0          0 0
```

So at least this is no firmware issue.

**Comment by anholt** [comment]
Those clk changes look like "we set up the HDMI clock, then disabled it again."  Given that we used to do that at DPMS time anyway (before CEC came along), that seems unlikely to be the issue.

What's the first firmware transaction that fails?

**Comment by lategoodbye** [comment]
In case of RPI Zero W it is the very first firmware transaction to get the firmware revision within driver probe and the following ones fails too. But on RPI 3B some transactions succeed.

**Comment by lategoodbye** [comment]
Okay, i was able to narrow down this a bit. In case V3D component is probing and the raspberry power is disabled, the issue happens after accessing V3D_READ(V3D_IDENT0):
https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/vc4/vc4_v3d.c#L377

If i uncomment V3D binding or return before this instruction the issue doesn't appear.
How can i identify a firmware crash?

**Comment by pelwell** [comment]
Accessing a powered-down domain will trigger an exception on the VPU. This may be handled successfully, but really you are rearranging the deckchairs on the Titanic at this point. As @anholt said earlier, we need domains to be powered up before the are probed, so you should concentrate your efforts on configuration changes to ensure that happens.

**Comment by lategoodbye** [comment]
Thanks for providing the missing part. Unfortunately the kernel configuration doesn't prevent the VC4 driver from probing before the power domain is ready. So it would be the best to check the power domains during probe.

**Comment by lategoodbye** [comment]
Yes, the firmware driver and the upcoming PM driver should fix this.
